- .travis.yml
> travis.yml: abort build if rendered deployment files are stale

- README.md
Fixed Kuard link that was pointing to Envoy proxy page; Added link to Envoy proxy page.
> Fixed Kuard and and Envoy proxy links

- cmd/contour/contour.go
Take care of a small TODO that I spotted while working in this area.
> cmd/contour: rename writeInitConfig to writeBootstrapConfig

- FAQ.md
- README.md
@joe @dfc PTAL:
Added FAQ 
Added links from README:
- to FAQ
- to launch blog post
> add FAQ and related references

- cmd/contour/contour.go
- internal/k8s/adapter.go
Also clean up logging to take advantage of #31 
> internal/k8s: refactor Watch{Services,Ingress,Endpoints} to register with workgroup

- CONTRIBUTING.md
> CONTRIBUTING.md: fix source checkout instructions

- deployment/deployment-json-v1/02-contour.yaml
- deployment/ds-hostnet/02-contour.yaml
- deployment/ds-json-v1/02-contour.yaml
- deployment/render/daemonset-norbac.yaml
- deployment/render/daemonset-rbac.yaml
- deployment/render/deployment-norbac.yaml
- deployment/render/deployment-rbac.yaml
> deployment: switch to docker.io/envoyproxy/envoy-alpine:latest

- README.md
Signed-off-by: Joe Beda <joe.github@bedafamily.com>
> Update j.hept.io links to https

- internal/envoy/translator.go
- internal/envoy/translator_test.go
> internal/envoy: add k8s to v2 gRPC translator

- cmd/contour/contour.go
- internal/contour/grpc.go
- internal/contour/grpc_test.go
- internal/envoy/translator.go
- internal/envoy/translator_test.go
> internal/contour: wire up grpc api, k8s listener, and envoy translator

- Gopkg.lock
- Gopkg.toml
> Gopkg.toml: add grpc constraint

- deployment/deployment-grpc-v2/02-contour.yaml
> deployment: set the deployment-grpc-v2 target to gcr.io

- deployment/deployment-grpc-v2/02-contour.yaml
> deployment: set grpc v2 deployment replicas to 2

- internal/envoy/translator.go
- internal/envoy/translator_test.go
> internal/envoy: add VirtualHost based routing support

- .travis.yml
- Makefile
> .travis.yml: use Makefile to encapsulate CI checks

- internal/envoy/translator.go
- internal/envoy/translator_test.go
> internal/envoy: add translator tests for remove ingress and endpoints

- cmd/contour/contour.go
- internal/contour/grpc.go
- internal/envoy/translator.go
> all: address TODOs and cleanup for gRPC cond support

- cmd/contour/contour.go
- internal/envoy/translator.go
- internal/envoy/translator_test.go
> interna/envoy: introduce envoy.Cond type

- internal/envoy/translator_test.go
Always use NewTranslator in tests.
> internal/envoy: clean up translator tests

- internal/contour/grpc.go
- internal/envoy/translator.go
This PR removes the timer based polling from gRPC streaming.
Notification signals are transmitted to all streamers using the embedded
envoy.Cond accompanying each cache.
> internal/contour: remove polling from gRPC streams

- Gopkg.lock
> Gopkg.lock: update deps

- internal/contour/grpc.go
Give each stream connection its own unique id.
> internal/contour: identify each stream connection uniquely

- internal/contour/grpc.go
- internal/contour/grpc_test.go
> internal/contour: add support for gRPC fetch operations

- internal/contour/grpc.go
Introduce the resourcer interface to abstract across the different
conversion strategies between the various cache.Values() results and
[]*any.Any.
With that in place, introduce a generic fetch function which can return
a *v2.DiscoveryResponse for any resource with a resourcer and a typeurl.
Introduce sender interface to generify a *v2.DiscoveryResponse stream
and add a generic stream function that can stream any notifyable
resource.
> Internal contour grpc refactor

- internal/k8s/buffer.go
- internal/k8s/watcher.go
> internal/k8s: cleanup k8s.Buffer

- README.md
Fixed via envoyproxy/envoy#1984
> Envoy now supports SNI with TLS

- internal/contour/grpc.go
Move typeurl computation into the notifier contour.resourcer interface.
> internal/envoy: refactor generic contour.stream function

- internal/contour/listener.go
- internal/contour/listener_test.go
DRY up listener creation code. Add unit tests.
> internal/contour: add listener unit tests

- internal/contour/listener.go
- internal/contour/listener_test.go
Fixes #88
Setting kubernetes.io/ingress.allow-http: "false" excludes this ingress
from the ingress_http listener calculation.
> internal/contour: support kubernetes.io/ingress.allow-http: "false"

- internal/contour/listener.go
- internal/contour/listener_test.go
> internal/contour: add validTLSIngress tests

- cmd/contour/contour.go
> cmd/contour: add warning that JSON will be removed in 0.4

- Gopkg.lock
> gopkg.lock: update dependencies

- internal/contour/grpc.go
- internal/envoy/cache_test.go
- internal/envoy/config.go
- internal/envoy/config_test.go
> Backport fix fir #136 to release-0.2

- deployment/deployment-grpc-v2/02-contour.yaml
- deployment/deployment-json-v1/02-contour.yaml
- deployment/ds-hostnet/02-contour.yaml
- deployment/ds-json-v1/02-contour.yaml
- deployment/render/daemonset-norbac.yaml
- deployment/render/daemonset-rbac.yaml
- deployment/render/deployment-norbac.yaml
- deployment/render/deployment-rbac.yaml
> Update deployment files for 0.2.1 tag

- deployment/ds-hostnet/02-contour.yaml
> deployment/ds-hostnet: switch to v2 yaml config

- internal/contour/translator_test.go
- internal/contour/virtualhost.go
- internal/contour/virtualhost_test.go
Fixes #88
Do not generate a http route for ingreses that specify allow-http: false
> internal/contour: support "kubernetes.io/ingress.allow-http": "false",

- internal/contour/translator.go
- internal/contour/translator_test.go
Add a small helper for apiconfigsource generation.
> internal/contour: add apiconfigsource helper

- cmd/contour/contour.go
This PR adds two new flags to bootstrap (init config) mode,
--admin-address and --admin-port which permit the configuration of the
admin api.
The default remains 127.0.0.1:9001.
> cmd/contour: make admin address and port configurable at bootstrap

- docs/tls.md
- docs/troubleshooting.md
- docs/upgrade.md
- release-0.3.md
`release-0.3.md` will be removed before commiting this PR.
> Added release 0.3 release notes and documentation

- README.md
> Fix changelog link in readme

- internal/e2e/grpc.go
- internal/e2e/grpc_e2e_test.go
> internal/e2e: add k8s api to gRPC end to end test

- internal/e2e/grpc_e2e_test.go
> internal/e2e: add test for issue 101

- cmd/contourcli/cli.go
> cmd/contourcli: use proto.TextMarshaler

- internal/e2e/grpc_test.go
> internal/e2e: clean up e2e test

- internal/grpc/grpc.go
> internal/grpc: switch to types.MarshalAny

- internal/e2e/grpc_test.go
> internal/e2e: add test for long service names

- internal/contour/listener.go
- internal/contour/listener_test.go
Signed-off-by: Cody Maloney <cody@emeraldcloudlab.com>
> Add AlpnProtocols to TLS Context so http2 with browsers works

- README.md
- docs/tls.md
Signed-off-by: JENNIFER RONDEAU <jrondeau@heptio.com>
> fix navigation, TLS content

- internal/contour/translator.go
> internal/contour: allow servicename helper to work on any ObjectMeta

- internal/e2e/grpc.go
- internal/e2e/grpc_test.go
> internal/e2e: backport e2e tests from master

- deployment/deployment-grpc-v2/02-contour.yaml
- deployment/deployment-json-v1/02-contour.yaml
- deployment/ds-grpc-v2/02-contour.yaml
- deployment/ds-hostnet/02-contour.yaml
- deployment/ds-json-v1/02-contour.yaml
- deployment/render/daemonset-norbac.yaml
- deployment/render/daemonset-rbac.yaml
- deployment/render/deployment-norbac.yaml
- deployment/render/deployment-rbac.yaml
> deployment: release 0.3.1

- internal/contour/translator.go
- internal/contour/translator_test.go
- internal/contour/virtualhost.go
- internal/contour/virtualhost_test.go
Move the various _pre render_ caches to Translator.cache.
> internal/contour: add translatorCache

- Gopkg.lock
- Gopkg.toml
- internal/contour/translator.go
- internal/e2e/grpc_test.go
Small change to the translator due to the a proto field being renamed.
> gopkg.toml: update to latest go-data-plane

- internal/contour/clusterloadassignment.go
- internal/contour/translator.go
Updates #175
This PR makes the refactoring to track both services and endpoints for
EDS easier.
> internal/contour: switch to recompute pattern for EDS

- cmd/contour/contour.go
- internal/envoy/config.go
> Remove hard coded 127.0.0.1:8001 xDS API address

- internal/contour/cluster.go
- internal/contour/cluster_test.go
- internal/e2e/cds_test.go
Simplify recomputeCluster by creating a map of items added, not items
to remove, during iteration of newsvc. Then it's simple a matter of
iteration over oldsvc and seeing if its contents were added or updated,
and if not, removing the entry.
This pattern will be reused in recomputeClusterLoadAssignments next.
> internal/contour: refactor recomputeCluster

- internal/contour/cluster_test.go
- internal/contour/clusterloadassignment.go
- internal/contour/clusterloadassignment_test.go
- internal/contour/translator.go
- internal/contour/translator_test.go
- internal/e2e/eds_test.go
- internal/grpc/grpc_test.go
> internal/contour: handle named service target ports

- deployment/deployment-grpc-v2/02-contour.yaml
- deployment/ds-grpc-v2/02-contour.yaml
- deployment/render/daemonset-norbac.yaml
- deployment/render/daemonset-rbac.yaml
- deployment/render/deployment-norbac.yaml
- deployment/render/deployment-rbac.yaml
- docs/upgrade.md
- internal/contour/listener.go
- internal/contour/listener_test.go
- internal/contour/translator.go
> Send TLS certificate data inline

- internal/contour/listener.go
- internal/e2e/lds_test.go
> internal/contour: turn off TLS 1.0

- internal/e2e/lds_test.go
> internal/e2e: Add more LDS tests

- internal/e2e/rds_test.go
> internal/e2e: add e2e test for renaming ingress route

- .dockerignore
> docker: reduce size of build context

- deployment/ds-grpc-v2/02-contour.yaml
- deployment/render/daemonset-norbac.yaml
- deployment/render/daemonset-rbac.yaml
I'm not sure it was on purpose or an oversight.
> deployment: add port 8443 to ds-grpc-v2's envoy

- Gopkg.lock
- Gopkg.toml
> gopkg.{lock,toml}: update dependencies

- design/routecrd.md
Initial RouteCRD design doc spec. 
> RouteCRD design spec

- docs/deploy-options.md
Arch link was broken on the deployment options page :)
Signed-off-by: John Harris <john@johnharris.io>
> Fix architecture link

- internal/contour/cluster.go
- internal/contour/virtualhost.go
> internal/contour: small cleanups and doc addition

- release-0.4.md
> Contour 0.4 draft release notes

- docs/cert-manager.md
Signed-off-by: JENNIFER RONDEAU <jrondeau@heptio.com>
Copyedits to trim length and create consistent instructions.
Still not sure the DNS record information is consistent throughout; will check again later if time.
> edit let's encrypt tutorial

- release-0.4.md
> Add release note for prometheus metric docs

- docs/deploy-options.md
Noticed these couple small issues when reading the docs. Thanks for the great tool!!
> Small grammar fix in docs/deploy-options.md

- deployment/ds-hostnet/02-contour.yaml
Signed-off-by: Cody Maloney <cody@emeraldcloudlab.com>
> Update ds-hostnet to match envoy command line, ports of other deploys

- deployment/deployment-grpc-v2/02-contour.yaml
- deployment/ds-grpc-v2/02-contour.yaml
- deployment/ds-hostnet/02-contour.yaml
- deployment/render/daemonset-norbac.yaml
- deployment/render/daemonset-rbac.yaml
- deployment/render/deployment-norbac.yaml
- deployment/render/deployment-rbac.yaml
> deployment: update image to v0.4.1

- docs/annotations.md
- internal/contour/listener.go
- internal/contour/listener_test.go
Addresses issue #185.
Signed-off-by: David Robinson <zxvdr.au@gmail.com>
> Support for setting TLS minimum protocol version

- _includes/header.html
- _includes/nav.html
- _layouts/default.html
- assets/css/style.scss
- assets/img/icon-menu.svg
- assets/js/scripts.js
Signed-off-by: JENNIFER RONDEAU <jrondeau@heptio.com>
Thanks to @rossfenrick on Ark project.
> add responsiveness, nav scrollbar

- internal/e2e/cds_test.go
- internal/e2e/rds_test.go
> internal/e2e: add cluster helper for CDS tests

- internal/contour/cache_test.go
> internal/contour: add tests for cache.Values(filter)

- internal/contour/listener.go
> internal/contour: simplify minTLS calculation

- internal/contour/listener.go
- internal/e2e/lds_test.go
Closes #300
Signed-off-by: Gorka Lerchundi Osa <glertxundi@gmail.com>
> internal/contour: add gRPC-Web support

- Makefile
- internal/grpc/server.go
Fix one small error reported by staticcheck
> Makefile: add staticcheck make check step

- Makefile
- internal/contour/annotations.go
- internal/e2e/eds_test.go
Fix two small issues found by unused
> Makefile: add unused target to make check

- internal/grpc/server.go
Fixes #363
This PR fixes a bug whereby stream watchers would jam if nothing matched
the supplied filter. This bug affected all xDS watchers, but would be
apparent in LDS.
The underlying cause was the sequence of operations in xDS is
1. receive request from envoy
2. look up the resource in the map of known types
3. construct a filter from the request and wait for the resource to
change
4. once we get a notification, filter the response
4a. if there are no resources after filtering then go to 1.
5. send response and go to 1.
The bug was 4a caused the stream watcher to block waiting for another
request object, but Envoy will not send one because we haven't replied
to the previous. The fix is in 4a to jump to 3, thereby reusing the
request that is outstanding.
Lamentably there is no test …
> internal/contour: reuse discoveryrequest if nothing matches filter

- design/ingressroute-design.md
Metrics to add to Contour and expose over `/metrics` for Prometheus to scrape. These are not contained within the current Envoy metrics. 
> Metrics proposal for IngressRoutes

- docs/troubleshooting.md
Fixes #338 
Add troubleshooting instructions for minikube installations.
> docs/troubleshooting: add note about minikube limitations

- deployment/common/common.yaml
- deployment/render/daemonset-norbac.yaml
- deployment/render/daemonset-rbac.yaml
- deployment/render/deployment-norbac.yaml
- deployment/render/deployment-rbac.yaml
Fixes https://github.com/heptio/contour/issues/384
Signed-off-by: Alex Price <awprice@gmail.com>
> fix issue with rendered daemonsets and deployments not being created properly

- Gopkg.lock
> gopkg.toml: freshen dependencies

- design/ingressroute-design.md
//cc @alexbrand @rosskukulinski @jbeda @davecheney 
> IngressRoute update / changes to increase functionality

- internal/grpc/xds.go
Fixes #420
In #350 I added the ability to filter the results of a discovery
request to address the scalability issues in sending the full copy of
the xDS caches to envoy on every request -- this was especially imporant
for EDS which would send an entire copy of the EDS cache to each
StreamEndpoints listener for every change in k8s endpoints.
As part of this change I recognised that there would be situations where
a notification that the cache had changed would result a wakeup and
calls to values for events which didn't match the filter. At the time I
mistakenly thought that if a wakeup was triggered that didn't match the
filter this would cause zero length responses to be sent to Envoy
causing EDS entries (and others) to pop in and out of existance.
For example, if you were watching for …
> internal/grpc: always send discoveryresponse with zero results

- internal/dag/dag_test.go
Adds tests for removal of ingressroute resources.
Fixes #457
> internal/dag: add ingressroute remove tests

- internal/debug/dot.go
> internal/debug: teach dot about dag.SecureVirtualHost

- internal/dag/dag.go
- internal/dag/dag_test.go
Fixes #448 
```
IngressRoute (IR) resources can either point to backend services, or delegate
a path to another IR. While building the DAG out of the IRs and routes
within each, we determine whether the route delegates to another IR.
When it does, we find the referenced IR and process it accordingly.
This processing is applied recursively until we traverse all the edges
and find a leaf route, or a route that does not delegate to another IR.
This is the base case, in which we grab the services, and add them to
the routes of the corresponding VHost.
Signed-off-by: Alexander Brand <alexbrand09@gmail.com>
```
To Do:
> internal/dag: Add support for ingressroute delegation

- deployment/common/common.yaml
- deployment/render/daemonset-norbac.yaml
- deployment/render/daemonset-rbac.yaml
- deployment/render/deployment-norbac.yaml
- deployment/render/deployment-rbac.yaml
> deployment: make delegation namespace optional in ingressroute CRD validation

- .gitignore
- Makefile
> .gitignore: ignore .vs/ turds

- internal/contour/cluster.go
- internal/contour/cluster_test.go
- internal/dag/annotations.go
- internal/dag/dag.go
- internal/dag/dag_test.go
- internal/e2e/cds_test.go
> Restore Service Circuitbreaker annotation support

- apis/contour/v1beta1/zz_generated.deepcopy.go
> apis/contour: Re-run client-go generator

- apis/contour/v1beta1/ingressroute.go
- deployment/common/common.yaml
- deployment/example-workload/ingressroute/02-basic/default-health-checks.ingressroute.yaml
- deployment/example-workload/ingressroute/02-basic/health-checks.ingressroute.yaml
- deployment/render/daemonset-norbac.yaml
- deployment/render/daemonset-rbac.yaml
- deployment/render/deployment-norbac.yaml
- deployment/render/deployment-rbac.yaml
- design/ingressroute-design.md
> Rename lbHealthCheck to healthCheck

- docs/README.md
- docs/ingressroute.md
Adds documentation for IngressRoute CRD.
Signed-off-by: Ross Kukulinski <ross@kukulinski.com>
> ingressroute documentation

- Makefile
> Makefile: disable staticcheck and unused targets

- README.md
> README.md: add goreportcard badge

- Gopkg.lock
- Gopkg.toml
- README.md
- cmd/contour/contour.go
- internal/debug/debug.go
Pick up a few changes that landed in the beta.2 branch while beta.1 was being finalised.
> Merge 0.6-beta.2 branch into master

- Makefile
> Makefile: reenable unused and staticcheck

- internal/dag/dag.go
Refactored the `processIngressRoute` function onto a method on a struct. The method only has parameters that change across recursive calls, while the rest of params now live on the struct.
Fixes #521
> internal/dag: move processIngressRoute func to a struct

- internal/dag/dag.go
Small cleanup to prepare for moving IngressRouteStatuses into dag.dag.
> internal/dag: small cleanups to dag.dag

- Makefile
- internal/dag/dag.go
Reported by unused -exported ./...
> internal/dag: remove unused public functions

- cmd/contour/contour.go
- internal/contour/adapter.go
- internal/dag/dag.go
- internal/dag/dag_test.go
- internal/debug/debug.go
- internal/metrics/metrics.go
- internal/metrics/metrics_test.go
Updates #525 by further scaffolding out Prometheus metrics and implementing the `IngressRouteTotal` metric. 
> Initial IngressRouteTotal metric wiring

- internal/dag/dag_test.go
Try to DRY up the lengthy DAG tests with a route(...) helper.
> internal/dag: introduce route helper

- design/ingressroute-design.md
> Update design docs with metrics update

- internal/contour/adapter_test.go
> internal/contour: add missing adapter tests

- cmd/contour/contour.go
- docs/ingressroute.md
Fixes #540 by allowing a comma-separated list of namespaces.
> Ingressroute ux

- cmd/contour/contour.go
- cmd/contour/contour_test.go
> cmd/contour: add parseRootNamespace tests

- internal/dag/builder.go
- internal/dag/builder_test.go
Pre-process the IngressRoutes in the dag builder to filter IngressRoutes that re-use a given FQDN, and mark them as invalid. The IngressRoutes that pass this pre-processing step are then further processed as usual.
Fixes #601
> internal/dag: invalidate ingressroutes that use the same fqdn

- internal/dag/builder.go
- internal/dag/builder_test.go
Updates #606
Move the handling of the IngressRule.IngressRuleValue.HTTP == nil
handling into a helper.
> internal/dag: introduce httppath helper

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature-enhancement-request.md
**What this PR does / why we need it**:
The PR adds standardized bug and feature-enhancement templates. Starting with sonobuoy we will apply these to all repos.
**Which issue(s) this PR fixes**
- Fixes #
N/A
**Special notes for your reviewer**:
I will start a document to track which repos have been updated with these templates.
**Release note**:
None
```
release-note
None
```
Signed-off-by: Jesse <jesse.hamilton@heptio.com>
> New templates

- internal/dag/builder.go
- internal/dag/builder_test.go
Updates #581 
Refactor dag.builder to encompass dag.ingressRouteProcessor.
> internal/dag: remove dag.ingressRouteProcessor

- internal/dag/builder.go
Updates #625
Currently lookupSecureVirtualHost takes a slice of aliases which is used when
lazy initalising the svhost record returned to the caller. This is a
problematic API for several reasons.
1. the aliases slice is passed around to all lookupSecureVirtualHost
call sites, this is redundant as aliases is not consulted if the svhost exists in the cache.
2. as aliases are not consulted if the svhost is cache, if a different
set of aliases is provided it is not clear to the caller that the
alias details will not be updated. Assuming it is known at the call site
that the svhost has been lookup up previous, nil can be passed for the
aliases set without penalty.
To resolve this situation we move responsibility for assigning the
aliases slice outside the call to lookupSecureVirtualHost. We …
> internal/dag: move svhost alias assignment outside lookupSecureVirtualHost

- internal/contour/k8s.go
Fixes #533 by ignoring updates for duplicate updates.
> internal/contour: Filter out duplicates for updates

- docs/prometheus.md
> docs/prometheus.md: update metrics/prometheus-related docs

- FAQ.md
Adds a question/answer to the FAQ around ingress vs ingressroute.
Updates #644
> faq.md: add ingress vs ingressroute question/answer

- docs/ingressroute.md
> Update docs around IngressRoute changes

- docs/annotations.md
> docs/annotations.md: add reference to IngressRoute

- README.md
- deployment/ds-hostnet-split/01-common.yaml
- deployment/ds-hostnet-split/02-rbac.yaml
- deployment/ds-hostnet-split/02-service-contour.yaml
- deployment/ds-hostnet-split/02-service-envoy.yaml
- deployment/ds-hostnet-split/03-contour.yaml
- deployment/ds-hostnet-split/03-envoy.yaml
- docs/README.md
- docs/deploy-seperate-pods.md
- docs/zenhub.md
> Update readme for Contour v0.6.0 release

- design/ingressroute-design.md
> Update IngressRoute CRD version to v1beta1

- deployment/example-workload/kuard-ingressroute.yaml
- deployment/example-workload/kuard.yaml
- docs/deploy-options.md
Updates #644 
Add instructions on how to test Contour with IngressRoute using the sample kuard deployment.
> docs: add ingressroute to deploy-options.md

- docs/about.md
> Add docs on DAG & IngressRoute objects

- Gopkg.lock
- internal/dag/builder_test.go
Introduce go-cmp in builder_test.go
> internal/dag: introduce go-cmp

- internal/dag/builder.go
> internal/dag: refactor minProtoVersion selection

- design/roadmap.md
Signed-off-by: Ross Kukulinski <ross@kukulinski.com>
> Fixes #658.  Update Roadmap.md file

- Gopkg.lock
- Gopkg.toml
> Gopkg.toml: unpin logrus and update to latest version

- Gopkg.lock
- Gopkg.toml
> Gopkg.toml: switch to latest grpc

- Gopkg.lock
- Gopkg.toml
For compatibility  with grpc 1.15.0
> gopkg.toml: update to protobuf 1.2.0

- deployment/common/common.yaml
- deployment/deployment-grpc-v2/02-contour.yaml
- deployment/ds-grpc-v2/02-contour.yaml
- deployment/ds-hostnet-split/03-envoy.yaml
- deployment/ds-hostnet/02-contour.yaml
- deployment/render/daemonset-rbac.yaml
- deployment/render/deployment-rbac.yaml
Resolves #443
To test this, I've upgraded the Envoy in an existing Contour setup and everything continued to work fine. If there is something more I can do to verify this change, please do tell.
> Upgrade envoy to v1.7.0

- apis/contour/v1beta1/zz_generated.deepcopy.go
- apis/generated/clientset/versioned/fake/register.go
- apis/generated/informers/externalversions/contour/v1beta1/ingressroute.go
> apis/...: regenerate generated code

- Gopkg.lock
- Gopkg.toml
- apis/generated/clientset/versioned/clientset.go
- apis/generated/clientset/versioned/fake/clientset_generated.go
- apis/generated/clientset/versioned/typed/contour/v1beta1/fake/fake_ingressroute.go
- apis/generated/informers/externalversions/factory.go
> gopkg.toml: upgrade generator to 1.11.3 and regenerate

- deployment/ds-hostnet-split/03-envoy.yaml
> Update the dns policy to match recommendation for pods running with hostNetork: true

- internal/envoy/cluster.go
- internal/envoy/cluster_test.go
> internal/envoy: dry up Cluster_CommonLbConfig generation

- Gopkg.lock
- internal/contour/listener.go
- internal/e2e/lds_test.go
> Hardcoded maximum tls version to 1.3

- internal/grpc/server_test.go
Fixes #705
Totally gross, but at least I didn't bump the timeout. Huzzah!
> internal/grpc: be more lenient with deadline exceeded status codes

- docs/ingressroute.md
> Fixed typo in IngressRoute prefix rewrite readme

- internal/contour/listener.go
- internal/contour/listener_test.go
- internal/e2e/lds_test.go
- internal/envoy/listener.go
- internal/envoy/listener_test.go
> internal/contour: move tlscontext to envoy.DownstreamTLSContext

- internal/contour/endpointstranslator.go
- internal/contour/endpointstranslator_test.go
- internal/e2e/eds_test.go
- internal/envoy/endpoint.go
- internal/envoy/endpoint_test.go
> internal/contour: move lbendpoint to envoy.LBEndpoint

- internal/contour/route.go
- internal/envoy/healthcheck_test.go
- internal/envoy/route.go
- internal/envoy/route_test.go
> internal/contour: move retry on support to envoy.RouteRoute

- internal/e2e/rds_test.go
RDS tests for routes with explicit lb strategies - fixes #681
> RDS tests for routes with explicit lb strategies

- internal/dag/builder.go
- internal/dag/builder_test.go
- internal/dag/dag.go
- internal/envoy/cluster.go
- internal/envoy/cluster_test.go
> internal/dag: add dag.TCPService Vertex implementation

- deployment/ds-hostnet/02-service.yaml
> deployment: add missing service to ds-hostnet example

- docs/deploy-aws-nlb.md
Signed-off-by: Joe Beda <joe.github@bedafamily.com>
> Update docs on AWS NLB

- .dockerignore
- Gopkg.lock
- Gopkg.toml
> Gopkg.toml: freshen depdenencies

- internal/contour/cluster.go
- internal/dag/builder.go
- internal/dag/builder_test.go
- internal/dag/dag.go
Handle TCPService objects in the dag.
> internal/contour: handle dag.TCPService objects

- docs/proxy-proto.md
closes #818 
Signed-off-by: Wade Holler wade.holler@ndatum.net
> update proxy-proto.md to have list sytax like get started yaml

- docs/ingressroute.md
Signed-off-by: Jonas Fonseca <jonas.fonseca@gmail.com>
> Fix typo in the IngressRoute TCP proxying docs

- internal/contour/holdoff.go
This shouldn't have made it into 0.8. Removing for 0.8.1
> internal/contour: remove "delaying update" log spam

- docs/tls.md
> docs: remove stale reference to upgrade.md

- deployment/common/common.yaml
- deployment/render/daemonset-rbac.yaml
- deployment/render/deployment-rbac.yaml
> deployment: remove requirement for spec.routes to be present

- Dockerfile
- Gopkg.lock
- Gopkg.toml
> Freshen dependencies

- docs/cert-manager.md
Fix cert-manager deployment instructions in docs/cert-manager.md
> cert-manager.md: Fix cert-manager deployment

- .travis.yml
- Dockerfile
> Upgrade to Go 1.11

- internal/dag/builder.go
> internal/dag: report missing service port in tcpproxy status

- deployment/deployment-grpc-v2/02-contour.yaml
- deployment/ds-grpc-v2/02-contour.yaml
- deployment/ds-hostnet-split/03-envoy.yaml
- deployment/ds-hostnet/02-contour.yaml
- deployment/render/daemonset-rbac.yaml
- deployment/render/deployment-rbac.yaml
> deployment: upgrade to envoy 1.9.0

- Gopkg.lock
- Gopkg.toml
- internal/dag/dag.go
> Gopkg.toml: update to k8s 1.11.7

- Makefile
Add a local target to generate a bootstrap config and run a local
envoy instance against it.
> Makefile: add local target

- internal/envoy/bootstrap.go
- internal/envoy/bootstrap_test.go
> Restore configuration flags removed in #738

- internal/dag/builder.go
Updates #661
Remove the port parameter from the lookup methods. It was always 80 or
443 depending on the variant used, so make it a constant inside the
function.
Remove hostport, it is not needed.
> internal/dag: remove port parameter from lookup{Secure}Vhost

- internal/contour/listener_test.go
- internal/e2e/lds_test.go
Fixes #475
Signed-off-by: Amarnath <vaamarnath@gmail.com>
> Adds missing tests for envoy access logs options

- design/secret-delegation.md
- design/tls-certificate-delegation.md
> design: add TLSCertificateDelegation design draft

- cmd/contour/cli.go
- cmd/contour/contour.go
- internal/contour/route.go
- internal/dag/builder.go
- internal/dag/builder_test.go
- internal/debug/dot.go
- internal/httpsvc/http.go
- internal/metrics/metrics_test.go
> all: address some issues identified by gocritic

- internal/dag/builder_test.go
> internal/dag: dry up tests with a method expression

- apis/contour/v1beta1/ingressroute.go
I successfully tested the fix (both server and client). Fixes #917.
> Omit Empty Secret Name

- Makefile
> Makefile: only tag latest when TAG_LATEST set to true

- deployment/deployment-grpc-v2/02-contour.yaml
- deployment/ds-grpc-v2/02-contour.yaml
- deployment/ds-hostnet/02-contour.yaml
- deployment/render/daemonset-rbac.yaml
- deployment/render/deployment-rbac.yaml
> deployment: switch to envoyproxy/envoy

- internal/e2e/cds_test.go
- internal/envoy/cluster_test.go
> E2E tests drain connections host removal

- Gopkg.lock
- Gopkg.toml
> Gopkg.toml: Upgrade to envoyproxy/go-control-plane 0.6.8

- Gopkg.toml
> Gopkg.toml: use kubernetes-* tag for client-go

- .travis.yml
- Makefile
Fixes build error on missing target
> travis.yaml: remove mod vendor step

- internal/dag/builder.go
- internal/dag/builder_test.go
> internal/dag: clean up some dag builder tests

- go.mod
- internal/contour/cluster_test.go
- internal/contour/visitor_test.go
- internal/e2e/cds_test.go
- internal/envoy/bootstrap.go
- internal/envoy/cluster.go
- internal/envoy/cluster_test.go
- internal/grpc/server.go
> go.mod: upgrade to go-control-plane v0.6.9

- go.mod
> go.mod: update golang.org/x/{crypto,net,sys}

- design/custom-request-timeout.md
Updates #815
Signed-off-by: Prasoon Telang <telangp@vmware.com>
> design: Support Custom Request Timeout

- docs/github.md
> doc: document how we use github on this project.

- go.mod
> go.mod: freshen dependencies for the 0.12 cycle

- go.mod
> go.mod: upgrade mdempsky/unconvert

- Makefile
> Makefile: fail the build if go.mod is stale

- Makefile
- go.mod
- hack/update-generated-crd-code.sh
- tools.go
Closes #996
Signed-off-by: Gorka Lerchundi Osa <glertxundi@gmail.com>
> modules: pin dependencies and fix updategenerated

- design/sds-design.md
Updates #898
Signed-off-by: Madhavan <bmadhavan@ebay.com>
> Initial draft of design for SDS support on Contour

- internal/dag/builder.go
- internal/dag/builder_test.go
Simplify per try timeout parsing using parseTimeout. Added a test to
ensure that an invalid per try timeout is parsed as 0 -- not set -- not
-1 -- infinite.
> internal/dag: clean up per try timeout parsing

- internal/contour/holdoff.go
Adds an atomic counter tracking the number of changes compacted by the
holdoff notifier.
Updates #499
Updates #1022
> internal/contour: track pending changes in holdoff notifier

- cmd/contour/contour.go
- internal/dag/builder_test.go
- internal/envoy/route_test.go
> all: fix a few lint warnings

- deployment/example-workload/ingressroute/02-basic/request-timeout.ingressroute.yaml
- docs/ingressroute.md
Updates: #1019
Signed-off-by: Rohan Vora <vorar@vmware.com>
> Documentation for request-timeout

- Dockerfile
Fixes #1066 
Hopefully this will be the last minor bump in the 1.12 series.
> Dockerfile: upgrade to Go 1.12.5

- internal/envoy/listener.go
> internal/envoy: convert HTTPConnectionManager to TypedConfig

- internal/dag/builder.go
Fixes #517 by setting the status of an IngressRoute if the TLS secret is not found or malformed. 
Example:
```
Status:
Current Status:  invalid
Description:     TLS Secret not found or is malformed
```
> Validate secret and set status on IngressRoute if secret is invalid 

- docs/how-we-work.md
The team is growing 🎉 it seems like a good time to write down the way we work.
> docs: add how we work document

- internal/envoy/cluster.go
> Fix small linting errors.

- deployment/deployment-grpc-v2/02-contour.yaml
- deployment/ds-grpc-v2/02-contour.yaml
- deployment/ds-hostnet-split/03-contour.yaml
- deployment/ds-hostnet-split/03-envoy.yaml
- deployment/ds-hostnet/02-contour.yaml
- deployment/render/daemonset-rbac.yaml
- deployment/render/deployment-rbac.yaml
> deployment: update deployment for v0.12.1

- internal/dag/dag.go
> internal/dag: remove unused Route field

- internal/dag/builder.go
- internal/dag/builder_test.go
- internal/dag/dag.go
- internal/envoy/cluster.go
- internal/envoy/cluster_test.go
- internal/envoy/healthcheck.go
- internal/envoy/healthcheck_test.go
Fixes #1145
Move HealthCheck parameter to dag.Cluster.
> internal/dag: move HealthCheck to dag.Cluster

- design/session-affinity.md
> design: add session affinity draft

- docs/ingressroute.md
Fixes #1160
Signed-off-by: Mitz Amano <mitz@linux.com>
> docs: Fix "permitInsecure: true" example with to work option properly

- design/session-affinity.md
- docs/ingressroute.md
- examples/common/common.yaml
- examples/render/daemonset-rbac.yaml
- examples/render/deployment-rbac.yaml
- internal/contour/route.go
- internal/e2e/rds_test.go
- internal/envoy/cluster.go
- internal/envoy/cluster_test.go
- internal/envoy/route.go
- internal/envoy/route_test.go
> internal/envoy: implement hash cookie policy session affinity

- internal/e2e/e2e.go
- internal/e2e/sds_test.go
> internal/e2e: add SDS test

- _integration/ingressroute-naming-test.yaml
- examples/common/common.yaml
- examples/render/daemonset-rbac.yaml
- examples/render/deployment-rbac.yaml
Update IngressRoute validation regex
Fixes #755
Fixes #1117
> Update IngressRoute validation regex and add test yaml

- internal/grpc/xds.go
Updates #499
Updates #273
Updates #1176
The [XDS spec](https://www.envoyproxy.io/docs/envoy/latest/api-docs/xds_protocol#when-to-send-an-update) says that Envoy will always initiate a stream with a
discovery request, and expects the management server to respond with
only one discovery response. After that, Envoy will initiate another
discovery request containing an ACK or a NACK from the previous
response.
Currently Contour ignores the ACK/NACK, this is #1176, however after
inspection of the current code it is evident that we're also not waiting
for Envoy to send the next discovery request.
This PR removes the inner `for {}` loop that would continue to reuse the
initial discovery request until the client disconnected. The previous
code was written in a time when we'd just implemented …
> internal/grpc: handle one response per request

- docs/deploy-options.md
Fixes #1196 by updating kind docs for new 0.4.0 version. 
> docs: Update kind deployment configuration

- apis/generated/clientset/versioned/clientset.go
- apis/generated/clientset/versioned/fake/clientset_generated.go
- apis/generated/clientset/versioned/typed/contour/v1beta1/fake/fake_ingressroute.go
- apis/generated/clientset/versioned/typed/contour/v1beta1/fake/fake_tlscertificatedelegation.go
- apis/generated/clientset/versioned/typed/contour/v1beta1/ingressroute.go
- apis/generated/clientset/versioned/typed/contour/v1beta1/tlscertificatedelegation.go
- apis/generated/informers/externalversions/internalinterfaces/factory_interfaces.go
- go.mod
> go.mod: upgrade to client-go v11.0.0

- cmd/contour/contour.go
Fixes #1210
Updates #371
Blocked:
> cmd/contour: remove glog turds

- go.mod
> go.mod: freshen dependencies

- cmd/contour/bootstrap.go
- cmd/contour/contour.go
This PR is the start of a series attempting to counter the bloat of
cmd/contour's main.main function. It established a pattern where we pass
into a helper function the kingpin Application object. The helper
registers the flags it needs and returns a context type object which
holds the references to all the flags needed by the subcommand. The
context object is later passed back to the function executing the
subcommand so it can pick up the context it established with its flags.
This is a little verbose, but preferable to pooping global variables
everywhere.
Additionally, the config.Namespace envvar helper was replaced with a
flag on bootstrap called `--namespace` which takes its value from Envar
first, then the flag secondly.
> cmd/contour: refactor bootstrap flag and command handling

- examples/grafana/02-grafana-configmap.yaml
> Update axes on example Envoy latency graphs to match metric

- cmd/contour/contour.go
- cmd/contour/serve.go
As all of the parameters for setupTLSContext were supplied by
serveContext, move the helper there. The replacement method, tlsconfig
is safe to call multiple times -- while the values from calling this
method twice won't be identical, they come from the same source, so are
effectively equal (not that we'd do that anyway, but it's smart to plan
ahead).
While here, clean up the error handling in tlsconfig -- and actually
check the error from loading a cert.
Lastly simplify the "is tls enabled check" to be just "is the value from
tlsconfig nil, if so, no tls"
> cmd/contour: move setupTLSContext to a method on serveCtx

- cmd/contour/contour.go
- cmd/contour/serve.go
> cmd/contour: move metrics' service parameters to serveContext

- cmd/contour/contour.go
- cmd/contour/serve.go
- cmd/contour/serve_test.go
> cmd/contour: move ingressroute root ns to serveContext

- Makefile
- cmd/contour/certgen.go
- cmd/contour/contour.go
- docs/deploy-seperate-pods.md
- docs/grpc-tls-howto.md
- go.mod
- internal/certgen/certgen.go
- internal/certgen/certgen_test.go
> Add `certgen` subcommand with output to PEM format.

- cmd/contour/contour.go
- cmd/contour/serve.go
> cmd/contour: move serve subcommand handling to doServe

- cmd/contour/certgen.go
- cmd/contour/certgen_test.go
- cmd/contour/contour.go
- docs/deploy-seperate-pods.md
- examples/ds-hostnet-split/02-job-certgen.yaml
- examples/ds-hostnet-split/03-contour.yaml
- examples/ds-hostnet-split/03-envoy.yaml
- internal/certgen/certgen.go
- internal/certgen/certgen_test.go
- internal/certgen/k8s.go
- internal/certgen/makecerts.go
- internal/certgen/output.go
> Add `--yaml` and `--kube` output options to `certgen` subcommand

- site/_posts/2019-07-23-contour-v014.md
> Remove Contour logo from blog post

- site/_posts/2019-07-23-contour-v014.md
> Fix spacing issue with v0.14 blog post

- docs/deploy-seperate-pods.md
- docs/grpc-tls-howto.md
Signed-off-by: Sudeepto Roy <sudeepto.roy@gmail.com>
> corrected the commands and the variable names

- go.mod
contour: Upgrade to client-go v12
Fixes #1213 
Signed-off-by: Dylan Graham <dylan.graham@gmail.com>
> go.mod: Upgrade to client-go v12

- .travis.yml
> travis.yml: speed up build by caching go build artifacts

- go.mod
> go.mod: upgrade to go-control-plane v0.8.2

- examples/deployment-grpc-v2/02-contour.yaml
- examples/ds-grpc-v2/02-contour.yaml
- examples/ds-hostnet-split/03-envoy.yaml
- examples/ds-hostnet/02-contour.yaml
- examples/render/daemonset-rbac.yaml
- examples/render/deployment-rbac.yaml
> examples: upgrade to envoy 1.11.0

- internal/contour/cluster.go
- internal/contour/listener.go
- internal/contour/listener_test.go
- internal/contour/visitor_test.go
- internal/e2e/cds_test.go
- internal/e2e/e2e.go
- internal/e2e/eds_test.go
- internal/e2e/lds_test.go
- internal/e2e/rds_test.go
- internal/e2e/sds_test.go
- internal/envoy/listener.go
> internal/envoy: move several helpers to internal/envoy

- internal/contour/cachehandler.go
- internal/contour/cachehandler_test.go
> internal/contour: simplify bulk status setting

- .travis.yml
- go.mod
> travis.yml: switch to proxy.golang.org

- Makefile
- Add $(MODULE) var to avoid excessive globbing
- No need to install ./... when the only command to install is ./cmd/contour
> Makefile: clean up makefile

- Dockerfile
> Dockerfile: update GOPROXY

- internal/e2e/e2e.go
- internal/e2e/rds_test.go
> internal/e2e: remove disablePermitInsecure global

- cmd/contour/serve.go
- internal/contour/cachehandler.go
- internal/contour/k8s.go
- internal/e2e/rds_test.go
> internal/contour: move DisablePermitInsecure to ResourceEventHandler

- Makefile
- examples/deployment-grpc-v2/02-contour.yaml
- examples/ds-grpc-v2/02-contour.yaml
- examples/ds-hostnet-split/03-envoy.yaml
- examples/ds-hostnet/02-contour.yaml
- examples/render/daemonset-rbac.yaml
- examples/render/deployment-rbac.yaml
> Update Envoy to 1.11.1 version

- Makefile
- examples/deployment-grpc-v2/02-contour.yaml
- examples/ds-grpc-v2/02-contour.yaml
- examples/ds-hostnet-split/03-envoy.yaml
- examples/ds-hostnet/02-contour.yaml
- examples/render/daemonset-rbac.yaml
- examples/render/deployment-rbac.yaml
> [backport] Update Envoy to 1.11.1

- Dockerfile
> Update dockerfile 0.14

- README.md
Taking a leaf from ocatant's book.
> readme: update readme badges

- Dockerfile
Is it Friday? Must be time to update Go again this week :)
> Dockerfile: update to Go 1.12.9

- examples/common/common.yaml
- examples/render/daemonset-rbac.yaml
- examples/render/deployment-rbac.yaml
> examples: remove validation of non existant ingressroute fields

- examples/common/common.yaml
- examples/render/daemonset-rbac.yaml
- examples/render/deployment-rbac.yaml
> examples: add validation for spec.tcpproxy

- internal/grpc/xds.go
Updates #1176
The xDS spec says that if Envoy NACKs an update we shouldn't try to send
it again. Given that the update came from k8s and was translated by Contour
either theres a bug in our translation or a mistake in the data that a user
entered into K8s.
For 0.15 log the NACK at ERROR level in the hope that this will give us
some visibility into what kind of invalid configuraion we're
transmitting to Envoy and the frequency of those mistakes.
Ideally we'd be able to trace a NACK all the way back to the originating
record and cordon it. However, given that records like RDS and LDS are
gestalts, cordoning the invalid part of the configuration is rather
complicated. Perhaps the better solution would be to strengthen our
validation to prevent these errors reaching Envoy.
Signed-off-by: Dave …
> internal/grpc: log xDS NACK messages at ERROR level

- internal/envoy/bootstrap.go
Updates #1159
Clean up envoy.Bootstrap with a few helper methods.
> internal/envoy: clean up bootstrap config

- Makefile
> Makefile: remove extraneous period in Makefile

- internal/contour/endpointstranslator.go
- internal/contour/endpointstranslator_test.go
- internal/e2e/eds_test.go
- internal/envoy/endpoint.go
- internal/envoy/endpoint_test.go
> internal/envoy: clean up ClusterLoadAssignment helpers

- internal/workgroup/group.go
- internal/workgroup/group_test.go
Add native support for functions which take a context.Context
not a stop <-chan.
> internal/workgroup: add support for func(context.Context) jobs

- internal/e2e/lds_test.go
> internal/e2e: add e2e tests for global minimum tls version

- internal/e2e/cds_test.go
> internal/e2e: port over e2e test from #1171

- Dockerfile
> Dockerfile: switch to Go1.13rc1

- go.mod
> go.mod: freshen dependencies for 1.0.0-beta.1 cycle

- internal/contour/route.go
- internal/contour/route_test.go
- internal/e2e/rds_test.go
- internal/envoy/route.go
- internal/envoy/route_test.go
> internal/envoy: introduce envoy.Route helper

- cmd/contour/serve.go
Adds a SIGTERM handler to `contour serve`.
Fixes #1364
> cmd/contour: add SIGTERM handler for graceful shutdown

- internal/contour/contour_test.go
- internal/contour/endpointstranslator_test.go
> internal/contour: clean up endpointtranslator tests

- internal/e2e/eds_test.go
Updates #1159
The names of ports in a service is defined by the service, _not_ the pod
spec. Thus it is not possible for a namespace+name+portname to refer to
more than one port number. The foo/9999 foo/8000 example cannot happen
in the wild because it is not possible to construct Service document
that has two named ports, Name: foo, Port 9999 AND Name: foo, Port:
8000.
As this condition is not possible, replace it by moving the port to the
NotReadySet and adjust the expected output.
> internal/e2e: fix invalid fixture

- design/delegation.md
I wanted to write down my understanding of the various mental models we have for discussing delegation.
> design: add delegation draft

- Dockerfile
- go.mod
> go.mod,Dockerfile: upgrade to Go 1.13rc2

- internal/dag/builder_test.go
- internal/dag/status_test.go
Updates #865
Status is invalid but the message is not correct, marketing/blog should
have been rejected as it is an ingressroot.
> internal/dag: add test for 865

- internal/dag/builder.go
> internal/dag: simplify dag TCPService generation

- .github/workflows/build_master.yaml
No way to test it without it being on master, yay.
> initial test run

- examples/common/common.yaml
- examples/common/job-certgen.yaml
- examples/common/rbac.yaml
- examples/contour/02-service-contour.yaml
- examples/contour/02-service-envoy.yaml
- examples/contour/03-contour.yaml
- examples/contour/03-envoy.yaml
- examples/render/contour.yaml
- examples/render/daemonset-rbac.yaml
- examples/render/deployment-rbac.yaml
> examples: fix missing yaml separators

- internal/dag/builder.go
- internal/dag/status_test.go
> internal/dag: report certificate delegation failure correctly

- internal/dag/status_test.go
Fixes #1348
Add test for same failure as #1347
> internal/dag: add test for issue 1348

- docs/making-a-release.md
> Add release documentation.

- docs/troubleshooting.md
> Update troubleshooting instructions for split-by-default.

- internal/dag/builder.go
- internal/dag/builder_test.go
- internal/dag/status_test.go
- internal/e2e/lds_test.go
> internal/dag: mark ingressroute as invalid if tls details incorrect

- examples/common/contour-config.yaml
- examples/render/contour.yaml
- examples/render/daemonset-rbac.yaml
- examples/render/deployment-rbac.yaml
Signed-off-by: Sudeepto Roy sudeepto.roy@gmail.com
> examples/common: corrected a config parameter

- site/_redirect
> site: redirect /quickstart/contour.yaml to most recent release

- CONTRIBUTING.md
- Makefile
- docs/proxy-proto.md
- docs/tagging.md
- docs/upgrading.md
- examples/common/job-certgen.yaml
- examples/contour/03-contour.yaml
- examples/contour/03-envoy.yaml
- examples/deployment-grpc-v2/02-contour.yaml
- examples/ds-grpc-v2/02-contour.yaml
- examples/ds-hostnet-split-httploadbalancer/02-job-certgen.yaml
- examples/ds-hostnet-split-httploadbalancer/03-contour.yaml
- examples/ds-hostnet-split-httploadbalancer/03-envoy.yaml
- examples/ds-hostnet-split/02-job-certgen.yaml
- examples/ds-hostnet-split/03-contour.yaml
- examples/ds-hostnet-split/03-envoy.yaml
- examples/ds-hostnet/02-contour.yaml
- examples/render/contour.yaml
- examples/render/daemonset-rbac.yaml
- examples/render/deployment-rbac.yaml
> Remove GCR from everywhere.

- site/_config.yml
> Update config for redirect

- internal/e2e/rds_test.go
Adds mostly all of the matching `IngressRoute` e2e tests for RDS applied to `HTTPProxy`.
> internal/e2e: Add e2e tests for RDS with HTTPProxy

- internal/dag/builder.go
- internal/dag/status.go
- internal/dag/status_test.go
Add HTTPProxy tests to dag/builder.go
Fixes #1459
> internal/dag: AddHTTPProxy tests

- docs/ingressroute.md
resulting page was rendered bad on the github page.
> docs/ingressroute.md - format improvement

- cmd/contour/servecontext.go
- docs/structured-logs.md
- examples/contour/01-contour-config.yaml
- examples/render/contour.yaml
Fixes #624.
Also update a small bug in config file definition that can lead to parsing weirdness.
> Add documentation for structured logs.

- site/_posts/2019-09-17-projectcontour.md
> site: add repository move blog post

- docs/upgrading.md
Updates #1476
Draft, first cut of the upgrade documentation.
> docs: update upgrading.md for Contour 1.0.0-beta.1

- internal/contour/route_test.go
- internal/featuretests/envoy.go
Remove two unused helper functions.
> internal/{contour,featuretests}: remove unused functions

- docs/upgrading.md
> Update upgrading guide with more 1.0.0-beta1 info

- internal/contour/route.go
- internal/contour/route_test.go
- internal/dag/builder.go
Merge all conditions for a route when multiple are defined for allowing for a final full pathPrefix.
> internal/contour: Merge conditions for pathPrefix

- internal/e2e/e2e.go
The featuretests compare two proto's in a way that isn't impossible to
debug. Even though e2e is going away, port this over to make it easier
to debug bringing the HTTPProxy tests back online.
Nick: yes, this would be the third time we've written this code.
Probably time for a helper package.
> internal/e2e: port over assertEquals fix from featuretests

- internal/e2e/rds_test.go
- internal/featuretests/ingressclass_test.go
> internal/{e2e,featuretests}: restore HTTPProxy tests

- internal/assert/assert.go
- internal/e2e/cds_test.go
- internal/e2e/e2e.go
- internal/e2e/eds_test.go
- internal/e2e/lds_test.go
- internal/e2e/rds_test.go
- internal/envoy/accesslog_test.go
- internal/envoy/listener_test.go
- internal/featuretests/featuretests.go
Introduce an assertion test helper package to DRY up the many calls to
cmp.Diff.
> internal/assert: new package

- docs/httpproxy.md
Updates #1462
Document HTTPProxy using the IngressRoute docs as a base.
> docs: add draft HTTPProxy documentation

- docs/httpproxy.md
- examples/example-workload/httpproxy/00-common/00-namespaces.yaml
- examples/example-workload/httpproxy/00-common/01-services.yaml
- examples/example-workload/httpproxy/00-common/02-deployments.yaml
- examples/example-workload/httpproxy/01-ingress-to-httpproxy/basic-httpproxy.yaml
- examples/example-workload/httpproxy/01-ingress-to-httpproxy/httpproxy-name.yaml
- examples/example-workload/httpproxy/01-ingress-to-httpproxy/httpproxy-tls.yaml
- examples/example-workload/httpproxy/02-tls-options/httpproxy-tls-cert-delegation.yaml
- examples/example-workload/httpproxy/02-tls-options/httpproxy-tls-upstream.yaml
- examples/example-workload/httpproxy/03-routes/httpproxy-externalname.yaml
- examples/example-workload/httpproxy/03-routes/httpproxy-health-checks.yaml
- examples/example-workload/httpproxy/03-routes/httpproxy-lb-strategy.yaml
- examples/example-workload/httpproxy/03-routes/httpproxy-multiple-headers.yaml
- examples/example-workload/httpproxy/03-routes/httpproxy-multiple-paths.yaml
- examples/example-workload/httpproxy/03-routes/httpproxy-multiple-upstreams.yaml
- examples/example-workload/httpproxy/03-routes/httpproxy-prefix-rewrite.yaml
- examples/example-workload/httpproxy/03-routes/httpproxy-request-timeout.yaml
- examples/example-workload/httpproxy/03-routes/httpproxy-sticky-sessions.yaml
- examples/example-workload/httpproxy/03-routes/httpproxy-tls-permitinsecure.yaml
- examples/example-workload/httpproxy/03-routes/httpproxy-websockets.yaml
- examples/example-workload/httpproxy/03-routes/httpproxy-weight-shfiting.yaml
- examples/example-workload/httpproxy/04-tcp-proxy/httpproxy-tls-passthrough.yaml
- examples/example-workload/httpproxy/04-tcp-proxy/httpproxy-tls-termination.yaml
- Add `examples/example-workload/httpproxy/` directory.
- Update timeoutPolicy documentation. Fixes #1553
See #1462 for full TODO list.
> Update docs for httploadbalancer

- internal/dag/builder.go
- internal/dag/status_test.go
- Fix commented out status tests
- Fix issue where status wasn't getting set properly on any Proxy that
has includes
> internal/dag: Fix status tests & setting status on proxies with includes

- docs/httpproxy.md
Updates #459
Add traffic mirroring documentation.
> docs: document mirror: true

- internal/dag/status_test.go
Updates #1425
Updates #1449
They're not different enough to carry the duplication.
> internal/dag: merge proxy and ingressroute status tests

- internal/e2e/rds_test.go
> internal/e2e: Add Header Condition tests to E2E route

- site/_posts/2019-09-27-from-ingressroute-to-httpproxy.md
> site: add blog post for IngressRoute to HTTPProxy transition

- internal/dag/builder_test.go
Re-enable some disabled httpproxy tests.
> internal/dag: re-enable proxy tests

- docs/httpproxy.md
> Update heading to be correct.

- design/routing-design.md
> design: Rev routing design doc

- internal/dag/builder_test.go
> internal/dag: add HeaderCondition test fixtures

- go.mod
- go.sum
Why there are so many updates to the sum file I have no idea.
> go.mod: update go version to 1.13

- internal/dag/builder_test.go
- internal/dag/cache_test.go
- internal/dag/secret.go
Updates #1164
Skip validation of ca.crt.
> internal/dag: do not attempt to validate ca.crt

- internal/dag/builder_test.go
- internal/dag/cache_test.go
- internal/dag/secret.go
Updates #1164
Fixes #1647 
Skip validation of ca.crt.
> [0.15] internal/dag: do not attempt to validate ca.crt

- docs/upgrading.md
> docs: update upgrading document for 0.15.1

- internal/dag/builder.go
- internal/dag/conditions.go
- internal/dag/conditions_test.go
- internal/dag/status_test.go
> Require prefix conditions to start with a /

- Makefile
- examples/deployment-grpc-v2/02-contour.yaml
- examples/ds-grpc-v2/02-contour.yaml
- examples/ds-hostnet-split/03-envoy.yaml
- examples/ds-hostnet/02-contour.yaml
- examples/render/daemonset-rbac.yaml
- examples/render/deployment-rbac.yaml
Fixes #1583
Not to be merged until October 8.
> backport: Upgrade Envoy to v.11.2 [0.15]

- Makefile
> Add some Makefile help.

- cmd/contour/bootstrap.go
- internal/envoy/config.go
This reverts commit cc8a44bc5546b9634a583c010592b227515cf407.
This fixes #1669.
> Revert "Add an option to emit bootstrap config to stdout."

- internal/dag/annotations.go
Add a helper function to consolidate checking for legacy
`contour.heptio.com` annotations.
Updates #1506
> internal/dag: consolidate compatibility annotation checks

- docs/upgrading.md
> docs: add rc.1 to upgrading guide

- site/_config.yml
- site/examples/proxydemo/01-prereq.yaml
- site/examples/proxydemo/02-proxy-basic.yaml
- site/examples/proxydemo/03-proxy-conditions.yaml
- site/examples/proxydemo/04-marketing-prereq.yaml
- site/examples/proxydemo/04-proxy-include-basic.yaml
- site/examples/proxydemo/05-proxy-include-info.yaml
- site/examples/proxydemo/06-proxy-include-headers.yaml
This is the first part of a new blog post demonstrating`HTTPProxy`. The content in in review inside a Google Doc, this just connects the dots with how the links are setup and referenced from the blog post content. 
> site/examples: HTTPProxy in action blog post additional examples

- internal/contour/route.go
- internal/contour/route_test.go
Ensure that the HeaderMatch slice on each Route is ordered. This
lets us endure that Route messages which have the same prefix and
number of header matches sort stably and will not cause unnecessary
Envoy API updates.
The previous code ordered the routes by first by the length of the
header match slice and then by the length of the prefix or regex
match. This change reverses that, but there is no net change in how
routes will be matched.
This fixes #1579.
> internal/contour: order the route header match list

- docs/ingressroute.md
- examples/contour/README.md
- site/_guides/cert-manager.md
- site/_guides/deploy-aws-nlb.md
- site/_guides/deploy-options.md
- site/_guides/structured-logs.md
> doc: fix broken links in the guide documentation

- docs/README.md
- site/_config.yml
- site/_docs_1_0/annotations.md
- site/_docs_1_0/configuration.md
- site/_docs_1_0/httpproxy.md
- site/_docs_1_0/ingressroute.md
- site/_guides/cert-manager.md
- site/_resources/ingressroute-to-httpproxy.md
- site/_resources/upgrading.md
- site/about.md
- site/architecture.md
- site/docs.md
> site: move the remainder of /docs to /site

- docs/upgrading.md
> docs: update upgrading doc for 0.15.2

- examples/deployment-grpc-v2/02-contour.yaml
- examples/ds-grpc-v2/02-contour.yaml
- examples/ds-hostnet-split/02-job-certgen.yaml
- examples/ds-hostnet-split/03-contour.yaml
- examples/ds-hostnet-split/03-envoy.yaml
- examples/ds-hostnet/02-contour.yaml
- examples/render/daemonset-rbac.yaml
- examples/render/deployment-rbac.yaml
> examples: update image version to v0.15.2

- .dockerignore
- Dockerfile
Fixes #1725
Also, add /site to .dockerignore.
> Dockerfile: update to Go 1.13.3

- cmd/contour/bootstrap.go
Add bootstrap subcommand support emissing the bootstrap JSON to
standard output by specifying the output file as `-`. The required
invocation to use this then becomes:
```
$ contour bootstrap -- -
```
The `--` is required so that the single `-` isn't interpreted as
an invalid flag.
> Add an option to emit bootstrap config to stdout.

- site/_docs_1_0/httpproxy.md
> Update annotation name to new standard.

- internal/contour/handler.go
This PR addresses incorrect comments that I noticed during #1745.
Something I noticed doing this is the holdoff logic is as follows.
1. When the EventHandler is created e.last is set to time.Now, this
causes the stream of updates from the informers to be heldoff for up to
e.HoldoffDelay + e.HoldoffMaxDelay. This process may happen several
times until all updates from the API server are processed.
2. Once the cluster settles down the _next_ update from the API server
will likely be larger than e.HoldoffMaxDelay from e.last and will be
processed _immediately_.
3. If another update arrives after 2. but before another
e.HoldoffMaxDelay then a pending timer will be started and the update
processed after e.HoldoffDelay.
The long and the short of the current logic is infrequent, O(seconds), …
> internal/contour: clean up holdoff timer

- site/_resources/upgrading.md
Fixes #1603
There are no specific upgrade instructions at the moment.
> site: add rc.1 to rc.2 upgrade notes

- site/_config.yml
- site/_includes/footer.html
- site/index.html
Updates #1619
Enables strict mode and fix strict mode failures.
> site: enable strict mode

- cmd/contour/servecontext.go
> Add gRPC keepalives for Contour->Envoy comms

- internal/envoy/bootstrap.go
- internal/envoy/bootstrap_test.go
> Add TCP Keepalives for Envoy->Contour xDS comms

- internal/envoy/route.go
- internal/envoy/route_test.go
Fixes #1751 by escaping characters that are special to a regex expression when type is 'contains' for a header matcher condition. 
> internal/envoy: Escape regex strings for header type contains

- design/routing-design.md
Updates #1179 by looking to add additional design considerations for wildcard path matching. 
> design: Wildcard path routing design details

- site/_posts/2019-10-23-httpproxy-in-action.md
> HTTPProxy in action blog post

- apis/projectcontour/v1/httpproxy.go
- examples/contour/01-crds.yaml
- examples/render/contour.yaml
> Remove status subresource from CRD autogeneration

- apis/contour/v1beta1/ingressroute.go
- examples/contour/01-crds.yaml
- examples/render/contour.yaml
> Remove status subresource for Ingress as well.

- docs/upgrading.md
- examples/deployment-grpc-v2/02-contour.yaml
- examples/ds-grpc-v2/02-contour.yaml
- examples/ds-hostnet-split/02-job-certgen.yaml
- examples/ds-hostnet-split/03-contour.yaml
- examples/ds-hostnet-split/03-envoy.yaml
- examples/ds-hostnet/02-contour.yaml
- examples/prometheus/03-prometheus-node-exporter.yaml
- examples/render/daemonset-rbac.yaml
- examples/render/deployment-rbac.yaml
Updates #1773
This doesn't include release notes, obviously.
> Change version to 0.15.3

- site/_resources/upgrading.md
> site: update upgrading doc for 0.15.3

- site/_docs_1_0/annotations.md
- site/_docs_1_0/httpproxy.md
- site/_docs_1_0/ingressroute.md
- site/_includes/footer.html
- site/_scss/_styles.scss
- site/_scss/site/objects/_toc.scss
- site/js/toc.js
Add a table of content for reference documentation. This is generated
by the bundled Javascript.
> doc: add TOC for reference documentation

- cmd/contour/serve.go
Updates #1280 by waiting for all informer caches must sync fully before starting Contour's gRPC server.
Big shoutout to @jpeach for help with the design!
> cmd/contour: Wait for informers to sync

- site/_docs_1_0/annotations.md
- site/_docs_1_0/ingressroute.md
- site/_scss/_styles.scss
- site/_scss/site/objects/_deprecated.scss
Style deprecation notices in a red alert box so that it jumps
out and muggs the reader.
> docs: style deprecation notices in red

- apis/projectcontour/v1/httpproxy.go
- examples/contour/01-crds.yaml
- examples/render/contour.yaml
> Remove 'first route' print column from HTTPProxy CRD

- examples/contour/02-job-certgen.yaml
- examples/contour/03-contour.yaml
- examples/contour/03-envoy.yaml
- examples/render/contour.yaml
> examples: update manifests for 1.0.0-rc.2

- site/_posts/2019-10-25-contour-v100rc2.md
> site: add Contour 1.0.0-rc.2 blog post

- examples/render.sh
- examples/render/contour.yaml
For examples/render/contour.yaml only.
Fixes #1528.
> Update render.sh to change ImagePullPolicy to IfNotPresent

- site/_resources/envoy.md
- site/_scss/site/objects/_post.scss
Fixes #1394
Add a document recording the compatibility between Envoy and Contour
versions.
Also, document the extension that are required by Contour.
> site: add envoy compatibility matrix

- site/_resources/envoy.md
> Fix the build since 'make check' is failing

- site/_guides/proxy-proto.md
> Add information about GKE and PROXY protocol

- site/_guides/cert-manager.md
> site: remove final j.hept.io shortlinks

- examples/contour/02-job-certgen.yaml
- examples/contour/03-contour.yaml
- examples/contour/03-envoy.yaml
- examples/render/contour.yaml
> examples: update image version to v1.0.0

- site/_docs_1_0/annotations.md
> doc: clarify Ingress annotations documentation

- internal/dag/builder.go
- internal/dag/builder_test.go
- internal/dag/status_test.go
- internal/e2e/rds_test.go
Fixes #1770 by looking for duplicate header conditions on an Include. 
> Adds a check for duplicate Conditions on a HTTPProxy include

- Dockerfile
> Dockerfile: upgrade to Go 1.13.4

- site/index.html
> site: Remove reference to IngressRoute on main site

- site/_includes/footer.html
- site/_includes/site-header.html
- site/_scss/site/objects/_card.scss
- site/_scss/site/settings/_variables.scss
- site/index.html
- site/resources.md
Fixes: #1819
Improve site accessibility score through improvements to background and foreground contrast ratios. Changes include alignment to VMware branding colour standards.
Contributor footer on the homepage does not match meet accessibility standards for contrast due to alignment with VMware colour standards.
Updated href tags in header and footer to provide improved link information which assists users who use text to voice applications such as Jaws.
Some buttons updated to comply with contrast standards on mouse cover.
References:
Accessibility Rules: https://dequeuniversity.com/rules/axe/
Contrast: https://dequeuniversity.com/rules/axe/3.4/color-contrast?application=lighthouse
Link text: https://dequeuniversity.com/rules/axe/3.4/link-name
Frame titles: …
> Site updates to improve accessibility

- go.mod
- go.sum
> go.mod: upgrade to go-control-plane v0.9.1

- Makefile
Consolidate check targets to they are contiguous in the Makefile.
Name them consistently as check-XXXX. Ensure they are all phony.
> build: consolidate check targets

- internal/contour/route.go
- internal/contour/route_test.go
> internal/contour: unexport sortRoutes function

- internal/envoy/route.go
- internal/envoy/secret.go
- internal/envoy/secret_test.go
> internal/envoy: add missing copyright headers

- internal/contour/secret_test.go
- internal/grpc/server.go
> Added / Corrected copyright notices

- netlify.toml
Updated netlify.toml file to enable post processing tasks and further improve site performance.
Replaces PR: #1815 
> Enable netlify post processing

- internal/featuretests/tcpproxy_test.go
Updates #1916
Assert that tcp proxying to backends using the
projectcontour.io/upstream-protocol.tls annotation configure envoy
to use TLS between envoy and the backend pod.
> internal/featuretest: add test for issue 1916

- site/getting-started.md
Fixes #1927
Thanks to @brito-rafa for spotting this.
> site: fix broken link in getting-started doc

- site/Gemfile.lock
Updated nokogiri to resolve vulnerability CVE-2019-13117
> Update nokogiri to 1.10.5

- site/_posts/2019-07-11-kindly-running-contour.md
- site/examples/kuard-httpproxy.yaml
This updates the blog post which referenced links to an older version of Contour. 
> Update kindly running contour blog post for Contour v1.0 and Kind v0.6

- site/_data/master-toc.yml
- site/_data/v1-0-0-toc.yml
> docs: fix TOC page title spelling

- internal/dag/status_test.go
Updates #1945
Updates #1951
Add status test for tcpservice with a missing backend service.
> internal/dag: add status test for missing tcpproxy service

- design/httpproxy-prefix-rewrite.md
> Initial design doc for HTTPProxy prefix rewrite.

- apis/projectcontour/v1/httpproxy.go
- examples/contour/01-crds.yaml
- examples/render/contour.yaml
> Add 'omitempty' to HTTPProxy Status field.

- site/_resources/upgrading.md
> doc: fix Contour versions in the upgrade guide

- Dockerfile
> dockerfile: update to Go 1.13.5

- site/docs/master/httpproxy.md
> doc: add HTTPProxy prefix rewrite documentation

- site/_config.yml
- site/_data/master-toc.yml
- site/_includes/footer.html
- site/_resources/envoy.md
- site/_resources/upgrading.md
- site/docs/index.md
- site/docs/master/annotations.md
- site/docs/master/architecture.md
- site/docs/master/configuration.md
- site/docs/master/deploy-options.md
- site/docs/master/httpproxy.md
- site/docs/master/ingressroute.md
* ensure that doc pages have a title
* add a TOC to the upgrade guide
* improve doc index titles
> docs: tidy the documentation tree

- examples/contour/03-envoy.yaml
- examples/render/contour.yaml
Updates #1351
Do not merge til 10th of December 2019 at 10:00 PDT (18:00 GMT).
https://groups.google.com/forum/#!msg/envoy-announce/Z4_JwSksPpY/aUGfjc86BwAJ
> example: update envoy to 1.12.2

- site/_resources/envoy.md
> site: update envoy support matrix for 1.0.1

- site/_resources/upgrading.md
> site: add 1.0.1 to the upgrading guide

- site/docs/v1.0.0/tagging.md
> site: update tagging document to reflect site.latest

- site/_data/v1-0-1-toc.yml
> site: add toc file for 1.0.1

- site/docs/v1.0.1/httpproxy.md
> site: backport #2004 to v1.0.1 docs

- Makefile
> Makefile: update to envoy 1.12.2

- design/httpproxy-header-rewrite.md
Signed-off-by: Matt Moore <mattmoor@vmware.com>
> Capture a design proposal for HTTPProxy header rewriting

- site/getting-started.md
The LB name changed from contour to envoy
Signed-off-by: Stefan Prodan stefan.prodan@gmail.com
> site: Fix getting started LB reference

- internal/grpc/xds.go
When Contour logs the close of a xDS stream, the log entry doesn't
include as much information as it could because it is captured before
and requests are made. Rather than defering the log, use a helper
function to write the log entry once it has been decorated with all
its fields.
> internal/grpc: improve xDS logging

- hack/kind-dev-cluster.sh
> Add a script to build a kind development cluster.

- internal/contour/route.go
I stared and puzzled at this code for 10 minutes before I realized
that there was an early return in the HTTPS upgrade case. Using an
if/else here makes the result more obvious to the unwwary reader.
> internal/contour: clarify route visitor code

- design/httpproxy-protocol-selection.md
Signed-off-by: Matt Moore <mattmoor@vmware.com>
> Sketch an initial design for #1962

- internal/dag/builder.go
> internal/dag: fix unused variable lint error

- site/docs/master/httpproxy.md
> site: Fix formatting of yaml for Request and Response Header Policies

- site/_resources/upgrading.md
> site: Update upgrade guide for v1.1.0

- site/_config.yml
- site/_data/toc-mapping.yml
- site/_data/v1-1-0-toc.yml
- site/_resources/faq.md
- site/_resources/upgrading.md
- site/docs/v1.1.0/README.md
- site/docs/v1.1.0/annotations.md
- site/docs/v1.1.0/api-reference.html
- site/docs/v1.1.0/api.md
- site/docs/v1.1.0/architecture.md
- site/docs/v1.1.0/configuration.md
- site/docs/v1.1.0/deploy-options.md
- site/docs/v1.1.0/github.md
- site/docs/v1.1.0/grpc-tls-howto.md
- site/docs/v1.1.0/httpproxy.md
- site/docs/v1.1.0/ingressroute.md
- site/docs/v1.1.0/start-contributing.md
- site/docs/v1.1.0/troubleshooting.md
- site/getting-started.md
> docs: clone versioned docs for v1.1.0

- examples/contour/03-contour.yaml
- examples/contour/03-envoy.yaml
- examples/render/contour.yaml
> deploy: update to Contour v1.1.0 images

- site/_redirects
> Update quickstart to v1.1

- README.md
> fix broken link to open issues list
