projectcontour/contour

- .gitignore
- Gopkg.lock
- Gopkg.toml
- internal/contour/cache.go
- internal/contour/cds.go
- internal/contour/cds_test.go
- internal/contour/grpc_test.go
- internal/contour/json.go
- internal/contour/json_test.go
- internal/contour/rds.go
- internal/contour/rds_test.go
- internal/contour/sds.go
- internal/contour/sds_test.go
- internal/k8s/adapter.go
Upgrading from `release-4.0` to `release-5.0` shaved 10mb off the final binary.
```
zapf(~/bin) % ls -alh contour*            
-rwxr-xr-x  1 dfc  staff    36M 31 Oct 11:50 contour                                
-rwxr-xr-x  1 dfc  staff    46M 31 Oct 11:49 contour.release-4.0 
```
> all: upgrade to client-go 5.0.1

- internal/contour/cds.go
- internal/contour/cds_test.go
- internal/contour/json.go
- internal/contour/json_test.go
- internal/contour/rds.go
- internal/contour/rds_test.go
Fixes #25
Envoy requires Name fields to be 60 characters or less. Rather than
doing the simple thing and using hashes as UUIDs everywhere, this PR
tries hard to preserve as much of the original name as possible, while
progressively truncating the longest fields to stay under the 60 char
limit.
> internal/contour: truncate object names to 60 characters

- cmd/contour/contour.go
- internal/contour/grpc.go
- internal/contour/grpc_test.go
This param doesn't make sense in a push populated cache, it'll be
replaced with a v2 version soon.
> internal/contour: remove unused gRPCAPI contour.DataSource param

- internal/log/stdlog/stdlog.go
- internal/log/stdlog/stdlog_test.go
stdlog.SetPrefix places the prefix at the front of the log line, not the
log message, which is not what we want.
Fix this and add some tests for the various Info/Error/Errorf methods.
> internal/log: insert prefix in correct location

- internal/contour/json.go
> internal/contour: register x/net/trace hooks on json API handler

- cmd/contour/contour.go
- internal/k8s/adapter.go
To prepare for sending data to v1 REST and v2 gRPC handlers, refactor
the k8s Service, Ingress and Endpoints SharedInformers to send
notifications to multiple ResourceEventHanders. The gRPC event handlers
are coming in a subsequent PR.
> internal/k8s: Watch{Services,Ingress,Endpoints} permit multiple ResourceEventHandlers

- internal/envoy/cache.go
- internal/envoy/cache_test.go
Add caches for
- Cluster
- ClusterLoadAssignment
- VirtualHost
- Listener
> internal/envoy: add various gRPC v2 caches

- deployment/deployment-grpc-v2/01-common.yaml
- deployment/deployment-grpc-v2/02-contour.yaml
- deployment/deployment-grpc-v2/02-rbac.yaml
- deployment/deployment-grpc-v2/02-service.yaml
Updates #8
This is a very alpha configuration for connecting Contour and Envoy over
gRPC.
If you want to play with this, make sure you delete your existing
contour deployment as (at least with 1.7.6) editing a deployment does
not appear to save changes to the initContainer section.
> deployment: add gRPC powered deployment manifest

- README.md
> README.md: fix travis badge to go to travis, not jenkins

- internal/log/stdlog/stdlog_test.go
Go 1.10 runs vet automatically on all tests. Fix the test to avoid the
spurious vet warning.
> internal/log/stdlog: fix spurious vet warning

- internal/envoy/cond.go
- internal/envoy/cond_test.go
- internal/envoy/example_test.go
Add a select friendly condition type to be used for notification of
cache changes to gRPC streamers.
> internal/envoy: add envoy.Cond type

- internal/envoy/cache.go
- internal/envoy/cache_test.go
- internal/envoy/config.go
- internal/envoy/translator.go
Refactor caches to remove unnecessary interfaces and constructors.
Caches and their Cond variables are composed together into an unnamed
structure per xDS type.
> internal/envoy: refactor caches

- cmd/contour/contour.go
- internal/k8s/buffer.go
Add a buffered ResourceEventHandler. The buffer ensures that
notifications from various watchers are processed sequentially. That is
the underlying ResourceEventHandler never called concurrently.
Placing a lock around the underlying ResourceEventHandler raises the
question of the effect of that lock being held for an extended period of
time and thus the effect on the watchers TCP streams. The buffered
ResourceEventHandler includes a provision for a buffer as well as
notificaiton when that buffer is overrun and the sender, the watcher, is
blocked.
> internal/k8s: add buffered ResourceEventHandler

- internal/contour/grpc.go
- internal/envoy/cache.go
- internal/envoy/cache_test.go
- internal/envoy/translator.go
Make LDS use a real listernerCache in preparation for SSL support (which
needs to create dynamic listeners).
Add tests, and move the `defaultListener` setup to internal/envoy.
> internal/envoy: add listenerCache

- internal/contour/grpc.go
- internal/contour/grpc_test.go
Add basic gRPC streaming tests of both a successful and timeout
condition.
> internal/contour: add basic gRPC streaming tests

- internal/envoy/cluster.go
- internal/envoy/clusterloadassignnent.go
- internal/envoy/listener.go
- internal/envoy/translator.go
- internal/envoy/virtualhost.go
> internal/envoy: split xDS caches into their own types

- internal/envoy/translator.go
- internal/envoy/translator_test.go
- internal/envoy/virtualhost.go
Updates #89
To support the definition of the vhost across multiple ingress objects,
we remove the component of the VirtualHost's (envoy side) name that
referred to the name and the namespace of the object, as it could be
potentially more than one.
> internal/envoy: support multiple ingresses per vhost

- cmd/contour/contour.go
- internal/grpc/grpc.go
- internal/grpc/grpc_test.go
Move grpc api server code to its own package.
> internal/grpc: move grpc API server code to its own package

- cmd/contour/contour.go
- internal/json/cache.go
- internal/json/cds.go
- internal/json/cds_test.go
- internal/json/json.go
- internal/json/json_test.go
- internal/json/rds.go
- internal/json/rds_test.go
- internal/json/sds.go
- internal/json/sds_test.go
Rename internal/contour (which only contains the JSON xDS API) to
internal/json which more accurately reflects its contents.
> internal/json: rename internal/contour to internal/json

- cmd/contour/contour.go
- internal/contour/cache.go
- internal/contour/cache_test.go
- internal/contour/cluster.go
- internal/contour/clusterloadassignnent.go
- internal/contour/cond.go
- internal/contour/cond_test.go
- internal/contour/example_test.go
- internal/contour/listener.go
- internal/contour/translator.go
- internal/contour/translator_test.go
- internal/contour/virtualhost.go
- internal/grpc/grpc.go
- internal/grpc/grpc_test.go
Move the k8s <> envoy translator components from internal/envour to
internal/contour. This leaves internal/envoy for JSON types and
configuration support.
> internal/contour: move translator to internal/contour

- cmd/contour/contour.go
- internal/contour/translator.go
- internal/k8s/watcher.go
Add support for watching secrets in all namespaces. This gives us access
to the TLS certs for LDS.
Secrets events are only transmitted to the contour.Translator via the
k8s.Buffer. They are not transmitted to the v1 json datasource.
> internal/contour: add support for watching secrets

- internal/contour/translator.go
- internal/contour/translator_test.go
- internal/contour/virtualhost.go
- internal/json/json_test.go
- internal/json/rds.go
- internal/json/rds_test.go
Fixes #101
The Ingress spec premits declaration of path routes without a `host`
key. This means those routes will be declared on the default vhost, in
envoy this is the `*` route.
> internal/{json,contour}: support prefix routes on default vhost

- deployment/deployment-grpc-v2/02-contour.yaml
- deployment/deployment-grpc-v2/02-service.yaml
- deployment/deployment-grpc-v2/03-service-tcp.yaml
Various changes to the grpc version of the deployment manifest
- mount `/config` on the contour container so we can pass cert material via the file system. See envoyproxy/envoy#1357
- expose 443/8443 on the service load balancer
- switch to `tcp` mode for the service load balancer. See #103 for PROXY protocol support to recover `X-Forwarded-For`
> deployment: update grpc manifest for sni

- internal/contour/listener.go
- internal/contour/translator.go
- internal/grpc/grpc.go
Updates #78 
This is a alpha cut of ssl support using Envoy's SNI support. It is by no means complete, but it is usable for testing.
You must use the deployment/deployment-grpc-v2 manifests. These are different to the quickstart manifests mentioned in the project README. SNI support requires switching to the grpc api, which will become the default for the 0.3 release.
Like other ingress controllers, contour watches for secret objects that contain `tls.crt` and `tls.key` values. You will need to manually configure these secret objects on a per ingress basis or use something like kube-lego to generate them from Let's Encrypt. 
Contour will work with kube-lego, but requires you to edit the ingress class on the ingress object that kube-lego creates to handle the authentication challenge.
``` …
```
> internal/contour: initial SNI support

- Gopkg.lock
- Gopkg.toml
- internal/contour/listener.go
- internal/contour/translator.go
- internal/contour/translator_test.go
- internal/grpc/grpc.go
Fixes #110
Update envoyproxy/go-control-plane which switches from goprotobuf to gogo
encoding.
> gopkg.toml: upgrade to latest go-control-plane

- Gopkg.lock
- Gopkg.toml
Fixes #108
Update from 5.0.1 tag to release-6.0 branch (tag is coming real soon
now, no need to wait)
Remove a few more hard coded constraints.
> gopkg.toml: upgrade to client-go release-6.0 branch

- cmd/contourcli/cli.go
Fixes #109
Adds a new command, contourctl. Contourctl is a gRPC client that can be
used to observe the xDS api responses from a contour serve process. It
is intended to be used as a debugging aid when developing and testing
contour locally.
> cmd/contourcli: add contourcli

- internal/contour/cache.go
- internal/contour/cache_test.go
- internal/contour/translator.go
Requiring the cache.init() setup step is a grotty code smell and
prevented the translator having a valid zero value.
Replace the (frankyly) far to clever channel based cache with a good old
mutex. The caches will be simplified more in the future, probably
collapsing down onto a single cache of type.Any's, but for now this
is one step in unblocking the transformer being usable without an
initaliser.
> internal/contour: refactor internal caches

- internal/contour/listener.go
- internal/contour/translator.go
- internal/grpc/grpc_test.go
Rather than hard coding a default (non tls) listener during Translator
creation, compute the `ingress_http` listener dynamically when there are
non tls ingress objects to serve.
This removes another blocker on Translator having a usable zero value.
> internal/contour: recompute non tls listener dynamically

- internal/contour/listener.go
- internal/contour/translator.go
- internal/contour/translator_test.go
- internal/contour/virtualhost.go
- internal/grpc/grpc.go
Fixes #104
RDS now publishes routes to http and https caches. LDS now binds the
http listener to the RDS http cache, ingress_http, by name, and vice
versa for the https listener.
This permits RDS to compute different routes for http and https
listeners, enabling http to https redirects.
> internal/contour: bind https listener to ingress_https routes

- internal/contour/cache.go
Simplify cache implementations internally to support efficient variadic `Add` and `Remove` operations.
This will be used in a refactor of the translator to produce lists of items to add and remove, which will then be passed unconditionally to the cache. This will hopefully decouple the translator a little bit more from the caches and make testing easier.
> internal/contour: make cache Add / Remove variadic

- internal/contour/listener.go
- internal/contour/listener_test.go
- internal/contour/translator.go
Refactor recompute{TLS,}Listener to be decoupled from the cache and the
notifier. In this way we can isolate most of the listener recompute
logic from cache and notifier management.
> internal/contour: refactor recompute{TLS,}Listener

- cmd/contour/contour.go
- internal/contour/translator.go
- internal/contour/translator_test.go
- internal/grpc/grpc_test.go
Translator no longer needs a NewTranslator constructor. The Logger
field remains mandatory, but now the translator can be embedded
directly.
> internal/contour: remove contour.NewTranslator

- cmd/contour/contour.go
- internal/contour/listener.go
- internal/contour/listener_test.go
- internal/contour/translator.go
Fixes #72
Introduce Translator.HTTPListenerPort and plumb it through to
--envoy-http-port.
> internal/contour: make envoy-http-port configurable

- cmd/contour/contour.go
- internal/contour/listener.go
- internal/contour/listener_test.go
Updates #72
Introduce Translator.HTTPSListenerPort and plumb it through to
--envoy-https-port.
> internal/contour: Make https listener port configurable

- cmd/contour/contour.go
- internal/contour/listener.go
- internal/contour/listener_test.go
Updates #48
Introduce Translator.HTTP{,S}Address and plumb it to
--envoy-http{,s}-address respectively.
You can use this --envoy-https-address=:: to bind to IPv6 _only_. Dual
stack should probably be done with --envoy-https-address=0.0.0.0 and
falling back to the host's preference.
>  internal/contour: make listener address configurable

- internal/contour/translator.go
- internal/contour/translator_test.go
- internal/contour/virtualhost.go
- internal/contour/virtualhost_test.go
Fixes #129
This PR refactors route (vhost) generation to generate independent route sets for http and https. Along the way this simplified the handling of the default, "*" vhost, which is now a little less special.
Creating separate http and https route sets means the default vhost will no longer be accessible on https -- this might need to be revisited later but for the moment should prevent the kuard example showing up on https.
This PR also creates placeholders for #63 and #88
> internal/contour: generate independent route tables for ingress_http and ingress_https

- internal/contour/virtualhost.go
- internal/contour/virtualhost_test.go
Fixes #63
Closes #146
Add support for the ingress.kubernetes.io/force-ssl-redirect: "true"
annotation
> internal/contour: support ingress.kubernetes.io/force-ssl-redirect: true

- internal/contour/translator.go
- internal/contour/virtualhost.go
- internal/contour/virtualhost_test.go
Fixes #150
appendIfMissing was not replacing the element if it was present in the
list. Perhaps we should be using a map, or at least add a test.
> internal/contour: always overwrite cached Ingress

- cmd/contour/contour.go
- internal/contour/listener.go
- internal/contour/listener_test.go
Fixes #103
Add support for the
`service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"`
annotation.
Support is enabled via the `--use-proxy-protocol` flag to `serve` which
configures all listeners served via LDS to be configured with
`UseProxyProto: true`.
> internal/contour: support PROXY protocol on listeners

- Gopkg.lock
- Makefile
- cmd/contour/contour.go
- cmd/contour/gcp.go
- cmd/contour/oidc.go
This PR makes the oicd and gcp auth packages selectable at build time.
The intent is to avoid bundling these libraries in the contour image as
they are not needed when running `--incluster`, however they are needed
for local development when running `contour serve` locally.
The Makefile contains example syntax of how to use the `-tags` flag to
enable plugins as required.
> cmd/contour: make oicd/gcp auth plugins build time options

- internal/contour/listener.go
Fixes https://github.com/heptio/contour/issues/168
Signed-off-by: Cody Maloney <cody@emeraldcloudlab.com>
> Add AlpnProtocols to TLS Context so http2 with browsers works

- deployment/deployment-grpc-v2/02-contour.yaml
- deployment/ds-grpc-v2/02-contour.yaml
- deployment/render/daemonset-norbac.yaml
- deployment/render/daemonset-rbac.yaml
- deployment/render/deployment-norbac.yaml
- deployment/render/deployment-rbac.yaml
Fixes: https://github.com/heptio/contour/issues/138
There are two side things I noticed while doing this, both fixed as well
1. `-l info` wasn't always passed, it now is
2. The DaemonSet definitions were broken with k8s 1.8 at least, because the updateStrategy was inside of the template rather than inside `spec` (https://kubernetes.io/docs/tasks/manage-daemon/update-daemon-set/#daemonset-update-strategy)
3. The daemon set config was missing a volume mount on the main contour container (`contour serve --incluster`), added that in. Without it starting on a cluster using ssl certs doesn't work.
> Launch envoy with --v2-config-only when using a yaml config file

- README.md
- docs/tls.md
- removed "Known limitations" section of README
- added navigation
- cleaned up a bit of TLS content (moved details about ELB PROXY protocol out of tls.md, linked to proxy-proto.md. Fixes duplicate content and keeps complexity for single use case in one place. See discussion in #159)
Signed-off-by: JENNIFER RONDEAU <jrondeau@heptio.com>
> fix navigation, TLS content

- internal/contour/translator_test.go
Make translator_test.go use the ResourceEventHandler API. This is
important for the next commit which extends the API and means
{add|remove}{Service,Endpoint,Ingress,Secret} should not be made
directly.
> internal/contour: make translator tests us ResourceEventHandler

- internal/contour/translator.go
- internal/contour/translator_test.go
Fixes #186 
```
The ClusterLoadAssignment's ClusterName must match the corresponding
Cluster's ServiceName in the EDS config. Given that the ServiceName does
not have a character limit and is not being hashed, we should not hash
the ClusterName field in the ClusterLoadAssignment.
Signed-off-by: Alexander Brand <alexbrand09@gmail.com>
```
> internal/contour: Do not hash ClusterLoadAssignment's ClusterName

- deployment/deployment-grpc-v2/02-contour.yaml
- deployment/ds-grpc-v2/02-contour.yaml
- deployment/render/daemonset-norbac.yaml
- deployment/render/daemonset-rbac.yaml
- deployment/render/deployment-norbac.yaml
- deployment/render/deployment-rbac.yaml
Fixes: #138
There are two side things I noticed while doing this, both fixed as well
-l info wasn't always passed, it now is
The DaemonSet definitions were broken with k8s 1.8 at least, because the updateStrategy was inside of the template rather than inside spec (https://kubernetes.io/docs/tasks/manage-daemon/update-daemon-set/#daemonset-update-strategy)
The daemon set config was missing a volume mount on the main contour container (contour serve --incluster), added that in. Without it starting on a cluster using ssl certs doesn't work.
> Backport contour#167

- internal/contour/translator.go
- internal/contour/translator_test.go
internal/contour: Do not hash ClusterLoadAssignment's ClusterName
Update #186 
The ClusterLoadAssignment's ClusterName must match the corresponding Cluster's ServiceName in the EDS config. Given that the ServiceName does not have a character limit and is not being hashed, we should not hash the ClusterName field in the ClusterLoadAssignment.
> Backport #187

- internal/k8s/buffer.go
Spotted during manual testing. buffer.loop was not respecting the stop
channel so would not exit when the group was torn down.
> internal/k8s: make buffer.loop respect stop channel

- docs/deploy-aws-nlb.md
> docs: fix link syntax typo

- Makefile
This commit ensures that the `deployment/render.sh` test fails and blocks the
build when there were differences in the working tree after rendering.
It seems that the `&&` and `||` operator have the same precedence in Bash. I've
used grouping to avoid the conflict.
This closes #199.
> make check: interrupt build if render.sh fails

- docs/troubleshooting.md
Closes #198
Rather than binding the admin interface to 0.0.0.0 or using a service
and kubectl proxy, recommend port forwarding directly to the admin
interface via the kubelet.
This has the advantages that can avoid the `--admin-address` flag our of
our example deployments, and as the admin interface remains bound to the
pod, it can't be accidentally exposed to other members of the cluster,
or the public internet.
> docs: recommend kubectl port-forward for envoy admin interface access

- internal/contour/clusterloadassignnent.go
- internal/contour/translator.go
- internal/contour/translator_test.go
Move the creation of ClusterLoadAssignments into a single helper. This
will make handling CLA specific params like Locality and Policy easier
in the future.
> internal/contour: centralise creation of ClusterLoadAssignment

- internal/contour/cluster.go
- internal/contour/cluster_test.go
- internal/contour/translator.go
- internal/contour/translator_test.go
- internal/e2e/cds_test.go
Prior to this PR the translator treated an OnUpdate event for a service
as an Add. This could lead to conditions where Envoy clusters would
remain in the CDS cache if the service was edited.
This PR refactors service handling to _always_ model as an update,
making add and remove degenerate cases.
> internal/contour: stop CDS entries leaking in service update

- internal/contour/translator.go
- internal/contour/translator_test.go
Updates #175
Store service and endpoint documents. In the next PR we will need both
service and endpoint to recompute both SDS and EDS.
> internal/contour: cache service and endpoints

- docs/tls.md
I've used a git tag ref because it never moves.
> docs/tls: fix broken link

- internal/contour/clusterloadassignment.go
- internal/contour/translator.go
Leader election uses endpoints without matching services. Silence the
regular updates by filtering endpoint updates with less than one subset.
> internal/contour: silence leader election messages

- internal/contour/listener.go
- internal/e2e/grpc_test.go
- internal/e2e/lds_test.go
This PR adds a scaffold for LDS tests. It uses the go-control-plane api
types to generate the configuration for the http connection manager. I
had initially decided not to use this method inside contour/listener.go
because of the barf worthy way of converting those types to a grpc
struct type.
For this e2e test I decided to use go-control-plane pkg's methods as a
way of double checking my hand rolled proto struct, I found a few small
errors which have been corrected in this PR, so it's good to double
check the data structures line up.
> internal/e2e: add listener e2e test skeleton

- internal/contour/clusterloadassignment.go
- internal/e2e/eds_test.go
Fixes #224
This PR removes the dummy locality data for each set of locality
lb endpoints.
> internal/contour: stop generating dummy locality data

- docs/README.md
- docs/annotations.md
- internal/contour/translator_test.go
- internal/contour/virtualhost.go
Adds support for an annotation to set the timeout per envoy RouteAction to get around envoy defaulting to 15s, which is too short for some applications.
Fixes https://github.com/heptio/contour/issues/164
Signed-off-by: Cody Maloney <cody@emeraldcloudlab.com>
> Add support for a request-timeout annotation

- internal/contour/cluster.go
- internal/contour/cluster_test.go
- internal/contour/listener.go
- internal/contour/translator_test.go
- internal/e2e/cds_test.go
- internal/e2e/lds_test.go
- internal/envoy/config.go
- internal/envoy/config_test.go
Fixes #229.
Rename cluster, use `contour` intead of `xds_cluster`.
It should not bring functional changes.
> internal/contour: update cluster name

- internal/contour/translator_test.go
- internal/contour/virtualhost.go
- internal/contour/virtualhost_test.go
Updates #164 
This PR refactors the `getRequestTimeout` function to return a timeout value, not a pointer to a timeout. This helps with writing unit tests.
In the process this made the usage of `getRequestTimeout` within `recomputevhost` more verbose. This is handled by moving the complexity of generating a `*v2.Route_Route` to its own helper which takes an ingress and a backend and applies the required business logic.
> internal/contour: refactor backend timeout handling

- Gopkg.lock
- cmd/contourcli/cli.go
- internal/contour/cache.go
- internal/contour/cache_test.go
- internal/contour/cluster.go
- internal/contour/cluster_test.go
- internal/contour/clusterloadassignment.go
- internal/contour/clusterloadassignment_test.go
- internal/contour/listener.go
- internal/contour/listener_test.go
- internal/contour/translator.go
- internal/contour/translator_test.go
- internal/contour/virtualhost.go
- internal/contour/virtualhost_test.go
- internal/e2e/cds_test.go
- internal/e2e/e2e_test.go
- internal/e2e/eds_test.go
- internal/e2e/lds_test.go
- internal/e2e/rds_test.go
- internal/grpc/grpc.go
- internal/grpc/grpc_test.go
- Consumes the changes in envoyproxy/go-control-plane#39.
- Changed Gopkg.lock to pick the latest go-control-plane.
- Changed code as per the changes in the structures
defined in go-control-plane.
- Updated the unit tests.
Fixes issue #225 
Signed-off-by: Amarnath V. A. <vaamarnath@gmail.com>
PS: Being a new to open source contribution, please bear with the mistakes in the PR.
> Consuming the new APIs provided by go-control-plane

- internal/envoy/config.go
- internal/envoy/config_test.go
Fixes #228.
This enable us to define the contour cluster as a DNS name. I have confirmed
that `STRICT_DNS` also works when the address is an IP.
As mentioned by @davecheney before, with #158 and #228 fixed we should be able
to split Contour and Envoy into separate pods. Proof of concept:
https://gist.github.com/sevein/d30e1791fbc0db786884360486e70737.
> internal/envoy: use strict DNS for resolving the cluster

- cmd/contour/contour.go
- internal/contour/translator_test.go
- internal/grpc/grpc.go
- internal/grpc/grpc_test.go
- internal/k8s/buffer.go
- internal/k8s/watcher.go
Updates #162 
This PR finalises the use of logrus across the project. The various
TODO's related to logging can be taken care of in latter PRs.
The basic rules for using logrus in this project are
- A worker is reponsible for adding its own fields like `context` or
`resource`. Pass a `logrus.FieldLogger` to the worker's constructor and
let it add fields as necessary.
- The name of the `logrus.FieldLogger` or `logrus.StdLogger` should be
`log` in formal parameters and local variables.
- If the function is not expected to add more fields, the type of it's
logger should be `logrus.StdLogger`.
- `logrus.FieldLogger` / `logrus.StdLogger` should be embedded by value
into long lived types that need to log. They should apply necessary
fields during construction.
Signed-off-by: Dave Cheney …
> all: normalise logrus use

- internal/contour/cluster.go
- internal/contour/cluster_test.go
- internal/contour/translator_test.go
- internal/e2e/cds_test.go
Fixes #243
Hopefully this is the _last_ issue relating to the interaction between
CDS, EDS, and the endpoint object.
The logic now follows that _iff_ a service port is named, use that name
for the cluster.service_name field in CDS. If the service port is
unnamed then derive the name from the service port's targetport, and use
that in cluster.service_name.
> internal/contour: derive cluster.service_name from targetport

- internal/contour/cluster.go
- internal/contour/cluster_test.go
- internal/contour/clusterloadassignment.go
- internal/contour/clusterloadassignment_test.go
- internal/contour/translator.go
- internal/contour/translator_test.go
- internal/e2e/cds_test.go
Fixes #247
Fingers crossed this finally closes the last issue with the EDS and CDS
servicename's not matching.
On the CDS side, the cluster.service_name field is always defined from
the namespace/name of the service document, and, if provided a slash and
the name of the service port. If this is blank, then the slash is also
elided. The end result is in the case that there is a single serviceport
in the service spec, the service_name generated for that CDS entry will
be simple "namespace/name". In all other cases, the api server requires
that service ports be named, so the CDS's service_name entry will be
"namespace/name/serviceportname".
On the EDS side, we only have the contents written by the endpoint
controller, but that is enough. If the service's port was named in the
service …
> internal/contour: generate stable service names for unnamed service ports

- internal/contour/listener.go
- internal/contour/virtualhost.go
- internal/contour/virtualhost_test.go
- internal/e2e/cds_test.go
- internal/e2e/rds_test.go
Fixes #250
Prior this PR if _any_ ingress which mentioned a vhost used the
ingress.kubernetes.io/force-ssl-redirect: "true" annotation, then all
routes would be 301 upgraded via the route.virtualhost.requireTls flag.
This PR changes the behaviour so per ingress (that is all routes in an
ingress object), not per vhost, the annotation is applied and this
causes the route.RouteRoute action to be replaced with a
route.Route_Redirect action. This has the same net effect as the
requireTls virtualhost flag, but is applied per route.
> internal/contour: 301 upgrade routes on a per ingress basis

- deployment/example-workload/kuard-minikube-route.yaml
- deployment/example-workload/kuard-route.yaml
- deployment/example-workload/kuard.yaml
- internal/contour/listener.go
- internal/contour/translator.go
- internal/contour/translator_test.go
- internal/contour/virtualhost.go
- internal/contour/virtualhost_test.go
This is a basic implementation of RouteCRDs to match http only current state of ingress. One note is it does not (yet) support multiple upstreams which will be handled in a future PR. 
> Initial implementation of RouteCRD for Ingress routes

- cmd/contour/contour.go
- internal/contour/translator.go
- internal/contour/translator_test.go
Fixes #255 
By default, the "kubernetes.io/ingress.class" was checked against
a hardcoded value. This value is now in a constant and overridable
at runtime.
Signed-off-by: Nicolas Bernard <nikkau@nikkau.net>
> internal/contour: make IngressClass configurable

- internal/contour/translator_test.go
- internal/contour/virtualhost.go
- internal/contour/virtualhost_test.go
Contour now passes the set of upstreams to envoy and calculates even distribution across.
> Implement multiple upstream to envoy

- design/routecrd.md
The original design was incorrect, lb strategies are applied to the upstreams.
> Fix reference to where lb strategy is applied

- internal/contour/annotations.go
- internal/contour/annotations_test.go
- internal/contour/listener.go
- internal/contour/listener_test.go
- internal/contour/virtualhost.go
- internal/contour/virtualhost_test.go
The ingress.class annotation is still unaccounted for, but this is overall an improvement and creates a place for annotation processing helpers in the future.
> internal/contour: consolidate annotation processing into a new file.

- internal/contour/translator.go
- internal/contour/translator_test.go
- internal/e2e/rds_test.go
Fixes #257
Previously updating and ingress object in place would not remove any
vhosts previously associated with that ingress object. This fixes the
problem by modeling update as add and remove as we do in the translator
cache.
> internal/contour: model ingress update as add and remove 

- deployment/deployment-grpc-v2/02-contour.yaml
- deployment/ds-grpc-v2/02-contour.yaml
- deployment/ds-hostnet/02-contour.yaml
- deployment/render/daemonset-norbac.yaml
- deployment/render/daemonset-rbac.yaml
- deployment/render/deployment-norbac.yaml
- deployment/render/deployment-rbac.yaml
- docs/prometheus.md
This PR adds docs on how to get envoy stats with Prometheus. It also adds Prometheus annotations for all deployments/daemonsets.
What's not ideal about this approach is that
* It requires a non-standard Prometheus config
* It requires exposing the Envoy admin socket which is especially bad when running with host network
I saw metrics are on the roadmap, what do you think about resolving the two above mentioned issues by proxying the Envoy stats with Contour?
> Add docs on how to get Envoy stats with prometheus

- deployment/deployment-grpc-v2/02-contour.yaml
- deployment/ds-grpc-v2/02-contour.yaml
- deployment/ds-hostnet/02-contour.yaml
- deployment/render/daemonset-norbac.yaml
- deployment/render/daemonset-rbac.yaml
- deployment/render/deployment-norbac.yaml
- deployment/render/deployment-rbac.yaml
- release-0.4.md
Fixes #142
Pin envoyproxy/envoy-alpine to the March 12 tagged version.
There is nothing special about this tag, other than it works.
> deployment: pin envoy version to known hash

- internal/contour/cache.go
- internal/contour/cache_test.go
Fixes #257
Ensure that blank VirtualHost entries are not added to the cache. This
should prevent them making their way through to Envoy.
> internal/contour: add additional checks for blank virtualhost items

- .travis.yml
- Dockerfile
Resolves #267 
Basically no change to codebase, everything seems to work the same.
I've also gone through the go 1.10 changelogs, not finding any changes that will affect the project.
Signed-off-by: Emman <eygohlolz@gmail.com>
> Bump up Go version in containers to 1.10

- deployment/deployment-grpc-v2/02-contour.yaml
- deployment/ds-grpc-v2/02-contour.yaml
- deployment/ds-hostnet/02-contour.yaml
- deployment/render/daemonset-norbac.yaml
- deployment/render/daemonset-rbac.yaml
- deployment/render/deployment-norbac.yaml
- deployment/render/deployment-rbac.yaml
Envoy v1.6.0 has been released: https://github.com/envoyproxy/envoy/releases/tag/v1.6.0
Closes #280
> Upgrade to Envoy v1.6.0

- Gopkg.lock
> gopkg.lock: update to go-control-plane 0.2

- design/ingressroute-design.md
This document describes the design of a new CRD designed to replace the v1beta1.Ingress Kubernetes object. This new CRD will be integrated into Contour 0.5/0.6. Contour will continue to support the current v1beta1.Ingress object for as long as it is supported in upstream Kubernetes.
> design: ingressroute first draft

- Makefile
- internal/contour/example_test.go
- internal/contour/listener_test.go
- internal/grpc/grpc_test.go
Always run go vet ./... as part of CI.
Address current crop of vet issues.
> Makefile: add vet step to check

- Gopkg.lock
- Gopkg.toml
Updates #327
Pin grpc library to v1.10.0 (was 1.11.3) to revert the test flakes since #321.
> gopkg.toml: pin google.golang.org/grpc to version 1.10.0

- cmd/contour/cli.go
- cmd/contour/contour.go
- internal/e2e/cds_test.go
- internal/e2e/eds_test.go
- internal/e2e/lds_test.go
- internal/e2e/rds_test.go
- internal/grpc/grpc.go
- internal/grpc/grpc_test.go
Updates #273, #277
This PR improves the xDS protocol support in Contour. Contour now waits
for an DiscoveryRequest before responding.
In plumbing DiscoveryRequest down a few more layers this has removed
some custom loggers and provided access to the ResourceName needed for #277.
> internal/grpc: wait for request before responding

- internal/contour/cache.go
- internal/contour/cluster_test.go
- internal/contour/clusterloadassignment_test.go
- internal/contour/listener_test.go
- internal/contour/translator_test.go
- internal/contour/virtualhost_test.go
- internal/grpc/resources.go
- internal/grpc/server.go
Updates #277 
This PR creates the scaffolding to allow Stream listeners to filter the resources sent back to them on the Contour side using a filter function constructed from the DiscoverRequest.ResourceName slice (or match everything if the slice is empty).
Currently the filters are not applied at the contour/cache level, but once they are resources presented to the grpc layer will be filtered by ResourceNames. This will also mean, if no events match the filter provided, then the update can be skipped. This will be the subject of a later PR.
> internal/grpc: filter stream requests by DiscoveryRequest.ResourceNames

- cmd/contour/contour.go
- cmd/contour/debug.go
- docs/troubleshooting.md
This PR adds a /debug/pprof handler to the Contour container. By default this is bound to 127.0.0.1:8000. This can be changed via flags, but cannot currently be disabled.
The troubleshooting document has been updated to show how to access this service.
> cmd/contour: add debug service endpoint

- Makefile
This PR adds some pretty basic targets for building and pushing docker images and should make this process a bit more straight forward.
By default they build an image with the version set to the truncated commit SHA. If we are building a tagged release we also tag the image `latest`.
Signed-off-by: Curt Micol <asenchi@heptio.com>
> Add targets to build and push containers

- cmd/contour/contour.go
- internal/contour/listener.go
- internal/contour/listener_test.go
Fixes #328 
Contour configures Envoy to write access logs to stdout. Envoy's logs are also written to stdout but in a different format. This change allows a user to specify an alternative location for access logs.
> Support for custom access log paths

- cmd/contour/contour.go
- internal/envoy/config.go
This enables statsd metric output. The end goal is to add the [statsd exporter](https://github.com/prometheus/statsd_exporter) to allow Prometheus to scrape for metrics and add Histogram support since it's not included natively in Envoy. 
> Enable statsd metric output

- cmd/contour/contour.go
- internal/envoy/config.go
- internal/envoy/config_test.go
Creating a static route for `/stats` on an interface over port `:8001` and restricting access to other admin functionality from being exposed. 
> Expose /stats from customizable port

- internal/envoy/config.go
- internal/envoy/config_test.go
Port 8001 is used by contour, when envoy and contour are colated in a
single pod, this causes a port conflict with the stats listener iff
envoy starts before contour (the owernship rules between binding to
0.0.0.0 and 127.0.0.1 are somewhat opaque)
Move the stats listener to 8002.
> cmd/contour: move envoy's stats listener to port 8002

- cmd/contour/contour.go
Fixes #371 
This must be done as glog requires flag.Parse before being used by anything else for logging purposes. However, doing this before any flags are defined with kingpin will override our flags, thus flag.Parse must be called after our kingpin calls, but before creating a new client.
Signed-off-by: David Muckle <dvdmuckle@dvdmuckle.xyz>
> cmd/contour: moving flag.Parse out of init()

- internal/envoy/config.go
- internal/envoy/config_test.go
Updates #376
Omit the statsd listener and cluster unless its enabled.
Also:
- bind the stats listener to 127.0.0.1 by default, which matches the
statsd collector which is also listening on 127.0.0.1.
- add tests for enabled and disabled configurations
> internal/envoy: omit statsd listener and cluster unless enabled

- internal/envoy/config.go
This fixes the stats configuration to be valid so Envoy does not error on start. Also, fix small nit in the spelling of the prefix name. 
> Fix bug with config erroring out when enabling stats

- design/ingressroute-design.md
Update ingressroute spec to acknowledge that the design is multi-team,
not multi-tenant. In doing so this resolves the security issue noted
previously.
We define multi-tenant to be a cluster who's members are not known or
trusted by each other, whereas multi-team share a level of trust, or
shared organisational responsibility. In effect the security of
multi-team clusters is delegated to the organisations reporting
structure, not enforced in code.
> design: note that ingressroute is multi-team, not multi-tenant

- design/ingressroute-design.md
- Revert path to be absolute in a delegate
- Remove unneeded metrics that will move to Gimbal discoverer
- Add flag to (optionally) disable k8s ingress resources from being discovered
- Update `contour_ingressroute_invalid_total` to reference `orphaned`
- Add note about healthchecks and they are different from any other built-in check
> Update design doc to clarify paths, metric name, and flags

- internal/contour/translator_test.go
- internal/contour/virtualhost.go
- internal/contour/virtualhost_test.go
- internal/e2e/rds_test.go
Adds both host and host:port to a virtualhost's route domains,
enabling routing when a client includes the port in the ```Host```
header.
Fixes #390
Signed-off-by: Matthew Alberts <malberts@cloudflare.com>
> Add domain alias host:port on vhost create

- cmd/contour/contour.go
- internal/debug/debug.go
This is in preparation for adding a /debug/dag handler.
> internal/debug: move debug service to an internal package

- internal/contour/translator.go
Endpoints are now handled outside contour.translator so will never be
presented to the translatorCache.
> internal/contour: do not cache endpoints in the translatorCache

- deployment/deployment-grpc-v2/02-contour.yaml
- deployment/ds-grpc-v2/02-contour.yaml
- deployment/ds-hostnet/02-contour.yaml
- deployment/render/daemonset-norbac.yaml
- deployment/render/daemonset-rbac.yaml
- deployment/render/deployment-norbac.yaml
- deployment/render/deployment-rbac.yaml
Updates #420
Prior to this PR the envoy container appeared first in the
deployment.spec so would likely start before the contour container. This
would cause envoy to fail to be able to contact contour immediately upon
startup and would then fall back to a retry behaviour.
With this change, contour appears first in the spec so will likely start
before contour, which agrevates a failure mode reported in issue #420.
> deployment: switch the order of envoy and contour containers

- cmd/contour/contour.go
- internal/dag/dag.go
- internal/dag/dag_test.go
- internal/dag/k8s.go
- internal/debug/debug.go
- internal/debug/dot.go
This PR introduces a new package, `internal/dag`, a data model to underpin the upcoming refactoring of the contour translator to work with Ingress and IngressRoute CRDs.
The DAG data model presents an abstract representation of the relationship between Ingress, ingressroutes, their constituent routes, the secrets used for ingress TLS, and the backend services that routes point too. The DAG is flexible enough to represent data that cannot be expressed today in Ingress, for example, a route with more than one backend object; that is, more than one service. In the DAG data model, this is simply a route with more than one Service object as a child.
Initially the dag is only plumbed into contour in a read only manner -- it is another watcher on certain object types only. You can view a …
> internal/dag: new package

- internal/dag/dag.go
- internal/dag/dag_test.go
- internal/dag/k8s.go
Updates #428
This PR replaces the previously mutable DAG implementation with an immutable version. The rational for this is laid out in #428, and this PR accomplishes the replacement of the data structure. The holdoff behaviour described in #428 is not implemented, and will be assessed during load testing.
This new DAG is simpler and more reliable to build, but comes at the cost of high rates of allocation during high load, expected during startup. For the moment we're just going to live with that and accept that reliable rebuilds of the dag under steady state running will be the target. This will let us build unit tests as we add features to the DAG production. If we need to optimise the DAG later on, those unit tests will keep us honest.
> internal/dag: rewrite DAG to be immutable

- internal/dag/annotations.go
- internal/dag/annotations_test.go
- internal/dag/dag.go
- internal/dag/dag_test.go
- internal/debug/dot.go
Updates #429
This PR alters the DAG generation to create unique roots for each host/port combination. This embeds more information into the dag, for example, the port number of a vhost is no longer determined by the presence of a child secret object. Now the port a vhost listens on and if it uses TLS is independent -- although a vhost _must_ have a child secret to be TLS enabled.
With this in place we can now start to generate different route graphs for the port 80 and port 443 listeners. This PR includes an example of this by adding support for the `kubernetes.io/ingress.allow-http: "false"` annotation. 
It should be noted that TLS objects will never be attached to virtualhosts that do not have hostnames. See #410 for details.
> internal/dag: create separate roots for port 80 and port 443 vhosts

- internal/contour/translator_test.go
- internal/contour/translatorcache_test.go
- internal/contour/virtualhost.go
- internal/contour/virtualhost_test.go
- internal/e2e/rds_test.go
Fixes #404
Only consule default ingress rules (that is, spec.host == "" or
spec.backend != nil) when recomputing the "*" vhost.
> internal/contour: only consult default ingress for vhost "*"

- internal/dag/dag.go
- internal/dag/dag_test.go
Initial support for processing ingress route documents.
- :443 support is missing
- no tests for remove
_note:_ kuard.davecheney.com points to both default/httpbin _and_ default/kuard
> internal/dag: process ingressroute documents     

- internal/dag/dag.go
- internal/dag/dag_test.go
- internal/debug/dot.go
Updates #211
Fixes #462
Handling the IntStr nature of Ingress's Backend.SevicePort field has
been a thorn in Contour's side for a long time (see #211). This PR
addesses both #211 and #462 by resolving the port number during DAG
recomputation if a named port is in use.
We store the selected port number on dag.Service and construct a tupple
of namespace/name/port to treat each service separately, ie. a service
with port 9000 is different to the port 9001 on the same service object.
In doing so we remove the requirement to store the particular
v1beta1.ServiceBackend on the Route object, which resolves the issue of
an ingressroutev1 object lacking that object. The route object doesn't
need to hold this information anyway, it's already present on the
Service object as described above. …
> internal/dag: canonicalise service port during Recompute

- deployment/common/common.yaml
- deployment/render/daemonset-norbac.yaml
- deployment/render/daemonset-rbac.yaml
- deployment/render/deployment-norbac.yaml
- deployment/render/deployment-rbac.yaml
This adds CRD Validation to the IngressRoute spec. One thing to note is it defines an Enum of values allowed for the `strategy` field which is not yet implemented. We may need to return to this validation once that feature lands.
// Fixes #416 
> IngressRoute CRD Validation

- internal/e2e/e2e.go
- internal/e2e/lds_test.go
Updates #454
Add e2e tests for tls-minimum-protocol and use-proxy-proto. These will
keep these scenarios covered when #460 lands.
> internal/e2e: add missing e2e LDS tests

- internal/dag/dag.go
- internal/dag/dag_test.go
Fixes #476
This PR introduces a second kind of root vertex, a SecureVirtualHost.
Unlike the existing VirtualHost, this type represents HTTPS vhosts.
This change resolves a number of ambiguities in the DAG
- a TLS backed vhost is no longer indicated by the presence of at least
one child secret. Now the presents of a secret only exists on a
SecureVirtualHost -- Secrets are no longer children of VirtualHosts.
- this prevents the intermediate situation where a TLS backed site would
appear on port 80 because the secret was not present. Now if the secret
is not present the LDS walker can skip it entirely.
- This gives a place to hang TLS parameters like protocol version from,
fixing #476.
> internal/dag: introduce SecureVirtualHost

- deployment/example-workload/ingressroute/00-common/00-namespaces.yaml
- deployment/example-workload/ingressroute/00-common/01-services.yaml
- deployment/example-workload/ingressroute/00-common/02-deployments.yaml
- deployment/example-workload/ingressroute/01-ingress-to-ingressroute/basic.ingressroute.yaml
- deployment/example-workload/ingressroute/01-ingress-to-ingressroute/name-based.ingressroute.yaml
- deployment/example-workload/ingressroute/01-ingress-to-ingressroute/tls.ingressroute.yaml
- deployment/example-workload/ingressroute/02-basic/default-health-checks.ingressroute.yaml
- deployment/example-workload/ingressroute/02-basic/default-lb-strategy.ingressroute.yaml
- deployment/example-workload/ingressroute/02-basic/domain-aliases.ingressroute.yaml
- deployment/example-workload/ingressroute/02-basic/health-checks.ingressroute.yaml
- deployment/example-workload/ingressroute/02-basic/lb-strategy.ingressroute.yaml
- deployment/example-workload/ingressroute/02-basic/multiple-upstreams.ingressroute.yaml
- deployment/example-workload/ingressroute/02-basic/weight-shifting.ingressroute.yaml
- deployment/example-workload/ingressroute/03-delegation-within-namespace/root.ingressroute.yaml
- deployment/example-workload/ingressroute/03-delegation-within-namespace/service2.ingressroute.yaml
- deployment/example-workload/ingressroute/04-blue-green-delegation/blue.ingressroute.yaml
- deployment/example-workload/ingressroute/04-blue-green-delegation/green.ingressroute.yaml
- deployment/example-workload/ingressroute/04-blue-green-delegation/root.ingressroute.yaml
- deployment/example-workload/ingressroute/05-delegation-across-namespaces/blog.ingressroute.yaml
- deployment/example-workload/ingressroute/05-delegation-across-namespaces/root.ingressroute.yaml
As part of #450, I wanted to create put together a suite of IngressRoute objects and corresponding services.
This should hopefully be helpful for the development team working on the IngressRoute DAG implementations.
> Add example ingressroute objects

- internal/dag/dag.go
- internal/dag/dag_test.go
- internal/route/visitor.go
During dag recompute keep a reference to the serviceport object, not
just the port number, we need this for CDS to compute the correct
service name to match eds.
> internal/dag: record service port object on dag.Service

- internal/dag/dag.go
- internal/dag/dag_test.go
Fixes #488 
Instead of performing a string prefix match, make sure that the child ingressroute matches the parent's path prefix. 
In the case that any of the routes of the child ingressroute does not match the parent's path prefix, the entire child ingressroute is considered invalid and not considered in the DAG.
> internal/dag: perform path prefix match instead of string prefix match

- cmd/contour/contour.go
- internal/dag/dag.go
- internal/dag/dag_test.go
- internal/e2e/lds_test.go
- internal/e2e/rds_test.go
Implements enforcing mode, in which root ingress routes can only be defined in specific namespaces.
If contour encounters a root ingress route that is defined outside of the blessed namespaces, the ingress route is ignored.
If the list of blessed namespaces is empty, root ingress routes can be defined in any namespace.
Fixes #461
> internal/dag: enforce root ingressroutes live in specific namespaces

- internal/contour/adapter.go
- internal/contour/cluster_test.go
- internal/contour/listener_test.go
- internal/contour/route_test.go
- internal/dag/dag.go
- internal/e2e/rds_test.go
Fixes #483
Reimplement ingress.class support in contour's DAGAdapter. There is some
trickiness in ensuring that if an ingress is edited from valid (matching
the ingress.class rules) to invalid then the previous version needs to
be purged from the DAG cache. The internal/e2e tests now capture this.
> internal/{dag,contour}: reimplement kubernetes/ingress.class support

- internal/dag/dag.go
- internal/dag/dag_test.go
Fixes #490 
The first step towards updating the status of IngressRoute (IR) resources is adding the validation that will determine the status.
Validation is performed while we are recomputing the DAG. There might be some validation that can be done before, but I think this will do for now. The `recompute` method of the DAG now also returns a list of statuses, each containing the IR in question, its status and a human readable message that explains the status.
Currently, the statuses are printed out to STDOUT instead of written up to the API server. This will be handled in a follow-up PR. 
This PR adds the following status checks for IRs:
- Negative weight provided in the route definition
- Invalid port number provided for service
- Prefix in parent does not match route in delegated route …
> internal/dag: validate ingressroutes and produce a list that contains a status entry for each

- Dockerfile
Right now the Dockerfile used to build the Contour image is looking for `alpine:latest`. This PR pins it to the last release to avoid issues with unknown latest tags. 
Reason is right now the :latest tag is broken in docker hub and no builds will happen. 
> Pin the alpine image to a version rather than :latest

- Dockerfile.race
- Makefile
- Upgrade to Go 1.10.3
- Use named targets
- Add race build
> Dockerfile: garden Dockerfile

- internal/contour/route_test.go
Fixes #447
Add a test to ensure that an ingressroute with a blank
spec.VirtualHost.FQDN is ignored.
> internal/contour: add test for issue/447

- deployment/common/common.yaml
- deployment/render/daemonset-norbac.yaml
- deployment/render/daemonset-rbac.yaml
- deployment/render/deployment-norbac.yaml
- deployment/render/deployment-rbac.yaml
- docs/ingressroute.md
Fixed the CRD deployment file to have the full list of load balancing strategies available. Also improved the documentation to make it more clear which load balancing strategies can be used in the IngressRoute.
Fixes #530
> Fix mismatch in load balancing strategy validation

- Gopkg.lock
- cmd/contour/contour.go
- internal/contour/adapter.go
- internal/contour/cluster_test.go
- internal/contour/listener_test.go
- internal/contour/route_test.go
- internal/dag/dag.go
- internal/dag/dag_test.go
- internal/e2e/e2e.go
- internal/e2e/lds_test.go
- internal/e2e/rds_test.go
- internal/k8s/status.go
- internal/k8s/status_test.go
Fixes #524 by updating IngressRoute Status fields after a DAG update. It only updates when the status changes (e.g. msg != ir.msg or desc != ir.desc)
> Write Status to Kubernetes IngressRoute object after DAG update 

- docs/ingressroute.md
Short term fix to update documentation to reflect current behavior of the `--ingressroute-root-namespaces` CLI flag which must be specified multiple times, one per namespace.
Current documentation recommends to use comma-separated values which does not work.  #540 is for the longer-term UX work.
Signed-off-by: Ross Kukulinski <ross@kukulinski.com>
> Fix ingressroute docs re: root-namespaces CLI flag

- Gopkg.lock
- Gopkg.toml
- cmd/contour/contour.go
- internal/debug/debug.go
Updates #525
- Rework admin/debug http API handler
- rename flags to http-address and http-port, the previous ones had a
space and were probably never used by anyone
- add /heath and /metrics endpoints on http API handler
This adds 6 new dependencies over beta.1 but only a few hundred kb to the image size.
> All: add prometheus metric handler

- Makefile
- internal/contour/annotations_test.go
- internal/contour/cluster_test.go
- internal/contour/listener_test.go
- internal/contour/route_test.go
- internal/dag/dag_test.go
Adding goreportcard showed that some source files were not properly
formatted. I'm not sure where I copy pasta'd the current gofmt check,
but it didn't do what it said on the tin.
Replace with a better copy pasta version and break out the check into
its own target.
> Makefile: fix gofmt target

- Gopkg.lock
- internal/contour/cluster.go
- internal/contour/cluster_test.go
- internal/contour/route.go
- internal/e2e/e2e.go
- internal/e2e/lds_test.go
- internal/grpc/server.go
- internal/k8s/status.go
Fixes #534
Upgrade to go-control-place v0.4 to pick up improvements to duration
handling in healthcheck and circuitbreaking.
> Gopkg.toml: upgrade to envoyproxy/go-control-plane@v0.4

- Makefile
- internal/contour/cluster_test.go
Fix gofmt target so it fails the build.
Also, fix a small formatting incompatibility between Go 1.10 and Go
1.11. The gofmt rules have changed slightly, so avoid that by moving the
Host line to the top of the declaration where the rules do not
differ.
> Makefile: fix gofmt target (again)

- internal/contour/route.go
- internal/contour/route_test.go
- internal/dag/dag.go
- internal/dag/dag_test.go
Fixes #506 by adding tests to `actionroute()` in `route.go`.
The downside is that I had to export the `Object` field of the `dag.Service` struct to add these tests.
Tests:
```
=== RUN   TestActionRoute
=== RUN   TestActionRoute/single_service
=== RUN   TestActionRoute/single_service_with_timeout
=== RUN   TestActionRoute/single_service_with_infinite_timeout
=== RUN   TestActionRoute/single_service_with_websockets
=== RUN   TestActionRoute/single_service_with_websockets_and_timeout
=== RUN   TestActionRoute/multiple_services
=== RUN   TestActionRoute/multiple_weighted_services
=== RUN   TestActionRoute/multiple_weighted_services_and_one_with_no_weight_specified
--- PASS: TestActionRoute (0.00s)
--- PASS: TestActionRoute/single_service (0.00s)
--- PASS: …
```
> internal/contour,dag: add test coverage to route.go:actionroute

- internal/dag/dag.go
- internal/dag/dag_test.go
Updates #445
Cleanup the computation of dag.version, and fix a bug where the version
assigned to the IngressRouteStatus was not incremented, thus
representing the version counter for the dag that would be replaced by
recompute.
The new value of 2 in the test fixture is caused by dh.Insert() calling
recompute internallary, then dh.Recompute() is called directly to
retrieve the current IngressRouteStatus.
> internal/dag: fix IngressRouteStatuses.version computation

- internal/contour/adapter.go
- internal/dag/dag.go
- internal/dag/dag_test.go
Updates #445
Remove getters on dag.Status object, make fields public instead.
> internal/dag: remove getters on dag.Status object

- internal/contour/adapter.go
- internal/dag/dag.go
- internal/dag/dag_test.go
- internal/dag/k8s.go
Updates #445
This PR merges the return values from `DAG.recompute`; the `dag.dag` and the
`[]Status` list, into one, the `dag.dag`. Thus a `dag.dag`'s set of roots, and
the status while generating those roots are bound together.
This has the side effect of removing the return parameter from
`DAGAdater`'s `OnAdd`/`Update`/`Remove` methods, allowing it to fulfil the
cache.ResourceEventHandler interface directly.
This PR also merges the `dag.dag.version` and `IngressrouteStatus.version`
field as they were derive from the same place, so storing the value
twice had no value. The `IngressrouteStatus.GetVersion` accessor was not
used and was removed. This meant that IngressrouteStatus was just a
wrapper around `[]Status`, so it was also removed.
A note about skew between the contents of …
> internal/dag: combine ingressroute status with dag roots

- internal/contour/adapter.go
- internal/dag/k8s.go
This PR moves the call to DAG.Recompute from the
dag.ResourceEventHandler k8s shim to contour.Adapter. This places this
call at the same level as the other post update grpc and status updates.
> internal/dag: remove d.Recompute from dag.ResourceEventHandler

- internal/contour/adapter.go
- internal/dag/dag.go
- internal/dag/dag_test.go
Calculating IngressRoute metrics is implemented as a visitor. This does
not need to be implemented in the dag package so move it to the contour
package and incorporate it into the general DAGAdapter.update method.
> internal/contour: move calculateIngressRouteMetric to DAGAdapter

- internal/contour/adapter.go
- internal/contour/cluster.go
- internal/contour/cluster_test.go
- internal/contour/listener.go
- internal/contour/listener_test.go
- internal/contour/route.go
- internal/contour/route_test.go
- internal/dag/dag.go
- internal/dag/dag_test.go
- internal/debug/dot.go
Updates #445
This is an early PR of the infrastructure to address the O(N) cost of
DAG.Recompute.
This PR replaces DAG.Recompute with a new method, DAG.Compute which
returns a interface with Visit and Statuses methods. This means the
current dag.dag is no longer stored on the parent dag.DAG value.
The result of this is computation of a dag.dag from the source dag.DAG
(I really have to find better names) is now idempotent. The result from
calling DAG.Compute is stable, you can visit it as many times as you
want and it will not change from under you, nor will the values reported
by Statuses skew with respect to Visit.
The intention of this change is to decouple the following
1. DAG.Insert, Remove operations arrising from k8s watchers firing.
These are always handled syncronously inside the …
> internal/dag: make dag.Compute idempotent

- deployment/deployment-grpc-v2/02-contour.yaml
- deployment/ds-grpc-v2/02-contour.yaml
- deployment/ds-hostnet/02-contour.yaml
- deployment/render/daemonset-norbac.yaml
- deployment/render/daemonset-rbac.yaml
- deployment/render/deployment-norbac.yaml
- deployment/render/deployment-rbac.yaml
- docs/troubleshooting.md
What does this MR do?
- Reduce long one liner args into multiple lines
Why is this MR needed?
- Enhance readability
- Easier readbility if adding additional optional arguments
> Reduce long one liner argument statements into multiple shorter lines

- cmd/contour/contour.go
- internal/contour/cachehandler.go
- internal/contour/cluster_test.go
- internal/contour/contour_test.go
- internal/contour/k8s.go
- internal/contour/listener_test.go
- internal/contour/route_test.go
- internal/e2e/e2e.go
- internal/e2e/lds_test.go
- internal/e2e/rds_test.go
- internal/grpc/server_test.go
Fixes #576 
Introduce contour.Notifier to break the coupling between `contour.ResourceEventHandler` and `contour.CacheHandler`. The former is now only concerned with converting k8s watcher events into `dag.Builder` `Insert` and `Remove`s. After each event it calls `Notifier.OnChange` with the `dag.Builder`.
This has had some nice flow on effects into the contour tests, which are now completely unconcerned with the `CacheHandler` at all, they just care about calling visit on the results of calling `Compute` on a `*dag.Builder` passed to `Notifier.OnChange`.
On the downside, the type assertions added to the internal/e2e tests will certainly make me curse my former self when they blow up the next time I touch the types in internal/contour. So I've got that going for me.
> internal/contour: decouple ResourceEventHandler and CacheHandler

- cmd/contour/contour.go
- internal/contour/cachehandler.go
- internal/e2e/e2e.go
- internal/metrics/metrics.go
- internal/metrics/metrics_test.go
Updates #575 
Updates #576 
This is a cleanup PR before adding the counters for #575 and #576.
- The creation of a registry is now handled by the caller of `metrics.NewMetrics`, this removes the need the boolean parameter to `metrics.RegisterMetrics`
- As the boolean is removed, metrics are automatically registered with a registry supplied by the called to `metrics.NewMetrics`
- Storing counters in a map is replaced by storing them as fields on the metrics object. This removed a bunch of type assertions and showed a bug in the e2e tests where metrics were not being properly initialised and thus discarded during e2e tests.
> internal/metrics: refactor metrics package

- Gopkg.lock
- Gopkg.toml
Updates #575
Updates #576
Update to the 0.9.0-pre1 client to get access to prometheus.NewTimer
which is needed to add a request latency histogram.
> gopkg.toml: update prometheus client to 0.9.0-pre1

- internal/contour/cachehandler.go
- internal/grpc/server_test.go
- internal/metrics/metrics.go
Fixes #575
Add prometheus metrics for CacheHandler.OnUpdate duration.
> internal/contour: add CacheHandler.OnUpdate metrics

- cmd/contour/contour.go
- internal/contour/cluster_test.go
- internal/contour/k8s.go
- internal/contour/listener_test.go
- internal/contour/route_test.go
- internal/e2e/e2e.go
- internal/grpc/server_test.go
- internal/metrics/metrics.go
Fixes #574
Emit prometheus metrics for ResourceEventHandler events.
> internal/contour: add ResourceEventHandler metrics

- cmd/contour/contour.go
- internal/contour/holdoff.go
Fixes #577
This PR introduces a HoldoffNotifier implementation that delays the
notification of the underlying Notifier by 100 ms since the previous
call to HoldoffNotifier.OnChange or 500ms, whichever is the smaller.
The 100ms/500ms values are currently hard coded, a future PR may make
them configurable, which will allow this type to be used in the e2e
tests -- currently the e2e tests go directly to the
contour.CacheHandler Notifier.
Tracing shows a modest improvement in utilisation before:
And after:
This change. This is synthetic data where the dag.Builder contains a lot of services and ingresses, but few match (as the fixture is random data), so the resulting dag.DAG will be small.
> internal/contour: add HoldoffNotifier

- cmd/contour/contour.go
- docs/troubleshooting.md
- internal/debug/debug.go
- internal/debug/dot.go
- internal/httpsvc/http.go
- internal/metrics/metrics.go
Fixes #588 
This PR bifurcates the previous port 8000 debug http service grab bag into two.
Port 8000 is retained and reallocated to hosting `/metrics` and `/health` endpoints, the `--http-addr` and `--http-port` flags are routed through to this http handler. This should reduce the impact of this change on the gimbal metric gathering configurations. While the port has not changed, but default this listener binds to 0.0.0.0, rather than 127.0.0.1.
The remaining /debug/pprof and /debug/dag endpoints are redirected to a new handler which listens on 127.0.0.1:6060. This address is configurable with `--debug-http-addr` and `--debug-http-port`.
> cmd/contour: split /metrics and /health away from /debug endpoint

- internal/contour/cluster.go
- internal/contour/cluster_test.go
- internal/e2e/cds_test.go
Fixes #579 by disabling the Envoy Healthy Panic Threshold. 
> Disable panic threshold

- internal/contour/endpointstranslator.go
- internal/contour/endpointstranslator_test.go
Fixes #602
```
Before this change, we were ignoring endpoint update events that had
zero endpoints in the updated object. This was a problem because we were
not handling the case where we went from N endpoints to zero endpoints.
With this change, we only ignore the update if we are going from zero
endpoints to zero endpoints. Otherwise, we handle the update like any
other.
Signed-off-by: Alexander Brand <alexbrand09@gmail.com>
```
> internal/contour: ignore endpoint updates if both old and new have zero endpoints

- apis/contour/v1beta1/ingressroute.go
- deployment/common/common.yaml
- deployment/render/daemonset-norbac.yaml
- deployment/render/daemonset-rbac.yaml
- deployment/render/deployment-norbac.yaml
- deployment/render/deployment-rbac.yaml
- design/ingressroute-design.md
- docs/ingressroute.md
- internal/contour/route_test.go
- internal/dag/builder.go
- internal/dag/builder_test.go
- internal/e2e/lds_test.go
This finalizes the last bits to enable TLS for IngressRoutes. In addition, it adds a `minimumProtocolVersion` option to the `IngressRoute.Spec.VirtualHost.TLS` struct to allow users to define the minimumProtocolVersion as well as update the CRD valiation enum to match the supported versions. 
Fixes #467 #458 #452 
> internal/: Implement TLS & min tls protocol version

- apis/contour/v1beta1/ingressroute.go
- docs/ingressroute.md
- internal/dag/builder.go
- internal/dag/builder_test.go
- internal/e2e/rds_test.go
Adds a new field to the Routes object inside the IngressRoute CRD called `EnableWebsockets`, which controls whether a client can upgrade to a websocket connection on the given route.
Fixes #595
> internal/dag: add websocket support to ingressroute

- internal/dag/builder.go
- internal/dag/builder_test.go
- internal/e2e/rds_test.go
Fixes #606
rule.IngressRuleValue.HTTP can be nil as rule.IngressRuleValue's zero
value contains a nil HTTP field. This is possible with the following,
valid, YAML:
```
spec:
rules:
- host: test1.test.com
```
> internal/dag: avoid panic if spec.rule.paths.HTTP missing

- internal/contour/route.go
- internal/contour/route_test.go
- internal/dag/builder.go
- internal/dag/builder_test.go
- internal/dag/dag.go
- internal/e2e/rds_test.go
Fixes #451 by adding support for `Aliases` inside IngressRoute documents. Any alias defined is appended to the RDS `domains` array. 
> Add support for Alias in IngressRoute

- internal/contour/cachehandler.go
- internal/contour/cachehandler_test.go
- internal/contour/cluster_test.go
- internal/contour/listener_test.go
- internal/contour/route_test.go
- internal/dag/builder.go
- internal/dag/builder_test.go
- internal/debug/debug.go
- internal/debug/dot.go
Updates #581 
Rename the current dag.Builder to dag.KubernetesCache. This violates the
tenet that the dag shouldn't know much about where k8s object come from,
but in return we free up the dag.Builder type to become a per build
invocation context.
> internal/dag: rename dag.Builder to dag.KubernetesCache

- apis/contour/v1beta1/ingressroute.go
- apis/contour/v1beta1/zz_generated.deepcopy.go
- docs/ingressroute.md
- internal/dag/builder.go
- internal/dag/builder_test.go
- internal/e2e/lds_test.go
Fixes #455 
Adds a new field to the IngressRoute to control whether HTTP is allowed on a given VirtualHost:
```
spec:
virtualhost:
fqdn: "example.com"
allowHttp: false
```
Update (Aug 10, 2018): renamed the `allowHttp` field to `httpAllowed`:
```
spec:
virtualhost:
fqdn: "example.com"
httpAllowed: false
```
> Add the equivalent of 'kubernetes.io/ingress.allow-http: false' to IngressRoute

- internal/dag/builder.go
Always assign routes to a SecureVirtualHost sepeculatively. Later,
during builder.DAG, we filter out SecureVirtualHosts that do not have a
secret assigned.
> internal/dag: assign routes to SecureVirtualHost speculatively

- internal/dag/builder.go
- internal/dag/dag.go
Move from direct routes[path] = r manipulation to a helper. This removes
the possiblity of using the wrong key in the map as the key must be
derived from the Route's path field. This also defers the cost of
creating the route map until it is used.
> internal/dag: add VirtualHost/SecureVirtualHost addRoute helper

- internal/dag/builder.go
Address TODO from #629
The arguments to builder.setOrphaned already identify an ingressroute
uniquely by name and namespace, so there is no need to check if we've
already set the orphaned status bit as we will only ever encounter this
ingressroute once.
Also, as the orphaned bit is only set in a single pass over the set
of ingressroutes we don't need to check if we're setting a bit that was
previously unset -- the logic is simply, if you're a delegate
ingressroute, you are orphaned until proven otherwise.
Lastly, pass the ingressroute, not its name and namespace to
setOrphaned, this makes it harder to transpose the name and namespace
parameters (not that i've done that, several times).
> internal/dag: set all delegate routes orphaned initially

- apis/contour/v1beta1/ingressroute.go
- apis/contour/v1beta1/zz_generated.deepcopy.go
- docs/ingressroute.md
- internal/dag/builder.go
- internal/dag/builder_test.go
- internal/e2e/lds_test.go
Fixes #627
Invert the logic of spec.virtualhost.httpAllowed: false to
spec.virtualhost.httpsOnly true. This makes the zero value of the field
default to false, meaning http and https permitted, without indirecting
via a *bool.
> internal/dag: switch from httpAllowed to httpsOnly

- deployment/common/common.yaml
- deployment/render/daemonset-norbac.yaml
- deployment/render/daemonset-rbac.yaml
- deployment/render/deployment-norbac.yaml
- deployment/render/deployment-rbac.yaml
Fixes #617. 
I have tested to ensure that this doesn't break anything for Kubernetes API or kubectl <1.11
Signed-off-by: Ross Kukulinski <ross@kukulinski.com>
> Add AdditionalPrinterColumns to IngressRoute CRD spec

- internal/dag/builder.go
- internal/dag/builder_test.go
- internal/dag/dag.go
- internal/e2e/cds_test.go
- internal/e2e/rds_test.go
Updates #581 
Move service weight assignment from Route.addService to builder.lookupService. This means services with different route weightings are considered different from the POV of the DAG -- each call to lookupService with a different weight will result in a new service entry in the builder's cache.
However, this does not affect the name of the CDS entry as service weights are a property of RDS, not CDS.
This resolves one form of ambiguity related to #581; services reachable by multiple routes or present multiple times in the same route, both with differing weights, will now behave properly.
> internal/dag: make route weights part of the service's cache properties

- internal/contour/route.go
- internal/e2e/rds_test.go
Fixes #638
Weight was added to Service in #635. Ensure that clusters with the same
name have a stable weight sorting.
> internal/contour: sort clusters with the same name by weight

- internal/metrics/metrics.go
- internal/metrics/metrics_test.go
Fixes #612 by adding a metric cache to the metrics package. After an update, metrics are processed and any metrics that are not touched during an update are removed which fixes the issue where when values change, they would stay reporting when are really invalid. 
> internal/metrics: Add cache to metrics to allow for deletion of unneeded metrics

- internal/dag/builder.go
- internal/dag/builder_test.go
- internal/dag/dag.go
SecureVirtualHosts are like VirtualHosts except they have additional
fields. Model this in the dag package's types using embedding. This
removes a bit of duplication between the two types.
> internal/dag: embed VirtualHost inside SecureVirtualHost

- apis/contour/v1beta1/ingressroute.go
- design/ingressroute-design.md
- internal/contour/route_test.go
- internal/dag/builder.go
- internal/dag/builder_test.go
- internal/e2e/lds_test.go
- internal/e2e/rds_test.go
Fixes #456 by implementing 301 redirects when a Root IngressRoute defines a TLS section. Adds a `permitInsecure` to the Route section allowing for specific routes to server insecure traffic.
> Since defining a TLS section of a root IngressRoute tells Contour that it should set up a TLS listener and serve the provided TLS certificate/key, it's inherent that all requests be served over TLS. This results in any request to an insecure endpoint will receive a 301 http status code informing the client to redirect to the secure endpoint. No additional parameters need to be set for this functionality other than specifying TLS on the IngressRoute.
> 
> Additionally, it may be necessary to serve specific routes over an insecure endpoint. An example would be the challenges sent from LetsEncyrpt. …
> internal/dag: Enforce TLS

- deployment/common/common.yaml
- deployment/render/daemonset-rbac.yaml
- deployment/render/deployment-rbac.yaml
The aliases field has been removed from the IngressRoute CRD. This PR removes Aliases from the CRD "additional printer columns".
> deployment: remove Aliases from CRD printer

- docs/ingressroute.md
This example was missing the `services:` key, which would cause failure
when trying to submit the example to a kubernetes cluster. The change
is on [line 294](https://github.com/heptio/contour/compare/master...jelmersnoeck:correct-yaml-spec?expand=1#diff-d1dacc562d1dac587ae8c3e7aa565e6bR294).
It also [sets a valid name](https://github.com/heptio/contour/compare/master...jelmersnoeck:correct-yaml-spec?expand=1#diff-d1dacc562d1dac587ae8c3e7aa565e6bR255) for the Disable HTTP example. The `disableHttp`
name contains a capitalized character which isn't allowed by the 
validation regex:
`[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*`
I'm not sure if this is desired - I couldn't find a guideline for this - but I've
also added a commit …
> Fix examples for the IngressRoute documentation

- deployment/example-workload/ingressroute/06-multiple-roots/delegate.ingressroute.yaml
- deployment/example-workload/ingressroute/06-multiple-roots/root.ingressroute.yaml
The original IngressRoute design spec had support for an `Aliases` field. We've since removed that and this example shows how to accomplish the same functionality with multiple root IngressRoutes. 
It demonstrates how to have `bar.com`, as well as `www.bar.com`,  have the same delegate route which enables multiple FQDN's to be processed equally. 
Updates #644 
> docs: Add example showing how multiple Root IngressRoute objects 

- internal/contour/listener.go
- internal/contour/route.go
- internal/dag/builder.go
- internal/dag/builder_test.go
- internal/dag/dag.go
- internal/debug/dot.go
Export the dag.VirtualHost.Host field. There is no need to add a FQDN
accessor method as the caller has already type asserted the vertex to
one of VirtualHost or SecureVirtualHost.
This is useful in intergrating go-cmp into the test suite.
> internal/dag: export dag.VirtualHost.Host

- internal/contour/holdoff.go
- internal/contour/route.go
- internal/dag/builder.go
- internal/dag/builder_test.go
- internal/dag/dag.go
- internal/debug/dot.go
- internal/metrics/metrics.go
Export Route.path and rename it to Route.Prefix. This removes the
Prefix() accessor and makes it clear that all routes are keyed on
prefixes.
Unexport Route.Object as its rarely accessed outside builder_test and
matches the other variations in Secret.
> internal/dag: export/unexport Route fields

- internal/contour/route.go
- internal/contour/route_test.go
Updates #665
Rather than pealing off a few values from the dag.Route entry during
visiting, pass the whole object, and its dag.Service children to
actionroute. This will allow us to handle the additional retry
parameters added to dag.Route in the previous commit.
> internal/contour: pass route and services to actionroute

- internal/contour/route.go
- internal/contour/route_test.go
- internal/e2e/rds_test.go
Fixes #665 
Reimplement that retry-on, num-retries, and per-try-timeout support added in Contour 0.4 by @cmaloney and lost after Contour 0.5 when the dag was introduced.
Also add some tests so we can't loose this support again.
> internal/dag,contour,e2e: reimplement retry-on feature

- internal/contour/cluster.go
- internal/dag/builder.go
Handling the default ingress backend; spec.backend, is annoying. This PR
introduces a rewrite where the default backend is converted to a regular
ingress spec.rule and handled as part of the other rules.
This permitted several other cleanups along the way.
> internal/dag: normalise default ingress backend handling

- internal/contour/cluster.go
- internal/contour/cluster_test.go
- internal/contour/endpointstranslator.go
- internal/dag/builder.go
- internal/dag/builder_test.go
- internal/dag/dag.go
- internal/e2e/cds_test.go
Updates #581
This PR alters the way the CDS cluster name is computed to include a
hash of the service's parameters. This this way, services with differing
parameters will have different CDS entries.
These CDS entries share the same EDS backends, as they share the same
Cluster.ServiceName identifier.
At the moment only load balancing strategy is included in the parameter
hash. The next PR will include the other components of the health check
strategy.
> internal/contour: include lbstrategy in cluster name

- internal/contour/cluster.go
- internal/contour/cluster_test.go
- internal/contour/endpointstranslator.go
- internal/contour/route.go
- internal/contour/route_test.go
- internal/e2e/rds_test.go
Updates #581
Update the RDS route visitor for the previous change to CDS
cluster name field.
Rearrange the helpers such that servicename generates the CDS cluster
name for use by EDS; the name of the field is servicename. This frees
clustername for use by the RDS and CDS visitors for generating the
canonical name of the cluster.
> internal/contour: update route vistor for cluster name change

- internal/contour/cluster.go
- internal/contour/cluster_test.go
- internal/dag/builder.go
- internal/dag/builder_test.go
- internal/dag/dag.go
Fixes #581
Update CDS and RDS's clustername helper to include healthcheck params in
the name of the cluster. This matches the change to the dag where the
healthcheck params are used as part of the servicemeta map key.
> internal/contour: include healthcheck params in cluster name

- internal/contour/cluster.go
- internal/contour/cluster_test.go
Updates #684
Add some tests to lock in the behaviour of clustername.
> internal/contour: add clustername test

- deployment/common/common.yaml
- deployment/deployment-grpc-v2/02-contour.yaml
- deployment/ds-grpc-v2/02-contour.yaml
- deployment/ds-hostnet-split/03-envoy.yaml
- deployment/ds-hostnet/02-contour.yaml
- deployment/render/daemonset-rbac.yaml
- deployment/render/deployment-rbac.yaml
- internal/contour/cluster.go
- internal/contour/listener.go
- internal/e2e/cds_test.go
- internal/e2e/lds_test.go
- internal/envoy/config.go
- internal/envoy/config_test.go
Updates #443
Fix configuration generated by Contour to avoid triggering warnings
under Envoy 1.7.0.
This is _not_ backward compatible with Envoy 1.6.0.
> all: update to Envoy 1.7.0

- Gopkg.lock
- Gopkg.toml
- internal/contour/annotations_test.go
- internal/dag/annotations_test.go
Updates #653 
This is required for the v0.5 of go-control-plane. The upgrade breaks a
few tests where it wasn't copacetic to compare proto types by value.
> Gopkg.toml: upgrade to gogo/protobuf 1.1.1

- apis/contour/v1beta1/ingressroute.go
- internal/contour/cachehandler_test.go
- internal/dag/builder.go
- internal/dag/builder_test.go
This fixes #713 by updating the `IngressRoute` struct to add `omitempty` to json params so that any params not supplied do not throw errors when integrating with golang. 
Other change is the `Delegate` struct is now a pointer so that we can add `omitempty` and make that optional. Tests / builder.go have been updated to reflect change.
> apis: Fix IngressRoute struct missing omitempty

- Makefile
- cmd/contour/bootstrap.go
- internal/e2e/e2e.go
- internal/k8s/status_test.go
Add an errcheck target for running kiselk's errcheck tool.
This check is not enabled in make check because it is too noisy; there
are legitimate cases to ignore an error and I'm not going to add helpers
to make errcheck happy, the value gained is too low.
However, for a few of the points that errcheck raises I have addressed
them by refactoring the code; this improved the cleanup handling in
internal/e2e, so win/win I say!
> Makefile: add errcheck target

- .gitignore
- Makefile
- internal/contour/route_test.go
Add unconvert to make check. Unconvert spots places in the code where
explicit conversions are unnecessary.
> Makefile: add an unconvert target

- Makefile
- internal/dag/builder.go
Add gosimple target to make check. This helps spot overcomplicated logic
expressions.
This PR also adds a make unparam check, but it is disabled at the
moment.
> Makefile: add a gosimple target

- Makefile
Add ineffassign from Gordon Klass. Enabled in make check as there are no
failing occurences in the codebase (there are in vendor/ but yolo).
> Makefile: add ineffassign target

- Gopkg.lock
- Gopkg.toml
- internal/contour/listener.go
- internal/contour/listener_test.go
- internal/e2e/lds_test.go
- internal/envoy/listener.go
Fixes #706
Always inject envoy.listener.tls_inspector listener filter into TLS
enabled listeners.
> internal/contour: add envoy.listener.tls_inspector filter

- docs/cert-manager.md
The docs on how to setup CertManager were a bit out of date. This updates the way to deploy CertManager as well as the Let's Encrypt server URLs.
> Fixup docs on how to setup CertManager with LetsEncrypt

- internal/grpc/server_test.go
- internal/grpc/xds.go
- internal/grpc/xds_test.go
Updates #705
Refactor xds and grpc server tests to try to smoke out the cause of
*status.statusError rpc error: code = Unknown desc = context deadline exceeded
> internal/grpc: refactor xds and grpc tests

- internal/contour/route.go
- internal/contour/route_test.go
- internal/e2e/rds_test.go
Fixes #726
Envoy 1.7.0 does not support websocket connections on a
routeaction_weightedcluster backend. This PR changes the route visitor
to generate routeaction_cluster configuration for routes with singleton
backend services.
> internal/contour: use routeaction_cluster for single backend routes

- internal/contour/cluster.go
- internal/contour/cluster_test.go
- internal/contour/route.go
- internal/envoy/cluster.go
- internal/envoy/cluster_test.go
- internal/envoy/listener.go
- internal/envoy/route.go
Updates #708
Move route related helpers into internal/envoy.
> internal/envoy: move v2/route helpers into internal/envoy

- internal/contour/listener.go
- internal/e2e/lds_test.go
This unconditionally enables envoys [gzip http_filter](https://www.envoyproxy.io/docs/envoy/latest/configuration/http_filters/gzip_filter), which will compress responses if the request indicates it can handle it (via a "accept-encoding: gzip" request header).
I've enabled it with no options, which means it gets the defaults, as
listed [here](https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/filter/http/gzip/v2/gzip.proto
). In envoy 1.7.0, they're:
```yaml
{
"memory_level": 5,
"content_length": 30",
"compression_level": "DEFAULT",
"compression_strategy": "DEFAULT",
"content_type": [“application/javascript”, “application/json”, “application/xhtml+xml”, “image/svg+xml”, “text/css”, “text/html”, “text/plain”, “text/xml”],
"disable_on_etag_header": false, …
```
> enable automatic gzip compression of responses

- Makefile
Add pedantic target with checks that currently do not pass cleanly.
> Makefile: add pedantic target

- internal/contour/cluster.go
- internal/contour/cluster_test.go
- internal/contour/route.go
- internal/contour/route_test.go
- internal/e2e/cds_test.go
- internal/envoy/cluster.go
- internal/envoy/cluster_test.go
- internal/envoy/config.go
- internal/envoy/healthcheck.go
- internal/envoy/healthcheck_test.go
- internal/envoy/route.go
- internal/envoy/route_test.go
Update #708
Move more route and healthcheck envoy helpers into the internal/envoy
package. Add tests to prove they work as expected.
> internal/envoy: move more helpers into internal/envoy

- internal/e2e/cds_test.go
- internal/e2e/eds_test.go
- internal/e2e/lds_test.go
- internal/e2e/rds_test.go
Updates #705
The 100ms timeout was too short in some circumstances; maybe there are
clock skew issues on the CI host.
Rather than playing the "let's increase the timeout and hope" game,
remove the timeout. There are no circumstances where the e2e tests do
not expect a result so if one goes missing this is a serious bug.
> internal/e2e: remove context.WithTimeout from steam* helpers

- apis/contour/v1beta1/ingressroute.go
- deployment/common/common.yaml
- deployment/ds-hostnet-split/01-common.yaml
- deployment/example-workload/ingressroute/02-basic/domain-aliases.ingressroute.yaml
- deployment/render/daemonset-rbac.yaml
- deployment/render/deployment-rbac.yaml
- design/ingressroute-design.md
- internal/dag/builder.go
Fixes #749 by removing all references to alias since it is no longer part of the IngressRoute spec. 
> Remove alias field

- apis/contour/v1beta1/ingressroute.go
- docs/ingressroute.md
- internal/contour/route.go
- internal/dag/builder.go
- internal/dag/builder_test.go
- internal/dag/dag.go
- internal/e2e/rds_test.go
Adds a `pathRewrite` parameter to the IngressRoute.Route struct which Indicates that during forwarding, the matched prefix (or path) should be swapped with this value.
Updates #64 
> Implement pathRewrite for IngressRoute 

- cmd/contour/contour.go
- deployment/deployment-grpc-v2/02-contour.yaml
- deployment/render/deployment-rbac.yaml
- internal/envoy/config.go
- internal/envoy/config_test.go
And fixing deployment defaults for prometheus scraping to match reality.
This is a small bugfix, so didn't file an issue. Let me know if that's not appropriate.
All tests pass. Built and tested via docker and confirmed that:
- init container is no longer crash looping with the '--stats-address=0.0.0.0' flag set (it did previously, even though 0.0.0.0 is the default)
- the generated contour.yaml file produces the correct output.
- prometheus when configured with port 8002 can scrap metrics.
> Changing StatsAddress flag from Int to String to prevent Init container crash loop.

- internal/contour/route_test.go
- internal/e2e/rds_test.go
- internal/envoy/route.go
- internal/envoy/route_test.go
Some tracing applications support reporting on queuing time for incoming requests. Generally this is implemented by adding a `X-Request-Start` timestamp header to the requests as early as possible in the request path.
[New Relic](https://docs.newrelic.com/docs/apm/applications-menu/features/request-queue-server-configuration-examples) and [datadog](https://github.com/DataDog/dd-trace-rb/blob/master/docs/GettingStarted.md#http-request-queuing) are two examples of tools that support this header.
The [envoy docs](https://www.envoyproxy.io/docs/envoy/latest/configuration/http_conn_man/headers#custom-request-response-headers) say:
> Custom request/response headers can be added to a request/response at
> the weighted cluster, route, virtual host, and/or global route
> configuration level
I've …
> append x-request-start header to incoming HTTP requests

- internal/contour/k8s.go
- internal/contour/route_test.go
- internal/e2e/rds_test.go
I would like to propose the following PR as a solution to #720 
It works by checking for IngressRoute objects and testing for a `contour.heptio.com/ingress.class` annotation `validIngressClass`
Not sure if this is the correct approach, but my tests suggest it is functional.
> Supports contour.heptio.com/ingress.class annotation for IngressRoutes

- internal/contour/listener.go
- internal/contour/listener_test.go
- internal/envoy/listener.go
Updates #537
Updates #708
Move contour.httpfilter to envoy.HTTPConnectionManager.
> internal/contour: move http conn manager filter to internal/envoy

- .dockerignore
- internal/e2e/lds_test.go
- internal/envoy/listener.go
Fixes #537
This PR enables Envoy's support for HTTP/1.0 requests, with limitations.
The limitations are:
- There is no support for HTTP/1.0 requests which lack a Host: header.
- There is no support for backend clusters which only talk HTTP/1.0
> internal/envoy: enable HTTP/1.0 support

- deployment/ds-grpc-v2/02-contour.yaml
- deployment/ds-hostnet/02-contour.yaml
- deployment/render/daemonset-rbac.yaml
Fixes #766 by updating the example deployments to use the default listen port for Prometheus metrics. 
> deployment: Updated example deployment file prometheus port 

- internal/contour/route.go
- internal/envoy/route.go
- internal/envoy/route_test.go
Updates #708
Move handling of websocket enabled routes from contour.actionroute to
envoy.RouteRoute.
> internal/contour: move websocket handling to envoy.RouteRoute

- Gopkg.lock
- cmd/contour/contour.go
Update dependencies for the start of the 0.8 cycle.
Highlights:
- envoyproxy/go-control-plane v0.6.1
- prometheus/client_golang 0.9.0
- sirupsen/logrus 1.1.1
- grpc 1.16.0
> gopkg.toml: freshen dependencies

- internal/contour/cluster.go
- internal/contour/route.go
- internal/dag/builder.go
- internal/dag/builder_test.go
- internal/dag/dag.go
- internal/debug/dot.go
- internal/envoy/cluster.go
- internal/envoy/cluster_test.go
- internal/envoy/route.go
- internal/envoy/route_test.go
Updates #785 
Create a new `dag.HTTPService` type to represent k8s services providing an L7 HTTP endpoint.
> internal/dag: embed dag.Service in dag.HTTPService

- internal/dag/builder.go
- internal/dag/builder_test.go
- internal/dag/dag.go
- internal/debug/dot.go
- internal/envoy/cluster.go
- internal/envoy/cluster_test.go
- internal/envoy/route_test.go
Updates #789
The only property of Service.Object we needed was the Metadata.Name and
Namespace fields. Extract these to the dag.Service object.
> internal/dag: remove Service.Object field

- deployment/ds-hostnet-split/02-service-envoy.yaml
AWS NLB forwards requests source IP to the nodes, but for this to work accordingly we must provide the `externalTrafficPolicy: Local` to the Service resource.
Ref: https://kubernetes.io/docs/concepts/services-networking/service/#network-load-balancer-support-on-aws-alpha
Related to #757
> docs: Add externalTrafficPolicy to NLB example svc

- deployment/deployment-grpc-v2/02-contour.yaml
- deployment/ds-grpc-v2/02-contour.yaml
- deployment/ds-hostnet-split/03-envoy.yaml
- deployment/ds-hostnet/02-contour.yaml
- deployment/render/daemonset-rbac.yaml
- deployment/render/deployment-rbac.yaml
Fixes #696 by adding a `preStop` lifecycle hook to the Envoy pod.
The process is as follows:
1. Shutdown is received
2. preStop hook will curl envoy and set its state to unhealthy
3. Envoy healthcheck will fail to stop requests from Kubernetes
4. Kubernetes will wait 30s to terminate (allowing requests to drop)
I ended up adding another container to the pod which includes `curl` since Envoy doesn't have it included in the container. 
@davecheney setting this to `WIP` since this needs a bit of discussion as well as a proper container (i.e. not from my personal account). 
> deployment: Added preStop hook to stop Envoy from receiving new requests

- internal/contour/cachehandler.go
- internal/contour/cluster.go
- internal/contour/cluster_test.go
- internal/contour/listener.go
- internal/contour/listener_test.go
- internal/contour/route.go
- internal/contour/route_test.go
- internal/dag/builder.go
- internal/dag/builder_test.go
- internal/dag/dag.go
Updates #787
While adding TCPForwarding to internal/contour I noticed the way the
vistors worked was very fragile. ListenerVisitor in particular expected
to be called with a visitor which delegated to a
VirtualHost/SecureVirtualHost. This PR fixes this and refactors the
visitors in general to be more robust.
> internal/contour: refactor visitors

- deployment/common/common.yaml
- deployment/render/daemonset-rbac.yaml
- deployment/render/deployment-rbac.yaml
The regular expressions in the CRD schema aren't consistent with what defines a valid names of the Kubernetes resource they are referring to.
The easiest way to find this out is to create an invalid name and look at the error Kubernetes gives back to you. In order of the changes in this PR, the errors are:
```
The Secret "invalid#name" is invalid: metadata.name: Invalid value: "invalid#name": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
The IngressRoute "invalid#name" is invalid: metadata.name: Invalid value: "invalid#name": a DNS-1123 subdomain must consist of lower case …
```
> Fix patterns for resource names in CRD schema

- internal/contour/visitor_test.go
- internal/dag/builder.go
- internal/dag/builder_test.go
- internal/dag/dag.go
- internal/envoy/listener.go
- internal/envoy/listener_test.go
Update #787
Support multiple tcpproxy services. We reuse the ingressroute Service
definition so weighting and default weighting is supported.
> internal/envoy: add support for multiple TCPProxy.Services

- internal/envoy/config.go
- internal/envoy/config_test.go
Update #737
The `endpoint: /healthz` syntax was deprecated in Envoy 1.7. Switch to
the replacement syntax.
This change is backwards compatible with Envoy 1.7.0.
> internal/contour: use header match for /healthz probe

- internal/contour/cluster_test.go
- internal/contour/visitor_test.go
- internal/e2e/cds_test.go
- internal/envoy/cluster.go
- internal/envoy/cluster_test.go
Attempt at providing a solution for https://github.com/heptio/contour/issues/689
Goal: Add support for Cluster.AltStatName to expose a more readable stat name.
Note: `AltStatName` does not seem to have the `maximum length of a cluster name is limited to 60` limitation, so it is possible that the cluster name and the stat name differ slightly.
Feedback welcome!
> Add support for Cluster.AltStatName

- Makefile
- internal/e2e/e2e.go
- internal/metrics/metrics.go
staticcheck has incorporated changes from go-simple and unused. Clean up
the Makefile to support that. Also address several issues found by the
recent version of static check.
> Makefile: Remove unused make targets

- docs/ingressroute.md
sorry for the garbage branch i made a second ago...tried to use github’s quick web-based editor / PR creator and it did a branch rather than fork :/
> docs/ingressroute: fix typo 'backedn' -> 'backend'

- deployment/common/common.yaml
- deployment/render/daemonset-rbac.yaml
- deployment/render/deployment-rbac.yaml
Fixes #821 
Allow numbers in TLD. 
Example:   `my.domain.k8s`
> CRD fqdn regex is too strict

- docs/ingressroute.md
- internal/contour/listener.go
- internal/dag/builder.go
- internal/dag/builder_test.go
Allow an IngressRoute for TCP forwarding but without a `tls` section
which implicitly configures it as a TLS Passthrough. TLS Passthrough
only reads the very first TLS packets and routes the traffic without
doing any kind of TLS termination. The chosen `virtualhost` is
discovered by reading the TLS SNI (Server Name Indication) extension.
Closes #15
Signed-off-by: Gorka Lerchundi Osa <glertxundi@gmail.com>
> tcpproxy: add tls passthrough

- design/ratelimit-design.md
Updates #370 to provide a design doc implementation for RateLimiting. 
_Note: I have much of this developed on a branch, but want to get a good design doc agreed upon first._
> RateLimit design doc

- apis/contour/v1beta1/ingressroute.go
- docs/ingressroute.md
- internal/dag/builder.go
- internal/dag/builder_test.go
- internal/dag/dag.go
- internal/e2e/lds_test.go
Updates #850
TCP proxying requires one of a `tls.secretName` or `tls.passthrough` to
be present. The `tls.passthrough` option has no effect if
`spec.tcpproxy` is empty.
> ingressroute: add a tls.passthrough key to indicate TLS passthrough

- cmd/contour/contour.go
- internal/contour/cluster_test.go
- internal/contour/k8s.go
- internal/contour/listener_test.go
- internal/contour/route_test.go
- internal/e2e/e2e.go
- internal/grpc/server_test.go
Updates #854
Depending on the order in which parts of an ingressroute document are
processed the invalid status message generated may differ over runs.
Specifically two or more invalid components of an ingressroute will
patch status in a random order, defeating patch's "is this the same"
check and causing Contour to see the update to the ingressroute's
document, thus triggering a new OnUpdate event and the cycle starts
again.
For the interim filter out fields which are known to change -- status,
and metadata.resourceversion, during the OnUpdate comparision.
> internal/contour: filter out status update OnUpdate

- Gopkg.lock
- Gopkg.toml
- internal/contour/route_test.go
- internal/e2e/lds_test.go
- internal/e2e/rds_test.go
- internal/envoy/listener.go
- internal/envoy/listener_test.go
- internal/envoy/route.go
- internal/envoy/route_test.go
Upgrade to go-control-plane 0.6.4. Note versions 0.6.2 and 0.6.3 lack
the route_action.upgrade_configs definition which makes it impossible to
retain support for websocket upgrades. 0.6.4 is the least recent version
that can support websocket upgrades per route.
> Gopkg.toml: upgrade go-control-plane to v0.6.4

- Gopkg.lock
- Gopkg.toml
- internal/contour/route_test.go
- internal/e2e/rds_test.go
- internal/envoy/endpoint.go
- internal/envoy/endpoint_test.go
- internal/envoy/route.go
- internal/envoy/route_test.go
Update to go-control-plane 0.6.7. Pin to that version to avoid it
floating ahead while upgrading other dependencies.
> Gopkg.toml: update to latest go-control-plane

- Gopkg.lock
Freshen our unpinned dependencies for the 0.10 cycle.
> Gopkg.lock: freshen dependencies

- internal/contour/listener.go
- internal/contour/listener_test.go
- internal/e2e/lds_test.go
- internal/envoy/listener.go
Fixes #802
The proxy_protocol listener filter supports PROXY V1 (AWS/ELB) and PROXY
V2 (HAProxy).
> internal/contour: use proxy_protocol PROXY listener

- internal/contour/listener.go
- internal/contour/listener_test.go
- internal/contour/visitor_test.go
- internal/e2e/lds_test.go
- internal/envoy/bootstrap.go
- internal/envoy/bootstrap_test.go
- internal/envoy/endpoint.go
- internal/envoy/listener.go
- internal/envoy/listener_test.go
Updates #738
Address outstanding TODO in bootstrap configuration. Switch from
Cluster.Host to Cluster.LoadAssignment.
> internal/envoy: stop using deprecated cluster.host stanza

- internal/contour/listener.go
- internal/envoy/listener.go
- internal/envoy/listener_test.go
Refactor listener creation into an internal/envoy helper in anticipation
of #661
> internal/contour: move Listener creation to internal/envoy

- internal/dag/builder.go
- internal/dag/builder_test.go
- internal/e2e/rds_test.go
Fixes #887
This PR replaces the last hard coded use of port 443 with the
b.externalSecurePort. Previously if b.externalSecurePort,
--envoy-external-secure-port, was set to anything other than its
default, HTTPS routes were assigned to a disconnected listener.
> internal/builder: use b.externalSecurePort throughout

- cmd/contour/contour.go
Fixes #895
that Envoy will listen on. Reintroduce this feature with two new flags
--envoy-service-http-address
--envoy-service-https-address
Which permit the address that Envoy will bind to as part of the service,
that is, in the container, or on the host via host networking.
> cmd/contour: reattach --envoy-service-http{s}-address flags

- design/tls-certificate-delegation.md
- docs/ingressroute.md
- internal/dag/builder.go
- internal/dag/builder_test.go
- internal/e2e/lds_test.go
Fixes #905
Updates #410
This PR implements TLS Certificate Delegation for ingress (untested) and
ingressroute objects. See #889 for design.
> internal/dag: implement TLS Certificate Delegation

- internal/contour/cluster_test.go
- internal/envoy/cluster.go
Fixes #603 by setting DrainConnectionsOnHostRemoval to true if the cluster has healthchecks enabled. 
//cc https://github.com/heptio/gimbal/issues/208
> Set DrainconnectionsOnHostRemoval to true for any cluster w/healthchecks

- Dockerfile
We don't need anything from Alpine, not even the certificates. If I need
the certs in the future I can copy them from the build container.
> Dockerfile: switch to scratch for the final image

- .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Addresses https://github.com/heptio/contour/issues/931
Adds a PR template which references the Contribution workflow. It specifically highlights two key points that I think can be common "gotchas" for new contributors:
1. Contour operates according to the talk, then code rule. If you plan to submit a pull request for anything more than a typo or obvious bug fix, first you should raise an issue to discuss your proposal, before submitting any code.
2. All commits to Contour must have a Developer Certificate of Origin (DCO) sign off. More about that here https://github.com/heptio/contour/blob/master/CONTRIBUTING.md#dco-sign-off
> add a PR template outlining the contribution workflow

- Gopkg.lock
- Gopkg.toml
Signed-off-by: Amarnath <vaamarnath@gmail.com>
Fixes #934
> gopkg.toml: upgrade to client-go v9.0.0 / kubernetes v1.12.6

- deployment/ds-hostnet-split/03-contour.yaml
The example hostnet-split example didn't have escaped strings for the host-ports causing an error when applying the manifest. 
Fixes #940 
> Fix split hostnet example not creating

- internal/grpc/xds_test.go
Go 1.13 changed the internal representation of errors, they are no
longer comparable with DeepEqual.
> internal/grpc: do no use reflect.DeepEqual on errors

- Dockerfile
- Build outside the implicit $GOPATH provided by golang:1.12.1. This
enables module mode without an ENV line
- Switch to go mod download to populate the build cache
> Dockerfile: update for go modules

- cmd/contour/contour.go
> Fixing a typo in the help menu for contour serve

- docs/prometheus.md
Envoy prints server stats in Prometheus format by default
now. This feature was introduced via
https://github.com/envoyproxy/envoy/pull/2896 in upstream.
> docs: Remove prometheus config for envoy metrics

- deployment/deployment-grpc-v2/02-contour.yaml
- deployment/ds-grpc-v2/02-contour.yaml
- deployment/ds-hostnet/02-contour.yaml
- deployment/render/daemonset-rbac.yaml
- deployment/render/deployment-rbac.yaml
Remove "--v2-config-only" option as it was already deprecated in
envoy 1.9.0 [1] and is already removed in envoy master. This is safe
just to be removed, there is nothing else needed to change as the link
says.
To create this patch I changed:
ds-hostnet/02-contour.yaml
ds-grpc-v2/02-contour.yaml
deployment-grpc-v2/02-contour.yaml
And then run depoyment/render.sh script
[1]: https://www.envoyproxy.io/docs/envoy/v1.9.0/operations/cli#cmdoption-v2-config-only
> Remove envoy deprecated flag "--v2-config-only"

- deployment/common/common.yaml
- deployment/render/daemonset-rbac.yaml
- deployment/render/deployment-rbac.yaml
Fixes heptio/contour#965
As described in the issue, the current regex does not allow namespaced tls delegation secrets as `secretName` which was introduced in contour v0.10.0.
This implementation is not perfect since it allows multiple '/' which should not be valid. But IMO it's better than removing the regex validation until something better is in place.
> Allow '/' in tls secretName for certificate delegations

- Makefile
- deployment/deployment-grpc-v2/02-contour.yaml
- deployment/ds-grpc-v2/02-contour.yaml
- deployment/ds-hostnet-split/03-envoy.yaml
- deployment/ds-hostnet/02-contour.yaml
- deployment/render/daemonset-rbac.yaml
- deployment/render/deployment-rbac.yaml
Updates #983 by updating the example deployment files to use Envoy v1.9.1
> Upgrade Envoy to v1.9.1

- .travis.yml
Try to make the build more stable by using gocenter as a proxy rather than
direct to github.
> travis: switch to gocenter proxy

- deployment/common/common.yaml
- deployment/render/daemonset-rbac.yaml
- deployment/render/deployment-rbac.yaml
- docs/ingressroute.md
Fixes #977
Also correct documentation that incorrectly stated that spec.delegations
was a singular key.
> deployment: add validation to enforce delegations is a list of objects

- internal/envoy/bootstrap.go
- internal/envoy/bootstrap_test.go
- internal/envoy/listener.go
Updates #983
Turn on the normalise_paths option for all http_connection_manager
instances. This field is recognised by Envoy 1.9.1 and is necessary to
mitigate CVE-2019-9901.
> internal/envoy: enable normalize_paths

- Dockerfile
> Dockerfile: use gocenter.io as proxy

- design/custom-request-timeout.md
- go.mod
Fix en-GB spelling in recently comitted design document. Also, give up
on the land war in asia over including test dependencies in go.mod.
> design: fix build

- apis/generated/clientset/versioned/fake/register.go
- apis/generated/clientset/versioned/scheme/register.go
Fixes #993
For the k8s version bump in the following commit
61102135ec798caa09e2e1f8fead9d98fb851a6d CRD apis needs to be
regenerated
Signed-off-by: Qiu Yu <unicell@gmail.com>
> apis: regenerate after client-go v9.0.0 / kubernetes v1.12.6

- cmd/contour/contour.go
Related to #959
Client-go uses glog even though Contour by itself doesn't. In the
failure scenario, such as CRD types not registered, glog in client-go
attempts to log to files under /tmp, which may not even exist (e.g in
`scratch` Docker image) or not accessible (container started with
non-root user etc.). And when that happens it'll crash the whole Contour
process which should not happen.
This change overrides the glog flag to let it always dumping to stderr,
avoid logging to files which is not desired in container environment
Signed-off-by: Qiu Yu <unicell@gmail.com>
> Always let glog write to stderr not files

- deployment/deployment-grpc-v2/02-contour.yaml
- deployment/ds-grpc-v2/02-contour.yaml
- deployment/ds-hostnet/02-contour.yaml
- deployment/render/daemonset-rbac.yaml
- deployment/render/deployment-rbac.yaml
There have been multiple cases in which users ask how to configure
Envoy's HTTP/HTTPS listening ports. By explicitly setting the
configuration flags in the deployment samples, users should have a
better sense of the flags that are available.
Fixes #1003
> deployment: explicitly set the listening ports for doc purposes

- internal/e2e/cds_test.go
- internal/e2e/eds_test.go
- internal/e2e/lds_test.go
- internal/e2e/rds_test.go
- internal/grpc/xds.go
Updates #499
Updates #273
Previously each response sent to Envoy set the version_info field to
"0". The xDS documentation says that the version_info field should
change if the result returned by the management server has changed.
The xDS protocol does not place constraints on what the version_info
field should contain, other than it is a string. Internally the
Cache.Register method maintains a count of updates to the cache, so this
PR uses the string form of this counter for the version_info field in
the response.
The nonce field on the response message is used in the ACK/NACK protocol
from Envoy back to the management server which Contour doesn't
implement, but it seems reasonable to also use the string form of the
cache counter in both the version_info and nonce fields.
Signed-off-by: …
> internal/grpc: increment version_info on each response

- internal/envoy/auth.go
- internal/envoy/listener_test.go
The full list of ciphers that envoy permits by default are listed at [here](https://www.envoyproxy.io/docs/envoy/v1.9.1/api-v2/api/v2/auth/cert.proto.html?highlight=ciphers).
The defaults rate an "A" on qualy's ssl labs, however the AES128-* and AES256-* ciphers are marked as "weak". This appears to be for a combination of two reasons:
1. They don't support [Forward Secrecy](https://en.wikipedia.org/wiki/Forward_secrecy
)
2. They are easy to implement wrongly, exposing users to the [ROBOT attack](https://robotattack.org/
). Presumably boringssl (which envoy uses) has implemented them correctly, but it seems the general [recommendation is to avoid them if possible, just in case](https://community.qualys.com/thread/17971-tlsrsawithaes256cbcsha-comes-to-be-weak-cipher#comment-39790). …
> remove AES128-* and AES256-* from permitted ciphers list

- CONTRIBUTING.md
- design/design-document-tmpl.md
Every time I go to write a design document I find myself cribbing the
pieces off a previous one.
Add a design document template and make mention of it in the
contribution guidelines.
> design: add design document template

- internal/dag/builder_test.go
In preparation for introducing a new dag.Cluster type, dry up the
builder tests to limit the blast radius.
> internal/dag: dry up the builder tests some more

- internal/contour/route.go
- internal/envoy/route.go
- internal/envoy/route_test.go
There is nothing in dag.HTTPService that envoy.RouteRoute cares about so
adjust the signature to take a slice of dag.TCPService.
This will make the upcoming introduction of dag.Cluster easier.
> internal/envoy: Pass a slice of *dag.TCPService to envoy.RouteRoute

- deployment/ds-hostnet-split/02-statsd.yaml
- deployment/ds-hostnet-split/03-envoy.yaml
- deployment/grafana/01-namespace.yaml
- deployment/grafana/02-grafana-configmap.yaml
- deployment/grafana/03-grafana-deployment.yaml
- deployment/grafana/03-grafana-service.yaml
- deployment/prometheus/01-namespace.yaml
- deployment/prometheus/02-prometheus-alertmanager-configmap.yaml
- deployment/prometheus/02-prometheus-alertrules-configmap.yaml
- deployment/prometheus/02-prometheus-configmap.yaml
- deployment/prometheus/03-prometheus-alertmanager-deployment.yaml
- deployment/prometheus/03-prometheus-deployment.yaml
- deployment/prometheus/03-prometheus-node-exporter.yaml
- docs/prometheus.md
Fixes #969 by adding example deployments for prometheus & grafana. It updates the `ds-hostnet-split` example to match quickstart defined in [/docs/prometheus.md](github.com/heptio/contour/docs/prometheus.md) so that users can follow along and end up with a working solution.
This also adds sample dashboards to Grafana which provide metrics for both Contour & Envoy.
> Add example deployments for prometheus / grafana

- deployment/common/service.yaml
- deployment/deployment-grpc-v2/02-contour.yaml
- deployment/ds-grpc-v2/02-contour.yaml
- deployment/ds-hostnet/02-contour.yaml
- deployment/ds-hostnet/02-service.yaml
- deployment/render/daemonset-rbac.yaml
- deployment/render/deployment-rbac.yaml
This PR adds two patches: one to be consistent and always /stats/prometheus to scrape envoy metrics (more info in the commit message) and another that enables metrics for all types of deployments (updates # 1035).
The description for the commit that Update #1035 follows, the other was a small fix that I found while doing this.
The deployments has annotations to scrape metrics only for envoy. This
patch adds annotations to scrape metrics for the contour container too.
The annotations are added to the contour k8s service. This is for two 
reasons:
* The pod spec annotations only support to specify one container,
AFAIK, and are already used for metrics for the envoy container
* This seems like the easiest way to work-around the just mentioned
annotations limitation while being a trivial …
> Add prometheus annotations for contour container

- cmd/contour/contour.go
- deployment/deployment-grpc-v2/02-contour.yaml
- deployment/ds-grpc-v2/02-contour.yaml
- deployment/ds-hostnet-split/03-envoy.yaml
- deployment/ds-hostnet/02-contour.yaml
- deployment/render/daemonset-rbac.yaml
- deployment/render/deployment-rbac.yaml
- internal/envoy/bootstrap.go
- internal/envoy/bootstrap_test.go
- internal/envoy/config.go
Fixes #1008 by adding `AltStatName` to static clusters (contour & service-stats). Also renames `service_stats` cluster to `service-stats` to handle upstream parsing in dashboards. 
> Fix static clusters stats output by enabling an 'AltStatName'

- deployment/deployment-grpc-v2/02-contour.yaml
- deployment/ds-grpc-v2/02-contour.yaml
- deployment/ds-hostnet-split/03-envoy.yaml
- deployment/ds-hostnet/02-contour.yaml
- deployment/render/daemonset-rbac.yaml
- deployment/render/deployment-rbac.yaml
Fixes #1033 by updating the preStop hook to send post-data to Envoy's admin interface properly. 
> Update prestopHook to send post-data

- internal/contour/cluster.go
- internal/contour/route.go
- internal/contour/visitor_test.go
- internal/dag/builder.go
- internal/dag/builder_test.go
- internal/dag/cache.go
- internal/dag/dag.go
- internal/debug/dot.go
- internal/e2e/rds_test.go
- internal/envoy/cluster.go
- internal/envoy/cluster_test.go
- internal/envoy/listener.go
- internal/envoy/listener_test.go
- internal/envoy/route.go
- internal/envoy/route_test.go
Updates #813 
Background:
Around the 0.5/0.6 timeframe we added initial support for retries and health check strategy. The problem was we added these parameters on the dag.Service object; creating different versions of the same backend service depending on the properties of the path between the route and and the backend service.
This created two problems. The first is the linkage between the route and the service is the CDS cluster entry. We identify the cluster entry by name, and we have to pack all the properties of the _path_ from the route to the cluster into the cluster's name--different health check parameters to the same service, they have a different cluster name. The extra fun part is we only have 60 characters to encode all this information.
The second problem is tracking all …
> internal/dag: introduce dag.Cluster

- Makefile
- go.mod
- internal/contour/holdoff.go
Adds back staticcheck to make check target.
Updates: #956
Signed-off-by: Rohan Vora <vorar@vmware.com>
> Re-enable staticcheck

- deployment/deployment-grpc-v2/02-contour.yaml
- deployment/render/deployment-rbac.yaml
Changed the flag from `statsd-enable` to `statsd-enabled`.
Didn't open an issue since its a small typo fix, hope that's ok.
Ref: https://github.com/heptio/contour/blob/master/cmd/contour/contour.go#L59
> Fix typo in statsd-enabled flag for contour deployment manifest

- internal/grpc/resources.go
- internal/grpc/server.go
Addresses the first high-level design bullet point, creatign a gRPC
server for SDS by adding an SDS cache interface, implementing
FetchSecrets and StreamSecrets, and registering the server as an SDS
handler.
Updates #898
> internal/grpc: adds SDS and registers xds for sds

- cmd/contour/contour.go
- internal/contour/cachehandler.go
- internal/contour/secret.go
- internal/contour/secret_test.go
- internal/contour/visitor_test.go
- internal/dag/dag.go
- internal/envoy/secret.go
- internal/envoy/secret_test.go
- internal/grpc/server.go
Addresses the second high-level design bullet point, creating a
SecretCache to be used by Contour to internally identify any changes.
The cache is also registered as a resource type for the gRPC server,
allowing it to respond to requests.
Updates: #898
> internal/contour: add SecretCache and link to grpc

- cmd/contour/cli.go
- cmd/contour/contour.go
Addresses the third high-level design bullet point, support sds in the
contour cli for debugging.
Updates: #898
> cmd/contour: adds sds cli

- go.mod
- internal/contour/route.go
- internal/contour/route_test.go
- internal/e2e/e2e.go
- internal/e2e/rds_test.go
- internal/envoy/route.go
- internal/envoy/route_test.go
The newer version of go-control-plane has some fields removed like
RouteAction.RequestHeadersToAdd[] which were deprecated in v0.6.9.
Due to this, the existing implementation which added headers at the
weightedCluster and RouteAction layer was changed. Headers are now
added at the route layer as per discussion with @stevesloka.
Signed-off-by: Rohan Vora <vorar@vmware.com>
#Fixes: #999
> Updated go-control-plane to v0.7.1

- deployment/ds-hostnet-split/03-envoy.yaml
Removes an unnecessary annotation (`steve: "sloka"`) from the example `ds-hostnet-split` deployment. The change was added in https://github.com/heptio/contour/pull/1034
Signed-off-by: Robert Syvarth <robert.syvarth@gmail.com>
> Remove extra annotation from sample deployment

- cmd/contour/cli.go
- cmd/contour/contour.go
- go.mod
- internal/grpc/resources.go
Rather than derive the resource type names from first principle,
reference the values provided by go-control-plane. If they change, we
get that for free, if they are removed, we will now notice.
Also, tidy the go.mod file from some unnecessary deps that crept in.
Updates #273 
> internal/grpc: derive grpc resource types from go-control-plane

- design/tls-backend-verification.md
Updates #813
This PR adds a draft design for validation of backend services accessed
over TLS.
> design: add a strawman design for backend TLS verification

- internal/dag/builder.go
- internal/dag/builder_test.go
- internal/e2e/rds_test.go
Fixes secret lookup in Dag builder. It returns nil if certificate or
private key is empty/null in the kubernetes secret.
Fixes: #1051
Signed-off-by: Rohan Vora <vorar@vmware.com>
> internal/dag: Fix secret lookup

- internal/contour/listener.go
- internal/contour/listener_test.go
- internal/e2e/lds_test.go
- internal/envoy/auth.go
- internal/envoy/bootstrap.go
- internal/envoy/listener_test.go
Addresses the non-goals of the high-level design for secret discovery,
converting auth.CommonTlsContext from TlsCertificates with inline bytes
for secret data to TlsCertificateSdsSecretConfigs for secret references
from the xDS gRPC server.
Updates: #898
> internal/contour: auth.SdsSecretConfig for auth.CommonTlsContext

- design/custom-request-timeout.md
- docs/ingressroute.md
- internal/contour/route_test.go
- internal/dag/builder.go
- internal/dag/builder_test.go
- internal/e2e/rds_test.go
Fixes #1062
Update all references to 50x to be 5xx. The former is not a valid retry
code.
> all: 50x -> 5xx

- internal/dag/builder.go
- internal/dag/builder_test.go
- internal/dag/policy.go
- internal/dag/policy_test.go
Updates #1019
The retry policy documentation (#1042) states that a `retryPolicy:`
stanza with no fields implies a retry count of 1 -- if you don't want to
retry, don't add a `retryPolicy:` key.
This PR addresses this issue, and breaks out the retryPolicy logic into
a new file with associated tests to isolate this buisiness logic.
> internal/dag: Missing retry count implies 1 retry

- internal/dag/annotations.go
- internal/dag/annotations_test.go
- internal/dag/builder.go
- internal/dag/policy.go
- internal/dag/policy_test.go
Updates #1019
Move timeout policy handling to policy.go and add unit tests.
Also move parseTimeout and tests into policy.go to capture the
unexpected invalid duration == infinity logic.
> internal/dag: break out timeout policy handling

- internal/dag/annotations.go
- internal/dag/builder.go
- internal/dag/policy.go
- internal/dag/policy_test.go
Updates #1019
Rename timeoutPolicyIngressRoute and friend to timeoutPolicy as they
represent the current best practice logic for handling timeout/retries.
The older annotation based logic is handled differently because if the
differences in not found vs no set logic with respect to retry-on and
timeout parsing.
There are some TODO's that highlight the inconsistencies in the logic,
its not clear if its worth taking a compatability break to change that
logic now. There is good code coverage in this area that ensures we
won't regress the logic so maybe just leaving well enough alone is good
enough.
> internal/dag: unify timeout and retry policy logic

- internal/envoy/listener.go
Hardcodes the listener idle_timeout to 60s.
Fixes #1054
> internal/envoy: listener idle timeouts

- Makefile
- deployment/deployment-grpc-v2/02-contour.yaml
- deployment/ds-grpc-v2/02-contour.yaml
- deployment/ds-hostnet-split/03-envoy.yaml
- deployment/ds-hostnet/02-contour.yaml
- deployment/render/daemonset-rbac.yaml
- deployment/render/deployment-rbac.yaml
Fixes #998 by updating all the example deployments to use Envoy v1.10.0. It also updates the Makefile to have the local task use the same version. 
> Update Envoy to v1.10.0

- internal/envoy/accesslog.go
- internal/envoy/listener.go
Upates #876
Move accesslog fitler generation into its own file and function.
This moves the gross accesslog renamed imports to their own file to hide
that horribleness.
Also this removes the accesslog helper which returned a
types.StructValue as those functions will be rewritten to return
TypedConfigs in the next PR.
> internal/envoy: move accesslog filter into its own file

- internal/e2e/e2e.go
- internal/e2e/lds_test.go
- internal/envoy/accesslog_test.go
- internal/envoy/listener.go
- internal/envoy/listener_test.go
Updates #876
Updates #499
Convert TCPProxy listener filter to a TypedConfig. This gives us
protection if Envoy changes the proto definition of the filter types in
the future. It also reduces the background churn of idempotent, but not
bit-for-bit identical messages between Contour and Envoy.
This has lots of pleasent follow on effects; sorting of TCP Proxy
members is less gross, and we remove all uses of the odeous
messageToStruct via JSON hack.
Also, add tests for FileAccessLog and HTTPConnectionManager. They're
simple, but by adding a test we can then be sure that we can use them in
other functions as we have a test to assert what they are returning --
and if we change it in the future.
> internal/envoy: convert TCPProxy to TypedConfig

- cmd/contour/contour.go
- internal/contour/listener.go
- internal/e2e/e2e.go
- internal/e2e/lds_test.go
- internal/envoy/bootstrap.go
- internal/envoy/bootstrap_test.go
- internal/envoy/listener.go
Fixes #376 by removing the static listener from the bootstrap config to contour/listeners. This doesn't change how Contour has worked in the past, just moves where it's configured from bootstrap to inside Contour's XDs server. 
> internal/contour: Move static listener configuration out of bootstrap

- cmd/contour/contour.go
- internal/contour/listener.go
- internal/e2e/lds_test.go
Updates #876
Updates #376
Convert ListenerCache static values from proto struct to typed config.
This could do with DRYing up with some more with helpers, which I'll
tackle in a followup PR.
> internal/contour: convert NewListenerCache to TypedConfig

- design/external-names.md
Updates #334 & #825 by providing an initial design doc for proxying traffic to dns endpoints instead of Kubernetes endpoints.
> Design doc for externalNames

- internal/contour/listener.go
- internal/e2e/lds_test.go
- internal/envoy/stats.go
- internal/envoy/stats_test.go
Move the generation of the StatsListener to a helper inside
internal/envoy. This defines what the canonical definition of the stats
listener is, in one place, with a test. It also removes a lot of the
implementation plumbing from internal/contour and internal/e2e.
> internal/envoy: move StatsListener generation to helper

- internal/envoy/listener.go
Fixes #876
Tested locally on my GKE installation. It looks like Envoy's requirement
to have empty configuration structures has been relaxed with the switch
to typed config.
> internal/envoy: remove remaining use of struct config

- Makefile
Promote mvdan's unparam to run as part of the make check target. This
would have spotted a condition in a recent PR where a paremeter was
declared in the signture but wasn't used in the body of the function.
Skip the api/ directory as the generated files aren't lint clean -- but
we don't really care because a computer wrote them for us.
> Makefile: promote unparam to check target

- internal/grpc/server.go
- internal/grpc/server_test.go
- internal/grpc/xds.go
- internal/grpc/xds_test.go
Fixes #1060
Updates #1091
Fetch is never used by Envoy, but supporting it (poorly) in Contour
complicates helpers and streaming code. Remove Fetch support to
facilitate rewriting the EDS streaming code to address #1091.
> internal/grpc: remove Fetch* support

- cmd/contour/contour.go
- internal/contour/cluster.go
- internal/contour/endpointstranslator.go
- internal/contour/listener.go
- internal/contour/route.go
- internal/contour/secret.go
- internal/contour/xds.go
- internal/e2e/e2e.go
- internal/grpc/resources.go
- internal/grpc/server.go
- internal/grpc/server_test.go
- internal/grpc/xds.go
- internal/grpc/xds_test.go
Updates #1091
To convert a proto.Message to a proto.Any you need to know its declared
type (not Go type, protobuf type). Previously this was handled by the
CDS/EDS/RDS/etc types in internal/grpc, but this isn't very useful as
those types are tightly coupled to the values that are sourced from
internal/contour. Thus splitting the type that declares TypeURL and the
type that provides proto.Messages of those types permits things to be
constructed inconsistently. With this change the thing that provides
proto.Message values, via the Values() method, also provides a TypeURL
method to describe the type of the things provided by Values.
Also, add missing StreamSecret test case.
> internal/grpc: move TypeURL into internal/contour

- docs/annotations.md
- internal/dag/builder.go
- internal/dag/builder_test.go
Fixes #1023
The behaviour when these two annotations are both specified is somewhat
surprising: `allow-http: false` meant that no routes were not registered
for port 80, even if `force-ssl-redirect: true` was set - leading to a
404 where a 3xx with an upgrade to `https` was expected.
With this commit, we prioritize respecting `force-ssl-redirect`: if this
annotation is specified and set to `true`, we always register a port 80
route for the ingress, even if `allow-http: false`, so that the forced
upgrade can take effect.
Signed-off-by: Cera Davies <ceralena.davies@gmail.com>
> internal/dag: respect force-ssl-redirect over allow-http annotation

- internal/contour/cluster.go
- internal/contour/cluster_test.go
- internal/contour/contour_test.go
- internal/contour/endpointstranslator.go
- internal/contour/endpointstranslator_test.go
- internal/contour/listener.go
- internal/contour/listener_test.go
- internal/contour/route.go
- internal/contour/route_test.go
- internal/contour/secret.go
- internal/contour/secret_test.go
- internal/e2e/cds_test.go
- internal/e2e/eds_test.go
- internal/e2e/lds_test.go
- internal/grpc/xds.go
- internal/grpc/xds_test.go
Fixes #1091 
Updates #420
Updates #439 
Problems with Contour not returning a value to Envoy when asked specifically have occurred several times in the past. When they have occurred, because I didn't understand the underlying issue, they were fixed in a piecemeal fashion. This PR addresses the root cause of the issue and hopefully we'll never have to talk about this again.
Envoy can ask Contour two different questions; the first is "please tell me the contents of the xDS table", the second is "please tell me the contents of these specific named xDS entries". The former is performed when a [xDS Discovery Request](https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/discovery.proto#envoy-api-msg-discoveryrequest) supplies no `resource_name` hints. The latter uses `resource_name` hints …
> internal/{grpc,contour}: EDS always returns a value

- deployment/example-workload/ingressroute/07-externalname/root.ingressroute.yaml
- deployment/example-workload/ingressroute/07-externalname/service.yaml
- docs/ingressroute.md
- internal/dag/builder.go
- internal/dag/dag.go
- internal/e2e/cds_test.go
- internal/e2e/rds_test.go
- internal/envoy/cluster.go
- internal/envoy/cluster_test.go
- internal/envoy/route.go
Fixes #334 by allowing routes to proxy traffic to DNS names specified in the service.spec.externalName field of a service. When defined, this skips EDS and specifies the dns endpoint directly on the cluster.
> internal/envoy: Support services type externalName

- .gitignore
- Makefile
Fixes #1114 
Turns out that the easiest way to do this is to pass a host IP to the `contour bootstrap` invocation inside the `make local` target. Obviously this means that `contour serve` must be listening on that IP, which means that it should either be run with `contour serve --xds-address=0.0.0.0` or with a local IP on the host in place of 0.0.0.0. (Listening on all interfaces carries obvious security concerns).
I'm not sure where the best place to document this process is, willing to be educated on that front.
> Update `make local` target to work with local `contour serve`

- Makefile
- internal/contour/listener.go
- internal/contour/listener_test.go
Fixes #1096 
Should cut down LDS updates by ensuring a stable LDS cache, with no map ordering perturbing it.
> Add stable sorting to https listener creation.

- docs/cert-manager.md
Fixes #1109 by updating the Cert Manager documentation on how to deploy Let's Encrypt certificates with Contour & Kubernetes Ingress resources.
> docs: Update cert-manager.md for how to deploy certmanager with Ingress

- docs/resource_limits.md
Fixes #409 by adding a sample test run results across a varying number of service/ingressroutes and load to Envoy running within a sample AWS environment. 
The sample doc is only a guideline across many different sets of test run criteria. 
Given the results, I came up with these sample resource constraints that could apply to a generic "catch-all" type environment:
**_Envoy:_**
```yaml
resources:
requests:
memory: "256Mi"
cpu: 1
limits:
memory: "512Mi"
cpu: 2
```
**_Contour:_**
```yaml
resources:
requests:
memory: "100Mi"
cpu: "500m"
limits:
memory: "256Mi"
cpu: 1
```
> docs: Sample performance metrics 

- design/ingressroute-design.md
- docs/ingressroute.md
- examples/common/common.yaml
- examples/render/daemonset-rbac.yaml
- examples/render/deployment-rbac.yaml
- internal/contour/cluster_test.go
- internal/e2e/cds_test.go
- internal/e2e/rds_test.go
- internal/envoy/cluster.go
- internal/envoy/cluster_test.go
Fixes #1150
Fixes #1030
Updates #1005
RingHash and Maglev are two balancing / affinity strategies that can be
configured per Cluster, however they are not useful by themselves.
Without the ability to configure the hash key, which is usually some for
of session af session or cookie, these strategies are not useful and
cannot be used correctly.
As such, remove them from the list of selectable options. Support for
session affinity will be added later.
> all: remove Maglev and RingHash as supported load balancer strategies

- docs/ingressroute.md
The ingressroute documentation is not the right place to advertise
features which have not been implemented.
> docs: remove mention of unsupported default lb strategy

- internal/dag/builder.go
- internal/dag/builder_test.go
- internal/dag/dag.go
- internal/envoy/cluster.go
- internal/envoy/cluster_test.go
Updates #1145
Move the LoadBalancingStrategy key from dag.Service to dag.Cluster. The
latter is more appropriate because it represents the load balancing
strategy used on the path between a route and the k8s service
represented by the dag.Service object.
> internal/dag: move LoadBalancingStrategy from dag.Service to dag.Cluster

- CONTRIBUTING.md
Fixes #1136 
Just a small change with some rules of thumb. I've tried to make it clear these are guidelines rather than firm rules, suggestions on wording welcomed.
> Add commit guidelines

- cmd/contour/contour.go
- internal/metrics/metrics.go
Fixes #283 by implementing health check for Contour. It does this by using the kubernetes client Contour uses and checks the server version. This api is simple enough to test the connection to the api server, and doesn't require understanding namespaces or anything additional from the cluster.
I think some future PR's should move this out of the `metrics` package. It was initially added there so Prometheus would be able to scrape metrics, but now does a bit more.
// cc #1132
> internal/metrics: Implemented healthcheck for Contour

- examples/deployment-grpc-v2/02-contour.yaml
- examples/ds-grpc-v2/02-contour.yaml
- examples/ds-hostnet-split/03-contour.yaml
- examples/ds-hostnet/02-contour.yaml
- examples/render/daemonset-rbac.yaml
- examples/render/deployment-rbac.yaml
- internal/metrics/metrics.go
This PR renames Contour health check endpoint from `/health` to `/healthz` to improve consistency with other components and adds liveness and readiness probes for this endpoint in the examples directory.
Related to #283
:warning: even though I've been using this endpoint in my environment, I've not tested all the examples manifests.
> Rename Contour health check endpoint for consistency, add probes to examples

- docs/zenhub.md
While reading the docs of Contour I reached a broken link to zenhub app in the `docs/zenhub.md` file.
> docs: fix zenhub broken link

- internal/contour/cachehandler.go
- internal/e2e/e2e.go
Fix formatting directive in status error message and missing TestLogger
in e2e setup. Both of these problems were found while upgrading the
client Go libraries.
> internal/contour: fix format directive in status error message

- design/secure-communication.md
> design: Add Secure Communication design doc

- internal/envoy/listener.go
- internal/envoy/listener_test.go
This makes envoy open port for both ipv4 and ipv6 if the ipv6-any address is used ("::"). This makes it possible to use the same config for ipv4-only and ipv6-only k8s, and enables dual-stack.
The contour addresses are configured to "::" like;
```
command: ["contour"]
args:
- serve
- --incluster
- --envoy-service-http-port=8080
- --envoy-service-https-port=8443
- "--stats-address=::"
- "--envoy-service-https-address=::"
- "--envoy-service-http-address=::"
```
> Enable ipv4_compat for ipv6-any (::) addresses

- .gitignore
- CONTRIBUTING.md
Fix a `go` command missing.
Update Building section with some corrections.
Add some detail about using `make push` to push a Docker image.
Fixes #1191 
> Update CONTRIBUTING, thanks @odacremolbap

- docs/cert-manager.md
- examples/deployment-grpc-v2/02-contour.yaml
- examples/ds-grpc-v2/02-contour.yaml
- examples/ds-hostnet-split/03-envoy.yaml
- examples/ds-hostnet/02-contour.yaml
- examples/example-workload/ingressroute/00-common/02-deployments.yaml
- examples/grafana/03-grafana-deployment.yaml
- examples/prometheus/03-prometheus-alertmanager-deployment.yaml
- examples/prometheus/03-prometheus-deployment.yaml
- examples/prometheus/03-prometheus-node-exporter.yaml
- examples/render/daemonset-rbac.yaml
- examples/render/deployment-rbac.yaml
Updates `apiVersion` 
- for `Deployments` and `Daemonsets`.
- at documentation and examples.
- from `extensions/v1beta1` to `apps/v1`.
Fixes #1181 
**NOT** fixed
- `Ingress` resources are served since 1.14 under `networking.k8s.io/v1beta1` but will remain working at `extensions/v1beta1` until 1.19. For backwards compatibility (pre 1.14 clusters using contour) upgrading `ingress` should not be done yet.
Signed-off-by: Pablo Mercado <odacremolbap@gmail.com>
> update to apps/v1 for deployment and ds

- cmd/contour/contour.go
- docs/troubleshooting.md
Remove flags:
- `envoy-external-http-port`
- `envoy-external-https-port`
from code and docs.
Fixes #1141 
Signed-off-by: Pablo Mercado <odacremolbap@gmail.com>
> Remove deprecated envoid-external flags

- go.mod
- internal/grpc/server.go
Fixes #1173
Also stub out some new gRPC methods which we don't implement.
> go.mod: update to go-control-plane v0.8.1

- docs/deploy-options.md
- examples/kind/kind-expose-port.yaml
Updates #1196 by adding kind configuration to the `examples` directory.
> Add example kind configuration to examples directory

- cmd/contour/contour.go
- internal/contour/cachehandler.go
- internal/contour/cachehandler_test.go
- internal/contour/cluster_test.go
- internal/contour/contour_test.go
- internal/contour/holdoff.go
- internal/contour/k8s.go
- internal/contour/listener_test.go
- internal/contour/route_test.go
- internal/contour/secret_test.go
- internal/dag/builder.go
- internal/dag/builder_test.go
- internal/debug/debug.go
- internal/debug/dot.go
Updates #1142
Removes the dag.Builder type and propagate dag.KubernetesCache in its place.
The next PR will move KubernetesCache.IngressRootNamespaces to contour.ResourceEventHandler.
> internal/dag: replace dag.Builder with dag.KubernetesCache

- Makefile
- _integration/cert-contour.ext
- _integration/cert-envoy.ext
- docs/deploy-seperate-pods.md
- docs/grpc-tls-howto.md
- examples/ds-hostnet-split/03-contour.yaml
- examples/ds-hostnet-split/03-envoy.yaml
- Add `make gencerts` and `make applycerts` to Makefile
- Update `ds-hostnet-split` to expect the new certs.
- Add documentation for gRPC with TLS including example.
- Change split deployments to use the 'contour' name instead of the service env vars. Fixes #1127 
Fixes #862
Updates #881
>  update split deployments with TLS secured gRPC

- cmd/contour/contour.go
- internal/contour/cachehandler.go
- internal/contour/holdoff.go
- internal/metrics/metrics.go
- internal/metrics/metrics_test.go
Updates #1142 
This change moves the responsibility of maintaining the DAG rebuild metric closer to where it occurs. This has the side effect of removing that responsibility from the holdoff interposer which now has no connection to our metrics. This will be useful in a followup change to simplify dag.KubernetesCache
> internal/contour: move rebuild timestamp closer to where it occurs

- cmd/contour/cli.go
- cmd/contour/contour.go
- cmd/contour/serve.go
Similar to #1218, start to split out the serve subcommand into a helper
in its own file -- keep chipping away at main.main.
This PR doesn't completely move all the flags for serve into
registerServe, but makes a start. I'll tackle the rest in a followup PR.
Also, take the opportunity to do a small drive by simplification on
cli.go
> cmd/contour: break serve flag setup into helper function

- cmd/contour/contour.go
- cmd/contour/serve.go
Keep chipping away at main.main.
> cmd/contour: move debug service params to serveContext

- cmd/contour/contour.go
- cmd/contour/serve.go
This PR continues the work of last week migrating the various CacheHandler and ResourceEventHandler parameters to `contour serve`'s `serveContext` type.
At this point the entire serve subcommand can be migrated out of `main.main`, which will be the subject of the next PR.
> cmd/contour: move CacheHandler and ResourceEventHandler cli params to serveContext

- Dockerfile
> Dockerfile: bump Go version to 1.12.7

- docs/deploy-seperate-pods.md
- docs/grpc-tls-howto.md
- Correct CA cert names from `CAcert` and `CAkey` to `cacert` and `cakey`.
- Fix secret details in deploy-separate-pods.md
> Update split deployment documentation

- go.mod
There doesn't seem to be an easy way to write a make target that will
fail the build if go mod tidy is needed.
> go.mod: go mod tidy

- internal/dag/builder.go
- internal/dag/builder_test.go
Disallow wildcarded FQDNs for `IngressRoutes`
- Will check and reject any FQDN containing `*` at DAG build time
- Wont check Ingress
Implementation details
- CDR untouched, there is a regex already in place that does this check among others
- Tests for `IngressRoutes` using `*` have been replaced with `bar.com`. `foo.com` is been used at other tests, but wanted to make it easy for reviewers to diff
- Added a test case at `TestDAGIngressRouteStatus`
Fixes #1167
Signed-off-by: Pablo Mercado <odacremolbap@gmail.com>
> internal/dag: reject * from IngressRoute FQDN

- internal/contour/cachehandler.go
- internal/dag/builder.go
- internal/dag/builder_test.go
- internal/dag/cache.go
- internal/dag/dag.go
Fixes #1206 by changing how status is set within the DAG. Previously, the set status method took a slice and status was pushed onto it. When an invalid secret was found, a status for the invalid secret was appended to the slice. Later, a 'valid' status was appended. This caused a loop in how the status got updated and forced a dag to rebuild over and over. 
I changed to using a map of `Status` types, if a status is set, then do not overwrite if an existing status already 
> internal/dag: Fix constant dag rebuild when invalid secret found

- internal/contour/cachehandler_test.go
- internal/contour/listener_test.go
- internal/dag/builder.go
- internal/dag/builder_test.go
- internal/e2e/lds_test.go
Fixes #520 by rejecting any IngressRoute object that references a Kubernetes service that doesn't exist or is malformed. When this situation is encountered, the status of the IngressRoute object will be updated and the object will be ignored.
> internal/dag: Reject invalid service configuration if referenced service is missing

- cmd/contour/contour.go
- cmd/contour/serve.go
Fixes #1130
This PR adds the ability to supply configuration values to contour serve
from a configuration file. Some gymnastics are required to make this
work with kingpin and keep the precedence of config file -> env vars ->
cli flags.
At the moment only a few values are plumbed into the config file, mainly
to keep the linters happy. More will be added in 0.15.
> cmd/contour: add -c config-path flag

- site/_posts/2019-04-22-Routing-Traffic-to-Applications-in-Kubernetes-with-Contour.md
This will fix how the list is rendered on https://projectcontour.io/routing-traffic-to-applications-in-kubernetes-with-contour/.
/cc @timh
> Small fix for a list in the routing traffic blog

- examples/deployment-grpc-v2/02-contour.yaml
- examples/ds-grpc-v2/02-contour.yaml
- examples/ds-hostnet-split/03-envoy.yaml
- examples/ds-hostnet/02-contour.yaml
- examples/render/daemonset-rbac.yaml
- examples/render/deployment-rbac.yaml
Fixes #1244 by updating example deployments to switch to downstream API and env var for Envoy's --service-cluster and --service-node flags.
This can be verified by looking at the admin page: `http://localhost:9001/server_info`
e.g. 
```
{
"service_cluster": "heptio-contour",
"service_node": "envoy-qc96l",
}
```
> examples: switch to downstream API and env var for Envoy's cluster & node params

- internal/contour/route.go
- internal/contour/route_test.go
- internal/e2e/rds_test.go
- internal/envoy/route.go
- internal/envoy/route_test.go
Fixes #1243 by implementing a routematch_regex for any Ingress route containing a regex. 
> internal/contour: Fix missing regex implementation for Ingress resources

- internal/contour/route.go
- internal/contour/route_test.go
- internal/e2e/rds_test.go
Fix build by stabilising the sorting of routes. Now regexes sort before
prefixes, withing regexes and prefixes, they sorted by length.
> contour: sort prefix routes after regex routes

- internal/contour/route.go
- internal/dag/builder.go
- internal/dag/builder_test.go
- internal/dag/dag.go
- internal/debug/dot.go
- internal/envoy/route.go
- internal/envoy/route_test.go
Fixes #1287
Move the representation of prefix route and regex route out of
internal/envoy and into the DAG. This moves the responsibility for
choosing when to emit a prefix or regex route from the vistors in
internal/contour (via internal/envoy) and into the internal/dag builder.
> internal/dag: split Route into PrefixRoute and RegexRoute

- examples/deployment-grpc-v2/02-contour.yaml
- examples/ds-grpc-v2/02-contour.yaml
- examples/ds-hostnet-split/02-job-certgen.yaml
- examples/ds-hostnet-split/03-contour.yaml
- examples/ds-hostnet-split/03-envoy.yaml
- examples/ds-hostnet/02-contour.yaml
- examples/render/daemonset-rbac.yaml
- examples/render/deployment-rbac.yaml
- internal/contour/route.go
- internal/contour/route_test.go
- internal/dag/builder.go
- internal/dag/builder_test.go
- internal/dag/dag.go
- internal/debug/dot.go
- internal/e2e/rds_test.go
- internal/envoy/route.go
- internal/envoy/route_test.go
> Release 0.14.1

- .travis.yml
gocenter.io seems to be having problems today. Also build caching
doesn't seem to be working.
> travis.yml: fix travis build caching

- .travis.yml
- Makefile
- go.mod
Restore make download install target
- remove $(PKGS) make variable, that was causing the download action to
run before make download was being called as a side effect of go list
/facepalm
- freshen various tools dependencies
> travis: restore make download install target

- cmd/contour/serve.go
- internal/contour/cluster_test.go
- internal/contour/contour_test.go
- internal/contour/k8s.go
- internal/contour/listener_test.go
- internal/contour/route_test.go
- internal/contour/secret_test.go
- internal/dag/annotations.go
- internal/dag/cache.go
- internal/dag/cache_test.go
Updates #1166
Updates #1172
Move the filtering of ingress class from the k8s resource event handler
to the dag KuberenetesCache. The cache now returns a boolean indicating
if the insert or remove operation caused the cache to change. This in
turn sets the ground rules for whether a dag update will take place in
the caller.
> internal/dag: move IngressClass filtering to dag.KubernetesCache

- go.mod
proxy.golang.org changed recently to reject non SIV versions. Rewrite
go.mod to use v0 pesudo versions.
> go.mod: fix proxy.golang.org incompatability

- cmd/contour/contour.go
- go.mod
The default behavior of klog will be to attempt to log to a file,
similar to glog, which will result in a container crash because the
filesystem is read-only.
closes #1279
> cmd/contour: init klog flags to set logging to stderr

- internal/contour/cachehandler.go
- internal/contour/k8s.go
- internal/dag/builder.go
- internal/dag/cache.go
Updates #1166
Updates #1172
This PR moves the lock that prevents the cache from being updated during
dag rebuild from the dag package to the caller. This is extremely poor
form, the lock of a thing shouldn't be mutated externally, but in this
case its a stepping stone to a better implementation that doesn't need a
lock.
> internal/contour: move dag.KubernetesCache logging to the caller

- cmd/contour/serve.go
- internal/contour/cachehandler.go
- internal/contour/cachehandler_test.go
- internal/contour/secret_test.go
- internal/dag/builder.go
- internal/dag/builder_test.go
- internal/debug/dot.go
- internal/e2e/e2e.go
- internal/e2e/rds_test.go
Fixes #864 by adding config items `allowPermitInsecure` which if set to false, disables the ability to use `permitInsecure` from an IngressRoute.
> internal/dag: Add config file item `allowPermitInsecure`

- internal/e2e/lds_test.go
- internal/e2e/rds_test.go
setup(t) already assigns a fake client set, we don't need to do this
again in each test.
> internal/e2e: remove unnessary fake client set assignment

- internal/contour/cachehandler_test.go
- internal/contour/k8s.go
- internal/contour/secret_test.go
- internal/dag/builder.go
- internal/dag/builder_test.go
- internal/dag/cache.go
- internal/debug/dot.go
Updates #1166
Updates #1172
Refactor builder to a public type, retire the dag.BuildDAG() method in
favor of constructing a dag.Builder and calling Build(). Build() is safe
to be called multple times -- but not concurrently -- so it doesn't need
to be hidden behind a BuildDAG() helper.
> internal/dag: refactor Builder

- Dockerfile
Fixes #1312
Merge once 1.12.8 base images are available, see https://groups.google.com/forum/#!topic/golang-announce/0uuMm1BwpHE
> Dockerfile: update to Go 1.12.8

- internal/contour/cachehandler.go
Spotted while working on #1166 / #1170 
Log more details of the failure to patch status message back to the API server.
> internal/contour: log details of failed to set status message

- cmd/contour/serve.go
- internal/contour/handler.go
- internal/contour/metrics_test.go
- internal/contour/secret_test.go
- internal/dag/builder.go
- internal/dag/builder_test.go
- internal/debug/debug.go
- internal/debug/dot.go
- internal/e2e/e2e.go
- internal/e2e/lds_test.go
- internal/e2e/rds_test.go
- internal/grpc/server_test.go
Rather than building a new dag.Builder each time, reuse the same one.
This is safe to do as Builder.Build resets its internal state each time.
This also means the canonical setting for DisablePermitInsecure lives on
the builder and is set directly during startup.
> internal/contour: embed builder into contour.EventHandler

- go.mod
Update to grpc v1.23.0 to address the HTTP/2 issues that Netflix have
disclosed. There is no requirement to backport this to 0.14 as we don't
expose HTTP/2 to the world; it's either over localhost to Envoy running
in the same pod, or over TLS to a trusted Envoy.
> go.mod: upgrade to grpc v1.23.0

- examples/deployment-grpc-v2/02-contour.yaml
- examples/ds-grpc-v2/02-contour.yaml
- examples/ds-hostnet-split/03-envoy.yaml
- examples/ds-hostnet/02-contour.yaml
- examples/render/daemonset-rbac.yaml
- examples/render/deployment-rbac.yaml
Fixes #1254
Sadly envoyproxy/proxy does not ship with wget, or curl, so resort to
bash-fu to hit Envoy's healthcheck/fail endpoint.
> example: replace wget with bash magic

- cmd/contour/serve.go
- cmd/contour/serve_test.go
The TLS flag logic got complex enough that I wanted to ensure we had tests for it.
> Add `--insecure` flag, with tests for the TLS flag logic.

- cmd/contour/serve.go
Following the pattern that httpsvc established log the gRPC listener
address during startup.
> cmd/contour: log gRPC listening address on startup

- cmd/contour/serve.go
- examples/common/common.yaml
- examples/common/contour-config.yaml
- examples/deployment-grpc-v2/01-contour-config.yaml
- examples/deployment-grpc-v2/02-contour.yaml
- examples/ds-grpc-v2/01-contour-config.yaml
- examples/ds-grpc-v2/02-contour.yaml
- examples/ds-hostnet-split/01-contour-config.yaml
- examples/ds-hostnet-split/03-contour.yaml
- examples/ds-hostnet/01-contour-config.yaml
- examples/ds-hostnet/02-contour.yaml
- examples/render/daemonset-rbac.yaml
- examples/render/deployment-rbac.yaml
- go.mod
Fixes #1344
- Switch from json to yaml for --config-path.
- Update examples to match.
- Break out config map for easier editing.
- Add commentary to example config using default values.
> cmd/contour: switch to yaml for contour config

- internal/envoy/bootstrap.go
- internal/envoy/cluster.go
- internal/envoy/endpoint.go
- internal/envoy/endpoint_test.go
Updates #1159
Turns out all the callers of LBEndpoint actually wanted a higher level
object. Who are we to complain?
> internal/envoy: add Endpoints helper

- internal/envoy/bootstrap.go
Remove redundant checks from upstreamFileTLSContext.
upstreamFileTLSContext only has one caller which already verifies it is
called with non empty arguments.
> internal/envoy: remove redundant checks

- internal/dag/builder.go
- internal/dag/builder_test.go
- internal/e2e/rds_test.go
Updates #732 by setting IngressRoute status has multiple services and enabled WebSockets. This is currently not supported in Envoy yet.
> internal/dag: Set IngressRoute status error if multiple services are configured with websockets

- cmd/contour/serve.go
Fixes #1361
The stop channel was not wired into the grpc server stop signal. This
meant unless the grpc server was the instigator contour serve would hang
on group shutdown.
This PR fixes this by wiring stop into grpc.Server.Stop. It also adjusts
the stopping message in startInformer to be stopped so it is the same as
the other workers. This is important because we don't issue a "stopped"
message thus the reader could be confused that what was stopping had not
yet stopped.
> cmd/contour: cleanly shutdown grpc server

- cmd/contour/certgen.go
- cmd/contour/contour.go
- cmd/contour/serve.go
- examples/common/rbac.yaml
- examples/common/service.yaml
- examples/ds-hostnet-split/03-contour.yaml
- examples/render/daemonset-rbac.yaml
- examples/render/deployment-rbac.yaml
- go.mod
- add `--disable-leader-election` command line flag.
- Leader election parameters, including ConfigMap name and namespace, are not tunable yet.
Updates #1204 
`serve.go` needs cleanup, but this establishes baseline functionality.
> Add leader election

- internal/dag/cache.go
- internal/dag/cache_test.go
- internal/e2e/cds_test.go
- internal/e2e/lds_test.go
- internal/e2e/rds_test.go
Fixes #1172
Teach dag.Cache.Insert to return false if the Service being inserted is
not referenced by an Ingress or IngressRoute object in the cache.
The implementation is O(N(ingress)+N(ingressroutes)) this can be
improved later with caching if required.
> internal/dag: do not trigger update for unreferenced service

- internal/dag/cache.go
- internal/dag/cache_test.go
- internal/e2e/cds_test.go
- internal/e2e/lds_test.go
- internal/e2e/rds_test.go
- internal/e2e/sds_test.go
Fixes #1166
Teach dag.Cache.Insert to return false if the Secret being inserted
is not referenced by an Ingress or IngressRoute object in the cache.
The implementation is O(N(ingress)+N(ingressroutes)+O(tlsdelegations)).
> internal/dag: do not trigger update for unreferenced secrets

- internal/dag/builder.go
- internal/dag/dag.go
- internal/dag/dag_test.go
Updates #1165
The rules for determining if a SecureVirtualHost is valid are subtle as
they must take into account the workarounds for TLS passthrough to a
proxy. Move those into methods on VirtualHost/SecureVirtualHost and add
tests to assert them.
> internal/dag: move validity check to VirtualHost/SecureVirtualHost

- internal/contour/listener_test.go
- internal/contour/route.go
- internal/contour/secret_test.go
- internal/dag/builder.go
- internal/dag/builder_test.go
- internal/dag/dag.go
- internal/e2e/lds_test.go
Updates #1165
When processing Ingress documents the dag.Builder would create routes
even if there was no matching Service available. These empty routes were
then filtered out in the contour.Route visitor.
After this change the empty routes are no longer created at the dag
level and don't need to be filtered out at the visitor level. It also
appears this filtering was not as good as it should have been and there
were cases where listeners were being created when there were routes
without any valid clusters backing them.
> internal/dag: do not create routes if there is no matching service

- internal/contour/visitor_test.go
- internal/dag/builder.go
- internal/dag/builder_test.go
- internal/dag/dag.go
Fixes #1135
This PR removes the Builder's listeners map by storing two maps of
virtualhost and securevirtualhost objects directly in the builder. This
resolves #1135 by hard coding that there will only ever be a listener
for port 80 and a listener for port 443 -- this might not be the case
forever, but it will be for 1.0 and we can revisit that later.
In the mean time this significantly simplifies the handling of listeners
inside the builder. There is no more messy map storing two kinds of
objects which must be carefully identified every time we walk through
the map. It simplifies the dag.Listener object which no longer needs to
store things in a map when a slice will do. And it simplifies dag.dag()
because we no longer delete from a map while iterating through it, we
simply copy the …
> internal/dag: simplify Builder's virtualhost map

- cmd/contour/serve.go
- internal/grpc/server.go
Use grpc.Creds option to ask the gRPC server to create the TLS listener
rather than creating our own. This lets us do more setup work before
entering leader election. Once we are elected leader all there is to do
is to open the socker and serve.
> cmd/contour: rework how we configure TLS required auth

- cmd/contour/serve.go
- cmd/contour/servecontext.go
- cmd/contour/servecontext_test.go
- go.mod
Fixes #1367
Also add some tests for the YAML parsing of the config file.
Changed those tests to use `github.com/go-test/deep` so I could actually find the errors.
> Fix leader election config and TLS config loading of partial values.

- internal/contour/cluster_test.go
- internal/contour/listener_test.go
- internal/contour/route_test.go
- internal/contour/secret_test.go
- internal/dag/builder.go
Updates #1165
Clean up buildDAG, also add a helper to reduce the size of the
internal/contour unit tests.
> internal/builder: cleanup buildDAG

- internal/contour/listener_test.go
- internal/contour/secret_test.go
- internal/e2e/lds_test.go
- internal/e2e/sds_test.go
Updates #1165
The logic for a TLS enabled v1beta1.Ingress says that each path must
have a hostname. This means that a `spec.backend` cannot be served over
HTTPS, even at / because it lacks a hostname to match it up with its
companion `spec.tls.hostname`.
The internal/dag tests correctly tested for this, however due to #1165
the fixtures in internal/contour and internal/e2e used `spec.backend`
incorrectly. These created virtualhosts _with_ a child secret, but no
routes. These virtualhosts would be filtered out before reaching the RDS
tables, however they were correct enough to trigger the behaviour we
wanted to test in SDS and LDS.
This PR corrects the fixtures to use the correct `spec.rule.host` form.
The next PR will address #1165.
> internal/{contour,e2e}: fix invalid tls enable ingress fixtures

- internal/dag/builder_test.go
- internal/dag/dag.go
- internal/dag/dag_test.go
- internal/e2e/sds_test.go
Fixes #1165
Filter out SecureVirtualHost objects that have a secret but no routes.
This will exclude the secret attached to those objects from SDS until
there are valid routes for that vhost.
> internal/dag: filter out secure virtual hosts without routes

- go.mod
> go.mod: upgrade envoyproxy/go-control-plane to v0.8.6

- internal/contour/listener.go
- internal/contour/visitor_test.go
- internal/dag/builder.go
- internal/dag/builder_test.go
- internal/dag/dag.go
- internal/dag/dag_test.go
Fixes #1374
Contour only supports tcp proxying on port 443. Adjust the DAG data
model so that it is not possible to create a DAG that has a tcpproxy on
a non secure port.
> internal/dag: move TCPProxy to SecureVirtualHost

- internal/dag/builder_test.go
- internal/dag/cache.go
- internal/dag/cache_test.go
- internal/e2e/cds_test.go
- internal/envoy/secret.go
Fixes #1372
Do not store secrets in the cache unless they are tls or CA certs.
Determining if a CA cert is referenced is too complex so any update to a
CA cert will trigger a rebuild.
> internal/dag: exclude any secrets other than tls and CA cert from cache

- internal/dag/cache.go
Updates #1419
Service account tokens frequently have a `ca.crt` key which trips up our
filtering logic for CA certs for upstream TLS delegation. As a short
term fix, filter these out explicitly, however we should probably
enforce a known Secret.Type to avoid this weak detection logic.
> internal/dag: ignore service account token secrets

- cmd/contour/serve.go
- internal/contour/metrics_test.go
- internal/dag/builder_test.go
- internal/dag/cache.go
- internal/dag/cache_test.go
Updates #513
Add a logger to the KubernetesCache. This is useful at the moment to
spot failures to promulgate the projectcontour.HTTPLoadbalancer objects
through Contour.
This will also be useful to log cert validation failures, see #513.
> internal/dag: add logger to KubernetesCache 

- cmd/contour/serve.go
- internal/dag/builder.go
- internal/dag/cache.go
- internal/dag/cache_test.go
Fixes #1411
Add support for projectcontour.HTTPLoadBalancer and
projectcontour.TLSCertificateDelegation to the KubernetesCache. They
should now be available for building a DAG.
There is one commented out test case to do with
projectcontour.HTTPLoadBalancer Upstream certificate validation as the
route matching syntax is not yet defined.
ingressroute.TLSCertificateDelegations and
projectcontour.TLSCertificateDelegations are stored seperately but
merged together when computing the set of secrets to rebuild on. This
effectively makes them the same from Contour's point of view.
ingressroute's TLSCertificateDelegation can be used to delegate a secret
to an projectcontour.HTTPLoadBalancer and vice versa. Given that
ingressroute will be deprecated by (possibly removed) by Contour 1.0
this is …
> internal/dag: add HTTPLoadbalancer to KubernetesCache

- examples/common/httploadbalancer.yaml
- examples/ds-hostnet-split-httploadbalancer/01-common.yaml
Updates the HTTPLoadBalancer CRD to have a shortname. Additionally, changed the spec so that it can be versioned as it progresses to v1.
> examples: Update HTTPLoadBalancer CRD to have a shortname & be versioned

- cmd/contour/serve.go
- internal/contour/cachehandler.go
- internal/contour/handler.go
- internal/e2e/e2e.go
Updates #1425
Move the k8s.IngressRouteStatus object from the CacheHandler to the
EventHandler. In doing so the CacheHandler is only responsible for
updating itself via its visitors when presented with a new DAG.
> internal/contour: move IngressRouteStatus to EventHandler

- internal/dag/builder.go
- internal/dag/builder_test.go
- internal/dag/dag.go
- internal/envoy/cluster.go
- internal/envoy/cluster_test.go
- internal/envoy/healthcheck.go
- internal/envoy/healthcheck_test.go
This PR is a cherry-pick from #1424.
Introduce a `dag.HealthCheckPolicy` type to normalise health check
policy parameters across IngressRoute and HTTPLoadBalancer.
> internal/dag: introduce HealthCheckPolicy

- internal/dag/builder.go
- internal/dag/builder_test.go
- internal/dag/status_test.go
- internal/e2e/lds_test.go
- internal/e2e/rds_test.go
Fixes #865
Since 0.6 we've had a method called `dag.Builder.validIngressRoutes`
which excluded all but the IngressRoute roots. However we didn't have a
check at delegation point that the delegate was not itself a root. This
PR fixes that and adds some belt and braces tests to assert it won't
happen.
Adjust status tests to deal with the various order of delegation checks
vs other status checks.
> internal/dag: reject delegations from any ingressroute to a root

- cmd/contour/serve.go
- cmd/contour/servecontext.go
- cmd/contour/servecontext_test.go
- examples/common/contour-config.yaml
- examples/common/rbac.yaml
- examples/contour/03-contour.yaml
- examples/render/contour.yaml
- examples/render/daemonset-rbac.yaml
- examples/render/deployment-rbac.yaml
Updates #1385 
- Leader election on by default.
- Leader election configmap now `leader-elect` not `contour` (will be created if it doesn't exist)
- Added RBAC for HttpLoadBalancer CRDs.
- Updated `contour` deployment.
> Update leader election in prep for changing to multi-read, single-write

- CONTRIBUTING.md
Small clarification to Contributing doc to explain what types of commits should be removed and what should be kept when sending a PR to the project.
> Update CONTRIBUTING.md to add note about what types of commits are desired

- docs/configuration.md
Fixes #1392 by adding a doc on the Contour configuration file passed to `contour serve`. 
> docs: Document configuration file passed to contour serve

- internal/dag/builder.go
- internal/dag/builder_test.go
- internal/dag/status_test.go
Fixes #910
The use case is for a service offering tls passthrough on port 443, the
same service may wish to offer a non tls port which informs users they
need to connect over port 443. Presumably port 443 is not HTTPS but some
other protocol, the port 80 fallback is a convenience for people typing
the address into their browsers.
> internal/dag: permit combining non tls routing with tcp proxy

- internal/dag/builder.go
- internal/dag/builder_test.go
Fixes #1234
Reject any k8s ingress routes which contain a * in their host field.
> internal/dag: reject v1beta1.Ingress routes with * in their hostname

- cmd/contour/leadership.go
- cmd/contour/serve.go
Updates #1385 
Only register leadership election workers if leadership election is
enabled.
Also remove the event recorder and broadcaster because it doesn't seem
to do anything -- leadership election still poops klog lines.
> cmd/contour: clean up leadership election setup

- internal/dag/builder.go
- internal/dag/builder_test.go
- internal/dag/status_test.go
Fixes #1470 by allowing multiple levels of includes to be processed within the builder. Also fixes #1458 by checking for a delegation cycle with Includes. 
> internal/dag: Allow for multiple levels of includes

- internal/dag/status_test.go
In #1471, the status tests were split into IngressRoute & HTTPLoadBalancers. Unfortunately, the IngressRoute were left commented out with local testing. 
> internal/dag: Re-enable status tests

- examples/contour/03-envoy.yaml
- examples/deployment-grpc-v2/02-contour.yaml
- examples/ds-grpc-v2/02-contour.yaml
- examples/ds-hostnet-split-httploadbalancer/03-envoy.yaml
- examples/ds-hostnet-split/03-envoy.yaml
- examples/ds-hostnet/02-contour.yaml
- examples/render/contour.yaml
- examples/render/daemonset-rbac.yaml
- examples/render/deployment-rbac.yaml
- internal/envoy/stats.go
- internal/envoy/stats_test.go
This PR enables Envoy's 1.11+ `/ready` endpoint for readiness probes.
Closes #1277
> Use Envoy's /ready endpoint for readiness probes

- internal/contour/metrics.go
- internal/dag/builder.go
- internal/dag/status.go
- internal/dag/status_test.go
Updates #1425 
Introduce a StatusWriter type and use it mostly within the builder. Fixing _orphaned_ status writing will be more complicated.
> internal/dag: introduce StatusWriter

- examples/common/httpproxy.yaml
Updates #1479 to rename `httploadbalancer.yaml` --> `httpproxy.yaml`. Also, fixes k8s api issue where CRD name must be plural:
```
The CustomResourceDefinition "httpproxy.projectcontour.io" is invalid: metadata.name: Invalid value: "httpproxy.projectcontour.io": must be spec.names.plural+"."+spec.group
```
> Rename CRD / Fix metada name

- internal/contour/cluster.go
- internal/contour/cond.go
- internal/contour/endpointstranslator.go
- internal/contour/listener.go
- internal/contour/route.go
- internal/contour/secret.go
- internal/e2e/eds_test.go
- internal/grpc/xds.go
- internal/grpc/xds_test.go
Updates #426 
Updates #499 
This PR consolidates all the `internal/contour` caches on the `Cond` type. The `Cond` type has been taught to send notifications to only those who register for those notification. At the moment this is only used for EDS however CDS and SDS may be possible. LDS and RDS are not useful as they only contain two entries each.
> internal/contour: filter EDS notifications

- internal/dag/builder.go
- internal/dag/status_test.go
- internal/e2e/rds_test.go
Fix e2e/rds test failure caused by virtual host that shouldn't be there
because it was part of an invalid delegation chain.
The fix required moving the check for delegation from a root to another
root earlier in the process which required changing some fixtures.
Specifically a non root can never delegate to a root, either directly or
indirectly so we can't use that as a test fixture.
> internal/dag: fix build

- go.mod
- go.sum
> go.mod: upgrade to honnef.co/go/tools v0.0.1-2019.2.3

- cmd/contour/serve.go
- cmd/contour/servecontext.go
- internal/contour/listener.go
- internal/contour/listener_test.go
- internal/contour/visitor_test.go
- internal/e2e/lds_test.go
- internal/envoy/accesslog.go
- internal/envoy/accesslog_test.go
- internal/envoy/listener.go
- internal/envoy/listener_test.go
Updates #624
This PR contains the code for JSON logging only. The ticket will be closed when the documentation is merged as well.
> Add support for JSON logging.

- examples/contour/01-common.yaml
- examples/render/contour.yaml
Updates #1516 which removed the working version of the HTTPProxy CRD. 
> examples: Update HTTPProxy CRD / validation

- examples/contour/01-contour-config.yaml
- examples/contour/02-job-certgen.yaml
- examples/render/contour.yaml
- Config file must have at least one value uncommented. Fixes #1527.
- Certgen Job must have imagePullPolicy set to Always for namespace change to take effect.
> Fix problems with example deployment

- internal/contour/cond.go
- internal/contour/cond_test.go
Fixes #1514
On Sept 10th I introduced a bug in #1480 which caused Cond.Register()
calls that supplied a hint, such as Envoy's RDS requests, to only
receive one initial update then ignore any further table updates.
The cause was a shadowing but on line 64 where `hints` was shadow from
outside the loop. The result was the `len(hints) == 0` condition would
be false, yet the map lookup version later would never be true because
the map would be empty.
Rewrite `Notify` to make it harder to shadow the variable `hints` and
also avoid the deeply nested logic requiring a break from the inner loop
to the outer loop. The new approach is slower for large values of
registered or notifited hints, but the former is usually no more than
one as Envoy either asks for everything, or a specific resource, and …
> internal/contour: fix shadowing error

- internal/contour/route_test.go
- internal/e2e/rds_test.go
- internal/envoy/accesslog_test.go
- internal/envoy/route.go
- internal/featuretests/ingressclass_test.go
Clean up the route visitor tests by introducing helpers from the envoy
package that we use elsewhere.
> internal/contour: clean up route visitor tests

- internal/contour/route.go
- internal/envoy/route.go
- internal/envoy/route_test.go
This PR fell out of debugging #1514.
A year ago #730 added the x-request-start header to each incoming
request. At the time this was done by adding the hedaer on each
route. This is verbose to see in the configuration and can be done
once at the enclosing RouteConfiguration.
This change means empty RouteConfigurations will have a
RequestHeadersToAdd field, but this is of little consiquence as it
applies to no routes as the list of virtualhosts is empty.
Another side effect of this change is the x-request-start header will be
added to redirects, however as this is a _request_ header, it is never
presented downstream during 301 processing so again it should have
little impact.
> internal/envoy: move x-request-start header to RouteConfiguration

- .yamllint
- Makefile
Yamllint is too noisy at the moment so it's not added to the check
target but we need to address these warnings before 1.0.
> Makefile: add yamllint target

- internal/contour/route.go
- internal/dag/builder.go
- internal/dag/builder_test.go
- internal/dag/dag.go
- internal/dag/dag_test.go
- internal/debug/dot.go
Add support to dag.Route to hold an ordered list of Conditions.
- dag.Condition is kind of a goofy interface, but will suffice for now
- dag.PrefixRoute/RegexRoute have gone away, this leaves the Route type
to stand alone
- dag.PrefixCondition/RegexCondition replace the previous
PrefixRoute/RegexRoute types.
- Rework dag.Build for condition support
- Rework contour.RouteVisitor for the simple Condition lists that
dag.Builder crates -- one Condition per Route is effectively hard coded.
- There is no support for HeaderConditions yet.
> internal/dag: refactor Route to hold Conditions

- apis/projectcontour/v1alpha1/httpproxy.go
- internal/dag/builder.go
- internal/dag/builder_test.go
Restore most of the HTTPProxy processing. Restored builder_test.go,
but not status_test.go.
It turns out that collecting routes and their conditions and processing
those routes are tightly coupled because to resolve a service that a
route points to, you need the context of the specific object that holds
the route because includes allow routes to span namespaces.
> internal/dag: restore HTTPProxy processing

- apis/projectcontour/v1alpha1/httpproxy.go
- internal/dag/builder.go
- internal/dag/builder_test.go
- internal/dag/dag.go
- internal/dag/policy.go
- internal/dag/policy_test.go
- internal/envoy/route.go
- internal/envoy/route_test.go
Updates #944
Rename spec.routes.timeout.request to respose because it is actually a
response timeout. The Envoy docs describe routeaction.timeout as
> This spans between the point at which the entire downstream request
(i.e. end-of-stream) has been processed and when the upstream response
has been completely processed. A value of 0 will disable the route’s
timeout.
When we initially added this field it was called request, which is not
accurate, this timeout is the response in reaction to a request.
We can't fix this for ingressroute, but we can for httpproxy, and patch
it up as best we can for ingressroute.
> api: rename TimeoutPolicy.Request to Response

- internal/contour/route.go
- internal/dag/builder.go
- internal/dag/dag.go
- internal/envoy/route.go
This PR allows all header conditions to be merged together and passed off to Envoy.
**NOTE**: This is currently missing tests to properly cover the new code. 
> internal: Add header contains support to HTTPProxy 

- examples/contour/03-contour.yaml
- examples/render/contour.yaml
Also set maxSurge so that new pods will be created before old pods are removed.
> Revert Contour deployment to Rolling Update

- docs/ingressroute-to-httpproxy.md
- docs/ingressroute.md
Fixes #1561
Also, mark IngressRoute as deprecated.
> docs: add IngressRoute to HTTPProxy migration document

- apis/projectcontour/v1alpha1/httpproxy.go
- internal/contour/route_test.go
- internal/dag/builder.go
- internal/dag/builder_test.go
- internal/dag/dag.go
- internal/envoy/route.go
- internal/featuretests/envoy.go
- internal/featuretests/mirrorpolicy_test.go
Fixes #459
Add support for per route traffic mirroring. Only available in HTTPProxy
```yaml
spec:
routes:
- conditions:
- prefix: "/"
- services:
- name: kuard
port: 8080
- name: kuard-mirror
port: 8080
mirror: true
```
> dag: add support for traffic mirroring

- docs/httpproxy.md
- examples/example-workload/httpproxy/01-ingress-to-httpproxy/basic-httpproxy.yaml
- examples/example-workload/httpproxy/01-ingress-to-httpproxy/httpproxy-name.yaml
- examples/example-workload/httpproxy/01-ingress-to-httpproxy/httpproxy-tls.yaml
- examples/example-workload/httpproxy/02-tls-options/httpproxy-tls-cert-delegation.yaml
- examples/example-workload/httpproxy/02-tls-options/httpproxy-tls-upstream.yaml
- examples/example-workload/httpproxy/03-routes/httpproxy-health-checks.yaml
- examples/example-workload/httpproxy/03-routes/httpproxy-lb-strategy.yaml
- examples/example-workload/httpproxy/03-routes/httpproxy-multiple-headers.yaml
- examples/example-workload/httpproxy/03-routes/httpproxy-multiple-paths.yaml
- examples/example-workload/httpproxy/03-routes/httpproxy-multiple-upstreams.yaml
- examples/example-workload/httpproxy/03-routes/httpproxy-prefix-rewrite.yaml
- examples/example-workload/httpproxy/03-routes/httpproxy-request-timeout.yaml
- examples/example-workload/httpproxy/03-routes/httpproxy-sticky-sessions.yaml
- examples/example-workload/httpproxy/03-routes/httpproxy-tls-permitinsecure.yaml
- examples/example-workload/httpproxy/03-routes/httpproxy-websockets.yaml
- examples/example-workload/httpproxy/03-routes/httpproxy-weight-shfiting.yaml
Updates #1564 by fixing some of the examples of `Conditions` which take a list of prefix or headers. 
> Update HTTPProxy docs / examples

- internal/assert/assert.go
- internal/dag/annotations.go
- internal/dag/builder.go
- internal/dag/policy.go
- internal/dag/status_test.go
Updates #459
Updates #1569
Clean up builder and add mirror status tests.
> internal/dag: add mirror status tests

- Dockerfile
Even thgouh we don't directly expose the Go net/http package to the
outside world, this is good hygene.
https://groups.google.com/forum/m/#!topic/golang-announce/cszieYyuL9Q
> Dockerfile: update to Go 1.13.1

- docs/httpproxy.md
- examples/example-workload/httpproxy/03-routes/httpproxy-response-timeout.yaml
Thanks to Michael P (@moderation on Kubernetes slack) for pointing this out.
Fixes #1588
> Update HTTPProxy docs with response timeout instead of request

- internal/contour/route.go
- internal/contour/route_test.go
- internal/e2e/rds_test.go
- internal/envoy/listener.go
- internal/envoy/route.go
- internal/envoy/route_test.go
Updates #1579
Preparation for a larger change to come next which will give us a
foothold to sort a set of *dag.Route objects.
This PR moves a lot of the duplicated logic out of
internal/contour/route.go into internal/envoy helpers.
> internal/contour: move dag.Route condition parsing to internal/envoy

- internal/contour/route_test.go
- internal/dag/builder.go
- internal/dag/builder_test.go
- internal/dag/conditions.go
- internal/dag/conditions_test.go
- internal/dag/dag.go
- internal/debug/dot.go
- internal/e2e/rds_test.go
- internal/envoy/route.go
Updates #1579
Rather than merging route conditions during the route visitor walk,
merge them earlier during the dag building stage. This simplifies the
dag.Route object to a single set of conditions. This also makes
dag.Route similer to envoy's route object, but because we control it we
stand a better chance of sorting it.
> internal/dag: merge route conditions in dag builder

- cmd/contour/serve.go
- cmd/contour/servecontext.go
- examples/contour/01-contour-config.yaml
- examples/render/contour.yaml
- internal/contour/listener.go
- internal/contour/listener_test.go
- internal/e2e/lds_test.go
- internal/envoy/listener.go
- internal/envoy/listener_test.go
Uses the Envoy Connection Manager request_timeout setting.
Fixes #1073.
> Add client request timeout function

- docs/httpproxy.md
- internal/dag/builder.go
- internal/dag/builder_test.go
> Fix HTTPProxy include so it assumes the same namespace if not present

- cmd/contour/serve.go
- internal/contour/metrics_test.go
- internal/dag/builder_test.go
- internal/dag/cache.go
- internal/dag/cache_test.go
Updates #513
Updates #1614
Add a logger to the KubernetesCache. This is useful at the moment to
spot failures to promulgate the projectcontour.HTTPLoadbalancer objects
through Contour.
This will also be useful to log cert validation failures, see #513.
> internal/dag: add logger to KubernetesCache

- docs/httpproxy.md
- internal/dag/builder.go
- internal/dag/builder_test.go
- internal/dag/conditions.go
- internal/dag/conditions_test.go
- internal/dag/status_test.go
Fixes #1611 
Set status on HTTPProxy if multiple path conditions are specified on a Route or Include.
Invalid Route Conditions:
```
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
name: root
spec:
virtualhost:
fqdn: kind.local
routes:
- services:
- name: app
port: 80
conditions:
- prefix: /v1
- prefix: /api
```
Invalid Include Conditions:
```
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
name: root
spec:
virtualhost:
fqdn: kind.local
includes:
- name: blogsite
namespace: teama
conditions:
- prefix: /v1
- prefix: /api
routes:
- services:
- name: app
port: 80
```
> internal/dag: Set status on HTTPProxy if multiple path conditions are specified

- docs/README.md
- docs/httpproxy.md
- internal/dag/builder.go
- internal/dag/conditions.go
- internal/dag/conditions_test.go
- internal/dag/status_test.go
Fixes #1559 by looking for any route that has duplicate header keys and marking them as invalid if found. The logic this includes is to only mark duplicate headers with the "exact" match type. I could see folks setting up multiple "notexact" or "notcontains" headers which should be logical match types.
> internal/dag: Look for duplicate header conditions and mark Proxy as invalid

- internal/e2e/rds_test.go
> Remove unused test function 'clustertimeout'.

- cmd/contour/contour.go
> Remove Heptio branding from the CLI help.

- cmd/contour/bootstrap.go
- internal/envoy/config.go
Add bootstrap subcommand support emissing the bootstrap JSON to
standard output by specifying the output file as `-`. The required
invocation to use this then becomes:
```
$ contour bootstrap -- -
```
> Add an option to emit bootstrap config to stdout.

- internal/e2e/rds_test.go
- internal/featuretests/envoy.go
- internal/featuretests/retrypolicy_test.go
Updates #1506
This is a followup to #1661. Move and consolidate the feature tests for
RetryPolicy acorss Ingress, IngressRoute and HTTPProxy.
> internal/featuretest: add RetryPolicy tests

- docs/httpproxy.md
- internal/dag/builder.go
- internal/dag/builder_test.go
- internal/dag/conditions.go
- internal/dag/conditions_test.go
Fixes #1597.
Also clarify the documentation language around prefix condtions
to make the requirements clear.
> Change prefix condition merge logic to not use path.Join()

- docs/ingressroute-to-httpproxy.md
`minimumProtocolVersion` is of type string. This prevents an unmarshalling error, potentially leading to an endless loop in Contour.
Signed-off-by: Michael Gasch <mgasch@vmware.com>
> Fix minimumProtocolVersion in migration doc

- README.md
- site/README-JEKYLL.md
- site/_config.yml
- site/_includes/site-header.html
- site/getting-started.md
- site/index.html
Updates #1619
Migrate the getting started section of the README to
projectcontour.io/getting-started.
> site: move getting-started documentation to website

- site/_config.yml
- site/getting-started.md
When using the Jekyll `site.url` variable, Jekyll doesn't know which
scheme to use, so we have to explicitly add it to the config. In
this case, we need to ensure the `https` scheme is present in the
`kubectl` examples so that `kubectl` can detect that the argument
is a URL.
> Fix default getting started URLs.

- examples/grafana/01-namespace.yaml
- examples/grafana/02-grafana-configmap.yaml
- examples/grafana/03-grafana-deployment.yaml
- examples/grafana/03-grafana-service.yaml
- examples/prometheus/01-namespace.yaml
- examples/prometheus/02-prometheus-alertmanager-configmap.yaml
- examples/prometheus/02-prometheus-alertrules-configmap.yaml
- examples/prometheus/02-prometheus-configmap.yaml
- examples/prometheus/03-prometheus-alertmanager-deployment.yaml
- examples/prometheus/03-prometheus-deployment.yaml
- examples/prometheus/03-prometheus-node-exporter.yaml
- site/_resources/prometheus.md
Fix prometheus / grafana examples for apps/v1 api groups as well as rename sample namespace of `contour-monitoring` to `projectcontour-monitoring`. 
> examples: Fix prometheus / grafana examples for apps/v1 api groups

- README.md
- site/_agendas/2019-06-18.md
- site/_agendas/2019-08-27.md
- site/_agendas/2019-09-24.md
- site/_agendas/2019-10-15.md
- site/_config.yml
- site/community.md
This adds links for the community channels and meetings to the README and site.
I updated the single HackMD with all the previous notes, so we can remove those.
> Add more community info to README and site

- .github/ISSUE_TEMPLATE/feature-enhancement-request.md
Remove the environment second from the feature request issue template,
it is redundant.
Also, try to guide the author towards describing the problem they have
not the specific feature they want us to add.
> .github: remove environment section from feature request template

- design/tls-backend-verification.md
- site/_guides/cert-manager.md
- site/_guides/deploy-aws-nlb.md
- site/_guides/grpc-tls-howto.md
- site/_resources/release-process.md
- site/_resources/troubleshooting.md
- site/getting-started.md
The Jekyll Markdown processor requires a newline before a block-quote.
If the newline isn't present, it renders it as quotes, but continuous
in the current paragraph.
Update shell command examples in the guides to consistently use `%`
as the shell prompt character.
> doc: improve shell command formatting in the guides

- internal/dag/cache_test.go
- internal/dag/secret.go
- internal/dag/secret_test.go
During certificate validation, walk the PEM and validate each
appropriate block.
closes #1702
> internal/dag: validate each pem block

- .dockerignore
- Dockerfile
Also, add /site to .dockerignore.
> Dockerfile: update to Go 1.13.3

- site/_docs_1_0/httpproxy.md
Fixes #1415 by adding docs for upstream validation
> Document upstream validation on a service

- site/_docs_1_0/httpproxy.md
Fixes #1645 by updating docs to show how secrets can be delegated to all namespaces.
> docs: Update HTTPProxy docs for TLS Cert Delegation to all namespaces

- internal/envoy/bootstrap.go
- internal/envoy/bootstrap_test.go
Fixes #1744.
Note that this only adds this to the xDS setup in `contour bootstrap`. No other upstreams will be affected, although it sees like it's worth investigating.
> Add TCP Keepalives for Envoy->Contour xDS comms

- cmd/contour/serve.go
- internal/contour/handler.go
Fixes #1425
Fixes #1385
Updates #499
This PR threads the leader elected signal throught to
contour.EventHandler allowing it to skip writing status back to the API
unless it is currently the leader.
This should fixes #1425 by removing the condition where several Contours
would fight to update status. This updates #499 by continuing to reduce
the number of updates that Contour generates, thereby processes.
This PR does create a condition where during startup no Contour may be
the leader and the xDS tables reach steady state before anyone is
elected. This would mean the status of an object would be stale until
the next update from the API server after leadership was established.
To address this a mechanism to force a rebuild of the dag is added to
the EventHandler and wired to election …
> internal/contour: only write status updates if we're the leader

- Makefile
- site/README-JEKYLL.md
Add a Dockerfile and make target that can be used for hacking on
the Contour website. This removes the need to deal with installing
Ruby and Jekyll locally.
> Add site development Docker image.

- site/README-JEKYLL.md
Update the Jekyll instructions to emphasise using the local docker
build. Keep the local install instructions for people who like to
do it by hand.
> doc: update the website development README

- internal/grpc/server.go
> Backport gRPC keepalives to 0.15.3

- site/_docs_1_0/httpproxy.md
- site/_docs_1_0/ingressroute.md
Add automatic line numbering to the HTTPProxy and IngressRoute
reference documention. This makes is easier for the reader to
follow the description of the YAML fields.
See also https://jekyllrb.com/docs/liquid/tags/#line-numbers
> doc: add line numbers to CRD references

- cmd/contour/servecontext.go
Fixes #1744 properly this time.
> Add keepalive policy to gRPC

- internal/grpc/server.go
> Backport gRPC keepalive policy change.

- examples/grafana/02-grafana-configmap.yaml
- internal/contour/handler.go
- internal/contour/metrics.go
- internal/contour/metrics_test.go
- internal/metrics/metrics.go
- internal/metrics/metrics_test.go
Fixes #1709 by adding `HTTPPRoxy` metrics to Contour's prometheus endpoint as well as updating the dashboard to match. 
> Update metrics for HTTPProxy as well as dashboard to match

- internal/contour/metrics.go
> internal/contour: Remove unused rootMetric var from internal/contour/metrics.go

- internal/contour/cluster_test.go
- internal/contour/visitor_test.go
- internal/e2e/cds_test.go
- internal/envoy/cluster.go
- internal/envoy/cluster_test.go
- internal/featuretests/envoy.go
Many tests need to specify default fields for envoy `Cluster` structs
so that struct equality tests can succeed. Specifying these defaults
in many places is fragile and tends to make it harder to see the
field values that actually matter to the tests.  Consolidating the
defaults into a handful of helpers reduces the overally clutter.
We still need a couple of duplicates of the helper so that we can
avoid package dependency cycles.
This updates #1375.
> tests: consolidate envoy Cluster defaults

- site/_includes/site-header.html
Use {% link consistently throughout the top navigation. This will
prevent the site from building if we remove/rename one of those pages
and has the added benefit that {% link generates the correct link rather
than bouncing through a 301 redirect to append a / to the url.
Lastly, remove the unused class tags on the li element.
> site: use {% link in top nav

- site/index.html
Improve the "download now" CTA link to point to the latest release,
rather than the /releases landing page.
Because Jekyll cannot use templating variables in front matter move the
second call to action description in line in the html. For consistency
move the first call to action in line and use the {% link helper to
ensure it always points to a valid page.
> site: automatically link to the latest release.

- site/_docs_1_0/annotations.md
Move the heptio annotation references to the end of the list so
that the reader doesn't have to work through a lot of clutter
of deprecated annotations.
> docs: condense heptio annotation documentation

- .travis.yml
Removed needed line go-import from travis-ci configuration file.
> Cleanup travis.yml

- site/README.md
Add a short README to direct users to the master branch for the
canonical source of the site.
> site: add README to direct users to the master branch

- cmd/contour/serve.go
Fix a regression where the Endpoints informer was getting the wrong
event handler.
> contour/serve: fix Endpoints event handling

- internal/dag/cache_test.go
- internal/dag/secret.go
- internal/dag/secret_test.go
It is valid for files to intermingle PEM and non-PEM data. The Go
`pem.Decode` API supports this, but doesn't emit any errors that
would let us distinguish between broken PEM and missing PEM. So,
verify that there is a remaining PEM header before we try to decode
it. That way, we know that any decoding failure is a actual error.
This fixes #1809.
> internal/dag: accept non-PEM data in PEM files

- internal/dag/builder.go
- internal/dag/builder_test.go
- internal/dag/status_test.go
If a `TCPProxy` object doesn't have any `Services` and does not
`Include` a delegate, then it's an empty no-op. Reject it with a
status message in this case.
This fixes #1776.
> internal/dag: reject a TCPProxy without services or includes

- Makefile
- hack/generate-metrics-doc.go
- internal/metrics/metrics.go
- site/_config.yml
- site/_guides/prometheus.md
- site/_includes/metrics.html
- site/_metrics/contour_cachehandler_onupdate_duration_seconds.md
- site/_metrics/contour_dagrebuild_timestamp.md
- site/_metrics/contour_httpproxy_invalid_total.md
- site/_metrics/contour_httpproxy_orphaned_total.md
- site/_metrics/contour_httpproxy_root_total.md
- site/_metrics/contour_httpproxy_total.md
- site/_metrics/contour_httpproxy_valid_total.md
- site/_metrics/contour_ingressroute_invalid_total.md
- site/_metrics/contour_ingressroute_orphaned_total.md
- site/_metrics/contour_ingressroute_root_total.md
- site/_metrics/contour_ingressroute_total.md
- site/_metrics/contour_ingressroute_valid_total.md
Move the metrics documentation from the "resources" section to the
"guides" section. Add build machinery to generate metrics reference
documentation from the Contour sources.
This updates #1750.
> docs: update metrics documentation

- Makefile
- site/_posts/2019-09-17-projectcontour.md
- site/_posts/2019-09-27-from-ingressroute-to-httpproxy.md
- site/_posts/2019-10-25-contour-v100rc2.md
Add site to misspell target and address issues.
> site: add site to misspell target

- apis/projectcontour/v1/tlscertificatedelegation.go
- examples/contour/01-crds.yaml
- examples/render/contour.yaml
Fixes #1739 by adding a shortname `tlscerts` to the TLSCertificateDelegation CRD.
> examples: Add shortname (tlscerts) to TLSCertificateDelegation

- site/_scss/site/objects/_deprecated.scss
Style the deprecation class as a warning (yellow) rather than an
error (red). The red is a bit too alarming.
> site: style deprecation blocks as warnings

- site/_resources/upgrading.md
Update the upgrade guide for Contour 1.0. Remove all the release
candidate information and roll it into a single section that describes
changes from 0.15.3 to 1.0.0.
This fixes #1604.
> docs: update upgrade guide for Contour 1.0

- site/_docs_1_0/ingressroute.md
- site/_guides/deploy-aws-nlb.md
- site/_guides/deploy-options.md
- site/_guides/grpc-tls-howto.md
- site/_guides/proxy-proto.md
- site/_guides/structured-logs.md
- site/_resources/support.md
- site/_resources/upgrading.md
Fixes #1619
For 1.0 the plan of record is to keep the examples on GitHub. This is
due to the difficulty in doing directory index style static resources
from projectcontour.io.
To support this weave the name of the current github release through the
website.
Note that at the present, in the rc.2 timeframe, this will break a lot
of links so this PR is targeted for 1.0 (or shortly after) which will
bring the guides, resources, and release documentation in line with the
latest released tag on GitHub.
> site: point to latest github release tag where possible

- site/_redirects
Update the quickstart redirect to point to the rendered version of
/examples/contour on release-1.0
> site: update quickstart redirect for release-1.0

- examples/contour/02-job-certgen.yaml
- examples/render/contour.yaml
This makes it easier to deploy examples/render/contour.yaml to a different namespace, via kustomization.yaml for example.
Without this change contour certgen will try to create a secret in the namespace projectcontour, which will not be accessable(, iff deoployed to different namespace).
The contour bootstrap initcontainer also has this namespace env, there should be no reason for certgen to not have it. :)
> Add namespace env var to certgen job

- cmd/contour/contour.go
> cmd/contour: fix lds subcommand spelling

- apis/projectcontour/v1/httpproxy.go
- site/_docs_1_0/httpproxy.md
Added GODOC strings for httpproxy TimeoutPolicy and updated site documentation to clarify valid input formats with reference to ParseDuration.
Fixes: #1822
> TimeoutPolicy GODOC strings and documentation updates

- internal/featuretests/featuretests.go
We need to ensure that the dag.KubernetesCache logger is initialized
otherwise the tests will crash if anything in the cache ever logs.
> internal/featuretests: initialize cache logger

- internal/dag/annotations.go
- internal/dag/annotations_test.go
- internal/dag/cache.go
When Contour makes use of annotations, it just checks the object
kind where the annotation ought to be. If a user has accidentally
placed the annotation on the wrong kind of object, there is no
indication that something is wrong.
This change adds some initial validation that annotations are applied
to the correct kind of object and defends against unknown annotations
in the Contour annotation namespace. If we detect a problem, we
just log a warning, but eventually we should place an indicator in
the object status so that the user has better visibility.
This fixes #1825.
> internal/dag: check annotation applicability

- .gitignore
- Makefile
- site/_config.yml
Fixes: #1852 
Added --path option to bunder install commands for site-devel and site-check make targets and added path to .gitignore.
First time running make site-devel or make site-check will install gems to site/bundler/cache. Each subsequent run will use the local cache instead of downloading and installing gems. Changes to the Gemfile and Gemfile.lock will install new / updated gem versions to the cache.
This approach also means that system gems will not be used, only those in the cache location and can provide more consistent results across local testing.
Bundler cache path has been added to .gitignore and Jekyll excludes
Bundler command options: https://bundler.io/v2.0/bundle_install.html
Jekyll excludes reference: https://jekyllrb.com/docs/troubleshooting/#configuration-problems …
> Enable bundler caching to decrease local site testing time

- Makefile
Fixes: #1887
Added `-rm` option to the `docker run` command for site-devel and site-check make targets. This will cause docker to automatically remove containers use for these processes when terminated. Currently they are not removed and the number of stopped containers will build up on the docker host unless manually removed.
Reference: [Clean up (--rm)](https://docs.docker.com/engine/reference/run/#clean-up---rm)
> Add --rm option to docker run commands for site-devel and site-check

- site/_resources/envoy.md
Updates #1351
Update Envoy support matrix to mention the abortive Envoy 1.12.0 and
1.12.1 replacement.
> site: update Envoy support matrix

- internal/envoy/route.go
- internal/envoy/route_test.go
Updates #1351
internal/envoy offered two ways to construct a regex route matcher. The
first was from a *dag.Route via RouteMatch, the second was directly from
a string passed to RouteRegex. The latter was used by internal/e2e to
construct test fixtures, however the former didn't use RouteRegex, it
duplicated the RouteRegex logic. This makes refactoring this code to use
SafeRegex more problematic.
This PR cleans up RouteMatch to use RouteRegex directly. This isn't as
clean as I would like because of the way gRPC union types do no expose
an interface for the union value, this means we cannot pass from
RouteRegex or RoutePrefix a PathSpecifier value as the interface those
types implement is not exported -- thanks protoc, you're a pal.
Also, add a few tests for RouteRegex matching. These will …
> internal/envoy: use RouteRegex in RouteMatch

- site/_scss/site/settings/_variables.scss
Fixes: #1892
Corrected colour setting for $header-foreground-selected
Changed $header-foreground from #000 to $black for consistency
Signed-off-by: Brett Johnson brett@sdbrett.com
> Resolve header foreground selected colour

- internal/envoy/route.go
- internal/envoy/route_test.go
Updates #1351
nb. there appear to be no internal/contour, internal/e2e, or
internal/featuretest tests for header contains matching. I've raised
#1880 to track this.
> internal/envoy: switch HeaderMatch to SafeRegex

- internal/contour/metrics_test.go
- internal/dag/builder.go
- internal/dag/status_test.go
Fixes #1904
This change causes the builder to reject HTTPProxies that include
missing documents.
> internal/dag: reject HTTPProxy with missing include

- internal/dag/builder.go
- internal/dag/builder_test.go
Fixes: #1924
Fixes: #1925
Processing IngressRoute did not stop to an error when validation.caSecret
referred to a non-existing secret.  As result, IngressRoute was considered
valid and upstream validation was skipped.
Stop processing IngressRoute and indicate invalid status when upstream
validation is defined but cannot be done due to error in configuration.
> Fix upstream validation error in IngressRoute

- internal/contour/route.go
- internal/envoy/regex.go
- internal/envoy/regex_test.go
- internal/envoy/route.go
- internal/envoy/route_test.go
Updates #1351
Fixes #1513
Switch path regex matching to safe regex. Refactor matcher.RegexMatcher
code to its own file and helper so it can be reused across
internal/envoy and internal/contour.
Also of note, internal/contour longestRouteFirst comparator has intimate
knowledge of RouteMatch_SafeRegex which is probably not ideal.
> internal/envoy: switch to safe regex for path match

- site/_includes/site-header.html
- site/guides.md
Fixes: #1911
Added classes to `<li>`  elements for header menu to match body class id tag in relevant page markdown file.
Added body class id tag for guides page
> Highlight selected header menu item

- internal/envoy/listener.go
- internal/envoy/listener_test.go
Updates #1351
HttpConnectionManager.IdleTimeout was deprecated in 1.11.2. Switch to
HttpConnectionManager.CommonHttpProtocolOptions.IdleTimeout.
Also, there was one case where ptypes.DurationProtocol was being used
where all the other cases uses protobuf.Duration. Make that the same as
everywhere else.
> internal/envoy: use common_http_protocol_options.idletimeout

- internal/e2e/cds_test.go
- internal/envoy/bootstrap.go
- internal/envoy/bootstrap_test.go
- internal/envoy/cluster.go
- internal/envoy/cluster_test.go
- internal/envoy/socket.go
- internal/envoy/socket_test.go
- internal/featuretests/envoy.go
Updates #1351
Envoy 1.12 has deprecated the Cluster.TLSContext field, instead the
UpstreamTLSContext must be provided via a typed config attached to a
TransportSocket.
ref: https://www.envoyproxy.io/docs/envoy/v1.12.0/api-v2/api/v2/cds.proto#envoy-api-field-cluster-tls-context
> internal/envoy: switch to Cluster.TransportSocket for upstream TLS

- site/_scss/site/settings/_variables.scss
- site/index.html
Simplified button colour declaration and changed index buttons back to one having a white background and one being an outline. Button change due to finding a variable in index.md front-mater.
Index footer background darkened with alignment to VMware branding colour standards.
> Additional accessibility fixes

- site/_guides/cert-manager.md
Updates #1836
This should hopefully complete the updating process for the cert-manager tutorial for now.
> Update ClusterIssuer api group to use correct version

- internal/featuretests/envoy.go
- internal/featuretests/tcpproxy_test.go
Updates #1945
Clean up the existing tcp proxy feature tests to assert that no
listeners are opened unexpectedly. Then add a test to assert that the
pattern of exposing a service both via tcpproxy and port 80 (permit
insecure) works
There are several bugs that have fallen out of this
- #1951 - Contour accepts a httpproxy with a missing service without
marking the httpproxy invalid.
- #1952 - httpproxy's tcpproxy plus permit insecure does not require the
service to be marked as permit insecure.
- #1954 - route should not be present on ingress_https if tcpproxy is
inuse.
Both of these should be fixed, but lets lock in the current behaviour.
> internal/featuretest: add test to assert tlspassthrough + permit insecure works

- internal/contour/listener_test.go
- internal/contour/visitor_test.go
- internal/e2e/lds_test.go
- internal/envoy/listener.go
- internal/envoy/socket.go
- internal/envoy/socket_test.go
- internal/featuretests/envoy.go
- internal/featuretests/tlsprotocolversion_test.go
Updates #1351
Envoy 1.12 has deprecated the FilterChain.TLSContext field, instead the
DownstreamTLSContext must be provided via a typed config attached to a
TransportSocket.
ref: https://www.envoyproxy.io/docs/envoy/v1.12.0/api-v2/api/v2/listener/listener.proto#envoy-api-field-listener-filterchain-tls-context
> internal/envoy: switch to FilterChain.TransportSocket for downstream TLS

- internal/dag/builder.go
- internal/dag/status_test.go
- internal/featuretests/tcpproxy_test.go
Fixes #1958
To be a valid HTTPProxy, if the tcpproxy stanza is provided, the
HTTPProxy must also feature a virtualhost.tls spec with either
passthrough: true, or a valid secretName.
> internal/dag: reject a tcpproxy httpproxy without valid tls details

- internal/dag/builder.go
- internal/dag/builder_test.go
- internal/featuretests/tcpproxy_test.go
Fixes #1954
Prior to the change the builder would generate suprious route on the
secure virtual host connected to a HTTPProxy in tcpproxy mode. This route
would not have been accessible because there is no http connection manager
attached to the filter chain for that secure virtual host however the route was
still present in RDS.
> internal/dag: do not generate ingress_https route for tcpproxy vhost

- internal/dag/status_test.go
Fixes #1951
Add a status test for a HTTPProxy with a valid tcpproxy service, valid
tls details, but a missing route service. The route service would have
been presented as a 301 upgrade on port 80, but it was not found, hence
the HTTPProxy is invalid.
> internal/dag: add status test for #1951

- README.md
Currently, users get a 404 from github :grimacing:
> Fix doc links in top-level readme

- internal/dag/builder.go
- internal/dag/builder_test.go
- internal/featuretests/tcpproxy_test.go
Fixes #1952
Clean the HTTPProxy spec.virtualhost.tls validation logic and fix the
last issue with HTTPProxy TCPProxy logic.
If a HTTPProxy is using TCP proxying then its secure port is forwarded
according to the spec.tcpproxy schema. The insecure port, port 80 is not
tcp forwarded and remains connected to a L7 http connection manager.
Because by definition a HTTPProxy using TCP proxying must supply a valid
spec.virtualhost.tls block, our 301 upgrade logic applies. Thus, after
this change, if a route on the insecure listener is not using
permitInsecure: true, it will by 301 upgraded.
> internal/dag: 301 upgrade insecure routes irrespective of tcpproxying

- internal/e2e/cds_test.go
- internal/e2e/rds_test.go
- internal/featuretests/envoy.go
- internal/featuretests/externalname_test.go
Updates #1431
Migrate tests for external name Services to featuretests.
> internal/featuretests: move externalname test to featuretests

- site/_guides/prometheus.md
- site/docs/master/annotations.md
- site/docs/master/httpproxy.md
- site/docs/master/ingressroute.md
- site/docs/v1.0.0/annotations.md
- site/docs/v1.0.0/httpproxy.md
- site/docs/v1.0.0/ingressroute.md
Add the "navigation" class to the in-page TOC elements so that it
can be used consistently with CSS selectors.
> site: add navigation class to the TOC

- cmd/contour/serve.go
- go.sum
- internal/contour/handler.go
- internal/dag/annotations_test.go
- internal/dag/cache.go
- internal/e2e/e2e.go
- internal/featuretests/featuretests.go
- internal/k8s/kind.go
- internal/k8s/status.go
- internal/k8s/status_test.go
Add a Kubernetes object status cache that can be used to assert
object status in feature tests. Status can be `Equals()` (all
fields must match) or `Like()` (only specified fields need to
match). The assertion functions return a `*Contour` to that a
fluent style can be used.
Sample usage:
```Go
c.Request().Equals(
...
).Status().Equals(
...
)
```
> internal/featuretests: add status check machinery

- internal/e2e/cds_test.go
- internal/featuretests/backendcavalidation_test.go
Updates #1436
Move upstream CA validation tests to internal/featuretests.
> internal/featuretests: move upstream ca validation tests

- examples/contour/02-job-certgen.yaml
- examples/contour/03-contour.yaml
- examples/render/contour.yaml
This commit adds `securityContext` to pods that don't need to run as
root, viz. certgen job and the contour deployment.
> manifests: Run contour & cert-gen job as non-root

- hack/site-proofing/cibuild
Missing `cd ./site` in `/hack/site-proofing/cibuild` causing travis-ci to fail on site checks.
> Fix error in site-proofing script

- site/_scss/site/objects/_section.scss
- site/_scss/site/settings/_variables.scss
Minor change to improve link colour in text based on feedback that they did not stand out enough and where easy to miss.
Added link colour for section.grey as lighter links do not have enough contrast ratio with the grey background. This is used on the home page.
> Improve link colour to help distinguish from regular text

- apis/projectcontour/v1/httpproxy.go
- examples/contour/01-crds.yaml
- examples/render/contour.yaml
Fixes #1993
Mark timeoutPolicy.request and timeoutPolicy.idle +optional (for schema
generation) and omitempty (for JSON encoding). This permits the user to
create a timeoutPolicy without having to specify both fields. We have
test coverage in internal/envoy and internal/dag for these scenarios.
> api: mark all timeoutPolicy parameters optional

- site/README.md
Fixes: #1990
Liquid link for master work when site is build but are broken if used from github repo.
Link to SITE_CONTRIBUTION.md worked through github but not on live site.
> Fixes broken link to SITE_CONTRIBUTION.md

- site/docs/master/httpproxy.md
Updates #2004
Updates #1668
The move from per service `strategy:` to per route `loadBalancerPolicy:` was never reflected in the HTTPProxy documentation. Oops.
> site: update HTTPProxy loadBalancerPolicy documentation

- site/_resources/release-process.md
Fixes #1871 by adding documentation on how to update the docs site for a new release.
> Add instructions on how to update the docs site for a new release

- site/_config.yml
- site/_data/toc-mapping.yml
- site/docs/v1.0.1/README.md
- site/docs/v1.0.1/annotations.md
- site/docs/v1.0.1/architecture.md
- site/docs/v1.0.1/configuration.md
- site/docs/v1.0.1/deploy-options.md
- site/docs/v1.0.1/github.md
- site/docs/v1.0.1/grpc-tls-howto.md
- site/docs/v1.0.1/httpproxy.md
- site/docs/v1.0.1/ingressroute.md
- site/docs/v1.0.1/start-contributing.md
- site/docs/v1.0.1/tagging.md
- site/docs/v1.0.1/troubleshooting.md
Fixes #2011
- set latest to v1.0.1
- add v1.0.1 documentation
- hand edit all v1.0.1 documentation to remove hard links to v1.0.0 docs
> site: add v1.0.1 documentation

- site/community.md
Add Project Contour Announce mailing list to the community page.
This closes #1796.
Signed-off-by: Jonas Rosland <jrosland@vmware.com>
> Add announce mailing list

- internal/envoy/bootstrap_test.go
- internal/envoy/socket.go
- internal/envoy/socket_test.go
The envoy documentation is inconsistent about the correct name of a tls
enabled transport socket.  envoyproxy/envoy#9319
This PR uses the name in more common usage inside envoy.
> internal/envoy: use correct transport socket name

- internal/dag/builder_test.go
- internal/dag/status_test.go
Fixes #1949
Issue #1949 is about ensuring that HTTPProxy objects will override IngressRoute
ones when they match on {FQDN, path} tuple. Turns out this is already the case,
this PR adds tests to assert this behaviour.
The tests have an Ingress, IngressRoute, and HTTPProxy that are identical aside from the service where the traffic is routed to, and assert that the override behaviour holds based on which service ends up chosen.
Note that routes that are not exactly the same (on FQDN, path tuple), will just be additive, no matter where they come from. This is why the cert-manager ingress-shim thing works.
> Add tests to cover override behaviour for IngressRoute and HTTPProxy

- internal/envoy/regex.go
- internal/envoy/regex_test.go
There's no obvious way to know what a reasonable regex program
size is (and that's not really what the RE2 program size number
means).  However, Envoy makes us send something here and if it's
too low, it will NACK the update and Contour will not handle that
gracefully. So, we send a large number that should be enough for
all reasonable regex cases.
This fixes #2043.
> internal/envoy: bump the max Envoy regex program size

- examples/README.md
- examples/contour/README.md
- site/_data/master-toc.yml
- site/_data/v1-0-0-toc.yml
- site/_data/v1-0-1-toc.yml
- site/docs/master/grpc-tls-howto.md
- site/docs/v1.0.0/grpc-tls-howto.md
- site/docs/v1.0.1/grpc-tls-howto.md
When the per-version documentation was changes, the documentation
for setting up TLS between Contour and Envoy wasn't linked. Add
links for all documentation versions and for the source tree
references.
This fixes #2055.
> doc: link the GRPC TLS deployment page

- internal/dag/builder.go
- internal/dag/builder_test.go
- internal/featuretests/websockets_test.go
Envoy has fixed the issue related to using websockets with weighted clusters, so this drops the exclusion which kept those clusters out of the DAG.
Fixes: https://github.com/projectcontour/contour/issues/2054
cc @stevesloka
> Remove the restriction on websockets with weighted clusters.

- internal/dag/builder.go
- internal/dag/conditions.go
- internal/dag/status.go
There are a fair number of locations that use fmt.Sprintf to
format errors for the object status writer. Simplify the call
sites by accepting a format string and formatting internally.
> interna/dag: accept format strings for status messages

- .gitattributes
We use this file to collapse generated files by default in code reviews in [Knative](https://github.com/knative/serving/blob/270c395bf985566649f3993b9d3f1c446518211d/.gitattributes#L5-L7), and it is generally useful to improve signal-to-noise ratios in changes that touch API surfaces.
Not sure if y'all want this, but I figured I'd see if there was interest :)
> Add .gitattributes to hide generated code from code reviews.

- internal/contour/handler.go
Found the EventHandler update compare logic was missing skipping `HTTPProxy` objects.
> internal/contour: Add missing HTTPProxy compare check in EventHandler updates

- internal/contour/endpointstranslator.go
- internal/contour/endpointstranslator_test.go
Just something I noticed poking around.
Signed-off-by: Matt Moore <mattmoor@vmware.com>
> Pre-size the array when dumping EndpointTranslator Contents()

- cmd/contour/certgen.go
- cmd/contour/contour.go
- cmd/contour/serve.go
If Contour failes to create a Kubernetes API clien on startup,
add context to the message to make it clear what kind of problem
happened.
For example, if you are running a local Contour and don't have a
current Kubernetes context, Contour would previously exit with the
message "invalid configuration: no configuration has been provided".
This doesn't make it clear the problem is the Kubernetes config,
not the Contour config.
> cmd/contour: improve Kubernetes client error message

- apis/projectcontour/v1/httpproxy.go
- apis/projectcontour/v1/zz_generated.deepcopy.go
- internal/featuretests/replaceprefix_test.go
Rename the HTTPProxy PathRewrite field to PathRewritePolicy to make
the Go field name the same as the YAML field name. This reduces the
likelihood of people being misled when referring to the Go structures
to write YAML specs by hand.
> apis/projectcontour: rename PathRewrite field to PathRewritePolicy

- examples/contour/02-job-certgen.yaml
- examples/render/contour.yaml
Fixes #2030 by implementing the following:
- Update the certgen job to use docker tag `latest`
- Add `ttlSecondsAfterFinished: 0` which if running a cluster v1.12+ and enabled feature gate will delete the cert-gen job after the job is complete
> examples: Add 'ttlSecondsFinished' to the certgen job and set the image to latest

- site/_config.yml
- site/_data/toc-mapping.yml
This fixes #2033  by changing the order of the release so the drop-down menu follows the most recent release to oldest. 
> site: Change ordering of releases so the docs menu is in proper order

- apis/projectcontour/v1/httpproxy.go
- apis/projectcontour/v1/zz_generated.deepcopy.go
- examples/contour/01-crds.yaml
- examples/render/contour.yaml
- internal/contour/route.go
- internal/contour/route_test.go
- internal/dag/builder.go
- internal/dag/builder_test.go
- internal/dag/dag.go
- internal/dag/policy.go
- internal/envoy/route.go
- internal/envoy/route_test.go
- internal/featuretests/headerpolicy_test.go
- site/docs/master/api-reference.html
- site/docs/master/httpproxy.md
This changes adds support for adding and removing request or response headers
for each service target in a Contour HTTPProxy resource.
The structure differs from the originally proposed shape in the linked issue
for two reasons:
1. A desire to support response-header manipulation.
2. A desire to support split-specific header manipulation (needed by Knative).
The resulting shape looks like:
```yaml
spec:
virtualhost:
fqdn: foo.default.mattmoor.io
routes:
- services:
- name: foo
port: 80
requestHeaders:
add:
- name: Foo
value: bar
remove:
- Baz
responseHeaders:
add:
- name: Ugh
value: tedious
remove:
- Secret-Stuff
```
Fixes: https://github.com/projectcontour/contour/issues/70
> Support per-Split header manipulation.

- apis/projectcontour/v1/httpproxy.go
- design/httpproxy-protocol-selection.md
- examples/contour/01-crds.yaml
- examples/render/contour.yaml
- internal/dag/builder.go
- internal/dag/builder_test.go
- internal/dag/dag.go
- internal/envoy/cluster.go
- internal/envoy/cluster_test.go
Fixes: #1962
Fixes: #2056
This is based on the design in: https://github.com/projectcontour/contour/pull/2072, which is also included as the base commit here.
Signed-off-by: Matt Moore <mattmoor@vmware.com>
> Implement support for specifying a service's protocol in HTTPProxy.

- Makefile
- cmd/contour/bootstrap.go
- cmd/contour/certgen.go
- cmd/contour/contour.go
- cmd/contour/serve.go
Improve CLI help text by making all the help text for flags and
subcommands begin with a capital letter and end with a period.
> cli: improve help text consistency

- apis/projectcontour/v1/httpproxy.go
- site/docs/master/api-reference.html
Always use "+optional" rather than "+kubebuilder:validation:Optional".
Although they do the same thing, the API reference documentation
generator only recognizes the former.
This fixes #2074.
> api: consistently use the +optional annotation

- examples/contour/01-contour-config.yaml
- examples/render/contour.yaml
- site/docs/master/configuration.md
- site/docs/v1.1.0/configuration.md
- configmap name defaults to `leader-elect`
- namespace defaults to `projectcontour`
Documentation for already-released versions was not updated, even if inaccurate.
> Fix documented defaults for leaderelection config

- examples/kind/kind-expose-port.yaml
Currently examples/kind/kind-expose-port.yaml is exposing port 8080 to the host. However, by default envoy is listening on hostPort 80 and 443. So, the kind-expose-port.yaml has to be changed to expose port 80 and 443 instead of 8080
> Update kind cluster example to expose port 80 and 443 instead of 8080

- internal/contour/metrics_test.go
When a test fails, the reported line number is in the subtest, and
you have to search for the tesst case name to find the test case
that had a problem. Refactor the test code into a local function
so we can preserve the attributed of table-driven tests but aldo
get accurate reporting of line numbers for failures.
> internal/contour: refactor metrics test for accurate line numbers

- site/_resources/upgrading.md
otherwise, users might see errors because of the old CRDs.
> docs: suggested to delete CRDs as well when upgrading with the easy way

- Makefile
Fixes #2125 by exposing the livereload port from the site-devel task. 
> Enable livereload for site-devel task

- internal/dag/annotations.go
The "kubernetes.io/ingress.class" annotation is valid for all
ingress-like document kinds.
This fixes #2119.
> internal/dag: mark ingress.class annotation valid for HTTPProxies

- Makefile
- apis/projectcontour/v1/httpproxy.go
- examples/contour/01-crds.yaml
- examples/render/contour.yaml
- site/docs/master/api-reference.html
- site/docs/v1.1.0/api-reference.html
Updates #2130 by adding the `site/docs` repo to the check for spelling errors. Additionally, it fixes some of the errors that resulted from this change.
One issue in testing this PR is that the spell-check tool doesn't always find errors. There are still errors that exist that the tool isn't finding, but this makes the check a little better.
> Makefile: Update spell check

- internal/dag/builder.go
- internal/dag/conditions.go
- internal/dag/conditions_test.go
- internal/dag/status_test.go
Have the caller set the HTTPPtoxy status based on the error propagted
from pathConditionsValid(). This makes it clearer where status is getting
set during procy processing.
> internal/dag: have caller set status for invalid path conditions

- design/tls-client-verification.md
Implementation proposal for #1090 
See also PR https://github.com/heptio/contour/pull/1226
> Client certificate validation (mTLS) design proposal

- go.mod
- go.sum
Updates #2132
Upgrade go-control-plane to give us access to the replacement types for
envoy 1.13 deprecated features.
> go.mod: upgrade go-control-plane to v0.9.2

- go.mod
- go.sum
Upgrade google/go-cmp to version 0.4.0. This release contains fixes for
unsafe pointer conversions which would trigger a test failure under the
race detector for Go 1.14 and later. See google/go-cmp#167
> go.mod: upgrade google/go-cmp

- apis/projectcontour/v1/httpproxy.go
- examples/contour/01-crds.yaml
- examples/render/contour.yaml
- site/docs/master/api-reference.html
- site/docs/v1.1.0/api-reference.html
Fixes #2152 by adding an enum validation to limit the values for the service.protocol field. 
```
Release Note: Users will need to reapply the crd spec to get the validation
```
> Add kubebuilder enum validation to limit the values for service.protocol

- internal/dag/builder.go
- internal/dag/builder_test.go
Fixes #2153 by allowing requestHeaderPolicy to set host header at the HTTProxy.Routes.Service level. Also, add tests to confirm that it's not possible to set the Host header for responseHeadersPolicy.
> internal/dag: Allow requestHeadersPolicy to set host header at the

- internal/contour/route_test.go
- internal/envoy/route.go
- internal/envoy/route_test.go
- internal/featuretests/envoy.go
Updates #2132
Envoy 1.13 deprecated RouteMirrorPolicy singular and replaced it with
RouteMirrorPolicies plural. Make this change throughout and address the
missing test of request mirroring for enovy.RouteRoute.
> internal/envoy: switch from route.RouteMirrorPolicy to RouteMirrorPolicies

- internal/envoy/auth.go
- internal/envoy/auth_test.go
- internal/envoy/bootstrap.go
- internal/envoy/bootstrap_test.go
Updates #2132
Envoy 1.13.2 deprecated the auth.CertificateValidationContext.verify_subject_alt_name
field, replacing it with match_subject_alt_names which takes an array of
string matchers.
> internal/envoy: switch to match_subject_alt_names for CA validation

- examples/contour/03-envoy.yaml
- examples/render/contour.yaml
- site/_resources/envoy.md
Fixes #2132
Also update the Envoy compatability matrix to include Contour 1.2.0 an
Envoy 1.13.0
> examples: update Envoy to 1.13.0

- .github/workflows/stale.yaml
Emable the Github stale action to label (and eventually close)
PRs that are inactive. This makes it easier to see which PRs
need to be followed up on.
This fixes #2174.
> ci: enable Github stale action

- internal/certgen/certgen.go
Fixes #2150 by ensuring that the `contour certgen` Job will succeed if the secrets already exist.
> Ensure certgen handles already-existing secrets correctly

- .travis.yml
- Makefile
Add a `check-coverage` make target that emits aggregated coverage across
all the project packages. Enable coverage data upload to codecov.io.
This fixes #2176.
> ci: enable codecov integration

- apis/contour/v1beta1/ingressroute.go
- apis/projectcontour/v1/httpproxy.go
- examples/contour/01-crds.yaml
- examples/render/contour.yaml
- internal/dag/builder.go
- internal/dag/policy.go
- site/docs/master/api-reference.html
This commit replaces the unsigned integers in the HTTPProxy and IngressRoute CRDs
with signed integers. Unsigned integers are discouraged due to API compatibility
issues. Validation rules have been added to the fields to ensure that the value
provided is always positive.
Fixes #2123
Signed-off-by: Alex Price <aprice@atlassian.com>
> apis: replace unsigned integers in CRD fields with signed integers, add validation

- .travis.yml
- Makefile
- hack/travis/check-uncommitted-codegen.sh
- hack/travis/travis-check-files-changed.sh
Break the Travis CI integration checks into separate jobs that run in
parallel. This makes is easier to see an overview of what categories
of checks we are running, and makes it easier to see any failures in
the logs.
This fixes #2181
> Break integration tests into discrete stages.

- cmd/contour/serve.go
- internal/contour/handler.go
- internal/httpsvc/http.go
When we starts and stop a subsystem, mention the subsystem that we are
starting or stopping to log better context around what Contour is doing.
> Improve server logging.

- internal/dag/cache.go
- internal/dag/cache_test.go
It can take a while to realize very simple errors like mismatched
ingress classes. Add a debug log that can be enabled by developers
to log this issue.
> internal/dag: improve ingress class matching logs

- apis/projectcontour/v1/httpproxy.go
This PR fixes `HTTPProxy` godoc references to use "SNI" instead of "CNI".
Signed-off-by: Daneyon Hansen daneyonhansen@gmail.com
> projectcontour/v1: Fixes CNI typos

- CONTRIBUTING.md
Previously, the DCO CI job would fail when creating a PR following `CONTRIBUTING.md`. This is due to the DCO email address being improperly formatted. This PR updates `CONTRIBUTING.md` to incase the DCO sign-off email in `<>`.
> docs: Fixes sign-off email reference

- internal/featuretests/featuretests.go
- internal/featuretests/ingressclass_test.go
- internal/k8s/status.go
Add a test to ensure that Contour will ignore objects when they change
their ingress class to an ingress class it is not configured to use.
This updates #2199.
> internal/featuretests: test ingress class updates

- site/_resources/envoy.md
- site/_resources/kubernetes.md
Fixes #2233
html elements cannot surround markdown tables or jekyll will treat the
table as text.
> site: fix html table rendering error

- internal/contour/handler.go
- internal/e2e/e2e.go
- internal/featuretests/featuretests.go
- internal/grpc/server_test.go
Updates #2235
The *metrics.Metrics is already promoted via the embedded *CacheHandler field.
> internal/contour: remove unused EventHandler.Metrics field

- internal/envoy/regex.go
Updates #2240
Raise the SafeRegex size limit from 1,000 to 1048576. There is no evidence
that this number is sufficient for all possible regex patterns, thus the
limit represents the "no limit" limit because it is currently not
possible for envoy to reject a regex entry in a way that Contour can
trace back to the original input.
> internal/envoy: raise SafeRegex limit to 1048576

- cmd/contour/serve.go
- internal/contour/handler.go
- internal/e2e/e2e.go
- internal/featuretests/featuretests.go
- internal/grpc/server_test.go
- internal/k8s/converter.go
- internal/k8s/converter_test.go
Updates #2235
Contour 1.2.x is moving to the k8s dynamic client for deserialising
Contour's CRD objects. To make #2244 easier to backport to Contour's 1.1
branch, which does not support the dynamic client, break this logic out
into its own ResourceEventHandler wrapper which returns the current
contour.EventHandler logic to Contour 1.1 spec.
As a side effect, we only need to use the DynamicClientHandler wrapper
in cases where we know the resources are coming from the DynamicClient.
Specifically we don't need to use this path for Core.v1 and Extension
objects. Also, we don't need to use the DynamicClientHandler wrapper in
e2e/feature tests as there is no k8s API server connected to those tests
-- we construct the final k8s object as a fixture and call …
> internal/k8s: move dynamic client translation to k8s package

- cmd/contour/serve.go
- internal/contour/metrics.go
- internal/metrics/metrics.go
- site/_metrics/contour_eventhandler_operation_total.md
Fixes #2235 
Introduce a new handler in the EventHandler chain which emits prometheus
metrics for the various API operations and kinds observed from informers
which sink to the EventHandler chain.
Inserting the EventRecorded between the DynamicClientHandler and the
EventHandler will make this PR easier to backport to Contour versions
which don't use the dynamic client.
> internal/contour: record EventHandler operation metrics

- examples/contour/03-contour.yaml
- examples/contour/03-envoy.yaml
- examples/render/contour.yaml
Fixes #2268 by updating the manifests tags to reference the v1.2.0 release tag.
> Update manifests for v1.2.0 release

- .golangci.yml
apis/generated was deleted in 1.2, we don't need to exclude it any
more.
> golangci.yml: remove exclude for deleted path

- cmd/contour/serve.go
- internal/k8s/syncer.go
Turns out the `informers` array was being added only to keep
track of whether the informer had synced yet. This PR adds
a new InformerSyncList type which stores the functions from each informer
and calls them for that first-sync check.
> cmd/contour: change registerEventHandler to new InformerSyncList type

- internal/contour/handler.go
Updates #2275
The holdoff logic is subtle, and under tested. To address both of these
issues I'm going to make the fix for #2275 in several stages so we have
a chance to git bisect.
This first change removes the explicit force code path when
holdoffmaxdelay is exceeded. The logic remains the same, if
holdoffmaxdelay is exceeded a delayed update will occur, however after
this change rather than their being a specific code path for the forced
update we set the timer delay to zero, which will make the <-pending
channel ready shortly afterwards.
Strictly speaking a stream of <-op updates can trump a <-pending which
can add further delay to rebuilding the dag but in practice this is
unlikely to occur indefinitely;
1. When more than one channel is selectable, the runtime chooses between
them …
> internal/contour: remove holdoffmaxdelay forced update

- internal/contour/handler.go
Updates #2275
Continue to chip away at the holdoff logic's hooks into the
EventHandler's state. This change renames e.last to a local
lastDAGUpdate variable and cleans up some incorrect comments.
> internal/contour: further clean up holdoff timer logic

- apis/projectcontour/v1/httpproxy.go
- apis/projectcontour/v1/zz_generated.deepcopy.go
- examples/contour/01-crds.yaml
- examples/render/contour.yaml
- internal/dag/builder.go
- internal/dag/builder_test.go
- internal/dag/status_test.go
- site/docs/master/api-reference.html
Fixes #2218 
The TCPProxy `include` example was wrong. According to our spec, it should be plural (But I think this is an oversight from conversion from IngressRoute). 
> site: Fix tcpproxy include to be singular

- Makefile
Fixes #2291 
This PR adds a `make checkall` task which runs the tests, install, linting and generate tasks. It's using the aliases such that as these commands grow, the meaning behind the commands doesn't have to be translated. 
Additionally, it renames the `check-` tasks under the `lint` task to be prefixed with `lint-*` to keep consistency. 
> makefile: Add a 'make checkall' target

- cmd/contour/serve.go
- cmd/contour/servecontext.go
- examples/contour/03-contour.yaml
- examples/render/contour.yaml
- internal/dag/annotations_test.go
- internal/dag/cache.go
- internal/e2e/rds_test.go
- internal/k8s/kind.go
Fixes #2302
Contour no longer supports a version of k8s that provides the
extensions/ingress.v1beta1 type. Remove support in cmd/contour for
automagically translating extensions/ingress to networking/ingress. From
k8s 1.13 onwards this is handled via the API server and as of Contour
1.2.0 there is no support for extensions/ingress in any form.
> cmd/contour: remove --use-extensions-v1beta1-ingress

- cmd/contour/serve.go
Updates #403
Update logger context after offline feedback.
> cmd/contour: update leadership election logger context

- site/docs/master/annotations.md
- site/docs/v1.2.0/annotations.md
Fixes #1835 by removing references to heptio annotations. Also, it moves references to `IngressRoute` to use `HTTPProxy` instead.
> site: Remove heptio annotations from documentation

- examples/grafana/02-grafana-configmap.yaml
Fixes #2271
The new dashboards are visible at https://grafana.youngnick.dev/d/khVnG8iiz/envoy-metrics?refresh=10s&orgId=1 (contour/contour)
Add memory info to Envoy dashboard
Add listener status to Envoy dashboard
Split Envoy dashboard into Envoy details and service details
Add "Envoy Pod" dropdown to allow for choosing a subset of Envoy pods for graphs
Fix bug with APIserver and Envoy dashes where `id` was included, which stopped them being loaded into Grafana.
> Update Envoy dashboard with extra metrics

- internal/dag/builder.go
- internal/dag/builder_test.go
- internal/dag/cache.go
- internal/dag/cache_test.go
- internal/dag/secret.go
- internal/dag/secret_test.go
- internal/envoy/cluster.go
- internal/envoy/cluster_test.go
- internal/featuretests/backendcavalidation_test.go
Cleaning up locally defined strings when referencing to secrets with
CA certificates and replaced them with a single constant.
> internal/dag,envoy: use constant for ca.crt

- site/_data/refdocs/members.tpl
- site/_data/refdocs/type.tpl
- site/docs/master/api-reference.html
- site/docs/master/ingressroute.md
- site/docs/v1.0.0/ingressroute.md
- site/docs/v1.0.1/annotations.md
- site/docs/v1.0.1/ingressroute.md
- site/docs/v1.1.0/annotations.md
- site/docs/v1.1.0/api-reference.html
- site/docs/v1.1.0/ingressroute.md
- site/docs/v1.2.0/api-reference.html
- site/docs/v1.2.0/ingressroute.md
- site/docs/v1.2.1/api-reference.html
- site/docs/v1.2.1/ingressroute.md
Remove extraneous slashes from `<br>` tags so that Jekyll
doesn't end up quoting them.
> site: fix API docs rendering

- internal/dag/builder.go
- internal/dag/builder_test.go
- internal/dag/status_test.go
Fixes #2309
Reject any HTTPProxy that does not have at least one service entry per
route. This logic is enforced in the 1.3.0 CRD validations.
This PR does not include support for IngressRoute.
> internal/dag: reject HTTPProxy's that lack at least one service per route

- hack/golangci-lint
Updates #2340 
The recently release 1.24.0 seems to OOM in CI.
> hack: pin golangci-lint version to v1.23.8

- cmd/contour/certgen.go
- cmd/contour/clients.go
- cmd/contour/contour.go
- cmd/contour/serve.go
- internal/k8s/clients.go
Updates #403
Before I can add ingress status support to cmd/contour I need to clean
up the serve method. This change unifies the creation of the various
clients to a single method and improves the naming of the various return
values -- they are infomer _factories_ not informers.
> cmd/contour: unify client creation

- internal/k8s/converter.go
- internal/k8s/converter_test.go
Updates #403
Currently in cmd/contour.doServe we have three ResourceEventHandler
types defined;
- eventHandler, which is the internal/contour.EventHandler connected to
the dag
- eventRecorder, which wraps eventHandler to add metrics
- dynamicHandler, which wraps eventRecorder to handle dynamic objects.
These three objects are all in scope and used to register with various
informers in a fragile pattern; eventHandler needs to be in scope to
be registed with the group later in the function, eventRecorder is
registered with the k8s core types, and dynamicHandler with the CRD
types. This is all rather fragile.
This PR prepares to make the DynamicHandler the only entry point for all
k8s types by refactoring the DynamicHandler to make accepting non
dynamic types less unexpected.
Signed-off-by: …
> internal/k8s: simplify DynamicConverter

- apis/projectcontour/v1/httpproxy.go
- examples/contour/01-crds.yaml
- examples/render/contour.yaml
- internal/envoy/cluster_test.go
- site/docs/master/api-reference.html
Document the LoadBalancerPolicy strategy names in the API reference.
> docs: document the allowed LoadBalancer strategies

- cmd/contour/serve.go
We already trap SIGTERM, also grab SIGINT.
> cmd/contour: trap and shutdown on ^C

- README.md
- site/community.md
This PR will fix the description of the community meeting times.
Reminder for myself to change the Australian time on April 5th for daylight savings.
> Fix community meeting times

- cmd/contour/leadership.go
- cmd/contour/serve.go
Updates #403
Ingress status updates depend on leadership election. This PR moves
leadership setup outside doServe and simplifies the interaction with
EventHandler.IsLeader.
> cmd/contour: simplify leadership election setup

- Makefile
Fixes a CI failure in SECURITY.md
> Add "mitre" to the skip list for lint-misspell

- cmd/contour/ingressstatus.go
- cmd/contour/serve.go
- internal/k8s/ingressstatus.go
Updates #403
This PR adds a worker to doServe's group which writes back load balancer
status to ingress.v1beta1 objects.
In this PR, the population of the isw.lbStatus channel is not present
but has been manually verified with the following code:
g.Add(func(stop <-chan struct{}) error {
tick := time.Tick(2 * time.Second)
for {
select {
case <-tick:
isw.lbStatus <- v1.LoadBalancerStatus{
Ingress: []v1.LoadBalancerIngress{{
Hostname: "gke.davecheney.com",
}},
}
case <-stop:
return nil
}
}
})
Future PRs will add workers to populate the channel.
> cmd/contour: add IngressStatusWriter

- go.mod
- go.sum
- hack/make-release-tag.sh
- hack/prepare-release.go
- site/_resources/release-process.md
- tools.go
Add some basic release tooling scripts to make releasing more consistent
and reliable.
`prepare-release.go` cuts a new copy of the versioned documentation and
updates the Jekyll metadata YAML in various places.
`make-release-tag.sh` updates the Docker image version and creates the
release tag, pupulating the tag message with the shortlog of changes
since the previous release.
This fixes #2351.
> Add release tooling scripts.

- site/_guides/cert-manager.md
Fixes #228
site: fix secret name in cert-manager documentation
Signed-off-by: vukg <vuk.gojnic@gmail.com>
> site\_guides\cert-manager.md

- internal/contour/listener.go
- internal/contour/listener_test.go
- internal/dag/builder.go
- internal/dag/builder_test.go
- internal/dag/dag.go
- internal/dag/dag_test.go
- internal/e2e/lds_test.go
- internal/envoy/auth.go
- internal/envoy/auth_test.go
- internal/envoy/cluster.go
- internal/envoy/cluster_test.go
- internal/envoy/listener.go
- internal/envoy/listener_test.go
- internal/envoy/socket_test.go
- internal/featuretests/envoy.go
- internal/featuretests/tlsprotocolversion_test.go
internal: Initial support for external client cert validation
Adds initial support for authentication of external clients (downstream) by
validating their client certificates against trusted CA certificate.
The feature is not yet exposed in the API.
> internal: Initial support for external client cert validation

- cmd/contour/serve.go
- internal/k8s/informers.go
- internal/k8s/syncer.go
This is in preparation for adding in filtering by discovered CRD types.
Updates #2219 
> Move CRD informer list generation to k8s

- site/resources.md
This will add a link to the new playlist for content other than the community meetings.
> Add the demos and deep dives YouTube link to resources

- cmd/contour/serve.go
- internal/k8s/converter.go
- internal/k8s/informers.go
This is further refactoring for #2219.
Moves Service and Ingress to the client-go dynamic client, leaving only Secrets and Endpoints not handled by the new InformerSet. Secrets need namespace handling, and Endpoints need a separate handler.
> Migrate Service and Ingress to client-go dynamic client

- .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
This will make sure that the PR template is recognized properly by GitHub's community health metrics, and I've also updated the links to the correct repo org.
Signed-off-by: Jonas Rosland <jrosland@vmware.com>
> Fix the PR template with new links and frontmatter

- internal/contour/cluster.go
- internal/contour/endpointstranslator.go
- internal/contour/endpointstranslator_test.go
- internal/contour/listener.go
- internal/contour/route.go
- internal/contour/route_test.go
- internal/contour/secret.go
- internal/envoy/listener.go
- internal/envoy/route.go
- internal/protobuf/helpers.go
- internal/sorter/sorter.go
- internal/sorter/sorter_test.go
Extract the various sorting policies for Envoy types into a single
package that can be tested and conveniently consumed without causing
dependency cycles.
This fixes #2376.
> internal: extract Envoy sort polices

- Dockerfile
- Makefile
- internal/build/version.go
- internal/metrics/metrics.go
- site/_metrics/contour_build_info.md
Fixes #2378
Signed-off-by: Peter Grant <pegrant@vmware.com>
Allows for passing version at build time and exposes build information as a metric.
> internal/contour: Add contour version to metrics

- Makefile
When Dockerfile build moved across the the Makefile, the `-w` Go linker
option was dropped. This option reduces the final binary size by 10MiB
on macOS, so it's probably worth keeping.
> build: omit the DWARF symbol table

- cmd/contour/serve.go
- cmd/contour/servecontext.go
- examples/contour/02-job-certgen.yaml
- examples/contour/03-contour.yaml
- examples/render/contour.yaml
Fixes #2255 by using the downward api to give the default namespace for configuration variables. They are still able to be overridden/configured as before but are no longer hardcoded to `projectcontour`.
> Contour namespace

- internal/dag/cache.go
- internal/e2e/rds_test.go
- internal/featuretests/ingressclass_test.go
- internal/featuretests/mirrorpolicy_test.go
- internal/featuretests/timeoutpolicy_test.go
Fixes #2199  
Only process ingress objects that match an ingress class when specified in Contour explicitly.
```
RELEASE NOTE: This is a change that needs to be called out in the release notes!
```
> internal/dag: only process ingress objects that match ingress.class 

- cmd/contour/ingressstatus.go
- cmd/contour/serve.go
- cmd/contour/servecontext.go
- examples/contour/02-rbac.yaml
- examples/contour/03-envoy.yaml
- examples/render/contour.yaml
- hack/release/prepare-release.go
- internal/contour/handler.go
- internal/k8s/ingressstatus.go
- internal/k8s/ingressstatus_test.go
Updates #403.
This version of Ingress status adds the wiring to manage Ingress status, and allows the configuration of an Envoy service and namespace to watch for addresses to publish into the `status.Loadbalancer` stanza of Ingress objects.
There are still TODOs, #2387 and #2388 amongst them.
> Add Ingress status management

- internal/contour/listener.go
- internal/contour/listener_test.go
- internal/contour/route.go
- internal/contour/route_test.go
- internal/e2e/lds_test.go
- internal/e2e/rds_test.go
- internal/envoy/listener.go
- internal/featuretests/externalname_test.go
- internal/featuretests/featuretests.go
- internal/featuretests/headercondition_test.go
- internal/featuretests/headerpolicy_test.go
- internal/featuretests/ingressclass_test.go
- internal/featuretests/loadbalancerpolicy_test.go
- internal/featuretests/mirrorpolicy_test.go
- internal/featuretests/replaceprefix_test.go
- internal/featuretests/retrypolicy_test.go
- internal/featuretests/rootnamespaces_test.go
- internal/featuretests/tcpproxy_test.go
- internal/featuretests/timeoutpolicy_test.go
- internal/featuretests/tlscertificatedelegation_test.go
- internal/featuretests/tlsprotocolversion_test.go
- internal/featuretests/websockets_test.go
- site/docs/master/httpproxy.md
reviously, Contour generates a single RouteConfiguration named
`ingress_https` that contained all the virtual hosts that were being
served over HTTPS. This meant that if the client request SNI name "A",
it could send a HTTP request for virtual host "B" and it would work.
This behaviour is generally unexpected and can violate security invariants
that we want to enforce, e.g. protecting virtual hosts with client
certificate validation.
The fix is to generate a unique route configuration for each virtual host
and match them to each unique SNI name. This means that once the SNI name
is matched, all the routes from the attached route aonfiguration belong
to the same virtual host. This enforces a one to one correspondence
between SNI names and virtual hosts.
After this, the well-known …
> internal/contour: enforce SNI name bindings

- cmd/contour/serve.go
- internal/annotation/annotations.go
- internal/annotation/annotations_test.go
- internal/contour/handler.go
- internal/contour/metrics.go
- internal/dag/builder.go
- internal/dag/builder_test.go
- internal/dag/cache.go
- internal/dag/dag.go
- internal/dag/policy.go
- internal/dag/policy_test.go
- internal/dag/secret.go
- internal/dag/status.go
- internal/dag/status_test.go
- internal/k8s/objectmeta.go
- internal/k8s/timeout.go
Updates #2388
Update #403
Refactor annotations code from `internal/dag` into `internal/annotation` so that
code dealing with ingress status will be able to use it.
This includes moving some generic Kubernetes structs (`Object` and `Meta`) into
`k8s` from `dag`. `Meta` has also been renamed to `FullName` for greater clarity.
> internal/annotation: Refactor annotations code from internal/dag

- Makefile
Ubuntu 18.04 has git version 2.17.1 which doesn't have the --show-current
flag available (It's in a newer version of git). This causes builds to
throw an error when the makefile looks for the current branch. Go back to
the old method of parsing `git branch` output to get the current branch.
This fixes #2414.
> build: support older git versions to detect current branch

- internal/annotation/annotations.go
- internal/annotation/annotations_test.go
- internal/annotation/timeout.go
- internal/dag/cache.go
- internal/dag/cache_test.go
- internal/dag/policy.go
- internal/dag/policy_test.go
- internal/k8s/ingressstatus.go
- internal/k8s/objectmeta.go
Fixes #2388
Updates #403
Move annotations to use upstream `ObjectMetaAccessor` instead of `k8s.Object`, removes an import cycle.
Copy `KindOf` from k8s to `annotations_test.go` for use in the tests only, also prevents an import cycle.
Move `ParseTimeout` from `k8s` to `annotation` for now as well, more import cycles.
Move ingress class matching code from `dag` to `annotation`, so it's only in one place.
Add ingress class filtering to `k8s.IngressStatusUpdater` `OnAdd` and `OnUpdate`.
I spent some time looking into adding Informer tests, but that requires a lot more fakeclient usage than I am comfortable with right now.
> Add ingress class filtering to ingress status updating

- internal/assert/assert.go
> internal/assert: Add docs to assert.Equal

- go.mod
- internal/dag/builder.go
- internal/dag/status_test.go
- internal/k8s/objectmeta.go
- internal/k8s/objectmeta_test.go
Capture the distinction between when Secrets are missing and when
they have some validation error. This is important to guide operators
when they are trying to figure out why a configuration isn't working
correctly. When we have an Ingress, log the information that we wold
otherwise send to status so that the error is not completely silent.
This fixes #2331.
> internal/dag: improve diagnostics for Secrets errors

- CONTRIBUTING.md
Update the DCO guidelines in the contribution documentation
to clarify that a real name and email address is required.
> docs: update DCO guidelines in CONTRIBUTING

- Makefile
- cmd/contour/contour.go
- internal/build/version.go
Fixes #2396
Signed-off-by: Peter Grant <pegrant@vmware.com>
Allows for a CLI option to print build and version information.
> internal/build: Add contour version as a CLI option

- cmd/contour/contour.go
- go.mod
- go.sum
- internal/assert/assert.go
- internal/contour/cluster.go
- internal/contour/endpointstranslator.go
- internal/contour/listener.go
- internal/contour/route.go
- internal/contour/secret.go
- internal/e2e/e2e.go
- internal/featuretests/featuretests.go
- internal/grpc/server_test.go
> Upgrade Envoy go-control-plane and fix related changes to the spec

- cmd/contour/serve.go
- cmd/contour/servecontext.go
- design/listener-design.md
- internal/health/health.go
- internal/metrics/metrics.go
- site/_guides/health-checking.md
- site/_guides/prometheus.md
Fixes #2380
Signed-off-by: Peter Grant pegrant@vmware.com
Allows for separating health/metric services.
> internal/health: separate health and metrics services

- Makefile
- site/css/fonts/Metropolis/README.md
Since files move around in the repository and it's hard to keep the glob
patterns for misspell up to date, just use `git ls-files` to find all
the markdown and html in the repository and check everything.
This updates #2130.
> build: run misspell across the whole repository

- README.md
- site/docs/master/start-contributing.md
Update current slack links to use the canonical one from the site
config. Add a slack badge to Github.
> site: update slack links

- cmd/contour/ingressstatus.go
- cmd/contour/ingressstatus_test.go
- cmd/contour/serve.go
- cmd/contour/servecontext.go
Adds the `--ingress-status-address` flag to specify what address should be added to Ingress `status.loadbalancer` stanza by Contour.
Setting this flag will disable the automatic Envoy service watching for those details.
Fixes #2387
Updates #403
Further documentation to come under #403.
> cmd/contour: Add flag to specify status.loadbalancer address statically

- internal/dag/builder.go
- internal/dag/builder_test.go
- internal/dag/dag.go
- internal/envoy/cluster.go
- internal/envoy/cluster_test.go
- internal/featuretests/headerpolicy_test.go
Fixes #2437 by setting the SNI for the request with the following rules:
1. If the requestHeadersPolicy.set.Host is set on the service
2. If the requestHeadersPolicy.set.Host is set on the route
3. If an externalName is defined 
//cc @jeremyrickard
> use sni for clusters when requestHeaderPolicy is set

- hack/release/sync-repo-labels.sh
- site/_data/github-labels.yaml
- site/_resources/how-we-work.md
Pull in a Github labels configuration file based on the Kubernetes labels
configuration. This enables a single source of truth for labels within
the projectcontour organization, and lets us document the purpose of
each label.
Add a proposed wrapper script that can be run in a scheduled Github
Action to periodically sync the labels.
Update the process documentation to show the labels and give advice on
how they should be used in the triage process.
> Add github label automation.

- site/_resources/envoy.md
Fixes #2435 by updating the Envoy support matrix for Envoy v1.14.1
> site: update envoy support matrix for Envoy v1.14.1

- cmd/contour/ingressstatus.go
- cmd/contour/ingressstatus_test.go
- cmd/contour/serve.go
- cmd/contour/servecontext.go
- internal/k8s/ingressstatus.go
- site/docs/master/configuration.md
Fixes #403.
Updates the `--ingress-status-address`, `--envoy-service-name`, and `--envoy-service-namespace` flags to be also readable from the config file.
The `serveContext` fields needed to be exported in order for the export to work.
Updated some logging to ensure that you can tell easily which settings are in effect.
> Document and improve UX of ingress status feature.

- site/community.md
Zoom links should not be published directly to prevent zoom-bombing.
> Remove public Zoom link from Community page

- apis/projectcontour/v1/httpproxy.go
- examples/contour/01-crds.yaml
- examples/render/contour.yaml
- site/docs/master/api-reference.html
- site/docs/master/httpproxy.md
Update the API reference for `HeadersPolicy` to clarfy the semantics of
setting headers and to mention the special treatment of the `Host` header.
Rewrite the primary HTTPProxy guide to document that general header
rewriting is available in the `HeadersPolicy` fields.
This fixes #2462.
> doc: update HeadersPolicy documentation

- site/_resources/kubernetes.md
> Update Kube support matrix

- design/fallbackcert.md
> design: add fallback certificate design doc

- site/_includes/blog-community-footer.html
This fixes the community footer that's included on the blog posts.
> Fix community footer to include the correct meeting times

- apis/projectcontour/v1/httpproxy.go
- examples/contour/01-crds.yaml
- examples/render/contour.yaml
- site/docs/master/api-reference.html
Move the description of timeout duration strings into the TimeoutPolicy
strict documentation so that the API generator includes it in the
final output. Clarify how idle timeouts are applied.
> doc: update TimeoutPolicy API documentation

- cmd/contour/ingressstatus.go
- cmd/contour/serve.go
Fixes #2481.
This is a missed bit of wiring to make the Ingress status updating work in the case
that you have supplied an ingress class that is not "contour".
> Pass `ingress.class` through to IngressStatusUpdater

- .github/workflows/sync-labels.yaml
- hack/release/sync-repo-labels.sh
Add a GitHub workflow to run the repository label sync tooling for the
"projectcontour" org. This runs when the labels YAML changes and every
hour in the meantime.
> Enable GitHub workflow to run label sync.

- site/_contributors/01-nick-young.md
- site/_contributors/02-james-peach.md
- site/_contributors/02-steve-sloka.md
- site/_contributors/03-tim-hinderliter.md
- site/_contributors/04-michael-michael.md
- site/_contributors/05-dave-cheney.md
- site/_includes/contributors.html
This will change the non-relevant links for each team member to proper links to GitHub user pages.
> Add GitHub links to team member list

- .github/workflows/stale.yaml
Now that the labels sync tooling is running, the `stale` label has been
renamed to `lifecycle/stale`. Update the GitHub stale issue workflow to
use the new label name.
This updates #2436.
> site: update labels for stale issue workflow

- _integration/testsuite/README.md
- _integration/testsuite/fixtures/httpbin.yaml
- _integration/testsuite/fixtures/ingress-conformance-echo.yaml
- _integration/testsuite/httpproxy/001-required-field-validation.yaml
- _integration/testsuite/httpproxy/002-header-condition-match.yaml
- _integration/testsuite/httpproxy/003-path-condition-match.yaml
- _integration/testsuite/httpproxy/004-https-sni-enforcement.yaml
- _integration/testsuite/httpproxy/005-pod-restart.yaml
- _integration/testsuite/httpproxy/006-merge-slash.yaml
- _integration/testsuite/httpproxy/007-client-cert-auth.yaml
- _integration/testsuite/make-kind-cluster.sh
- _integration/testsuite/policies/contour-client.rego
- _integration/testsuite/policies/contour-resources.rego
- _integration/testsuite/policies/contour-response.rego
- _integration/testsuite/run-test-case.sh
Add an initial set of integration test documents, along with
helper scripts to install a kind cluster and to run the tests.
This updates #2223.
> test: add initial integration test scripts

- apis/projectcontour/v1/httpproxy.go
- examples/contour/01-crds.yaml
- examples/render/contour.yaml
- site/docs/master/api-reference.html
The CRD documentation generator inteprets Godoc comments as markdown,
so by adding som paragraph breaks, it will also turn list items into
proper HTML lists.
> doc: improve TLS API documentation formatting

- design/fallbackcert.md
Updates some additional concepts around how the fallbackCertificate is going to be enabled. The key changes are:
1. The fallbackSecret must be delegated via `TLSCertificateDelegation`
2. The `minimum-protocol-version` will be used from the Contour configuration file
3. Client Validation is not compatible with Fallback Certificate
> update fallbackCertificate design

- examples/contour/dummy.go
While kustomize is explored at HEAD, this adds dummy.go to the 1.4 release branch to unblock consuming the example configurations through `go mod` vendoring.
Related: https://github.com/projectcontour/contour/issues/2486
> [RELEASE 1.4] Optimistically add dummy.go to release-1.4

- apis/projectcontour/v1/httpproxy.go
- cmd/contour/serve.go
- examples/contour/01-crds.yaml
- examples/contour/02-rbac.yaml
- examples/render/contour.yaml
- internal/k8s/converter.go
- internal/k8s/converter_test.go
- internal/k8s/status.go
- internal/k8s/status_test.go
- internal/k8s/syncer.go
This commit enables the status subresource for HTTPProxy.
This means that:
- normal HTTPProxy changes that include updates to the `status` stanza will have the status updates dropped
- updates to `status` can only be made using requests to the status subresource.
Also changes the HTTPProxy status updating to use the status subresource,
and adds RBAC for Contour to be able to update it.
Having the status subresource enabled is best-practice for CRDs and will be a foundation for further status work.
It also means that HTTPProxy objects no longer need to include the `status` stanza to be valid.
Updates #2495
> Add status subresource to HTTPProxy

- site/_data/github-labels.yaml
There's no obvious distinction between `kind/documentation` and
`area/documentation`. Since `area` scopes the part of the project
an issue applies to, that seems lke the better choice, so move all
the `kind/documentation` issues to `area/documentation`.
> site: remove `kind/documentation` label

- codecov.yaml
Add a default codecov settings file, and make the `codecov/project`
status informational, since it otherwise makes CI look broken.
> site: tune codecov settings

- apis/contour/v1beta1/register.go
- apis/projectcontour/v1/register.go
- internal/k8s/converter.go
- internal/k8s/status_test.go
Restore the kubebuilder-compatible API type registration exports for
IngressRoute and HTTPProxy. Keep exporting AddKnownTypes() for projects
that already started consuming this symmbol, but note that it is not
should no longer be used.
This updates #2487.
> api: add kubebuilder-compatible type registration exports

- .golangci.yml
- cmd/contour/servecontext_test.go
- cmd/contour/shutdownmanager.go
- hack/golangci-lint
- internal/certgen/makecerts.go
- internal/envoy/cluster.go
- internal/envoy/secret.go
- internal/workgroup/example_test.go
All the issues currently flagged by gosec are false positives,
but there's no real harm in adding it to the lint checks.
This fixes #2525.
> internal: add gosec to the linter checks

- cmd/contour/bootstrap.go
- cmd/contour/contour.go
- internal/envoy/bootstrap.go
- internal/envoy/bootstrap_test.go
bootstrap: support for Envoy xDS certificate rotation
Added new flag --resources-dir to bootstrap command for supporting path-based
SDS resources to define xDS certificate and key.  When using the flag,
following changes take place:
- Bootstrap file will contain references to SDS resource files instead of direct cert/key paths.
- SDS resource file is written into resources dir for xDS client cert and key
- SDS resource file is written into resources dir for xDS trusted CA cert
With this change there is no need to restart Envoy anymore when certificates
are rotated.  Envoy will monitor and automatically reload the certificate and
key files without causing an interruption to traffic.
Any recent version of Envoy supports the above configuration, but Envoy 1.14.1
or later is required for …
> bootstrap: support for Envoy xDS certificate rotation

- internal/e2e/e2e.go
- internal/envoy/accesslog.go
- internal/envoy/accesslog_test.go
- internal/envoy/bootstrap.go
- internal/envoy/listener.go
- internal/envoy/listener_test.go
- internal/envoy/socket.go
- internal/envoy/socket_test.go
- internal/envoy/stats.go
- internal/envoy/stats_test.go
- internal/featuretests/envoy.go
- internal/featuretests/featuretests.go
- internal/featuretests/tcpproxy_test.go
- internal/grpc/xds.go
- internal/protobuf/helpers.go
Create a `protobuf.MustMarshalAny` wrapper and use it to replace
local copies of the `toAny` helper function.
This fixes #2493.
> internal: consolidate duplicate toAny functions

- apis/projectcontour/v1/httpproxy.go
- cmd/contour/serve.go
- cmd/contour/servecontext.go
- cmd/contour/servecontext_test.go
- examples/contour/01-contour-config.yaml
- examples/contour/01-crds.yaml
- examples/render/contour.yaml
- internal/contour/listener.go
- internal/contour/listener_test.go
- internal/contour/route.go
- internal/contour/route_test.go
- internal/contour/secret_test.go
- internal/contour/visitor_test.go
- internal/dag/builder.go
- internal/dag/builder_test.go
- internal/dag/dag.go
- internal/dag/status_test.go
- internal/envoy/listener.go
- internal/featuretests/envoy.go
- internal/featuretests/fallbackcert_test.go
- internal/featuretests/featuretests.go
- internal/k8s/status.go
- internal/sorter/sorter.go
- internal/sorter/sorter_test.go
- site/docs/master/api-reference.html
Fixes #1503 by adding a `FallbackCertificate` so that clients who do not offer SNI will still match a filterchain in Envoy. Envoy will present a default/fallback certificate to the client. 
Note: One side-effect of this is when you have 2 fqdn's in a cluster, one's enabled for fallback and the other isn't, requests will only route without SNI for the enabled cluster, however, if you request a cert for the non-enabled fqdn, the fallback cert will still be presented. The normal result is an error from Envoy: `curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to fdqn:443` 
Docs to come in a new PR. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
> internal: implement fallback certificate

- internal/annotation/annotations_test.go
- internal/dag/cache_test.go
Working on `v1beta1.Ingress.Spec.IngressClassName`, found a bunch of missing tests for the `projectcontour.io/ingress.class` annotation. 
> add missing projectcontour.io/ingress.class annotation tests

- internal/featuretests/downstreamvalidation_test.go
- internal/featuretests/externalname_test.go
- internal/featuretests/headercondition_test.go
- internal/featuretests/headerpolicy_test.go
- internal/featuretests/ingressclass_test.go
- internal/featuretests/kubernetes.go
- internal/featuretests/loadbalancerpolicy_test.go
- internal/featuretests/replaceprefix_test.go
- internal/fixture/httpproxy.go
- internal/fixture/meta.go
Add some simple helpers to generate HTTPProxy test fixtures. This
helps reduce some boilerplate in setting up test cases.
> internal/featuretests: add simple HTTPProxy fixtures

- site/docs/master/annotations.md
- site/docs/master/httpproxy.md
The text that attempts to describe using annotations to enable upstream
TLS doesn't match the example properly, and the example isn't very clear.
Update both the HTTPProxy and the annotations documentation for clarity,
and add a better example that demonstrates how to apply the protocol
annotation.
This fixes #2457.
> doc: improve ambiguous upstream TLS example

- cmd/contour/ingressstatus.go
- cmd/contour/ingressstatus_test.go
When using a cluster without a LoadBalancer, it's common to configure
Envoy to use host networking and to run on some number of nodes (maybe
all of them, using a DaemonSet).
In that case, Contour won't pick up the IP addresses automatically as
there's no LoadBalancer; one approach to working around this is to
supply the --ingress-status-address argument, but this only supported
a single address.
This changeset adds support for multiple addresses, separated by
commas.
Fixes #2540
Signed-off-by: Alastair Houghton <alastair@alastairs-place.net>
> cmd/contour: support comma-separated ingress-status-address

- examples/contour/02-job-certgen.yaml
- examples/render/contour.yaml
The RBAC verbs for certgen are both too permissive (e.g. it doesn't
need watch or list) and too restrictive (and upcoming change will let
it update secrets).
This fixes #2538.
> examples/contour: grant update to certgen RBAC

- _integration/testsuite/httpproxy/004-https-sni-enforcement.yaml
- _integration/testsuite/httpproxy/009-https-misdirected-request.yaml
- _integration/testsuite/policies/contour-client.rego
- _integration/testsuite/policies/contour-resources.rego
- _integration/testsuite/policies/contour-response.rego
- internal/contour/listener.go
- internal/contour/listener_test.go
- internal/e2e/lds_test.go
- internal/envoy/listener.go
- internal/featuretests/downstreamvalidation_test.go
- internal/featuretests/envoy.go
- internal/featuretests/fallbackcert_test.go
- internal/featuretests/tcpproxy_test.go
- internal/featuretests/tlscertificatedelegation_test.go
- internal/featuretests/tlsprotocolversion_test.go
- site/_resources/envoy.md
TLS routes are specialized to a unique virtual hostname. However, if
wildcard certificates are being used, browsers will aggressively coalesce
and reuse server connections even when the full origin hostname doesn't
match. This results on 404 responses because each TLS virtual host only
has routes for one host.
We can avoid this behaviour bleeding out to users by generating a 421
Misdirected Request response if the request authority doesn't match
the FQDN of the virtual host. In this case, the browser is supposed
to understand that the request wasn't processed and re-send it on a
new connection.
> internal: filter misdirected TLS requests

- internal/dag/builder.go
- internal/dag/builder_test.go
- internal/dag/status_test.go
- internal/featuretests/fallbackcert_test.go
Updates #1503 by requiring TLSCertificateDelegation to each namespace where a root HTTPProxy enables tls fallback certificate.
> internal/dag: update TLS fallbackCertificate logic to require tlscertificatedelegation

- site/docs/master/configuration.md
- site/docs/master/httpproxy.md
Updates #1503 by adding fallback certificate documentation.
> docs: add fallback certificate docs

- netlify.toml
- site/_redirects
- site/_resources/release-process.md
- site/_resources/upgrading.md
Add netlify redirects to the versioned quickstart YAML. This improves
the deployment experience for operators pinning to Contour versions,
and for testers verifying upgrades.
> site: add versioned quickstart redirects

- _integration/testsuite/make-kind-cluster.sh
- examples/render/contour.yaml
- hack/generate-deployment.sh
When deploying release builds, Contour images are tagged with the release
version and are intended to be immutable. This means we can generally use
the `IfNotPresent` image pull policy, except for cthe certgen job, which
needs to use `Always` because it pulls the mutable `:latest` image tag.
This fixes #2537.
> test: switch to IfNotPresent image pull policy

- .travis.yml
- examples/contour/02-job-certgen.yaml
- examples/contour/03-contour.yaml
- examples/contour/03-envoy.yaml
- examples/render/contour.yaml
Switch the certgen xDS certificate generation over to using certificates
that are compatible with certificate-manager. This requires the certgen
job to run again, which means we have to give is a unique name. Using
a version-locked name will let it run on each upgrade, which will have
the beneficial side-effect of rotating the xDS certificates.
The envoy and contour pods will restart because the secrets mounts change,
but they will restart at release time anyway because the container image
will change.
After this change, re-running certgen to rotate the xDS certificates
will not require restarting and pods.
This fixes #2524.
This updates #2143.
> examples/contour: switch to reloadable xDS certificates

- examples/contour/README.md
- site/docs/master/grpc-tls-howto.md
This makes some purely proofreading changes to the TLS howto, making
minor grammar and formatting improvements.
> docs: make proofing changes to TLS howto

- examples/contour/03-envoy.yaml
- examples/render/contour.yaml
Envoy does not need to talk to kubernetes apiserver, hence disable
mounting service account in the envoy container.
This still enables the pod to acquire identity for mechanisms like
PodSecurityPolicy.
Related https://github.com/projectcontour/contour/issues/1896
> envoy config: Don't mount service account token

- _integration/testsuite/httpproxy/010-include-prefix-condition.yaml
Create two namespaces with two different echo servers. Use a prefix
include proxy to bind them together into a single vhost that discriminates
using the path prefix.
This updates #2561.
> testsuite: add a test for include prefix conditions

- _integration/testsuite/httpproxy/010-include-prefix-condition.yaml
In 010-include-prefix-condition.yaml test , echo http proxy is created before echo-admin and echo-app which are its dependencies. So, the echo http proxy resource initially goes into invalid state since its dependencies are not there. Changing the order of creation of echo http proxy resource avoids the echo http proxy going into invalid state .
> Change order of creation of echo http proxy resource in 010-include-prefix-condition test

- _integration/testsuite/httpproxy/009-https-misdirected-request.yaml
- internal/envoy/listener.go
- internal/envoy/route.go
Since Contour configures virtual host matches to ignore the port
specifier, it should do the same when matching for misdirected requests.
This fixes #2568.
> internal/envoy: ignore ports for misdirected requests

- cmd/contour/ingressstatus.go
- cmd/contour/serve.go
- internal/k8s/clients.go
- internal/k8s/converter.go
- internal/k8s/converter_test.go
- internal/k8s/informers.go
- internal/k8s/kind.go
- internal/k8s/kind_test.go
- internal/k8s/syncer.go
This change standardizes Contour to always use dynamic Informers. This
makes the startup code path a little simpler, and lets us consolidate
on a single method of handling object updates. Update the downstream
handlers to fully support unstructured objects.
> cmd/contour: exclusively use dynamic Informers

- hack/release/prepare-release.go
Example use:
```
prepare-release v1.5.0 v1.5.1 
Verifying repository state ...
Cloning versioned documentation ...
modified:   site/_config.yml
modified:   site/_data/toc-mapping.yml
new: site/_data/v1-5-1-toc.yml
new: site/docs/v1.5.1/
```
> Update prepare-release to accept old version as doc source

- _integration/testsuite/httpproxy/001-required-field-validation.yaml
- apis/projectcontour/v1/httpproxy.go
- examples/contour/01-crds.yaml
- examples/render/contour.yaml
Add Kubebuilder annotations to validate the Service port range.
> apis/projectcontour: add Service port range validation

- cmd/contour/leadership.go
- internal/k8s/clients.go
`Clients` currently instantiates a Kubernetes clientset plus a `CoordinationV1` client. Since the former already contains a `CoordinationV1` client, the latter is redundant, so this PR removes it.
> internal/k8s: remove redundant coordination client

- cmd/contour/contour.go
> cmd/contour: add -h as a short flag for --help

- internal/envoy/bootstrap.go
Currently during envoy bootstrap, TLS cert file is checked for existence. Adding a check for empty file too since cert-manager generates secret with empty certificates first and then updates it.
Short term fix for: https://github.com/projectcontour/contour/issues/2602 . Long term fix is to come up with a liveness probe for envoy which can restart envoy if it fails to start.
Signed-off-by: Shyaam Nagarajan <nagarajans@vmware.com>
> Check for empty envoy TLS cert file during bootstrap

- cmd/contour/serve.go
- internal/k8s/syncer.go
We all missed in #2583 that not all informers handle Unstructured objects; wrap the service status informer in the dynamicHandler to ensure that no Unstructured objects make it through.
Service status watching was broken before this, as it didn't handle Unstructured.
> Fix Envoy service status watching

- cmd/contour/serve.go
- internal/k8s/status.go
- internal/k8s/status_test.go
- internal/k8s/statusaddress.go
- internal/k8s/statusaddress_test.go
- internal/k8s/statusupdater.go
Updates the DAG StatusClient to use the StatusUpdateWriter pattern.
Fixes #2560
Fixes #2580 - I *think* it fixes it, but I haven't been able to reproduce, even with the excellent script provided by @primeroz. 
Fixes #2522 - I've confirmed this one with testing.
We should be able to remove the StatusClient eventually, but that API also needs refactoring for adding Conditions (currently under #2495), so for now I've just updated it to send updates via the StatusUpdateWriter rather than make API calls directly.
> Send DAG status updates via StatusUpdateHandler

- site/docs/master/configuration.md
closes #2403 
I kept this simple and avoided getting into precisely what each of the related flags/config settings controls in this PR, but I'm happy to add more detail if you think it's necessary now.
I'll spin out a separate issue to cover the bigger changes to this page to fully cover all CLI flags and env vars.
> docs: describe CONTOUR_NAMESPACE env var usage

- examples/example-workload/httpproxy/04-inclusion/httpproxy-inclusion-samenamespace.yaml
- site/docs/master/httpproxy.md
Uses the correct name to refer to the included HTTPProxy and removes an
incorrect prefix condition from the child proxy.
The relevant scenarios are covered by [these test cases](https://github.com/projectcontour/contour/blob/master/internal/dag/builder_test.go#L4722-L4785) using [this test data](https://github.com/projectcontour/contour/blob/master/internal/dag/builder_test.go#L2394-L2479).
> docs: fix inclusion example

- internal/dag/builder_test.go
- internal/dag/dag.go
- internal/featuretests/headercondition_test.go
closes #2597 
Fixes a bug where an HTTPProxy with multiple routes with the same prefixes
and conditions on the same headers, differing only on the condition operators
or values, would result in only the last route being configured in Envoy and
all others being dropped.
> internal/dag: allow routes with overlapping header conditions

- _integration/testsuite/httpproxy/007-client-cert-auth.yaml
_integration/testsuite: Add commonName to client certificates
Older versions of cert-manager dont have emailSANs. So, one of
commonName, dnsNames, uriSANs is required. Hence adding commonName
to client certificate to be backward compatible with older versions
of cert-manager
Signed-off-by: Shyaam Nagarajan <nagarajans@vmware.com>
> Testsuite: Add commonName to client certificates

- site/_data/refdocs/config.json
- site/docs/master/api-reference.html
> docs: update Kubernetes links in master docs to 1.18

- hack/site-proofing/cibuild
- site/docs/v1.1.0/api-reference.html
- site/docs/v1.2.0/api-reference.html
- site/docs/v1.2.1/api-reference.html
- site/docs/v1.3.0/api-reference.html
- site/docs/v1.4.0/api-reference.html
- site/docs/v1.5.0/api-reference.html
- site/docs/v1.5.1/api-reference.html
closes #2624 
Due to #2031 the updated job won't run for this PR, but you can see a passing build on my fork [here](https://travis-ci.org/github/skriss/contour/jobs/702120241).
For now, I opted to update the broken links in the old versioned docs. We can decide down the road to exclude those subdirs from the site proofing job if they continue to create more issues that we don't want to fix.
The haproxy.org link appears to be unresponsive when requested from Travis workers - even a simple curl times out - so I added it to the excludes list for the proofer.
> Fix site proofing on master builds

- Makefile
- hack/yamllint
When running `make checkall`, the task`lint-yamllint` required docker. For users not wanting to keep docker running locally, this change allows to run the same command from a binary without a docker container. 
> makefile: allow lint-yamllint to be run from binary and not require docker

- site/_data/github-labels.yaml
Add a label to manage issues related to TLS support.
> site: add `area/tls` label

- cmd/contour/serve.go
- cmd/contour/servecontext.go
- examples/contour/01-contour-config.yaml
- examples/render/contour.yaml
- internal/contour/listener.go
- internal/contour/listener_test.go
- internal/envoy/listener.go
- internal/envoy/listener_test.go
- site/docs/master/configuration.md
updates #2225 
I started with just one timeout setting chosen at random; I'll add the others if the approach looks OK.
I can see how adding additional tuneables one-by-one is not ideal (+268 LOC to add a single config parameter). I'm still paging in the context to see if there are other ideas/options for how to do this in a more general way.
> add configurable idle timeout

- cmd/contour/serve.go
- cmd/contour/servecontext.go
- examples/contour/01-contour-config.yaml
- examples/render/contour.yaml
- internal/contour/listener.go
- internal/contour/listener_test.go
- internal/envoy/listener.go
- internal/envoy/listener_test.go
- site/docs/master/configuration.md
> cmd/contour: add config file option to set stream idle timeout

- site/_resources/kubernetes.md
Adds missing Contour releases to the Kubernetes Support Matrix.
> site/resources: add missing Contour releases

- .github/workflows/codeql-analysis.yml
Adds the github code scanning action to run on PRs and any merge to `master` branch.
Fixes #2659
> .github/workflows: add code scanning GH action

- site/docs/master/README.md
- site/docs/v1.0.0/README.md
- site/docs/v1.0.1/README.md
- site/docs/v1.1.0/README.md
- site/docs/v1.2.0/README.md
- site/docs/v1.2.1/README.md
- site/docs/v1.3.0/README.md
- site/docs/v1.4.0/README.md
- site/docs/v1.5.0/README.md
- site/docs/v1.5.1/README.md
- site/docs/v1.6.0/README.md
- site/docs/v1.6.1/README.md
Remove the badges from the README.md on the projectcontour.io docs section.
Fixes #2532
> site/docs: remove badges from README.md

- cmd/contour/serve.go
- cmd/contour/servecontext.go
- examples/contour/01-contour-config.yaml
- examples/render/contour.yaml
- internal/contour/listener.go
- internal/contour/listener_test.go
- internal/envoy/listener.go
- internal/envoy/listener_test.go
- site/docs/master/configuration.md
> cmd/contour: add config file option to set max connection duration

- cmd/contour/servecontext.go
- cmd/contour/servecontext_test.go
- go.mod
- internal/contour/handler.go
- internal/contour/listener_test.go
- internal/contour/metrics.go
- internal/contour/route_test.go
- internal/contour/secret_test.go
- internal/dag/builder.go
- internal/dag/builder_test.go
- internal/dag/cache.go
- internal/dag/dag.go
- internal/dag/status.go
- internal/dag/status_test.go
- internal/featuretests/featuretests.go
- internal/fixture/meta.go
- internal/k8s/objectmeta.go
- internal/k8s/objectmeta_test.go
- internal/k8s/statusupdater.go
The client-go type `types.NamespacedName` is almost identical to our
`k8s.FullName`, so switch to it everywhere. The difference is that
`NamespacedName` doesn't implicitly fill in the default namespace
when stringifying, so we need to make sure that we always add
this explicitly.
> internal: adopt types.NamespacedName

- site/_guides/cert-manager.md
closes #2692 
Edits the cert-manager guide to remove references to ingress-shim,
which is an internal component of cert-manager, knowledge of which
is unnecessary for a Contour user. Also adds a link to the relevant
cert-manager docs.
> site: clarify cert-manager guide

- design/external-authorization-design.md
This updates #432.
This updates #2459.
> design: add initial external authorization proposal

- internal/contour/secret.go
- internal/featuretests/fallbackcert_test.go
Update the DAG visitor to emit an Envoy secret if the Contour fallback
certificate is used by a secure virtual host.
This fixes #2720.
> internal/contour: generate an Envoy secret for the fallback certificate

- cmd/contour/serve.go
- internal/dag/cache.go
- internal/dag/cache_test.go
- internal/k8s/converter.go
- internal/k8s/converter_test.go
If the cluster has the ExtensionService CRD installed, inform on
ExtensionService resources and update the DAG cache.
This fixes #2712.
> internal/dag: cache ExtensionService resources

- cmd/contour/serve.go
- cmd/contour/serve_test.go
- cmd/contour/servecontext.go
- examples/contour/01-contour-config.yaml
- examples/render/contour.yaml
- internal/contour/listener.go
- internal/envoy/listener.go
- internal/envoy/listener_test.go
- internal/featuretests/envoy.go
- site/docs/master/configuration.md
updates #2690 
Adds a new RequestTimeout field to the TimeoutConfig struct. If
specified in the config file, this field takes precedence over
the now-deprecated RequestTimeout field in the root of the
serveContext struct.
> cmd/contour: add TimeoutConfig.RequestTimeout

- internal/envoy/tcp_keepalive.go
When programming the Envoy socket options, we need to use system call
constants for the platform that Envoy is running on. Ensure that we
always use Linux values since that is what we know (by fiat) that
Envoy is running on.
This fixes #2729.
> internal/envoy: hard code Linux system call constants

- Makefile
Introduce a new variable for the Envoy image used for the
`make local` & `make secure-local` tasks. Also updates to the version
to latest v1.15.0.
> makefile: Update Contour version for `local` task.

- _integration/testsuite/run-test-case.sh
- internal/contour/listener.go
- internal/contour/listener_test.go
- internal/envoy/listener.go
- internal/envoy/listener_test.go
- internal/featuretests/envoy.go
Ensure that the `http.Router` filter is present whenever we build a
HTTP Connection Manager. The `Router` filter is responsible for actually
forwarding HTTP requests, so omitting it leads to configurations that
are syntactically valid but otherwise inoperable.
This fixes #2733.
> internal/contour: ensure the http.Router filter is present

- internal/envoy/cluster.go
- internal/featuretests/envoy.go
- internal/featuretests/externalname_test.go
When the SNI server name is overridden by rewriting the `Host` header,
Contour was updating the outbound SNI name for the `tls` protocol but
still using the external name value for the `h2` protocol. Since `h2`
implies TLS, Contour should do the same thing in both cases.
> internal/envoy: use a consistent SNI server name for H2

- examples/contour/02-job-certgen.yaml
- examples/render/contour.yaml
- hack/release/make-release-tag.sh
Updates the `hack/make-release-tag.sh` script to change the job name to match
the release being created.
> hack: Update  make-release-tag script to update certgen-job

- .travis.yml
- Makefile
- _integration/testsuite/cleanup.sh
- _integration/testsuite/make-kind-cluster.sh
- hack/travis/install-kubernetes-toolchain.sh
Adds a `makefile` task which spins up a kind cluster, loads in a Contour build and runs all the integrations tests.
> travis: Run integration tests on each build

- cmd/contour/servecontext_test.go
Signed-off-by: Gaurav Singh <gaurav1086@gmail.com>
Fix data race on the err variable.
> TestServeContextCertificateHandling: fix data race on err variable

- go.mod
- internal/contour/endpointstranslator.go
- internal/envoy/cluster.go
- internal/envoy/cluster_test.go
- internal/featuretests/externalname_test.go
Various parts of an Envoy configuration depend upon the EDS service
emitting a ClusterLoadAssignment with a matching name. Hoist a common
function to generate a ClusterLoadAssignment name to (1) ensure that it
is generated consistently, and (2) make it easier to track the dependency.
> internal/envoy: add common API for ClusterLoadAssignment names

- Makefile
After update to use Github actions, there was a broken reference to a travis link. This updates that path to the script. 
> makefile: Fix broken reference to script in check-generate

- cmd/contour/contour.go
- cmd/contour/shutdownmanager.go
- examples/contour/03-envoy.yaml
- examples/render/contour.yaml
This changes the preStop lifecycle hook to utilize a command instead of an http request. The /shutdown http endpoint now only returns when the pod is ready to be terminated, and no longer initiates the Envoy shutdown sequence.
The Envoy container will block on its preStop hook until the /shutdown endpoint returns. That endpoint, implemented in the shutdown-manager, will utilize a file messaging pattern to know when it is safe for Envoy to terminate by checking for the existence of a file in the filesystem.
> cmd/contour: refactor shutdown-manager to initiate shutdown using an Exec command

- _integration/testsuite/httpproxy/002-header-condition-match.yaml
The Rego expression `count(data.resources.httpproxies[_])` generates a
map of the length of each proxy resource name. What we actually want is
`count(data.resources.httpproxies)` which is the number of elements in
the proxies map.
> testsuite: fix httproxies count

- internal/contour/endpointstranslator.go
- internal/contour/endpointstranslator_test.go
Breaking EndpointsTranslator into two parts doesn't provide any benefits
and we can make the code easier to follow by removing all the indirection.
> internal/contour: simplify the endpoints translator

- cmd/contour/serve.go
- internal/e2e/e2e.go
- internal/featuretests/featuretests.go
- internal/workgroup/example_test.go
- internal/workgroup/group.go
- internal/workgroup/group_test.go
Replace the weird hack that feature tests use to cancel running
a workgroup with structured context cancellation.
> internal/workgroup: add cancellation support

- _integration/testsuite/httpproxy/009-https-misdirected-request.yaml
- internal/envoy/listener.go
Host header (authority) checks should be case insensitive. Lowercase
both the target match and the candidate header when we check for
misdirected requests.
> internal/envoy: check misdirected requests case insensitively

- internal/e2e/e2e.go
- internal/e2e/rds_test.go
- internal/featuretests/cluster_test.go
- internal/featuretests/envoy.go
Moves the CDS tests from the e2e package to the featuretests package.
Updates #2549
> internal/e2e: Move cluster tests to featuretests package

- internal/e2e/e2e.go
- internal/featuretests/endpoints_test.go
- internal/featuretests/featuretests.go
- internal/featuretests/kubernetes.go
Moves the EDS tests from the e2e package to the featuretests package.
Updates #2549
> internal/e2e: Move endpoint tests to featuretests package

- internal/e2e/e2e.go
- internal/e2e/sds_test.go
- internal/featuretests/listeners_test.go
Moves the LDS tests from the e2e package to the featuretests package.
Updates #2549
> internal/e2e: Move listener tests to featuretests package

- cmd/contour/serve.go
Enables strict configuration YAML parsing.
Fixes #2623
Signed-off-by: Tim Gretler "gretler.tim@gmail.com"
> Parse yaml

- apis/projectcontour/v1/httpproxy.go
- examples/contour/01-crds.yaml
- examples/render/contour.yaml
- internal/dag/builder.go
- internal/dag/status_test.go
- site/docs/master/api-reference.html
When validating an HTTPProxy's TLS configuration, separately check
for cases where both secretName and passthrough are specified, and
for cases where neither secretName nor passthrough are specified.
Sets a corresponding HTTPProxy status message for both cases. Also
improves the status message for when TCPProxy is enabled, but TLS
is not enabled.
Fixes #2501 
Fixes #2273
> internal/dag: improve status errors for invalid TLS

- Makefile
- _integration/testsuite/httpproxy/012-https-fallback-certificate.yaml
- _integration/testsuite/install-fallback-certificate.sh
- _integration/testsuite/make-kind-cluster.sh
- _integration/testsuite/policies/contour-configmap.rego
Add a simple integration test to ensure that using the fallback
certificate works as expected. This requires that Contour is deployed
with a valid fallback certificate. For integration testing, we can use
cert-manager to pre-configure that, but this approach won't work well
for large numbers of configuration permutations, so we should revisit
it relatively soon.
> testsuite: add a fallback certificate test

- cmd/contour/serve.go
- cmd/contour/servecontext_test.go
- internal/contour/server_test.go
- internal/e2e/e2e.go
- internal/featuretests/featuretests.go
- internal/fixture/log.go
- internal/workgroup/group_test.go
* Switch from shutting down gRPC server with `Stop()` to `GracefulStop()`.
which waits for current requests to drain before returning. This
means that tests which log to the test runner won't ever attempt to
log after the test has completed.
* Hoist test loggers into the fixtures package and use them from there.
* Add a workgroup context cancellation test.
This updates #2775.
> internal: test reliability improvements

- internal/contour/visitor_test.go
- internal/dag/builder.go
- internal/dag/builder_test.go
- internal/dag/dag.go
- internal/debug/dot.go
- internal/envoy/cluster.go
- internal/envoy/cluster_test.go
- internal/envoy/listener_test.go
- internal/envoy/route_test.go
The Kubernetes `v1.ServicePort` is embedded in `dag.Service` as a pointer
field. There's no need to have a pointer here, since it is always assumed
to be non-nil, and using the type as an explicit field makes is easier to
see where it is used, and clarifies overlapping field (i.e. `Protocol`).
This updates #2769.
> internal/dag: stop embedding ServicePort in dag.Service

- internal/envoy/route_test.go
- internal/featuretests/backendcavalidation_test.go
- internal/featuretests/cluster_test.go
- internal/featuretests/downstreamvalidation_test.go
- internal/featuretests/externalname_test.go
- internal/featuretests/fallbackcert_test.go
- internal/featuretests/headercondition_test.go
- internal/featuretests/headerpolicy_test.go
- internal/featuretests/ingressclass_test.go
- internal/featuretests/listeners_test.go
- internal/featuretests/loadbalancerpolicy_test.go
- internal/featuretests/mirrorpolicy_test.go
- internal/featuretests/replaceprefix_test.go
- internal/featuretests/retrypolicy_test.go
- internal/featuretests/rootnamespaces_test.go
- internal/featuretests/route_test.go
- internal/featuretests/secrets_test.go
- internal/featuretests/tcpproxy_test.go
- internal/featuretests/timeoutpolicy_test.go
- internal/featuretests/timeouts_test.go
- internal/featuretests/tlscertificatedelegation_test.go
- internal/featuretests/tlsprotocolversion_test.go
- internal/featuretests/upstreamprotocol_test.go
- internal/featuretests/websockets_test.go
- internal/fixture/httpproxy.go
- internal/fixture/meta.go
- internal/fixture/service.go
Add fixture support for generating `v1.Service` resources with a reduced
amount of boilerplate.
> internal/featuretests: add v1.Service fixture support

- cmd/contour/serve.go
Fix a regression from #2780, where the Contour xDS server would fail
to stop because it is waiting for xDS connections to drain (they won't
drain).
This updates #2780.
> cmd/contour: forcibly terminate the xDS server on shutdown

- internal/contour/contour_test.go
- internal/contour/endpointstranslator_test.go
- internal/contour/metrics_test.go
- internal/contour/secret_test.go
- internal/dag/builder_test.go
- internal/dag/cache_test.go
- internal/dag/status_test.go
- internal/fixture/meta.go
- internal/k8s/statusaddress_test.go
Remove copies of testLogger and replace them with
fixture.NewTestLogger.
> internal: remove copies of testLogger

- internal/contour/cluster_test.go
- internal/contour/listener_test.go
- internal/contour/route_test.go
- internal/contour/secret_test.go
- internal/contour/visitor_test.go
I don't know why I didn't swap these over before. :facepalm:
> internal/dag: Update DAG tests to use assert.EqualProto

- internal/dag/builder.go
- internal/dag/cache.go
Moves some common components from the builder into the KubernetesCache
so that it can be reused from other components. This is the first of a few PRs in refactoring
the builder out. 
Updates #2226
> internal/dag: Refactor some logic from builder into KubernetesCache

- site/_guides/cert-manager.md
Set correct `secretName` for resources related to `httpbinproxy`.
Also set correct namespace for the dummy ingress object.
Fixes #2800
Signed-off-by: Rajat Goyal <404rajat@gmail.com>
> docs: guides/cert-manager

- internal/dag/builder.go
- internal/dag/cache.go
Moves some common components from the builder into the KubernetesCache
so that it can be reused from other components. This is the first of a few PRs in refactoring
the builder out.
Updates #2226
> internal/dag: Refactor out DelegationPermitted into the KubernetesCache

- site/_data/github-labels.yaml
Add a label to capture issues that are related to operating Contour in a
production environment. This includes troubleshooting and observability,
as well as behaviors that improve the operational experience (e.g. rate
limiting failures, improving error visibility, and so on).
> site: add `area/operational` label

- internal/dag/cache.go
- internal/k8s/kind.go
- internal/k8s/kind_test.go
Signed-off-by: Fahri Yardımcı 
Tested on minikube v1.12.3  - Kubernetes v1.17.11 on Docker 19.03.8
logs:
``` 
time="2020-08-18T20:50:34Z" level=info msg="started HTTP server" address="127.0.0.1:6060" context=debugsvc
time="2020-08-18T20:50:34Z" level=error msg="ignoring invalid or unsupported annotation" annotation=projectcontour.io/wololo context=KubernetesCache kind=Ingress name=kuard namespace=default version=networking.k8s.io/v1beta1
time="2020-08-18T20:50:34Z" level=error msg="ignoring invalid or unsupported annotation" annotation=projectcontour.io/wololo context=KubernetesCache kind=HTTPProxy name=basic namespace=default version=projectcontour.io/v1
```
> #2589 - add groupversion for logging

- _integration/testsuite/httpproxy/006-merge-slash.yaml
The `httpbin` container takes a long time to start up, and there's no good
way to figure out how long it should take or when to start the timeout
from. Replace this with the `ingress-conformance-echo` container which
has much better startup time.
This updates #2743.
> testsuite: switch merge-slash test away from httpbin

- internal/assert/assert.go
- internal/certgen/certgen_test.go
- internal/contour/server_test.go
- internal/dag/builder_test.go
- internal/dag/cache_test.go
- internal/envoy/auth_test.go
- internal/envoy/endpoint_test.go
- internal/envoy/secret_test.go
- internal/k8s/kind_test.go
- internal/k8s/objectmeta_test.go
- internal/metrics/metrics_test.go
- internal/xds/contour_test.go
Needed to update some aliases in internal/assert to cover all the cases.
Updates #2786.
> testing: Migrate as many tests as possible to internal/assert

- cmd/contour/shutdownmanager.go
Fixes #2819
Depends on #2817
Signed-off-by: Lauro Ramos Venancio <lauro.venancio@inloco.com.br>
> cmd/contour: add drain-delay arg to the envoy shutdown command

- internal/dag/builder.go
- internal/dag/builder_test.go
> internal/dag: upstream server cert validation for HTTP/2

- examples/gatekeeper/01-sync-config.yml
- examples/gatekeeper/README.md
- examples/gatekeeper/policies/01-template-retry-count-range.yml
- examples/gatekeeper/policies/01-template-timeout-range.yml
- examples/gatekeeper/policies/02-constraint-idle-timeout-range.yml
- examples/gatekeeper/policies/02-constraint-response-timeout-range.yml
- examples/gatekeeper/policies/02-constraint-retry-count-range.yml
- examples/gatekeeper/validations/01-template-unique-fqdn.yml
- examples/gatekeeper/validations/02-constraint-unique-fqdn.yml
- site/_guides/gatekeeper.md
replaces #2791 
updates #2742 
To do:
> add Gatekeeper guide and sample configs

- internal/dag/cache.go
- internal/k8s/statusaddress.go
Make the two debug log messages for Ingress class matching emit
the same field.
> internal: improve Ingress class matching log messages

- site/_guides/deploy-aws-nlb.md
On deploy-aws-nlb guide, it refers to a wrong service envoy file.
Fix the file name to point to correct file.
Change-Id: Ia2186796c9babb84d199c72bbbdc3da2fd9262ae
Signed-off-by: Tong Liu <tongl@vmware.com>
> Fix a nlb doc typo

- cmd/contour/serve.go
- internal/contour/endpointstranslator.go
- internal/contour/endpointstranslator_test.go
- internal/contour/server_test.go
- internal/contour/visitor_test.go
- internal/dag/builder.go
- internal/dag/builder_test.go
- internal/dag/dag.go
- internal/debug/dot.go
- internal/envoy/cluster.go
- internal/envoy/cluster_test.go
- internal/envoy/endpoint.go
- internal/envoy/listener_test.go
- internal/envoy/route_test.go
- internal/featuretests/endpoints_test.go
- internal/featuretests/featuretests.go
- internal/xds/util.go
The EndpointsTranslator generates Envoy ClusterLoadAssignment resources
in a fixed configuration. Each service/port pair generates a separate
ClusterLoadAssignment, that is associated with an Envoy Cluster solely
by its matching name.
This change introduces a new ServiceCluster concept that represents a
single set of endpoints, weighted across multiple Kubernetes Services.
This allows the upcoming ext_auth support to weight traffic, even though
(by definition), it still uses a single Envoy Cluster. The weighted
balancing is done within the cluster.
The DAG Service object is updated to use a ServiceCluster rather than
referencing a Service directly. This is exposed to the EndpointsTranslator,
which is now a DAG observer. The EndpointsTranslator rebuilds the
ClusterLoadAssigments globally …
> internal: rebuild endpoints based on the DAG services

- cmd/contour/serve.go
- cmd/contour/servecontext.go
- examples/contour/01-contour-config.yaml
- examples/render/contour.yaml
Adds a config file option to define the XDS server to use when serving Envoy's gRPC XDS.
> cmd/contour: add xds-server-type arg to config file

- site/docs/main/configuration.md
- site/docs/v1.8.0/configuration.md
Fix a typo in `default-http-versions` by moving description to the same row.
[Link](https://projectcontour.io/docs/main/configuration/) to the current Contour Configuration Reference.
Signed-off-by: Zian Ke <zian.ke@zian.ke>
> site: Fix typo in configuration reference

- internal/dag/builder.go
- internal/k8s/helpers.go
Google's `cmp` library is great, but it's intended for test code, so it can panic as a failure mode.  Also, the K8s equality package seems purpose built for the use case here.
Fixes: https://github.com/projectcontour/contour/issues/2851
> Switch from cmp.Equal to equality.Semantic.DeepEqual

- site/_includes/footer.html
- site/_resources/faq.md
- site/_resources/philosophy.md
- site/_resources/upgrading.md
- site/_scss/_styles.scss
- site/_scss/site/common/_core.scss
- site/_scss/site/objects/_anchor.scss
- site/_scss/site/objects/_button.scss
- site/_scss/site/objects/_deprecated.scss
- site/_scss/site/objects/_footer.scss
- site/_scss/site/objects/_header.scss
- site/_scss/site/objects/_home-hero.scss
- site/_scss/site/objects/_post.scss
- site/_scss/site/objects/_toc.scss
- site/_scss/site/settings/_variables.scss
Use [anchor.js](https://github.com/bryanbraun/anchorjs) to put an anchored element by the webpage headers, which can be used to obtain a link. It currently uses the default style (displayed on hover) and adds anchors to `h2`, `h3`, `h4`, `h5`, `h6` elements, which looks good to me, though there are other [options](https://www.bryanbraun.com/anchorjs/#options).
Fixes #2469.
A preview with `make site-devel`:
Signed-off-by: Zian Ke <zian.ke@zian.ke>
> site: Add clickable anchor links to the website

- cmd/contour/serve.go
- internal/k8s/statusupdater.go
Replace the dynamic client Get (uncached) with a read from
the informer's lister cache.  This code path is evaluated
for every HTTP Proxy on each DAG rebuild, and the call to
the API Server on each results in a thundering herd that
triggers the built-in rate limiting in k8s.io/client-go.
With this change, the only API Server calls on DAG rebuilds
happen only when our cached copy of the HTTP Proxy shows
that we need to perform a status update.
Updates #2857
> Second attempt at fixing knative-sandbox/net-contour#226

- cmd/contour/serve.go
- internal/k8s/statusupdater.go
`git cherry-pick 413fab783d9a92b660ba968e5b35ded8756be004`
> [release 1.8] Cherry Pick #2864
