site/getting-started.md
=> site: Fix link to docs from quickstart

Dockerfile
Like sand through the hourglass,
these are the upgrades of our lives.
=> Dockerfile: update to Go 1.13.6

site/resources.md
=> site: Add Kubecon & Blog post videos

Makefile
=> Fixes the check-flags task to not use a pager if users have enabled

examples/kind/kind-expose-port.yaml, site/_guides/deploy-aws-nlb.md, site/_guides/proxy-proto.md, site/_guides/tls.md, site/docs/master/deploy-options.md, site/docs/v1.1.0/deploy-options.md, site/getting-started.md
Fixes #2109 by updating docs for the following sections:
- Getting started guides
- TLS Configuration
- Deployment Guides
- AWS NLB Guides
=> site: Update docs

internal/contour/route.go
=> internal/contour: use internal RouteConfiguration helper

site/_resources/envoy.md
Fixes #2165
Add missing Envoy/Contour entry for Contour 1.1.
=> site/resources: update Envoy support matrix for Contour 1.1

Dockerfile
=> Dockerfile: update Go to 1.13.7

design/envoy-shutdown.md
Updates #145 by adding a design doc to handle Envoy rollout across a cluster
=> design: Design doc for Envoy Shutdown logic 

site/_data/master-toc.yml, site/_data/v1-1-0-toc.yml
Fixes: #2168
Removed additional line in TOC data file
=> Resolve FAQ listed twice in v1.1.0 docs

site/_contributors/04-michael-michael.md
Simple rename of the role M2 has.
Signed-off-by: Jonas Rosland <jrosland@vmware.com>
=> Change M2 from project to product mgr

site/docs/master/httpproxy.md
Fixes #2147 by adding docs for TCPHealthCheckPolicy
=> site: Add docs for TCPHealthCheck policy

examples/contour/01-crds.yaml, examples/render/contour.yaml, hack/travis/check-uncommitted-codegen.sh, site/docs/master/api-reference.html, site/docs/v1.1.0/api-reference.html
Followup to #2202 by regenerating the example CRDs.
Fixes #2217 
=> examples: Regenerate CRD examples

examples/render/kustomization.yaml
This will add a kustomization.yaml file, to let users use kustomize.
Signed-off-by: Alex Szakaly <alex.szakaly@gmail.com>
=> Add kustomization.yaml

internal/metrics/metrics.go
Updates #2235
Remove the unused Metrics.ResourceEventHandlerSummary. It wasn't used,
and wasn't capable of recording the right data anyway.
=> internal/metrics: remove unused ResourceEventHandlerSummary

site/docs/master/httpproxy.md
Fixes another HeaderPolicy -> HeadersPolicy typo.
Signed-off-by: Dominik Hannen <dhxgit@users.noreply.github.com>
=> Fix a type that was missed in #2127

Dockerfile
=> Dockerfile: update to Go 1.13.8

site/_resources/upgrading.md
Fixes #2252
Jekyll 4.0 is sentitive to janky html.
=> site: fix broken html in resources/upgrading.md

site/_config.yml, site/docs/v1.2.0/README.md, site/docs/v1.2.0/annotations.md, site/docs/v1.2.0/api-reference.html, site/docs/v1.2.0/api.md, site/docs/v1.2.0/architecture.md, site/docs/v1.2.0/configuration.md, site/docs/v1.2.0/deploy-options.md, site/docs/v1.2.0/github.md, site/docs/v1.2.0/grpc-tls-howto.md, site/docs/v1.2.0/httpproxy.md, site/docs/v1.2.0/ingressroute.md, site/docs/v1.2.0/start-contributing.md, site/docs/v1.2.0/troubleshooting.md
=> site: add docs/v1.2.0

site/_config.yml, site/_redirects, site/_resources/release-process.md
=> Update various site things for 1.2 release

apis/projectcontour/v1/httpproxy.go, examples/contour/01-crds.yaml, examples/render/contour.yaml
=> api: enforce at least one service entry per route & tcpproxy

cmd/contour/contour.go, cmd/contour/serve.go, cmd/contour/servecontext.go
I don't believe that we want to add any more levels than error, info, and debug at this point.
=> Add simple debug logging flag

examples/contour/02-rbac.yaml, examples/render/contour.yaml, internal/dag/cache.go
I missed the RBAC, more fool me.
Also, fix a small typo in one of the log lines :facepalm:
=> Update contour ClusterRole to add ServiceAPIs objects

design/ingress-status-loadbalancer.md
Updates #403
Strawman design for supporting the ingress.status.loadbalancer field.
=> design: add draft for ingress status loadbalancer support

internal/dag/builder.go
When looking up and validating TLS peer validation policy, construct
the error details in the caller. This allows better error context and
later will let us re-use this code.
=> internal/dag: clean up TLS validation errors

site/docs/master/architecture.md, site/docs/v1.2.0/architecture.md
=> Fixes Contour architecture overview docs

examples/contour/03-envoy.yaml, examples/render/contour.yaml
Updates #2232
Update to Envoy 1.13.1.
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/envoy-announce/sVqmxy0un2s/8aq430xiHAAJ
=> examples/contour: update to Envoy 1.13.1

examples/contour/03-contour.yaml, examples/contour/03-envoy.yaml, examples/render/contour.yaml
=> examples: update deployments manifests for Contour 1.2.1

site/community.md
Add a corrected community meeting link
=> Correct community meeting link

site/_resources/envoy.md
=> site/resources/envoy: add Contour 1.2.1 and Envoy 1.13.1

site/_posts/2020-03-03-hot-reload-certificates-safely-rollout-envoy-contour-1.2.md
=> site: correct Tero's GitHub profile link

site/_posts/2020-03-03-hot-reload-certificates-safely-rollout-envoy-contour-1.2.md
=> Fix link to @tssarni in contributors for v1.2 blog post

apis/projectcontour/v1/httpproxy.go, examples/contour/01-crds.yaml, examples/render/contour.yaml, site/docs/master/api-reference.html
Make sure we accurately describe the types and semantics
of the HeaderCondition fields.
=> doc: improve HeaderCondition API documentation

site/_data/master-toc.yml, site/_data/v1-0-0-toc.yml, site/_data/v1-0-1-toc.yml, site/_data/v1-1-0-toc.yml, site/_data/v1-2-0-toc.yml, site/_data/v1-2-1-toc.yml, site/_resources/philosophy.md
=> Add Contour Philosophy document

cmd/contour/serve.go
Updates #403
wasn't an unstructured.Unstructured type. This allows us to send all the
traffic through the DynamicConverter, removing the eventRecorder and
reducing the number of ResourceEventHandlers in scope inside doServe.
=> cmd/contour: connect all informers to the dynamicHandler

examples/contour/03-contour.yaml, examples/contour/03-envoy.yaml, examples/render/contour.yaml
=> Update Contour Docker image to v1.3.0.

site/_redirects
=> site: update redirect for the 1.3 release

site/_resources/envoy.md, site/_resources/upgrading.md, site/docs/master/ingressroute.md
=> site: update support docs for the 1.3.0 release

site/_resources/upgrading.md
Fixes a new nits in the upgrade guide since the v1.3.0 release. 
=> site: Fix upgrade guide for v1.3.0

internal/contour/route.go
The three levels of nested function contexts in (*routeVisitor)visit()
makes it hard to read and keep track of the right scope. Break out the
VirtualHost and SecureVirtualHost actions into helper methods so that
this code is easier to follow.
Updates: #2347
=> internal/contour: inprove routeVisitor readability

site/docs/master/httpproxy.md
Added documentation describing the external client certificate validation.
=> site: documentation for TLS client authentication

site/docs/master/annotations.md
=> site: Update annotations doc with better ingress.class information

examples/contour/02-job-certgen.yaml, examples/render/contour.yaml
Updates #2423
Updates #2395
Updates #2150
Updates #2030
=> Add explanation of certgen Job image tag usage

site/_config.yml, site/_scss/_styles.scss, site/_scss/site/utilities/_highlighter.css, site/docs/master/httpproxy.md
Enable rouge as the code higherlighter. Add CSS for the default pygments
theme, which has reasonable contrast against a grey background.
=> site: add code highlighting

site/_data/master-toc.yml, site/_guides/structured-logs.md, site/docs/master/configuration.md
Document the Contour configuration file.
This updates #2045.
=> doc: document the Contour configuration file

examples/contour/00-common.yaml, examples/contour/03-envoy.yaml, examples/render/contour.yaml
Updates #1896
This will enable further work on PodSecurityPolicy and other security mechanisms.
=> Add ServiceAccount for Envoy

site/_resources/upgrading.md
=> Update Upgrading documentation for 1.4 release

site/_resources/release-process.md
Add a couple of things I noticed doing the 1.4 release.
=> Update release notes process

internal/envoy/listener.go
=> internal/envoy: use the helper to create a ConfigSource

site/_posts/2020-04-27-client-cert-auth-ingress-improvements.md
=> Add 1.4 release blog

.travis.yml, CONTRIBUTING.md, Dockerfile, go.mod
=> build: upgrade to Go 1.14

site/_guides/proxy-proto.md, site/_posts/2020-04-27-client-cert-auth-ingress-improvements.md
Signed-off-by: savithruml <slokanath@salesforce.com>
Fixes: https://github.com/projectcontour/contour/issues/2478
=> docs: Update content for proxy protocol support on AWS ELBs

_integration/testsuite/README.md, _integration/testsuite/httpproxy/002-header-condition-match.yaml, _integration/testsuite/httpproxy/003-path-condition-match.yaml, _integration/testsuite/httpproxy/004-https-sni-enforcement.yaml, _integration/testsuite/httpproxy/005-pod-restart.yaml, _integration/testsuite/httpproxy/006-merge-slash.yaml, _integration/testsuite/httpproxy/007-client-cert-auth.yaml, _integration/testsuite/kind-expose-port.yaml, _integration/testsuite/make-kind-cluster.sh, _integration/testsuite/policies/contour-client.rego
=> update integration tests to use non-standard ports by default

site/docs/master/grpc-tls-howto.md
Update the instructions for generating and rotating xDS gRPC certificates:
- aligned with new example manifest #2553
- removed instructions to restart Envoy
=> doc: update xDS cert rotation instructions

site/_resources/upgrading.md
=> doc: document upgrading for the 1.5 release

site/docs/master/redeploy-envoy.md, site/docs/v1.2.0/redeploy-envoy.md, site/docs/v1.2.1/redeploy-envoy.md, site/docs/v1.3.0/redeploy-envoy.md, site/docs/v1.4.0/redeploy-envoy.md, site/docs/v1.5.0/redeploy-envoy.md
Fixes a typo in the redeploy-envoy.md documentation
=> Fix typo in redeploy-envoy.md

cmd/contour/serve.go, internal/k8s/informers.go
This disables IngressRoute functionality.
Updates #2572.
=> Remove informers from contour serve.

examples/contour/03-envoy.yaml, examples/render/contour.yaml
Update yaml definitions and documentation to point to the latest Envoy version.
=> Update Envoy to 1.14.2

internal/dag/cache.go
Rather than initializing the maps for the Kubernetes resource cache at
the insertion point for each type, consolidate a single initialization
helper to improve readability.
=> internal/dag: simplify the cache initialization

site/_resources/upgrading.md
=> docs: note IngressRoute removal on the upgrade documentation

site/_resources/envoy.md, site/_resources/upgrading.md, site/docs/v1.5.1/grpc-tls-howto.md
Signed-off-by: tim <tim@fewagainstmany.com>
=> (documentation) update envoy and contour references to latest

hack/release/make-release-tag.sh
Fix the make-release-tag.sh script to support both BSD and GNU variants
of sed. Support running it from a release branch, where the image version
substitution we need to make is different. Update the test for detecting
the git remote, which was backwards.
=> hack/release: fix make-release-tag.sh script

apis/projectcontour/v1/httpproxy.go, examples/contour/01-crds.yaml, examples/render/contour.yaml, site/docs/master/api-reference.html, site/docs/master/httpproxy.md
=> docs: correct errors in timeout policy section

site/_resources/envoy.md, site/_resources/kubernetes.md
=> Update supported versions for v1.6.0 release

netlify.toml, site/_resources/upgrading.md, site/docs/v1.6.0/annotations.md
Update upgrading doc.
Update quickstart redirect.
=> Add final updates for 1.6.0 release

go.mod, site/_resources/release-process.md
=> Update release process doc

examples/contour/03-envoy.yaml, examples/render/contour.yaml
=> examples/contour: upgrade Envoy to v1.14.3

site/_resources/envoy.md, site/_resources/upgrading.md
=> docs: add Contour 1.6.1 upgrade

.travis.yml
Fixes #2651
result:
https://travis-ci.com/github/u5surf/contour
Signed-off-by: yugo-horie <u5.horie@gmail.com>
=> ci: Add macOS build and check

examples/example-workload/httpproxy/04-inclusion/httpproxy-inclusion-samenamespace.yaml
=> Small fix to inclusion example

examples/contour/03-envoy.yaml, examples/render/contour.yaml
This updates #2662.
This updates #2673.
=> examples/contour: upgrade to Envoy  v1.15.0

internal/dag/builder.go, internal/dag/builder_test.go, internal/dag/status_test.go
When a service with the given name+port can't be found during a DAG
build, returns an error indicating whether the service wasn't present
or the port couldn't be found.
closes #2641
=> internal/dag: return precise error for failed service lookup

site/community.md
This will add Contour Office Hours information to the community page
=> Add Contour Office Hours to the site

internal/featuretests/timeouts_test.go
@stevesloka is this what you had in mind?
=> internal/featuretests: add tests for timeouts

cmd/contour/servecontext.go, site/docs/master/configuration.md
=> cmd/contour: improve docs for timeout settings

cmd/contour/serve.go, cmd/contour/servecontext.go, examples/contour/01-contour-config.yaml, examples/render/contour.yaml, internal/contour/listener.go, internal/contour/listener_test.go, internal/envoy/listener.go, internal/envoy/listener_test.go, internal/featuretests/timeouts_test.go, site/docs/master/configuration.md
=> rename DrainTimeout to ConnectionShutdownGracePeriod

hack/travis/install-kubernetes-toolchain.sh
=> hack: Update kind & kubectl versions for TravisCI builds

site/_resources/envoy.md, site/_resources/kubernetes.md, site/_resources/upgrading.md
- adds v1.7.0 to the compatibility matrices
- adds v1.7.0 upgrading instructions to the site
=> v1.7.0 final updates

netlify.toml
=> update netlify redirect for v1.7.0

site/guides.md
=> site: fix typo

internal/featuretests/featuretests.go
In the featuretests driver, rather than using concrete types, use
the underlying `cache.ResourceEventHandler` interface that is the real
requirement. This will allow the endpoints translator to change its type
in upcoming PRs.
This updates #2769.
=> internal/featuretests: apply resource handler interfaces

design/cors-configuration.md
Updates #437
Signed-off-by: Aritz Berasarte <raskasso@hotmail.com>
=> design: add CORS support

internal/featuretests/featuretests.go
The featuretests `check` helper is the same as the testify `NoError`
helper. Now that we have a testify dependency, we can just use that.
=> internal/featuretests: remove check helper

internal/dag/cache.go
Note that I've added it in here rather than in the annotation package
because it would be a substantial change for the package API, and
we're removing the code anyway.
Updates #2749.
=> Add deprecation warning log for contour.heptio.com annotations

site/_resources/upgrading.md
=> Update upgrade guide for 1.8 release

site/_guides/gatekeeper.md
=> site: fix link in Gatekeeper guide

hack/actions/install-kubernetes-toolchain.sh
=> testsuite: upgrade integration-tester

.github/workflows/prbuild.yaml, CONTRIBUTING.md, Dockerfile, go.mod
=> build: upgrade to go 1.15.2

site/_guides/prometheus.md
=> site: update metrics page with link to envoy docs

site/_data/main-toc.yml, site/_data/v1-8-1-toc.yml, site/_resources/deprecation-policy.md
=> docs: Add Contour deprecation policy

site/docs/main/troubleshooting.md
=> site/docs: add Envoy debug logging section to troubleshooting

CONTRIBUTING.md
Outline how import aliases should be approached when contributing to Contour. 
=> contributing: Update the contributing doc for import aliases

site/docs/main/httpproxy.md
=> docs: add CORS policy related documentation

cmd/contour/cli.go, cmd/contour/servecontext.go, hack/golangci-lint, internal/featuretests/featuretests.go
=> build: update golangci-lint to v1.31.0.

netlify.toml
=> Update quickstart redirect to v1.9.0

internal/featuretests/secrets_test.go
Fixes test TestSDSShouldNotIncrementVersionNumberForUnrelatedSecret
that was a no-op because the fields it was trying to validate were
not being compared by the equality function being used.
Closes #2782
=> internal/featuretests: fix no-op SDS test

hack/actions/install-kubernetes-toolchain.sh
=> testsuite: upgrade to integration-tester v5

site/docs/v1.0.0/httpproxy.md, site/docs/v1.0.1/httpproxy.md, site/docs/v1.2.0/httpproxy.md, site/docs/v1.2.1/httpproxy.md, site/docs/v1.3.0/httpproxy.md, site/docs/v1.4.0/httpproxy.md, site/docs/v1.5.0/httpproxy.md, site/docs/v1.5.1/httpproxy.md, site/docs/v1.6.0/httpproxy.md, site/docs/v1.6.1/httpproxy.md, site/docs/v1.7.0/httpproxy.md, site/docs/v1.8.0/httpproxy.md, site/docs/v1.8.1/httpproxy.md, site/docs/v1.8.2/httpproxy.md, site/docs/v1.9.0/httpproxy.md
=> doc: fix intra-version annotations links

internal/xds/v2/contour.go, internal/xds/v3/contour.go
=> internal/xds: improve xDS stream log message

internal/envoy/bootstrap.go, internal/envoy/v2/bootstrap_test.go
=> internal/envoy: Fix nit misspelling of SDSTLSCertificateFile const name

_integration/testsuite/httpproxy/015-http-health-checks.yaml
=> testsuite: add an integration test for health checking

site/_guides/structured-logs.md
follow-up for https://github.com/projectcontour/contour/pull/3059
=> Site: Document support for custom Envoy JSON Fields

hack/actions/install-kubernetes-toolchain.sh
Update the kustomize, kubectl, & kind versions.
=> hack: Update Kubernetes dependencies

internal/xdscache/v2/endpointstranslator.go, internal/xdscache/v2/endpointstranslator_test.go
Only updates the ClusterLoadAssignment xDS cache and notifies via the
condition variable if the contents have changed during recalculation.
Closes #3053.
=> internal/xdscache: only update ClusterLoadAssignment cache on changes

site/_resources/envoy.md, site/_resources/kubernetes.md
=> site: update compatibility matrices for 1.10

site/_resources/upgrading.md
=> site: Add upgrade guide for v1.10.0

site/_guides/xds-migration.md
=> site: Fixup some nits with working on the xds migration guide

cmd/contour/serve.go, internal/annotation/annotations.go, internal/dag/builder_test.go, internal/dag/dag.go, internal/dag/httpproxy_processor.go, internal/dag/ingress_processor.go, internal/envoy/v2/tls.go, internal/featuretests/v2/listeners_test.go, internal/xdscache/v2/listener.go, internal/xdscache/v2/listener_test.go, internal/xdscache/v2/visitor_test.go
=> internal: use string representation of TLS version

.golangci.yml, Makefile, cmd/contour/shutdownmanager_test.go, hack/license-template.txt, internal/envoy/bootstrap.go, internal/envoy/tcp_keepalive.go, internal/envoy/v3/tcp_keepalive.go, internal/envoy/v3/tls.go, internal/fixture/certificate_constants.go, internal/fixture/log.go, internal/fixture/service.go, internal/k8s/kind_test.go, internal/k8s/log.go, internal/k8s/objectmeta_test.go, internal/protobuf/helpers_test.go, pkg/config/accesslog.go, pkg/config/parameters_test.go
=> golanglint-ci: Add goheader to check for license header compliance

site/_scss/site/settings/_variables.scss
This will improve readability and remove a lot of whitespace on the site.
=> Increase the max width of the container to 1340px

Makefile
=> makefile: Remove extra codespell line

internal/envoy/v3/listener.go, internal/envoy/v3/listener_test.go
The auth integration test was finding a problem; that in v3
the HTTP router filter must be the last in the list. This was not the
case when external auth was enabled.
This commit updates the `AddFilter` logic to always move the Router
filter to the end of the filter chain, whenever any filter is added,
and updates the tests accordingly.
It is also technically possible, though a programmer error, to add
a second Router filter to the filter chain. Added a panic in this case,
as there is no way it's possible using the `AddFilter` method. This
catches a programmer error and fails fast and hard to tell that person
not to do that, and a test to lock in the behavior.
=> Fix integration test failure

netlify.toml, site/getting-started.md
Adds contour-operator to Contour's quick-start workflow and guide.
Requires: https://github.com/projectcontour/contour-operator/pull/120
=> Adds Operator Installation to Quickstart

site/docs/main/deploy-options.md
Adds Contour Operator to Contour's deployment docs page.
=> Adds Contour Operator to Deployment Docs Page

README.md
=> docs: Fix the broken link "HTTPProxy" in README.md

site/_data/main-toc.yml, site/docs/main/troubleshooting/operator.md
Adds an initial guide for troubleshooting Contour Operator.
=> Adds Operator Troubleshooting Guide

site/community.md
This will update the YouTube playlist link for recorded community meetings.
=> Update YouTube playlist link for recorded community meetings

site/_resources/release-process.md
Contour Operator follows the same release process as Contour. This PR updates the release process doc to include Contour Operator.
=> Adds Contour Operator to Release Doc

site/_guides/cert-manager.md
Updates the cert-manager guide for cert-manager v1.0 as well as other minor clean up items.
Fixes #2879
=> site/guides: Update cert-manager guide for v1.0

_integration/testsuite/httpproxy/004-https-sni-enforcement.yaml, _integration/testsuite/httpproxy/007-client-cert-auth.yaml, _integration/testsuite/httpproxy/008-tcproute-https-termination.yaml, _integration/testsuite/httpproxy/009-https-misdirected-request.yaml, _integration/testsuite/httpproxy/012-https-fallback-certificate.yaml, _integration/testsuite/httpproxy/013-backend-tls.yaml, _integration/testsuite/httpproxy/014-auth-basic-testserver.yaml, _integration/testsuite/install-fallback-certificate.sh, _integration/testsuite/make-kind-cluster.sh, site/_guides/external-authorization.md
Also bump API version on some docs pages
Fixes https://github.com/projectcontour/contour/issues/3051
=> Update cert-manager to v1.1.0 in integration

site/_resources/upgrading.md
Also removes extra `<br>`
Fixes: https://github.com/projectcontour/contour/issues/2094
=> site: Fix upgrading page table of contents

site/_resources/envoy.md
=> site: Update Envoy extensions list required by Contour

examples/contour/02-job-certgen.yaml, examples/contour/03-contour.yaml, examples/contour/03-envoy.yaml, examples/render/contour.yaml
=> [release-1.10] Update Contour Docker image to v1.10.1.

site/_resources/upgrading.md
=> site: Upgrade guide for v1.11

netlify.toml
/hold until v1.11.0 release is done.
Fixes: https://github.com/projectcontour/contour-operator/issues/134
@stevesloka @skriss let me know if the update should be accomplished in separate PRs, one for Contour and the other for the operator.
=> site: update quickstart redirect for 1.11

site/_posts/2020-12-18-contour_v1110.md
=> site: Add v1.11 blog post

netlify.toml
=> netlify.toml: remove addressed TODO

hack/site-proofing/cibuild, site/_posts/2020-12-18-contour_v1110.md
- Add user agent to htmlproofer check as Twitter rejects non-browsers and out of date browsers
- Fix latest blog post
Fixes https://github.com/projectcontour/contour/issues/3229
=> ci: Fix siteproof

site/_resources/release-process.md
This is a rough draft of revised documentation for the release process. The intent is to make it easier to execute manually and to serve as a better blueprint for automation. I specifically did a few things:
- ensure every step is included, and have bash snippets where appropriate
- separated out minor vs. patch releases so the reader doesn't need to decide if each step is needed or not.
- separate out a general overview of what needs to be done, from the actionable steps to make it happen
Please give me a 👍  or 👎  as to whether this format is an improvement over the current https://projectcontour.io/resources/release-process/, as well as any specific feedback. If folks like it, I'll bring it to completion; if not, we can try something else. …
=> site: rewrite release instructions

go.mod, go.sum
=> deps: update go-control-plane dep to v0.9.8

hack/actions/install-kubernetes-toolchain.sh
We will not have to PR contour each time integration-tester changes
Fixes https://github.com/projectcontour/contour/issues/3257
=> Always download latest integration-tester release

_integration/testsuite/httpproxy/018-external-name-service.yaml
=> _integration: add ExternalName service test

apis/projectcontour/v1/httpproxy.go, examples/contour/01-crds.yaml, examples/render/contour.yaml, site/docs/main/config/api-reference.html
Adds valid options to the godoc for LocalRateLimitPolicy's
Unit field.
=> apis/projectcontour: improve godoc

cmd/contour/serve.go, internal/dag/serviceapis_processor.go
=> internal: Add initial scaffolding for service-apis processing

netlify.toml
=> [v1.12.0] update quickstart redirects for v1.12

site/_posts/2021-02-02-contour_v1120.md
=> site: add v1.12.0 blog post

.github/workflows/prbuild.yaml, Dockerfile
See golang release notes: https://golang.org/doc/devel/release.html#go1.15
=> Bump golang to 1.15.8

site/docs/main/architecture.md
Endpoint objects for SDS -> Endpoint objects for EDS
=> Minor fix to documentation

site/_resources/deprecation-policy.md
Tickets: #2554
Signed-off-by: Amey Bhide <amey15@gmail.com>
=> Update deprecation policy for metrics

cmd/contour/bootstrap.go, internal/envoy/bootstrap.go, internal/envoy/v3/bootstrap.go, internal/envoy/v3/bootstrap_test.go, site/docs/main/configuration.md
=> Allow user to set DNS lookup family as part of bootstrap config

site/_posts/2021-02-25-contour_v1130.md
Adds a blog post for the v1.13.0 release.
=> Adds v1.13.0 Release Blog Post

internal/metrics/metrics_test.go
=> internal/metrics: fix linter error

cmd/contour/serve.go
Only adds the Gateway API DAG processor to the DAG
builder if the Gateway API resources exist in the
cluster.
Closes #3449.
=> cmd/contour: only add Gateway API processor if API exists

site/_resources/release-process.md
Adds a step to ensure contour/operator example manifests are in-sync.
=> Updates Release Docs

CONTRIBUTING.md
=> CONTRIBUTING.md: add section on testing

.github/workflows/prbuild.yaml, hack/golangci-lint
=> update golangci-lint version to v1.38

internal/dag/builder_test.go, internal/dag/gatewayapi_processor.go
This patch adds validaiton for HTTPRoute.
The requirement is same with
`ingresses.networking.k8s.io.spec.rules.host` (please refer to it by
`$ kubectl explain ingresses.networking.k8s.io.spec.rules.host`) so
this patch just adds the same code from [here](https://github.com/kubernetes/kubernetes/blob/3b5d809eedcc60e1e8fe63dace1f453d6a27b949/pkg/apis/networking/validation/validation.go#L346-L360).
Fix https://github.com/projectcontour/contour/issues/3353
/cc @stevesloka @sunjayBhatia @danehans
=> Add validation for hostnames in HTTPRoute

pkg/certs/certgen_test.go
Updates the custom lifetime cert test to use
a lifetime longer than the default, and to
verify the certs as of an hour before expiration
rather than 5 seconds, to avoid a race condition
when test execution is slow.
Closes #3516.
=> pkg/certs: fix flaky test

SITE_CONTRIBUTION.md
Fixes #3524
Signed-off-by: prondubuisi <onyemenamndu@gmail.com>
=> Fix links to makefile and gemfile for website

_integration/testsuite/gatewayapi/001-path-condition-match.yaml, internal/dag/builder_test.go, internal/dag/gatewayapi_processor.go, internal/dag/status_test.go
This patch adds "Exact" HTTPPathMatch.
/cc @stevesloka @youngnick
=> Implement "Exact" HTTPPathMatch

internal/xdscache/v3/route.go
Extracts a helper function, toEnvoyVirtualHost, to reduce
duplication across the route cache code for virtual hosts,
secure virtual hosts, and fallback virtual hosts.
Closes #3507.
=> internal/xdscache: extract route cache helper

site/_resources/release-process.md
Also release cutter should diff the example deployment to check for
significant changes
=> Release instructions: Add notes about running through upgrade

site/_resources/philosophy.md, site/docs/main/config/ingress.md, site/docs/main/config/tls-delegation.md
Details which features we support, caveats, gotchas
Fixes: https://github.com/projectcontour/contour/issues/3546
Fixes: https://github.com/projectcontour/contour/issues/3469
Updates: https://github.com/projectcontour/contour/issues/3544
=> Ingress: Add detailed documentation

examples/contour/02-job-certgen.yaml, examples/contour/03-contour.yaml, examples/contour/03-envoy.yaml, examples/render/contour.yaml
=> Update Contour image to v1.14.1 & Envoy to v1.17.2

Makefile, examples/contour/03-envoy.yaml, examples/render/contour.yaml
=> Bump Envoy dep to v1.18.2 to resolve Envoy CVEs in prior versions.

CONTRIBUTING.md
=> Add docs for how to test Contour<>Envoy locally in a kind cluster.

site/docs/main/config/rate-limiting.md
Updates the rate-limiting.md page to include detailed documentation
on each rate limiting descriptor entry type.
Closes #3604.
=> site/docs: add rate limit descriptor entry docs

netlify.toml
=> netlify.toml: update redirects for v1.15.0

test/e2e/httpproxy/008_tcproute_https_termination_test.go, test/e2e/httpproxy/009_https_misdirected_request_test.go, test/e2e/httpproxy/010_include_prefix_condition_test.go, test/e2e/httpproxy/012_https_fallback_certificate_test.go, test/e2e/httpproxy/httpproxy_test.go
=> test/e2e: add HTTPProxy tests 008,009,010,012

test/e2e/framework.go
Set a higher default QPS & Burst for the k8s client when talking to the API server.
Should help to resolve errors:
```
I0506 20:31:00.425549   26017 request.go:668] Waited for 1.033231194s due to client-side throttling, not priority and fairness, request: GET:https://127.0.0.1:34087/apis/policy/v1beta1?timeout=32s
```
=> test/e2e: Set default QPS/Burst for client

site/_guides/cert-manager.md, site/_resources/philosophy.md, site/docs/main/config/fundamentals.md, site/docs/main/config/ingress.md, site/docs/main/config/tls-delegation.md, site/docs/main/config/virtual-hosts.md, site/examples/httpbin.yaml, site/examples/kuard.yaml
- Clarifies some docs that still need to mention it
- Updates examples to v1 Ingress
Updates: #3628
=> site: Remove usage of v1beta1

internal/xdscache/v3/cluster_test.go, internal/xdscache/v3/listener_test.go, internal/xdscache/v3/route_test.go, internal/xdscache/v3/secret_test.go, internal/xdscache/v3/server_test.go
Removes Ingress v1beta1 from tests in internal/xdscache/v3 package
Updates: #3628
=> internal/xdscache/v3: Remove Ingress v1beta1

test/e2e/fixtures.go, test/e2e/framework.go, test/e2e/httpproxy/014_external_auth_test.go, test/e2e/httpproxy/015_http_health_checks_test.go, test/e2e/httpproxy/httpproxy_test.go
=> test/e2e: add HTTPProxy tests 014, 015

Makefile, go.mod, go.sum, hack/actions/install-kubernetes-toolchain.sh
Adds ability to randomize, set thresholds, and will let us do
parallel test runs once we refactor the e2e suites a bit
=> Use ginkgo CLI for e2e tests

internal/dag/status_test.go
Following up to #3636, refactors the status tests to allow for the the FullName
to be validated along with the Conditions so that if there are two different
objects, each will have a set of conditions to be asserted against.
=> internal/status: Refactor status tests to allow for FullName to be validated

test/e2e/httpproxy/005_pod_restart_test.go
The pod restart test occasionally times out waiting for
the original pod to delete. This PR gives it 2m to delete
instead of the default 1m.
Updates #3621.
=> test/e2e: pod restart test: allow 2m for pod deletion

Makefile, examples/contour/03-envoy.yaml, examples/render/contour.yaml, site/_resources/compatibility-matrix.md
=> update Envoy to v1.18.3

test/e2e/httpproxy/001_required_field_validation_test.go, test/e2e/httpproxy/011_retry_policy_validation_test.go, test/e2e/httpproxy/httpproxy_test.go
=> test/e2e: add HTTPProxy tests 001, 011

internal/dag/gatewayapi_processor.go, internal/dag/gatewayapi_processor_test.go
Adds missing tests for gatewayMatches method in GatewayProcessor
to validate the route gateway allow from types.
=> internal/dag: Add tests for gatewayMatches

internal/status/conditions.go
=> internal/status: set a Controller on route status updates

test/e2e/framework.go, test/e2e/gateway/008_tlsroute_test.go, test/e2e/gateway/gateway_test.go
=> test/e2e: add gateway/008_tlsroute test

CONTRIBUTING.md
=> update CONTRIBUTING.md for new E2E tests

Makefile
site examples now moved to site/content
=> Fix yamllint for new site format

hack/actions/check-uncommitted-codegen.sh
Checks paths from new site format
=> Fix check-uncommitted-codegen.sh for new site format

internal/dag/builder_test.go, internal/dag/gatewayapi_processor.go, test/e2e/gateway/009_tls_wildcard_host_test.go, test/e2e/gateway/gateway_test.go
=> gateway wildcard hostname e2e test

hack/release/prepare-release.go
=> hack/release: update prepare-release.go for Hugo

Makefile, hack/generate-metrics-doc.go, site/content/guides/metrics/contour_build_info.md, site/content/guides/metrics/contour_cachehandler_onupdate_duration_seconds.md, site/content/guides/metrics/contour_dagrebuild_timestamp.md, site/content/guides/metrics/contour_dagrebuild_total.md, site/content/guides/metrics/contour_eventhandler_operation_total.md, site/content/guides/metrics/contour_httpproxy.md, site/content/guides/metrics/contour_httpproxy_invalid.md, site/content/guides/metrics/contour_httpproxy_orphaned.md, site/content/guides/metrics/contour_httpproxy_root.md, site/content/guides/metrics/contour_httpproxy_valid.md, site/content/guides/metrics/table.md, site/content/guides/prometheus.md
Merges metrics into a single table instead of separate tables
Fixes: #3717
=> Fixup metric doc generation for hugo site

test/e2e/httpproxy/007_client_cert_auth_test.go
Adds retries to code that makes HTTPS requests and expects
an error to avoid flakes.
Fixes #3730.
=> test/e2e: add retries to avoid flake

site/content/examples/httpbin.yaml
=> fixup site example for ingress/v1

.github/workflows/prbuild.yaml, hack/actions/install-kubernetes-toolchain.sh
https://github.com/kubernetes-sigs/kind/releases/tag/v0.11.1
=> Bump kind cli and images

site/themes/contour/layouts/partials/docs-right-bar.html
=> site: Fixes the edit button on the docs site

site/content/docs/v1.10.0/architecture.md, site/content/docs/v1.10.1/architecture.md, site/content/docs/v1.11.0/architecture.md, site/content/docs/v1.12.0/architecture.md, site/content/docs/v1.13.0/architecture.md, site/content/docs/v1.13.1/architecture.md, site/content/docs/v1.14.0/architecture.md, site/content/docs/v1.14.1/architecture.md, site/content/docs/v1.15.0/architecture.md, site/content/docs/v1.2.1/architecture.md, site/content/docs/v1.3.0/architecture.md, site/content/docs/v1.4.0/architecture.md, site/content/docs/v1.5.0/architecture.md, site/content/docs/v1.5.1/architecture.md, site/content/docs/v1.6.0/architecture.md, site/content/docs/v1.6.1/architecture.md, site/content/docs/v1.7.0/architecture.md, site/content/docs/v1.8.0/architecture.md, site/content/docs/v1.8.1/architecture.md, site/content/docs/v1.8.2/architecture.md, site/content/docs/v1.9.0/architecture.md
=> site: Fix architecture page with extra center tags after upgrade to Hugo

site/content/docs/v1.10.0/config/fundamentals.md, site/content/docs/v1.10.1/config/fundamentals.md, site/content/docs/v1.11.0/config/fundamentals.md, site/content/docs/v1.12.0/config/fundamentals.md, site/content/docs/v1.13.0/config/fundamentals.md, site/content/docs/v1.13.1/config/fundamentals.md, site/content/docs/v1.14.0/config/fundamentals.md, site/content/docs/v1.14.1/config/fundamentals.md, site/content/docs/v1.15.0/config/fundamentals.md
=> site: Fix fundamentals pages for extra markdown & bad link

site/content/docs/main/config/inclusion-delegation.md, site/content/docs/v1.10.0/config/inclusion-delegation.md, site/content/docs/v1.10.1/config/inclusion-delegation.md, site/content/docs/v1.11.0/config/inclusion-delegation.md, site/content/docs/v1.12.0/config/inclusion-delegation.md, site/content/docs/v1.13.0/config/inclusion-delegation.md, site/content/docs/v1.13.1/config/inclusion-delegation.md, site/content/docs/v1.14.0/config/inclusion-delegation.md, site/content/docs/v1.14.1/config/inclusion-delegation.md, site/content/docs/v1.15.0/config/inclusion-delegation.md, site/content/docs/v1.15.1/config/inclusion-delegation.md, site/content/docs/v1.16.0/config/inclusion-delegation.md
=> site: Fix site inclusion-delegation links for Hugo site move

.github/workflows/prbuild.yaml
Use exact image digests, as we just changed to in the operator
=> Use exact kind images to avoid issues

test/e2e/upgrade/upgrade_test.go
Will enable us to run upgrade against release branches or in situations
where we keep the certgen job name static
=> test/e2e/upgrade: Delete certgen job if exists with the same name

test/e2e/upgrade/upgrade_test.go
Will enable us to run upgrade against release branches or in situations
where we keep the certgen job name static
=> [release-1.16 cherry-pick] test/e2e/upgrade: Delete certgen job if exists with the same name

site/content/docs/main/config/client-authorization.md, site/content/docs/v1.10.0/config/client-authorization.md, site/content/docs/v1.10.1/config/client-authorization.md, site/content/docs/v1.11.0/config/client-authorization.md, site/content/docs/v1.12.0/config/client-authorization.md, site/content/docs/v1.13.0/config/client-authorization.md, site/content/docs/v1.13.1/config/client-authorization.md, site/content/docs/v1.14.0/config/client-authorization.md, site/content/docs/v1.14.1/config/client-authorization.md, site/content/docs/v1.15.0/config/client-authorization.md, site/content/docs/v1.15.1/config/client-authorization.md, site/content/docs/v1.16.0/config/client-authorization.md
=> site: Fix client authorization docs with 404 links after move to Hugo

site/content/docs/v1.10.0/config/annotations.md, site/content/docs/v1.10.1/config/annotations.md, site/content/docs/v1.11.0/config/annotations.md, site/content/docs/v1.12.0/config/annotations.md, site/content/docs/v1.13.0/config/annotations.md, site/content/docs/v1.13.1/config/annotations.md, site/content/docs/v1.14.0/config/annotations.md, site/content/docs/v1.14.1/config/annotations.md, site/content/docs/v1.15.0/config/annotations.md
=> site: Fix link to HTTPProxy fundamentals for Annotations page

site/content/docs/main/config/tls-termination.md, site/content/docs/v1.10.0/config/tls-termination.md, site/content/docs/v1.10.1/config/tls-termination.md, site/content/docs/v1.11.0/config/tls-termination.md, site/content/docs/v1.12.0/config/tls-termination.md, site/content/docs/v1.13.0/config/tls-termination.md, site/content/docs/v1.13.1/config/tls-termination.md, site/content/docs/v1.14.0/config/tls-termination.md, site/content/docs/v1.14.1/config/tls-termination.md, site/content/docs/v1.15.0/config/tls-termination.md, site/content/docs/v1.15.1/config/tls-termination.md, site/content/docs/v1.16.0/config/tls-termination.md
=> site: Fix links in tls-termination docs for change to Hugo

site/content/docs/main/configuration.md, site/content/docs/v1.0.0/configuration.md, site/content/docs/v1.0.1/configuration.md, site/content/docs/v1.1.0/configuration.md, site/content/docs/v1.10.0/configuration.md, site/content/docs/v1.10.1/configuration.md, site/content/docs/v1.11.0/configuration.md, site/content/docs/v1.12.0/configuration.md, site/content/docs/v1.13.0/configuration.md, site/content/docs/v1.13.1/configuration.md, site/content/docs/v1.14.0/configuration.md, site/content/docs/v1.14.1/configuration.md, site/content/docs/v1.15.0/configuration.md, site/content/docs/v1.15.1/configuration.md, site/content/docs/v1.16.0/configuration.md, site/content/docs/v1.2.0/configuration.md, site/content/docs/v1.2.1/configuration.md, site/content/docs/v1.3.0/configuration.md, site/content/docs/v1.4.0/configuration.md, site/content/docs/v1.5.0/configuration.md, site/content/docs/v1.5.1/configuration.md, site/content/docs/v1.6.0/configuration.md, site/content/docs/v1.6.1/configuration.md, site/content/docs/v1.7.0/configuration.md, site/content/docs/v1.8.0/configuration.md, site/content/docs/v1.8.1/configuration.md, site/content/docs/v1.8.2/configuration.md, site/content/docs/v1.9.0/configuration.md
=> site: Fixup configuration page for move to Hugo

site/content/docs/main/deploy-options.md, site/content/docs/v1.0.0/deploy-options.md, site/content/docs/v1.0.1/deploy-options.md, site/content/docs/v1.1.0/deploy-options.md, site/content/docs/v1.10.0/deploy-options.md, site/content/docs/v1.10.1/deploy-options.md, site/content/docs/v1.11.0/deploy-options.md, site/content/docs/v1.12.0/deploy-options.md, site/content/docs/v1.13.0/deploy-options.md, site/content/docs/v1.13.1/deploy-options.md, site/content/docs/v1.14.0/deploy-options.md, site/content/docs/v1.14.1/deploy-options.md, site/content/docs/v1.15.0/deploy-options.md, site/content/docs/v1.15.1/deploy-options.md, site/content/docs/v1.16.0/deploy-options.md, site/content/docs/v1.2.0/deploy-options.md, site/content/docs/v1.2.1/deploy-options.md, site/content/docs/v1.3.0/deploy-options.md, site/content/docs/v1.4.0/deploy-options.md, site/content/docs/v1.5.0/deploy-options.md, site/content/docs/v1.5.1/deploy-options.md, site/content/docs/v1.6.0/deploy-options.md, site/content/docs/v1.6.1/deploy-options.md, site/content/docs/v1.7.0/deploy-options.md, site/content/docs/v1.8.0/deploy-options.md, site/content/docs/v1.8.1/deploy-options.md, site/content/docs/v1.8.2/deploy-options.md, site/content/docs/v1.9.0/deploy-options.md
=> site: Fix links on deploy-options pages

site/content/resources/upgrading.md
I'd like to revamp this guide, it's sort of a mess, but for now, this makes the guide work with all the links properly. 
Updates #3712
=> site: Fixup the upgrade guide

SITE_CONTRIBUTION.md, site/config.yaml, site/content/getting-started/_index.md, site/content/guides/fips.md, site/content/guides/global-rate-limiting.md, site/themes/contour/layouts/partials/docs-right-bar.html
Fixes up the ratelimiting guide's links along with some other
links in the SITE_CONTRIBUTION, and getting started guide.
Upates #3712
=> site: Fixup RateLimiting Guide & some other links

Makefile
This is a WIP PR to update the local dev options. I'm aiming to have
a make target that will:
- spin you up a kind cluster
- set you up with Envoys running in there, trying to connect to a Contour
running on the host.
- with the SSL pulled out for you.
First up though, is a Makefile refactor to make it a bit more composable.
This is a WIP PR because it's quicker to use Actions for testing than my
local machine. :)
This commit splits up many of the make targets into sub-steps,
that we can reuse, instead of having the same script called in
multiple places.
I've also removed the old local-dev shortcuts, I think we can do
better.
The intent here is to make it so that we can use the pieces
more easily, eventually aiming at making local dev and bug
reproduction quicker and easier. …
=> Refactor Makefile and update local dev options

site/content/docs/main/troubleshooting/contour-graph.md, site/content/docs/v1.0.0/troubleshooting.md, site/content/docs/v1.0.1/troubleshooting.md, site/content/docs/v1.1.0/troubleshooting.md, site/content/docs/v1.10.0/troubleshooting/contour-graph.md, site/content/docs/v1.10.1/troubleshooting/contour-graph.md, site/content/docs/v1.11.0/troubleshooting/contour-graph.md, site/content/docs/v1.12.0/troubleshooting/contour-graph.md, site/content/docs/v1.13.0/troubleshooting/contour-graph.md, site/content/docs/v1.13.1/troubleshooting/contour-graph.md, site/content/docs/v1.14.0/troubleshooting/contour-graph.md, site/content/docs/v1.14.1/troubleshooting/contour-graph.md, site/content/docs/v1.15.0/troubleshooting/contour-graph.md, site/content/docs/v1.15.1/troubleshooting/contour-graph.md, site/content/docs/v1.16.0/troubleshooting/contour-graph.md, site/content/docs/v1.2.0/troubleshooting.md, site/content/docs/v1.2.1/troubleshooting.md, site/content/docs/v1.3.0/troubleshooting.md, site/content/docs/v1.4.0/troubleshooting.md, site/content/docs/v1.5.0/troubleshooting.md, site/content/docs/v1.5.1/troubleshooting.md, site/content/docs/v1.6.0/troubleshooting.md, site/content/docs/v1.6.1/troubleshooting.md, site/content/docs/v1.7.0/troubleshooting.md, site/content/docs/v1.8.0/troubleshooting.md, site/content/docs/v1.8.1/troubleshooting.md, site/content/docs/v1.8.2/troubleshooting.md, site/content/docs/v1.9.0/troubleshooting.md
=> Fix references to kuard-dag.png

.github/workflows/prbuild.yaml, Makefile
See release notes: https://golang.org/doc/devel/release#go1.16.minor
=> Bump golang to 1.16.5

.github/workflows/prbuild.yaml, hack/actions/install-kubernetes-toolchain.sh, internal/controller/gatewayclass.go, internal/controller/gatewayclass_test.go, internal/controller/suite_test.go
Adds a test suite to test controller-runtime controllers, starting with the gatewayclass controller.
Fixes https://github.com/projectcontour/contour/issues/3705
=> Adds Controller Runtime Test Suite

internal/dag/builder_test.go
=> internal/dag: fix test case name

test/e2e/gateway/008_tlsroute_test.go
Rather than use SecureRequestUntil, use the require.Never method to make
sure the request never works
=> test/e2e/gateway: Change assertion in tls terminate test

test/e2e/httpproxy/backend_tls_test.go, test/e2e/httpproxy/httpproxy_test.go, test/e2e/ingress/backend_tls_test.go, test/e2e/ingress/ingress_test.go
Ingress and HTTPProxy backend TLS tests
Fixes: #3729
=> Add backend tls e2e tests

.github/workflows/build_main.yaml, .github/workflows/build_tag.yaml, .github/workflows/prbuild.yaml
=> notify slack channel if failures on main builds

Makefile, examples/contour/03-envoy.yaml, examples/render/contour-gateway.yaml, examples/render/contour.yaml, site/content/resources/compatibility-matrix.md
=> update Envoy to 1.19.0

.github/workflows/build_main.yaml
=> fix yaml syntax for main job build

netlify.toml
=> update netlify redirects for 1.17.0 release

CONTRIBUTING.md
=> Add contributing guidelines for how the project board is used

Makefile
Should be considered when checking coverage
=> Add pkg to coverage check

internal/controller/gateway.go, internal/controller/gatewayclass.go
Switches from using EnqueueRequestsFromMapFunc to EnqueueRequestForObject
along with a filtering predicate to control which events trigger reconcile
requests. This is a cleanup only, functionality should not change.
IMHO this is more idiomatic/logical for what we're doing here and is easier to read.
=> internal/controller: switch to using event predicates for filtering

internal/controller/gateway.go, internal/controller/gatewayclass.go
Fixes a bug where when Gateways/GatewayClasses were deleted, they
were not being removed from the DAG.
Updates #3905.
=> internal/controller: fix Gateway/GatewayClass deletion bug

site/content/docs/main/config/access-logging.md
=> site: update access logging links

site/content/posts/2019-07-11-kindly-running-contour.md, site/content/posts/2019-07-23-contour-v014.md, site/content/posts/2020-11-06-contour_v1100.md
Updated to fix broken image links:
https://projectcontour.io/contour_v1100/
https://projectcontour.io/contour-v014/
=> Blog updates - fix 2 blog posts for broken image links

site/content/community/_index.html, site/content/resources/_index.html, site/themes/contour/layouts/partials/cloud-native.html, site/themes/contour/layouts/partials/header.html, site/themes/contour/layouts/partials/homepage-grid.html, site/themes/contour/layouts/partials/pagination.html, site/themes/contour/layouts/partials/team.html, site/themes/contour/layouts/partials/use-cases.html
This pull request adds alt attributes to images and title attributes to iframes in the Contour site. The pull request updates #3835
=> Updates Accessibility Assessment Issue #3835

internal/envoy/v3/listener.go, internal/envoy/v3/listener_test.go
Fixes a bug where when a TCPProxy had more than one
service defined, any service with a zero weight was
updated to have a weight of 1. The correct behavior
is that if all service have no weights, then they
should be evenly weighted, but if some have non-zero
weights and others have zero weights, they stay as-is.
Notes for reviewers:
- The desired behavior that I describe in the commit message is not explicitly documented anywhere for TCPProxy, however it is for HTTPProxy (and my assumption is that the behavior should be the same between them): https://projectcontour.io/docs/v1.18.0/config/request-routing/#upstream-weighting
- This came up while working on supporting weighted forward to's for TLSRoute (#3440).
=> internal/envoy: fix TCPProxy weights bug

cmd/contour/serve.go, cmd/contour/serve_test.go, internal/contour/metrics_test.go, internal/dag/builder.go, internal/dag/builder_test.go, internal/dag/cache.go, internal/dag/cache_test.go, internal/dag/gatewayapi_processor.go, internal/dag/gatewayapi_processor_test.go, internal/dag/status_test.go, internal/featuretests/v3/featuretests.go, internal/k8s/objectmeta.go, pkg/config/parameters.go, pkg/config/parameters_test.go, test/e2e/gateway/gateway_test.go
=> Deprecate gateway name/namespace from config file + internal packages

site/content/docs/main/start-contributing.md
Signed-off-by: Gary Tai <gary.c.tai@gmail.com>
=> Issue 3820 - update content

examples/contour/01-contour-config.yaml, examples/render/contour-gateway.yaml, examples/render/contour.yaml, hack/generate-gateway-deployment.sh, site/content/docs/main/configuration.md
We removed the Gateway name/ns fields
=> Update gateway example manifest

internal/dag/builder_test.go
Adds test coverage for the matching of TLSRoutes with Gateways.
Updates #3440.
For reviewers: I replaced some of the existing test cases that covered some of this functionality just because it was easier to start fresh and build out the matrix. I did not cover every possible permutation of Gateway + TLSRoute binding settings as the matrix is pretty big, but this should cover each setting individually.
The diff is not very useful, here's the section I added: https://github.com/projectcontour/contour/blob/e9d26ee418e14e410e3010d2c4771554b7c62a6a/internal/dag/builder_test.go#L1169-L1605
=> internal/dag: improve TLSRoute selection test coverage

site/themes/contour/assets/scss/_variables.scss
Updates #3835 
Signed-off-by: johnnycase <johneverettcase@gmail.com>
Changing the color for grey and blue in the variables so the contrast meets accessibility standards.
=> Contrast change - accessibility

Makefile, examples/contour/03-envoy.yaml, examples/render/contour-gateway.yaml, examples/render/contour.yaml
=> (release-1.18) update Envoy to v1.19.1

.github/workflows/prbuild.yaml, hack/actions/install-kubernetes-toolchain.sh
Using just a tag, kind cluster does not start up properly
=> [Release 1.14] Use exact kind node image

_integration/testsuite/install-contour-working.sh
Updates the example manifests to use the "working"
image tag when running integration tests, so the
locally built image is used rather than a versioned
image from the registry.
=> (release-1.14) CI: use locally built image for integration tests

Makefile, examples/contour/03-envoy.yaml, examples/render/contour-gateway.yaml, examples/render/contour.yaml
=> (release-1.17) update Envoy to v1.18.4

cmd/contour/serve.go, internal/controller/gateway.go, internal/controller/gatewayclass.go
Triggers reconciles of all GatewayClasses and
Gateways when a Contour pod is elected leader,
to ensure that their statuses are up-to-date.
=> internal/controller: trigger reconciles when elected leader

.github/workflows/build_main.yaml, .github/workflows/build_tag.yaml, .github/workflows/prbuild.yaml, CONTRIBUTING.md, Makefile, examples/contour/02-job-certgen.yaml, examples/contour/03-contour.yaml, examples/contour/03-envoy.yaml, examples/render/contour-gateway.yaml, examples/render/contour.yaml, hack/release/make-release-tag.sh, site/content/docs/main/redeploy-envoy.md, site/content/examples/authdemo/02-certsjob.yaml, test/scripts/install-contour-working.sh
=> use GHCR image by default

examples/example-workload/httpproxy/03-routes/httpproxy-sticky-sessions.yaml
without this line you are getting an error from the api.
=> added missing line "loadBalancerPolicy:"

design/changelog.md
=> Add changelog design proposal

site/content/docs/main/config/fundamentals.md
Documentation changes related to #3824.
=> doc: program 502/503 routes for misconfigured services and includes

Makefile
Removes unused certgen targets from the Makefile
which are no longer used.
Fixes #3736
=> makefile: Remove certgen targets

test/e2e/httpproxy/external_name_test.go
Checks the HTTPProxy for the expected invalid
condition rather than polling a full minute
and asserting that it never becomes valid.
=> test/e2e: speed up HTTPProxy external name test

internal/dag/accessors.go
Removes code that walks the DAG looking for
a matching existing Service when adding a
new Service. This code is very inefficient
when the DAG is large and creates a
performance bottleneck. Some extra memory
may end up being used if duplicate Services
are created, but it's unlikely to be a
material issue in practice.
Closes #4058.
=> internal/dag: don't walk DAG to look for service

internal/dag/accessors.go
Removes code that walks the DAG looking for
a matching existing Service when adding a
new Service. This code is very inefficient
when the DAG is large and creates a
performance bottleneck. Some extra memory
may end up being used if duplicate Services
are created, but it's unlikely to be a
material issue in practice.
Closes #4058.
=> [release-1.18] internal/dag: don't walk DAG to look for service (#4061)

Makefile, go.mod, go.sum, hack/actions/install-kubernetes-toolchain.sh
ginkgo v2's new gmeasure package is useful for new bench/scale testing
suite
=> Use ginkgo v2 and update gomega

site/content/posts/2020-10-07-contour_v190.md
Signed-off-by: OrlinVasilev <ovasilev@vmware.com>
=> Fix figure and youtube link in old post for 1.9.0

examples/gateway/kuard/kuard.yaml, test/scripts/install-contour-working.sh
Useful for local dev and manual testing
=> Fix examples and install-contour-working script

pkg/config/parameters.go
=> fixup nit linting errors

.github/workflows/prbuild.yaml, Makefile
See release notes: https://golang.org/doc/devel/release#go1.17.minor
=> Bump golang to 1.17.3

changelogs/CHANGELOG-v1.20.0-beta.1.md
=> v1.20.0-beta.1 changelog

test/e2e/incluster/rbac_test.go
=> test/e2e: add retry for HTTPProxy update

.github/workflows/prbuild.yaml, Makefile, changelogs/unreleased/4232-skriss-small.md
=> update Go version to 1.17.5

test/e2e/incluster/leaderelection_test.go
To mitigate flakes like:
https://github.com/projectcontour/contour/runs/4525125381?check_suite_focus=true
=> test/e2e/incluster: Retry get events in leaderelection test

.github/workflows/build_daily.yaml
Also adds support for running it manually.
=> update daily E2E run for Kubernetes 1.23

examples/deployment/03-envoy-deployment.yaml, examples/render/contour-deployment.yaml, hack/release/make-release-tag.sh
- Bumps Envoy to v1.21.0
- Adds Envoy deployment files to the release scripts
cc @OrlinVasilev
=> fix envoy deployment release stuff

examples/deployment/03-envoy-deployment.yaml, examples/render/contour-deployment.yaml, hack/release/make-release-tag.sh
Cherry-pick of #4307 onto release-1.20 branch
=> [release-1.20 branch] fix envoy deployment release

site/content/docs/main/_index.md, site/content/docs/v1.20.0/_index.md, site/content/resources/philosophy.md
Minor edits to bring the initial docs
pages that would be visited by a user
up to date.
=> minor docs edits

site/data/github-labels.yaml
Signed-off-by: Sunjay Bhatia <sunjayb@vmware.com>
=> Add deprecation PR label

site/content/community/_index.html
Signed-off-by: OrlinVasilev <ovasilev@vmware.com>
=> Combine office hours and community meetings in one

SITE_CONTRIBUTION.md, site/content/docs/main/start-contributing.md, site/content/resources/faq.md, site/content/resources/how-we-work.md, site/content/resources/philosophy.md, site/content/resources/security-threat-model.md, site/content/resources/support.md, site/themes/contour/layouts/partials/team.html
First PR!
Edit review of site, fixes typos, links and other minor display issues. 
Fixes #4383
=> Fix typos and links in docs

test/scripts/run-gateway-conformance.sh
Sets the provisioner's --contour-image flag
when running Gateway API conformance, to use
the image built from the current CI run for
the provisioned Contour instances.
=> CI: set --contour-image when running Gateway API conformance

internal/provisioner/controller/gateway.go
Some standardization and simplification
of logging in the provisioner's Gateway
controller.
=> internal/provisioner: clean up controller logging

site/content/docs/main/config/ingress.md, test/e2e/httpproxy/fqdn_test.go, test/e2e/httpproxy/httpproxy_test.go
=> Add test and documentation to show precise hostnames override wildcards

cmd/contour/servecontext.go, internal/contourconfig/contourconfiguration.go
Little refactor for cmd/contour and internal/contourconfig
=> cmd/contour & internal/contourconfig:  little refactor

cmd/contour/gatewayprovisioner.go, examples/contour/02-job-certgen.yaml, examples/contour/03-contour.yaml, examples/contour/03-envoy.yaml, examples/deployment/03-envoy-deployment.yaml, examples/gateway-provisioner/03-gateway-provisioner.yaml, examples/render/contour-deployment.yaml, examples/render/contour-gateway-provisioner.yaml, examples/render/contour-gateway.yaml, examples/render/contour.yaml
Keeping as a PR for now to save the work, will push tag when PR is merged
=> Image tag changes for v1.21.0-rc.1

.github/workflows/prbuild.yaml
Fixes https://github.com/projectcontour/contour/actions/runs/2240180554
=> CI: Use specific prefix for image file name to find sha/tag

.github/workflows/build_daily.yaml, .github/workflows/label_check.yaml, .github/workflows/prbuild.yaml, Makefile, changelogs/unreleased/4509-sunjayBhatia-small.md
See release notes: https://go.dev/doc/devel/release#go1.18.minor
=> Bump Go to 1.18.1

netlify.toml, site/content/getting-started/_index.md, site/content/guides/gateway-api.md
=> fix gateway provisioner manifest links

site/content/community/_index.html, site/themes/contour/layouts/partials/footer.html
Community on Slack is 1000+ now and the H in GitHub was not capitalized.
=> Update Community Page and Footer

hack/kind-dev-cluster.sh, internal/provisioner/objects/service/service.go
=> internal/provisioner: Refactor for objects/service

test/e2e/incluster/incluster_test.go
This works since we set up Envoy to listen on ipv6 with ipv4
compatibility and we set up Contour to listen via golang net.Listen with
the "tcp" network, which when using an ipv6 address, golang
automatically sets ipv6/ipv4 compatible socket options.
This configuration can be an option we advertise to users who want a configuration
they can use across ipv4, dual-stack, and/or ipv6 clusters.
=> test/e2e/incluster: Contour/Envoy listening on ipv6 in an ipv4 cluster

changelogs/unreleased/4588-skriss-minor.md, internal/dag/builder_test.go, internal/dag/dag.go, internal/dag/gatewayapi_processor.go, internal/dag/status_test.go, internal/envoy/v3/route.go, internal/envoy/v3/route_test.go, internal/gatewayapi/helpers.go, internal/sorter/sorter.go, internal/sorter/sorter_test.go, internal/status/routeconditions.go, test/e2e/gateway/gateway_test.go, test/e2e/gateway/query_param_match_test.go
=> Gateway API: implement HTTP query param matching

site/themes/contour/layouts/partials/team.html
Add correct contributing documentation document link on website
=> Correct contributing documentation link on website

Makefile, examples/gateway/00-crds.yaml, examples/render/contour-gateway-provisioner.yaml, examples/render/contour-gateway.yaml, go.mod, go.sum
=> Update Gateway API to v0.5.0-rc2

changelogs/unreleased/4617-skriss-major.md, examples/gateway/00-crds.yaml, examples/gateway/01-admission_webhook.yaml, examples/render/contour-gateway-provisioner.yaml, examples/render/contour-gateway.yaml, go.mod, go.sum, site/content/resources/compatibility-matrix.md, versions.yaml
=> update Gateway API to v0.5.0

changelogs/unreleased/4635-gary-tai-docs.md, site/themes/contour/layouts/index.html
Remove the grey banner section from the main page.
Signed-off-by: Gary Tai <gary.c.tai@gmail.com>
Closes https://github.com/projectcontour/contour/issues/4320
=> Issue 4320 - Remove grey banner from main page

netlify.toml
=> update netlify redirects for v1.22.0

.github/workflows/prbuild.yaml, go.mod, go.sum
For conformance fixes, until 0.5.1 is released
=> Bump gateway-api version to release-0.5 branch

examples/gateway/01-admission_webhook.yaml, examples/render/contour-gateway-provisioner.yaml, examples/render/contour-gateway.yaml
=> update Gateway API webhook manifest

apis/projectcontour/v1alpha1/register.go, changelogs/unreleased/4700-izturn-small.md
add gvr definition for ContourDeployments
=> apis/projectcontour: add gvr for contourdeployments

test/e2e/httpproxy/grpc_test.go
Updates: https://github.com/projectcontour/contour/issues/4707
=> Add flake attempts for grpc test

Makefile, examples/gateway/00-namespace.yaml, examples/gateway/01-admission_webhook.yaml, examples/gateway/02-certificate_config.yaml, examples/render/contour-gateway-provisioner.yaml, examples/render/contour-gateway.yaml, hack/generate-gateway-deployment.sh, hack/generate-provisioner-deployment.sh, test/scripts/make-kind-cluster.sh
=> Update Gateway YAML generation for extracted namespace file

design/jwt-verification-design.md
=> design: add JWT verification design doc

changelogs/unreleased/4725-sunjayBhatia-docs.md, site/content/guides/grpc.md
=> Add guide on configuring gRPC routes

.github/workflows/prbuild.yaml
=> switch to GitHub Action codecov uploader

examples/gateway/00-crds.yaml, examples/render/contour-gateway-provisioner.yaml, examples/render/contour-gateway.yaml
Recent changes to release-0.5 branch
=> Sync Gateway API CRDs

.github/workflows/prbuild.yaml, changelogs/unreleased/4755-skriss-small.md, examples/gateway/00-crds.yaml, examples/gateway/01-admission_webhook.yaml, examples/render/contour-gateway-provisioner.yaml, examples/render/contour-gateway.yaml, go.mod, go.sum
=> update to Gateway API v0.5.1

.github/workflows/prbuild.yaml, hack/actions/install-kubernetes-toolchain.sh, test/scripts/make-kind-cluster.sh
In preparation for k8s 1.25 bump
Updates: #4740
=> Bump kind to 0.16.0

.github/workflows/stale.yaml
Also an issues with kind/flake label
=> Exempt issues/prs with an assigned milestone from going stale

.github/workflows/label_check.yaml
=> only run release note/label check on PRs to main

internal/provisioner/equality/equality.go, internal/provisioner/equality/equality_test.go
=>  internal/provisioner: fix current & expect number of  ports changed bug

hack/release/prepare-release.go, site/content/resources/release-process.md
Updates the prepare-release script and release instructions
Fixes: #4634
=> Updates for release-candidate release process

test/scripts/make-kind-cluster.sh
Log showing flake + fix:
```
validatingwebhookconfiguration.admissionregistration.k8s.io/metallb-webhook-configuration configured
deployment.apps/controller condition met
Error from server (InternalError): error when creating "STDIN": Internal error occurred: failed calling webhook "ipaddresspoolvalidationwebhook.metallb.io": failed to call webhook: Post "https://webhook-service.metallb-system.svc:443/validate-metallb-io-v1beta1-ipaddresspool?timeout=10s": dial tcp 10.96.232.198:443: connect: connection refused
Error from server (InternalError): error when creating "STDIN": Internal error occurred: failed calling webhook "l2advertisementvalidationwebhook.metallb.io": failed to call webhook: Post …
```
=> test/scripts: add retry loop for metallb config

apis/projectcontour/v1/httpproxy.go, examples/contour/01-crds.yaml, examples/render/contour-deployment.yaml, examples/render/contour-gateway-provisioner.yaml, examples/render/contour-gateway.yaml, examples/render/contour.yaml, internal/dag/httpproxy_processor.go, internal/dag/status_test.go, internal/featuretests/v3/jwtverification_test.go, site/content/docs/main/config/api-reference.html
=> add optional DNS lookup family for remote JWKS

site/content/community/_index.html
Close: #4787 
I updated the links of mailing list and changed some meeting information with the help of @pnbrown
=> Update the Community Page on the Website

Makefile, changelogs/unreleased/4804-skriss-small.md, cmd/contour/gatewayprovisioner.go, examples/contour/03-envoy.yaml, examples/deployment/03-envoy-deployment.yaml, examples/render/contour-deployment.yaml, examples/render/contour-gateway.yaml, examples/render/contour.yaml, site/content/resources/compatibility-matrix.md, versions.yaml
=> update Envoy to v1.24.0

test/scripts/install-contour-working.sh
Drops steps that were previously needed for
E2E tests but are no longer relevant. This
script now sets up a standard Contour install
from the working copy of Contour.
=> test/scripts: remove unneeded steps from install-contour-working.sh

internal/envoy/v3/endpoint.go, internal/envoy/v3/endpoint_test.go, internal/xdscache/v3/endpointstranslator_test.go
=> Fix merge issue and move test helpers to be unexported in test file

apis/projectcontour/v1alpha1/contourdeployment.go, changelogs/unreleased/4801-izturn-small.md, examples/contour/01-crds.yaml, examples/render/contour-deployment.yaml, examples/render/contour-gateway-provisioner.yaml, examples/render/contour-gateway.yaml, examples/render/contour.yaml, internal/provisioner/controller/gateway.go, internal/provisioner/controller/gatewayclass.go, internal/provisioner/controller/gatewayclass_test.go, internal/provisioner/model/model.go, internal/provisioner/objects/dataplane/dataplane.go, internal/provisioner/objects/dataplane/dataplane_test.go, internal/provisioner/objects/deployment/deployment.go, internal/provisioner/objects/deployment/deployment_test.go, site/content/docs/main/config/api-reference.html
add the fields to `crd/ContourDeployment` to support changing Envoy log level
=> gateway provisioner: support changing Envoy log level

.github/workflows/prbuild.yaml, cmd/contour/serve.go, examples/gateway/00-crds.yaml, examples/render/contour-gateway-provisioner.yaml, examples/render/contour-gateway.yaml, go.mod, go.sum, internal/controller/gateway.go, internal/dag/builder_test.go, internal/dag/cache.go, internal/dag/cache_test.go, internal/dag/gatewayapi_processor.go, internal/dag/policy.go, internal/dag/status_test.go, internal/featuretests/v3/routeweight_test.go, internal/featuretests/v3/tlsroute_test.go, internal/gatewayapi/helpers.go, internal/gatewayapi/listeners.go, internal/gatewayapi/listeners_test.go, internal/provisioner/controller/gateway.go, internal/provisioner/controller/gateway_test.go, internal/status/gatewaystatus_test.go, internal/status/routeconditions.go, test/conformance/gatewayapi/gateway_conformance_test.go, test/e2e/gateway/host_rewrite_test.go, test/e2e/gateway/multiple_gateways_and_classes_test.go, test/e2e/gateway/request_header_modifier_test.go, test/e2e/gateway/tlsroute_test.go, test/e2e/provisioner/provisioner_test.go
- Update to v1beta1 ReferenceGrant
- HTTPRequestHeaderFilter -> HTTPHeaderFilter
- GatewayConditionScheduled -> GatewayConditionAccepted
- ListenerConditionDetached -> ListenerConditionAccepted
Updates #4555.
Updates #4738.
=> [dev-gwapi-0.6] update to latest Gateway API commit

.github/dependabot.yml
See documentation here: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
=> Add dependabot dependency update configuration

Makefile, changelogs/unreleased/4889-sunjayBhatia-minor.md, cmd/contour/gatewayprovisioner.go, examples/contour/03-envoy.yaml, examples/deployment/03-envoy-deployment.yaml, examples/render/contour-deployment.yaml, examples/render/contour-gateway.yaml, examples/render/contour.yaml, test/e2e/deployment.go, test/e2e/upgrade/upgrade_test.go
Release notes should be populated here eventually: https://www.envoyproxy.io/docs/envoy/latest/version_history/v1.22/v1.22.6
=> Bump Envoy to 1.22.6

go.mod, go.sum
=> deps: bump golang.org/x/net to v0.4.0

site/content/docs/main/architecture.md, site/content/docs/v1.23.2/architecture.md
Replaces #4893.
Co-authored-by: Bhagwat kumar Singh <bhagwat0709@gmail.com>
=> update docs on leader election

changelogs/unreleased/4944-sunjayBhatia-minor.md, examples/gateway/00-crds.yaml, examples/gateway/01-admission_webhook.yaml, examples/render/contour-gateway-provisioner.yaml, examples/render/contour-gateway.yaml, go.mod, go.sum
=> Bump Gateway API to v0.6.0

README.md, site/content/getting-started/_index.md
=> Gateway API-related docs updates

internal/envoy/v3/listener.go
=> internal/envoy: fix no router filter crash

changelogs/unreleased/4958-izturn-small.md, cmd/contour/bootstrap.go, cmd/contour/certgen.go, cmd/contour/certgen_test.go, cmd/contour/cli.go, cmd/contour/contour.go, cmd/contour/contour_test.go, cmd/contour/gatewayprovisioner.go, cmd/contour/serve.go, cmd/contour/shutdownmanager.go
sort the option flags
fix #2397
=> cmd/contour:  sort the option flags

test/e2e/poller.go, test/e2e/upgrade/upgrade_test.go
Should help in seeing which stage of upgrade test causes errors and what they are
=> test/e2e: App poller logs request/response errors

hack/generate-crd-yaml.sh
=> update generate-crd-yaml.sh to be macOS-compatible

.github/workflows/build_daily.yaml, .github/workflows/prbuild.yaml, Makefile, changelogs/unreleased/4980-skriss-small.md
=> update to Go 1.19.5

internal/dag/cache.go, internal/dag/cache_test.go, internal/k8s/kind.go, internal/k8s/kind_test.go
Add kind and cache support for GRPCRoute
Updates #4820
Signed-off-by: Fang Peng <fpeng@vmware.com>
=> GRPCRoute: Add GRPCRoute support

test/e2e/deployment.go
Failures in main daily build showed we were not checking the right status/etc. fields for Envoy in Deployment mode.
Now mimic DaemonSet check, since we can have runs where there is no Contour image container in the Deployment pods.
=> test/e2e: Fix wait for Envoy Deployment update

site/content/resources/upgrading.md
Generalizes the upgrading instructions so
they no longer need to be updated for every
Contour version.
Closes #3223.
=> site: generalize upgrading instructions

Makefile, cmd/contour/gatewayprovisioner.go, examples/contour/03-envoy.yaml, examples/deployment/03-envoy-deployment.yaml, examples/render/contour-deployment.yaml, examples/render/contour-gateway.yaml, examples/render/contour.yaml
=> [release-1.24] update Envoy to 1.25.1

internal/dag/status_test.go
=> internal/dag: Add more status test for GRPCRoute

internal/dag/gatewayapi_processor.go
Extracts a helper method `processRoute` that can
be used for any route type and implements common
logic around hostnames, parent attachment, etc.
=> internal/dag: merge common route processing code

internal/dag/status_test.go
=> internal/dag: simplify ut for dag/status

internal/dag/gatewayapi_processor.go
=> internal/dag: simplify add invalid listener condition for gateway-api

internal/dag/policy.go
=> internal/dag: simplify api for gateway-api

.github/workflows/prbuild.yaml, design/cors-configuration.md, site/content/docs/main/config/rate-limiting.md, site/content/docs/v1.13.0/config/rate-limiting.md, site/content/docs/v1.13.1/config/rate-limiting.md, site/content/docs/v1.14.0/config/rate-limiting.md, site/content/docs/v1.14.1/config/rate-limiting.md, site/content/docs/v1.14.2/config/rate-limiting.md, site/content/docs/v1.15.0/config/rate-limiting.md, site/content/docs/v1.15.1/config/rate-limiting.md, site/content/docs/v1.15.2/config/rate-limiting.md, site/content/docs/v1.16.0/config/rate-limiting.md, site/content/docs/v1.16.1/config/rate-limiting.md, site/content/docs/v1.17.0/config/rate-limiting.md, site/content/docs/v1.17.1/config/rate-limiting.md, site/content/docs/v1.17.2/config/rate-limiting.md, site/content/docs/v1.18.0/config/rate-limiting.md, site/content/docs/v1.18.1/config/rate-limiting.md, site/content/docs/v1.18.2/config/rate-limiting.md, site/content/docs/v1.18.3/config/rate-limiting.md, site/content/docs/v1.19.0/config/rate-limiting.md, site/content/docs/v1.19.1/config/rate-limiting.md, site/content/docs/v1.20.0/config/rate-limiting.md, site/content/docs/v1.20.1/config/rate-limiting.md, site/content/docs/v1.20.2/config/rate-limiting.md, site/content/docs/v1.21.0/config/rate-limiting.md, site/content/docs/v1.21.1/config/rate-limiting.md, site/content/docs/v1.22.0/config/rate-limiting.md
- Fixes spelling errors
- Update golangci-lint GitHub action
=> [release-1.22] CI fixes

.github/workflows/prbuild.yaml, design/cors-configuration.md, site/content/docs/main/config/rate-limiting.md, site/content/docs/v1.13.0/config/rate-limiting.md, site/content/docs/v1.13.1/config/rate-limiting.md, site/content/docs/v1.14.0/config/rate-limiting.md, site/content/docs/v1.14.1/config/rate-limiting.md, site/content/docs/v1.14.2/config/rate-limiting.md, site/content/docs/v1.15.0/config/rate-limiting.md, site/content/docs/v1.15.1/config/rate-limiting.md, site/content/docs/v1.15.2/config/rate-limiting.md, site/content/docs/v1.16.0/config/rate-limiting.md, site/content/docs/v1.16.1/config/rate-limiting.md, site/content/docs/v1.17.0/config/rate-limiting.md, site/content/docs/v1.17.1/config/rate-limiting.md, site/content/docs/v1.17.2/config/rate-limiting.md, site/content/docs/v1.18.0/config/rate-limiting.md, site/content/docs/v1.18.1/config/rate-limiting.md, site/content/docs/v1.18.2/config/rate-limiting.md, site/content/docs/v1.18.3/config/rate-limiting.md, site/content/docs/v1.19.0/config/rate-limiting.md, site/content/docs/v1.19.1/config/rate-limiting.md, site/content/docs/v1.20.0/config/rate-limiting.md, site/content/docs/v1.20.1/config/rate-limiting.md, site/content/docs/v1.20.2/config/rate-limiting.md, site/content/docs/v1.21.0/config/rate-limiting.md, site/content/docs/v1.21.1/config/rate-limiting.md, site/content/docs/v1.22.0/config/rate-limiting.md, site/content/docs/v1.22.1/config/rate-limiting.md
- Fixes spelling errors
- Update golangci-lint GitHub action
=> [release-1.23] CI fixes

Makefile, examples/gateway/02-certificate_config.yaml, examples/render/contour-gateway-provisioner.yaml, examples/render/contour-gateway.yaml, hack/generate-gateway-yaml.sh
=> Gateway API: k8s.gcr.io -> registry.k8s.io

test/e2e/httpproxy/httpproxy_test.go, test/e2e/httpproxy/internal_redirect_test.go
Use internal generic from ref package
Follow up to #5010
=> test/e2e/httpproxy: Remove pointer package usage

design/multiple-listeners-design.md
=> multiple Listeners design doc

apis/projectcontour/v1/httpproxy.go, changelogs/unreleased/5195-fangfpeng-small.md, examples/contour/01-crds.yaml, examples/example-workload/httpproxy/03-routes/httpproxy-header-rewrite.yaml, examples/render/contour-deployment.yaml, examples/render/contour-gateway-provisioner.yaml, examples/render/contour-gateway.yaml, examples/render/contour.yaml, internal/dag/builder_test.go, internal/dag/httpproxy_processor.go, internal/dag/ingress_processor.go, internal/dag/policy.go, internal/dag/policy_test.go, internal/dag/status_test.go, internal/envoy/route.go, internal/envoy/v3/route.go, internal/envoy/v3/route_test.go, site/content/docs/main/config/api-reference.html
=> HTTPProxy: support Host header rewrites per-service

test/scripts/get-contour-upgrade-from-version.sh
=> [release-1.24] test/scripts: fix upgrade from version

test/scripts/get-contour-upgrade-from-version.sh
=> [release-1.23] test/scripts: fix upgrade from version

test/scripts/get-contour-upgrade-from-version.sh
=> [release-1.22] test/scripts: fix upgrade from version

site/content/community/_index.html
=> site: add Kubernetes slack inviter link

changelogs/CHANGELOG-v1.22.6.md, changelogs/CHANGELOG-v1.23.5.md, changelogs/CHANGELOG-v1.24.3.md, site/content/resources/compatibility-matrix.md, versions.yaml
Versions 1.24.3, 1.23.5, 1.22.6
=> Changelogs and site updates for patch releases

internal/dag/gatewayapi_processor.go, internal/dag/status_test.go
If no matching listeners, we still walk the route and resolve any backendrefs
To cover GW conformance for v0.6.2
=> internal/dag: Always set resolved refs in GW API processor

internal/envoy/v3/listener.go
=> chore: remove double package import

test/scripts/make-kind-cluster.sh
fixed https://github.com/projectcontour/contour/issues/5293
Signed-off-by: IdanAtias <idan2k3@gmail.com>
=> Upgrading metallb to v0.13.9

internal/envoy/v3/cluster_test.go
internal/envoy/v3: adds a testcase for slow start mode with non-default LB policy.
fixes https://github.com/projectcontour/contour/issues/5292
=> internal/envoy/v3: adds a testcase for slow start mode with non-default LB policy

changelogs/unreleased/5080-nsimons-minor.md, cmd/contour/serve.go, examples/optional-features/kustomization.yaml, examples/render/kustomization.yaml, site/content/docs/main/configuration.md, site/content/docs/main/deploy-options.md
Fixes #5247
Signed-off-by: Niklas Simons [niklas.simons@est.tech](mailto:niklas.simons@est.tech)
=> Make alpha Gateway APIs optional

internal/featuretests/v3/tracing_test.go
=> chore: extend tracing test for custom tags

Makefile, changelogs/unreleased/5320-skriss-small.md, cmd/contour/gatewayprovisioner.go, examples/contour/03-envoy.yaml, examples/deployment/03-envoy-deployment.yaml, examples/render/contour-deployment.yaml, examples/render/contour-gateway.yaml, examples/render/contour.yaml, site/content/resources/compatibility-matrix.md, versions.yaml
=> update to Envoy v1.26.1

Makefile, test/scripts/install-provisioner-release.sh
=> add make install-provisioner-release

cmd/contour/serve.go, internal/featuretests/v3/global_authorization_test.go, internal/featuretests/v3/globalratelimit_test.go, internal/featuretests/v3/tracing_test.go, internal/xdscache/v3/listener.go, internal/xdscache/v3/listener_test.go
=> De-dupe ExtensionService resolution code

Makefile, test/e2e/deployment.go, test/e2e/gateway/gateway_test.go, test/e2e/gateway/host_rewrite_test.go, test/e2e/gateway/multiple_gateways_and_classes_test.go, test/e2e/gateway/multiple_https_listeners_test.go, test/e2e/gateway/query_param_match_test.go, test/e2e/gateway/request_header_modifier_test.go, test/e2e/gateway/request_mirror_test.go, test/e2e/gateway/request_redirect_test.go, test/e2e/gateway/response_header_modifier_test.go, test/e2e/gateway/tls_gateway_test.go, test/e2e/gateway/tls_wildcard_host_test.go, test/e2e/gatewayapi_predicates.go, test/e2e/provisioner/provisioner_test.go, test/e2e/upgrade/upgrade_test.go, test/e2e/waiter.go
Adds an upgrade test for Contour provisioned
by the Gateway provisioner.
=> test/e2e: provisioner upgrade test

internal/featuretests/v3/extensionservice_test.go, internal/featuretests/v3/global_authorization_test.go, internal/featuretests/v3/jwtverification_test.go, internal/featuretests/v3/listeners_test.go, internal/provisioner/controller/gateway.go, internal/provisioner/controller/gatewayclass.go, internal/xds/v3/contour.go
refactor to fix shadow variable: `any`  and import the packages more then once.
=> refactor to fix shadow-vars & dup import

internal/provisioner/controller/gateway_test.go
=> internal/provisioner: simplify ut for provisioner/controller

test/e2e/framework.go
=> test/e2e: extract generic helper for creating/waiting

.github/workflows/build_daily.yaml, .github/workflows/prbuild.yaml, Makefile, changelogs/CHANGELOG-v1.20.0.md, site/content/posts/2020-01-16-announcing-contour-1.1.md
See release notes: https://go.dev/doc/devel/release#go1.20
=> release-1.25: Bump go to 1.20.5

.github/workflows/build_daily.yaml, .github/workflows/prbuild.yaml, Makefile, changelogs/CHANGELOG-v1.20.0.md, site/content/posts/2020-01-16-announcing-contour-1.1.md
See release notes https://go.dev/doc/devel/release#go1.19
=> release-1.24: Bump go to 1.19.10

changelogs/unreleased/5415-sunjayBhatia-docs.md, site/content/docs/1.25/guides/fips.md, site/content/docs/main/guides/fips.md
Updates docs for main and 1.25
Fixes: #5411
=> site: Update guide on building Envoy in FIPS compliant mode

cmd/contour/servecontext.go
name: code clean
about: Delete redundance code.
labels: ["release-note/none-required"]
=> Delete redundance code.

Makefile, cmd/contour/gatewayprovisioner.go, examples/contour/03-envoy.yaml, examples/deployment/03-envoy-deployment.yaml, examples/render/contour-deployment.yaml, examples/render/contour-gateway.yaml, examples/render/contour.yaml
https://www.envoyproxy.io/docs/envoy/v1.25.9/version_history/v1.25/v1.25.9
=> release-1.24: Bump Envoy to 1.25.9

internal/dag/secret_test.go
=> internal/dag: simplify ut for dag/secret

internal/dag/accessors_test.go, internal/dag/builder_test.go, internal/dag/cache_test.go, internal/dag/dag_test.go, internal/dag/status_test.go
=> internal/dag: simplify ut for dag

.github/workflows/build_daily.yaml, .github/workflows/prbuild.yaml, Makefile, changelogs/unreleased/5555-skriss-small.md, changelogs/unreleased/5663-sunjayBhatia-small.md
See release notes: https://go.dev/doc/devel/release#go1.20
=> Bump golang to 1.20.7

changelogs/unreleased/5670-HeavenTonight-small.md, internal/dag/httpproxy_processor.go, internal/dag/status_test.go
Fixes #5638 
add more information in Error Message of httpproxy
=> add more information in Error Message of httpproxy

.github/dependabot.yml
So dependency updates are ready to triage on Mondays
=> Run dependabot scans on Sundays

.github/workflows/build_daily.yaml, .github/workflows/prbuild.yaml, Makefile
See Go release notes for details:
https://go.dev/doc/devel/release#go1.20.minor
=> [release-1.26] update Go to 1.20.8

.github/workflows/build_daily.yaml, .github/workflows/prbuild.yaml, Makefile
See Go release notes for details:
https://go.dev/doc/devel/release#go1.20.minor
=> [release-1.25] update Go to 1.20.8

.github/workflows/build_daily.yaml, .github/workflows/prbuild.yaml, Makefile
See Go release notes for details:
https://go.dev/doc/devel/release#go1.19.minor
=> [release-1.24] update Go to 1.19.13

netlify.toml
Also implement more consistent toml file indenting for readability
=> site: Bump Hugo to 0.119.0

Makefile, cmd/contour/gatewayprovisioner.go, examples/contour/03-envoy.yaml, examples/deployment/03-envoy-deployment.yaml, examples/render/contour-deployment.yaml, examples/render/contour-gateway.yaml, examples/render/contour.yaml
https://www.envoyproxy.io/docs/envoy/v1.25.11/version_history/v1.25/v1.25.11
=> release-1.24: Bump Envoy to v1.25.11

Makefile, changelogs/unreleased/5863-sunjayBhatia-small.md, changelogs/unreleased/5870-skriss-small.md, cmd/contour/gatewayprovisioner.go, examples/contour/03-envoy.yaml, examples/deployment/03-envoy-deployment.yaml, examples/render/contour-deployment.yaml, examples/render/contour-gateway.yaml, examples/render/contour.yaml, go.mod, go.sum, site/content/resources/compatibility-matrix.md, versions.yaml
=> update Envoy to 1.28.0

.github/dependabot.yml, .github/workflows/trivy-scan.yaml, netlify.toml
Updates netlify, dependabot, trivy config.
=> v1.27.0 post-release updates

.github/workflows/stale.yaml
Mention PRs passing CI checks are more likely to be reviewed
=> Add more options on how to resolve stale PRs

cmd/contour/serve.go
Since the snapshot handler is only used for the envoy
xDS server type, only instantiate it and wire it up
when using that server type.
=> cmd/contour: only create snapshot handler for envoy xDS server

apis/projectcontour/v1alpha1/contourdeployment.go, changelogs/unreleased/5968-skriss-deprecation.md, changelogs/unreleased/5968-skriss-small.md, examples/contour/01-crds.yaml, examples/render/contour-deployment.yaml, examples/render/contour-gateway-provisioner.yaml, examples/render/contour-gateway.yaml, examples/render/contour.yaml, internal/provisioner/controller/gateway.go, internal/provisioner/controller/gateway_test.go, internal/provisioner/model/model.go, internal/provisioner/model/names.go, internal/provisioner/objects/contourconfig/contourconfig.go, internal/provisioner/objects/dataplane/dataplane.go, internal/provisioner/objects/dataplane/dataplane_test.go, internal/provisioner/objects/deployment/deployment.go, internal/provisioner/objects/deployment/deployment_test.go, internal/provisioner/objects/rbac/clusterrole/cluster_role.go, internal/provisioner/objects/rbac/clusterrolebinding/cluster_role_binding.go, internal/provisioner/objects/rbac/role/role.go, internal/provisioner/objects/rbac/rolebinding/role_binding.go, internal/provisioner/objects/rbac/serviceaccount/service_account.go, internal/provisioner/objects/secret/secret.go, internal/provisioner/objects/service/service.go, site/content/docs/main/config/api-reference.html
=> implement Gateway infrastructure labels/annotations

.github/workflows/openssf-scorecard.yaml
Generates scorecard to ensure repo/project is passing open source best practices.
=> Add action for generating OpenSSF scorecard

.github/workflows/build_daily.yaml, .github/workflows/build_main.yaml, .github/workflows/build_tag.yaml, .github/workflows/codeql-analysis.yml, .github/workflows/openssf-scorecard.yaml, .github/workflows/stale.yaml, .github/workflows/trivy-scan.yaml
Fixes codeql workflow to add write permissions
=> Update minimum permissions on remaining workflows

README.md, examples/example-workload/gatewayapi/blue-green/blue-green.yaml, examples/example-workload/gatewayapi/kuard/kuard.yaml, examples/gateway/03-gatewayclass.yaml, examples/gateway/04-gateway.yaml, examples/render/contour-gateway.yaml, internal/sorter/sorter_test.go, site/content/docs/main/config/gateway-api.md, site/content/docs/main/guides/gateway-api.md, site/content/getting-started/_index.md, site/content/guides/gateway-api.md, test/scripts/run-gateway-conformance.sh
=> update docs & examples to match gateway-api/v1

site/content/docs/main/config/gateway-api.md, site/content/getting-started/_index.md
Missed a couple small things in previous PRs.
=> site/content: minor Gateway API docs updates

.github/workflows/build_daily.yaml, .github/workflows/build_tag.yaml, .github/workflows/codeql-analysis.yml, .github/workflows/prbuild.yaml, Makefile, changelogs/unreleased/6181-sunjayBhatia-small.md
See release notes: https://go.dev/doc/go1.22
=> Bump golang to 1.22.0

Makefile, changelogs/unreleased/6353-tico88612-small.md, cmd/contour/gatewayprovisioner.go, examples/contour/03-envoy.yaml, examples/deployment/03-envoy-deployment.yaml, examples/render/contour-deployment.yaml, examples/render/contour-gateway.yaml, examples/render/contour.yaml, site/content/resources/compatibility-matrix.md, versions.yaml
=> Bump envoy to v1.30.0

.github/workflows/prbuild.yaml, Makefile
=> re-enable linting the tools build tag

changelogs/unreleased/6328-skriss-small.md
Changelog #6328 was superceded by #6353.
=> remove old changelog entry

hack/release/release-notes-template.md
Update installing/upgrading section to include
Gateway provisioner option.
=> hack/release: update release notes template

.github/workflows/build_daily.yaml, .github/workflows/build_tag.yaml, .github/workflows/codeql-analysis.yml, .github/workflows/prbuild.yaml, Makefile, changelogs/unreleased/6499-sunjayBhatia-small.md
=> Bump golang to 1.22.4

.github/workflows/build_daily.yaml, .github/workflows/build_tag.yaml, .github/workflows/codeql-analysis.yml, .github/workflows/prbuild.yaml, Makefile, cmd/contour/gatewayprovisioner.go, examples/contour/03-envoy.yaml, examples/deployment/03-envoy-deployment.yaml, examples/render/contour-deployment.yaml, examples/render/contour-gateway.yaml, examples/render/contour.yaml
combined in one PR for expediency
=> release-1.28: Envoy 1.29.7 and go 1.21.12 bump

Makefile
=> chang the envoy version to v1.31.0

hack/actions/install-kubernetes-toolchain.sh
=> Bump kind 0.24.0 and kubectl 1.31.0

.github/workflows/build_daily.yaml, .github/workflows/build_tag.yaml, .github/workflows/codeql-analysis.yml, .github/workflows/prbuild.yaml, Makefile, changelogs/unreleased/6718-tsaarni-small.md, changelogs/unreleased/6838-sunjayBhatia-small.md
See release notes: https://go.dev/doc/devel/release#go1.23.0
=> Bump go to 1.23.4

Makefile, cmd/contour/gatewayprovisioner.go, examples/contour/03-envoy.yaml, examples/deployment/03-envoy-deployment.yaml, examples/render/contour-deployment.yaml, examples/render/contour-gateway.yaml, examples/render/contour.yaml
See release notes: https://www.envoyproxy.io/docs/envoy/v1.31.5/version_history/v1.31/v1.31.5
=> release-1.30: Bump Envoy to 1.31.5

changelogs/CHANGELOG-v1.29.5.md, changelogs/CHANGELOG-v1.30.3.md, site/content/resources/compatibility-matrix.md, versions.yaml
This PR includes the release details for the latest set of patch updates.
=> Added info for patch releases 1.29.5 and 1.30.3

test/e2e/httpproxy/backend_tls_test.go
This PR works around e2e test flake where backend TLS is tested while Envoy client certificate is rotated. After rotation, the request towards backend is now retried until it returns new client certificate (or until timeout). This should avoid failing the test case if Envoy has not picked up the new client certificate yet.
Fixes #7030
=> Retry until envoy client cert is rotated

test/conformance/gatewayapi/gateway_conformance_test.go
Initialize supported features map before adding to it
=> Fix gateway api conformance report generation
