internal/k8s/statusupdater.go

Updates #2857.
This should ensure that the DAG has some headroom before
status updates start blocking the DAG rebuilds, even in
reasonably busy clusters.

internal/k8s: Change StatusUpdaterHandler channel to buffered

---

internal/k8s/statusupdater.go

Updates #2857.
This should ensure that the DAG has some headroom before
status updates start blocking the DAG rebuilds, even in
reasonably busy clusters.

[release-1.8] internal/k8s: Change StatusUpdaterHandler channel to buffered

---

internal/dag/dag.go
internal/dag/dag_test.go

`(*ServiceCluster).AddWeightedService` didn't copy the service name
properly, leading to a failure to match the service endpoints. Copy
the correct fields and add tests for `ServiceCluster` type.
This updates #2713.

internal/dag: fix adding a ServiceCluster entry

---

site/_guides/tls.md

Currently SNI matching during TLS handshake is case-sensitive in Envoy. Add a section in TLS guide doc to document this.
Fixes #2793

docs/tls: Add a note for case-sensitive cert

---

examples/gatekeeper/validations/01-template-non-empty.yml
examples/gatekeeper/validations/02-constraint-non-empty.yml
internal/dag/httpproxy_processor.go
internal/dag/status_test.go

Fixes #2835 
This was what I had in mind for #2835. It does not attempt to solve the whole issue around inclusion described in #2141. It simply ensures that one of `spec.routes`, `spec.includes`, or `spec.tcpproxy` is defined/non-empty for each proxy.
I think this has value separate from addressing #2141, since it is a useful validation for folks who aren't using inclusion, and it shouldn't have any impact on inclusion chains, but let me know if I'm missing something.
Will likely rebase this on #2847.

internal/dag: set HTTPProxy with no routes/includes/tcpproxy invalid

---

internal/dag/cache.go
internal/dag/httpproxy_processor.go

Build processors for both the ExtensionService and HTTPProxy types
have to deal with `UpstreamValidation`. Move the helpers that look up
`UpstreamValidation` and `DownstreamValidation` types to the Kubernetes
cache so that they are accessible to all the build processors.
This updates #2713.

internal/dag: move validation struct lookups

---

internal/contour/endpointstranslator.go
internal/contour/endpointstranslator_test.go
internal/dag/dag.go
internal/dag/dag_test.go
internal/envoy/cluster.go
internal/envoy/cluster_test.go
internal/envoy/healthcheck.go
internal/protobuf/helpers.go
internal/protobuf/helpers_test.go

Make ServiceCluster weights consistent with HTTPProxy Route weights. If
no weights are specified, distribute the load equally, otherwise take
the weights as specified by the users. In the latter case, 0 is a valid
weight and removes all traffic from that destination.
Hoist the 2 helpers for marshaling protobuf uint32 wrappers into the
`protobuf` package since they are part of an API family we now use one
of them in the endpoints handler.
This updates #2713.

internal: make ServiceCluster weights consistent

---

internal/k8s/kind.go
internal/k8s/kind_test.go

Add ExtensionService to the builtin Kubernetes type helpers for accessing
the resource kind and version.
This updates #2713.

internal/k8s: add ExtensionService to Kind helpers

---

cmd/contour/serve.go
internal/contour/cluster.go
internal/contour/snapshot.go
internal/xds/hash.go
internal/xds/server.go

Adds the snapshotHandler to react to DAG rebuilds so that new
snapshots can be created.
Follows #2845 
Updates #2134 

internal: Wire up new snapshots to DAG rebuilds

---

design/tls-backend-client-authentication.md

This proposal describes how to implement support for client certificate for Envoy for the TLS connection between Envoy and backend services.
This updates #2338

design: backend TLS with client certificate

---

Makefile

The `lint` task fails when a previous vendor directory is out of date resulting in having to run `go mod vendor` manually, then run the `checkall` task again. This has the vendor step happen automatically to solve that problem. 

makefile: Update checkall task to vendor go modules before running

---

cmd/contour/contour.go
cmd/contour/serve.go
cmd/contour/servecontext.go
internal/k8s/log.go
site/docs/main/troubleshooting.md

Add a `--kubernetes-debug` flag that enables verbose client-go logging
in the `klog` package. The logs are piped through `logrus` so that the
output format is consistent.

cmd/contour: add a Kubernetes debug logging flag

---

cmd/contour/serve.go
internal/contour/metrics_test.go
internal/contour/secret_test.go
internal/dag/builder.go
internal/dag/builder_test.go
internal/dag/ingress_processor.go
internal/dag/status_test.go
internal/featuretests/featuretests.go

Removes the logrus.FieldLogger from the DAG builder and adds
it directly to the IngressProcessor where it's used.
Updates #2226

internal/dag: move logger from builder to processors

---

.golangci.yml
cmd/contour/shutdownmanager.go
internal/build/version.go
internal/contour/endpointstranslator_test.go
internal/contour/listener.go
internal/contour/route.go
internal/contour/secret.go
internal/envoy/cluster.go
internal/featuretests/route_test.go
internal/k8s/clients_test.go
internal/protobuf/testhelpers.go
internal/sorter/sorter_test.go

Ensure that `golint` and `gofmt -s` are run as part of the lint
configuration.

Update linter configuration.

---

cmd/contour/shutdownmanager.go
cmd/contour/shutdownmanager_test.go

Fixes #2896 , fixes #2897 
- shutdownReady filepath ("/ok") is configurable
- os.Stat() interval is configurable
- detect client disconnection and stop check loop
- don't use error logging level when os.Stat() tells us the file does not yet exist
- add test coverage for success and client disconnect cases

cmd/shutdownmanager: /shutdown handler fixes

---

apis/projectcontour/v1/httpproxy.go
examples/contour/01-crds.yaml
examples/render/contour.yaml
internal/dag/builder_test.go
internal/dag/httpproxy_processor.go
internal/dag/policy.go
internal/dag/status_test.go
site/docs/main/api-reference.html

The 'Host" header value is special when applied to a
requestHeadersPolicy. When this is set it configures
the hostRewrite field in envoy to match the value of the
requestHeadersPolicy value field.
However, setting this value is only valid when applied to
a route in Envoy, it cannot be applied to a cluster, so
any user setting the "host" header field on a requestHeadersPolicy
on a Spec.Route.Service is invalid.
Fixes #2872

internal/dag: Update how headers are processed for special 'Host' header

---

cmd/contour/serve.go
cmd/contour/serve_test.go
internal/annotation/annotations.go
internal/contour/route_test.go
internal/dag/builder_test.go
internal/dag/extension_processor.go
internal/dag/httpproxy_processor.go
internal/dag/ingress_processor.go
internal/dag/policy.go
internal/dag/policy_test.go
internal/dag/status_test.go
internal/featuretests/authorization_test.go
internal/featuretests/extensionservice_test.go
internal/featuretests/timeoutpolicy_test.go
internal/timeout/timeout.go
internal/timeout/timeout_test.go

Returns errors when parsing timeout strings so they can be reported to
the user, either as invalid HTTPProxies, or in Contour logs. Previously,
such errors were swallowed and the timeout in question was disabled/set
to infinity.
Updates #2728

internal/timeout: return parse errors instead of defaulting to infinity

---

Makefile
apis/projectcontour/v1alpha1/register.go
cmd/contour/serve.go
examples/contour/01-crds.yaml
examples/render/contour.yaml
internal/k8s/informers.go
site/docs/main/api-reference.html

Enables the creation of the ExtensionService CRD when running `make generate`.
Fixes #2711

makefile: Enable creating ExtensionService CRD yaml

---

apis/projectcontour/v1/httpproxy.go
examples/contour/01-crds.yaml
examples/render/contour.yaml
internal/timeout/validation_test.go
site/docs/main/api-reference.html

Adds kubebuilder regex validations for all timeout string API
fields.
Closes #2728 

apis: add kubebuilder regex validation for timeout strings

---

cmd/contour/servecontext.go
cmd/contour/servecontext_test.go
examples/contour/01-contour-config.yaml
examples/render/contour.yaml
site/docs/main/configuration.md

Moves the xds-server-type field into a ServerConfig struct to allow
for other future server parameters to be added to the config file
under the same section.
Updates: #2134
Fixes: #2923

config file: Move xds-server-type into a ServerConfig struct

---

go.mod
go.sum
internal/xds/contour.go

Updates the go-control-plane dep which fixes up a bunch of wellknown name types.
Updates #2479

deps: update go-control-plane to v0.9.6

---

README.md
cmd/contour/serve.go
examples/contour/01-crds.yaml
examples/contour/02-role-contour.yaml
examples/render/contour.yaml
hack/generate-crd-yaml.sh

Updates the Contour CustomResourceDefinition YAML files
to contain v1 resources instead of v1beta1.
Closes #2678
Closes #1723
Closes #1978
Closes #2903
Closes #2527
**Release note**: 
- we need to be very clear that Kubernetes 1.16 is now the hard minimum supported version since the sample YAML contains v1 CRDs.
- For upgrade instructions, for folks who don't want to reapply the full YAML, they can either reapply just the CRD YAML, or they can run the following:
```
kubectl patch crd httpproxies.projectcontour.io --type json -p '[{"op": "replace", "path": "/spec/preserveUnknownFields", value: false}]'
kubectl patch crd tlscertificatedelegations.projectcontour.io --type json -p '[{"op": "replace", "path": "/spec/preserveUnknownFields", value: …
```

examples: generate v1 CustomResourceDefinitions

---

cmd/contour/serve.go
cmd/contour/servecontext.go
cmd/contour/servecontext_test.go
examples/contour/01-contour-config.yaml
examples/render/contour.yaml
internal/dag/dag.go
internal/dag/httpproxy_processor.go
internal/envoy/v2/cluster.go
internal/envoy/v2/cluster_test.go
site/docs/main/api-reference.html
site/docs/main/configuration.md

Adds a config file option `Cluster.DnsLookupFamily` which allows users to define what dns lookup family is used for any
externalName type cluster. This ensures that lookups to external resources are resolved correctly.
Fixes #2873

internal/envoy: Set the dns lookup family on externalName type clusters

---

cmd/contour/servecontext.go
cmd/contour/servecontext_test.go

Set the minimum TLS version to TLSv1.2 for gRPC XDS interface, removing
support for TLSv1.0 and TLSv1.1, which are now deprecated.
Fixes #2944

cmd/contour: deprecate TLS versions for gRPC XDS

---

site/_data/github-labels.yaml

Adds the Hacktoberfest label to the Contour repo to help users who
want to participate in the hacktoberfest program: https://hacktoberfest.digitalocean.com/

site/_data: Add Hacktoberfest label

---

examples/contour/02-job-certgen.yaml
examples/contour/03-contour.yaml
examples/contour/03-envoy.yaml
examples/render/contour.yaml

Bumps the Envoy version to v1.15.1 to address Envoy CVEs (https://www.envoyproxy.io/docs/envoy/latest/version_history/v1.15.1). 
Fixes #2925

Release v1.8.2 onto branch release-1.8

---

_integration/testsuite/httpproxy/013-auth-basic-testserver.yaml
_integration/testsuite/make-kind-cluster.sh
_integration/testsuite/policies/contour-response.rego

Add a basic integration test for an external authorization server. This
ensures that if the authorization server is present, context is propagated
correctly, and authorization can be disabled on routes.
This updates #2717.

testsuite: add a basic external auth test

---

Makefile
examples/contour/03-envoy.yaml
examples/render/contour.yaml

examples: update Envoy to v1.15.1

---

site/_data/main-toc.yml
site/_guides/external-authorization.md

Add a guide that gives an overview of how external authorization works,
and a worked example of deploying it with `contour-authserver`.
This updates #2716.

docs: add an external auth guide

---

internal/k8s/helpers.go

Change how the comparison of the status of the object of HTTPProxy objects by
ignoring the LastTransitionTime which is always updates on each DAG rebuild
regardless if the status of object changed or not.
Not ignoring this causes each status to be updated each time since the objects
are always different for each DAG rebuild.
Fixes #2979

internal/k8s: Ignore LastTransitionTime for HTTPProxy objects status equal check

---

apis/projectcontour/v1alpha1/helpers.go
internal/dag/extension_processor.go
internal/status/cache.go
internal/status/cache_test.go
internal/status/extensionstatus.go

Add status cache support for `ExtensionService` resources. This is built
on a more general cache interface, which ought to be extensible to more
types, but that whill need to wait for additional refactoring passes.
Adopt the status cache in the `ExtensionService` processor so that
conditions are correctly updates for `ExtensionService` resources.
The processor doesn't fail on errors, which allows multiple errors
to be published in the same condition.
This fixes #2874.

internal: update ExtensionService status conditions

---

internal/contour/handler.go

Ignores ManagedFields when checking if an object update should trigger
a DAG rebuild. Previously, ManagedFields would get updated when an
object's status changed, resulting in an extraneous DAG update.
Reviewers: I don't think this *needs* to go in 1.9 if we want to hold it back, since it doesn't seem to cause material perf issues.

internal/contour: don't trigger DAG rebuild on ManagedFields change

---

internal/k8s/converter.go
internal/k8s/scheme.go

Add a constructor to generate a scheme that includes all the
Contour API types.
This updates #2818.

internal/k8s: add a Contour scheme constructor

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature-enhancement-request.md

Add initial labels when issues are submitted. This ensures that when
contributors file issues they get an initial `kind/bug` or `kind/feature`
label.

site: update issue templates

---

Makefile

Enables `force_polling` and `incremental` building when using the `make site-devel` makefile task.

makefile: Update site-devel to refresh automatically

---

cmd/contour/serve.go
internal/annotation/annotations.go
internal/dag/builder_test.go
internal/dag/httpproxy_processor.go
internal/dag/ingress_processor.go
internal/featuretests/envoy.go
internal/featuretests/listeners_test.go
internal/xdscache/v2/listener_test.go
site/docs/main/annotations.md
site/docs/main/httpproxy.md

Changes the default minimum TLS protocol version from 1.1 to 1.2 for
HTTPProxies and Ingresses that don't specify it, since 1.1 is now
end-of-life. 1.1 can still be used, but it must be explicitly configured.
Updates #2777

internal: update HTTPProxy & Ingress default min TLS version to 1.2

---

go.mod
go.sum
internal/xdscache/snapshot.go

Update go-control-plane version to v0.9.7 and fix up snapshots for secrets

---

examples/contour/02-job-certgen.yaml
examples/contour/02-rbac.yaml
examples/prometheus/03-prometheus-deployment.yaml
examples/render/contour.yaml
examples/root-rbac/rbac.yaml

Update the apiVersions of resources in rbac group such as  ClusterRoleBinding, Role etc. to
v1 version from  v1beta1 as it's deprecated since kubernetes 1.17 version and will be removed
in 1.22 version.
Fixes #2991
Signed-off-by: hnarahari <hnarahari@vmware.com>

deployment: Update rbac versions from v1beta1 to v1

---

cmd/contour/serve.go

Logs warnings on server startup for HTTPProxies and Ingresses using
a TLS minimum protocol version of 1.1 without also having the config
file's tls.minimum-protocol-version set to 1.1, since the default
value for the config file field will change to 1.2 in an upcoming
release.
Updates #2777.

cmd/contour: log warning for HTTPProxies/Ingresses using TLS 1.1

---

cmd/contour/serve.go
internal/featuretests/v2/featuretests.go
internal/xds/resource.go
internal/xds/v2/contour.go
internal/xds/v2/contour_test.go
internal/xds/v2/server.go
internal/xdscache/v2/server_test.go

Refactors the xDS Server into a v2 package allowing for
a v3 server to be created seperate from the v2 instance.
Updates #1898

internal/xds: Refactor xDS Server into a v2 package

---

internal/dag/httpproxy_processor.go
internal/featuretests/v2/authorization_test.go

If the authorization spec on the virtual host doesn't set the response
timeout, default it from the corresponding `ExtensionService`.
This fixes #3025.

internal/dag: default the authorization response timeout

---

Makefile
examples/contour/03-envoy.yaml
examples/render/contour.yaml

This PR updates `Makefile` to use the latest version of Envoy (v1.16.0).
It also updates the examples to reflect this change.
Fixes #3013

Update Envoy to v1.16.0

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature-enhancement-request.md
site/_data/github-labels.yaml

Add a `lifecycle/needs-triage` label and apply it on all new
issues opened with the issue templates.
This fixes #2981.

site: add `lifecycle/needs-triage` label

---

.github/workflows/build_tag.yaml
Makefile
hack/actions/build-and-push-release-images.sh
site/_resources/release-process.md

Adds logic to release tag builds to detect if the tag being built
is the highest semantic version that's not a pre-release, and if
so, sets TAG_LATEST to true so the image will be tagged as 'latest'
in addition to the version-specific tag.
Closes #1844

.github/workflows: automatically tag new release images as 'latest'

---

internal/xds/resource.go
internal/xds/resource_test.go
internal/xds/v3/contour.go
internal/xds/v3/contour_test.go
internal/xds/v3/server.go

Follows #3016 by adding an xDS v3 server.  Follow-up PR will introduce a config option to specify the xDS version wanting to serve. 
Updates #1898

internal/xds: xDS v3 server implementation

---

go.mod
internal/k8s/log.go

Updates k8s.io/klog to v2.2.0 to match the version used by
k8s.io/client-go.
Closes #3038

deps: upgrade k8s.io/klog to v2.2.0

---

_integration/testsuite/fixtures/ingress-conformance-echo.yaml
_integration/testsuite/httpproxy/002-header-condition-match.yaml
_integration/testsuite/httpproxy/003-path-condition-match.yaml
_integration/testsuite/httpproxy/004-https-sni-enforcement.yaml
_integration/testsuite/httpproxy/005-pod-restart.yaml
_integration/testsuite/httpproxy/006-merge-slash.yaml
_integration/testsuite/httpproxy/007-client-cert-auth.yaml
_integration/testsuite/httpproxy/008-tcproute-https-termination.yaml
_integration/testsuite/httpproxy/009-https-misdirected-request.yaml
_integration/testsuite/httpproxy/010-include-prefix-condition.yaml
_integration/testsuite/httpproxy/012-https-fallback-certificate.yaml
_integration/testsuite/make-kind-cluster.sh
_integration/testsuite/policies/contour-response.rego

Switch the integration test suite over to use the official
ingress-conformance-echo image. The echo server no longer emits the
value of the `TEST_ID` environment variable, but we can switch to using
`SERVICE_NAME` for the same purpose. Adding some policy helpers makes
this more consistent across test scripts.
This fixes #3034.

testsuite: use official ingress-conformance-echo image

---

.github/workflows/build_main.yaml
.github/workflows/build_tag.yaml
Dockerfile
Makefile
hack/actions/build-and-push-release-images.sh

Adds multi-arch Docker image support, and defaults to building
for linux/amd64 and linux/arm64. Uses the docker buildx plugin
along with go cross-compilation.
Closes #2868
Test images that I built via CI: https://hub.docker.com/layers/steveheptio/contour/latest/images/sha256-077a7a69520afcfb1618ee5d2ecada2d9249e644b411e3a63c2679cc55efca14?context=explore

build multi-arch Docker image for linux/amd64 and linux/arm64

---

site/_data/main-toc.yml

Move the Contour configuration reference under the "Deployment" heading,
since it is more properly related to that. This leaves the "Configuration"
heading more strictly aligned with configuring the Contour API.
This updates #2070.

doc: reclassify Contour configuration as deployment

---

Makefile
_integration/testsuite/README.md
_integration/testsuite/install-contour-release.sh
_integration/testsuite/install-contour-working.sh
_integration/testsuite/install-fallback-certificate.sh
_integration/testsuite/make-kind-cluster.sh

Separate the Contour installation from the script that builds a kind
cluster for integration testing. This makes it easier to install a
released version of Contour and test upgrading.

testsuite: add Contour installation scripts

---

site/_includes/nav.html

The leftmost navbar headings are `h1` elements, which means that table
of contents generators would notice them. However, for the structure of
the documentation, they should be ignored and we shoild only have to
care about the `h` elelements in the main page.
To fix this, we can use a `p` element styled like a heading. This also
fixes the inline per-page TOC which can otherwise erroneously display
the nav headings.

site: change navbar element type

---

Makefile
site/Gemfile
site/Gemfile.lock
site/_posts/2020-10-07-contour_v190.md
site/docs/main/README.md
site/docs/main/config/annotations.md
site/docs/main/config/upstream-tls.md
site/docs/main/deploy-options.md

After merging #3057, we have some broken links that still point to the
now-deleted httpproxy.md page.
This fixes #3063.

site: fix broken documentation links

---

site/examples/kuard-httpproxy.yaml

Updates the documentation site HTTProxy example to use `prefix` instead of `path`.
Fixes: https://github.com/projectcontour/contour/issues/3065
/assign @stevesloka @jpeach 
/cc @Miciah 

Updates Docs Site HTTProxy Example

---

site/docs/main/config/fundamentals.md

Running my local `make checkall` on a local branch for a different PR, I got this error for spelling:

site: Fix nit spelling in fundamentals.md that failed spell check task

---

internal/envoy/v2/accesslog.go
internal/envoy/v2/accesslog_test.go
internal/xdscache/v2/listener.go
pkg/config/accesslog.go
pkg/config/parameters.go
pkg/config/parameters_test.go

Add support for custom Envoy JSON fields via `=` in the fields name. The specify custom field name and its Envoy format string use `=` in the field name. The syntax is the following: `field_name=Envoy format string`, where Envoy format string can have any command except `DYNAMIC_METADATA` and `FILTER_STATE` commands. 
Example of custom field:
```yaml
json-fields:
- @timestamp
- customer_id=%REQ(X-CUSTOMER-ID)%
```
Fixes #3032, Fixes #1507
cc @KauzClay

Add support for custom Envoy JSON fields

---

cmd/contour/serve.go
examples/contour/01-contour-config.yaml
examples/render/contour.yaml
internal/featuretests/v2/featuretests.go
internal/xds/server.go
internal/xds/v2/server.go
internal/xds/v3/server.go
internal/xdscache/v2/server_test.go
pkg/config/parameters.go
pkg/config/parameters_test.go
site/docs/main/configuration.md

Changes the xds-server-version config item to be plural so that users can specify a set
of xDS versions Contour will serve. Defaults to V2 only for now.
Updates #1898
Updates #3047 

config: Change xds-server-version to be plural and serve multiple xDS versions

---

cmd/contour/bootstrap.go
cmd/contour/contour.go
internal/envoy/bootstrap.go
internal/envoy/v3/bootstrap.go
internal/envoy/v3/bootstrap_test.go
internal/envoy/v3/cluster.go
internal/envoy/v3/endpoint.go
internal/envoy/v3/endpoint_test.go
internal/envoy/v3/listener.go
internal/envoy/v3/socket.go
pkg/config/parameters.go
pkg/config/parameters_test.go

Adds new config file option to generate a v3 xDS boostrap configuration file.
To generate the v3 version a new arg is passed to the bootstrap config file (`--xds-server-version`)
which defaults to v2, but passing v3 will generate a v3 config.
Updates #1898

internal/envoy: Add xDS v3 bootstrap config file

---

cmd/contour/serve.go
examples/contour/01-contour-config.yaml
examples/render/contour.yaml
pkg/config/parameters.go
pkg/config/parameters_test.go

Remove the xds-server-version from the Contour configuration file. The original
intent was to allow users to specify the xDS resource version Contour would serve
to Envoy clients, but is now no longer needed.

cmd/contour: Remove xds-server-version config parameter

---

_integration/testsuite/install-contour-working.sh
cmd/contour/bootstrap.go

Set "v2" as the xDS bootstrap default (for now) so that the bootstrapper
doesn't fail if the flag isn't given. Fix the integration test script
to populate the right image tags.

cmd/contour: fix bootstrap xDS version default

---

internal/envoy/v2/regex.go
internal/envoy/v2/regex_test.go
internal/envoy/v2/route.go
internal/envoy/v2/route_test.go

The matcher package is for v2 xDS resource APIs, so needs to be in the internal/envoy/v2 package.

internal/envoy: Refactor the regex file into the v2 package

---

examples/contour/01-contour-config.yaml
examples/render/contour.yaml
site/docs/main/configuration.md

Following up to #3078, remove references to xds-server-version from docs and examples.

site: Remove extra references to xds-server-version

---

cmd/contour/bootstrap.go
internal/envoy/bootstrap.go

Following up to #3069, update the cafile, cert-file, and key-file flag help messages
to be more descriptive.

internal/contour: Update help message for envoy cert flags

---

cmd/contour/serve.go
examples/contour/03-envoy.yaml
examples/render/contour.yaml
internal/protobuf/helpers.go
internal/xds/util.go
internal/xds/v2/contour.go
internal/xds/v3/contour.go

internal/xds: convert v3 protobufs automatically

---

site/_guides/xds-migration.md

Add a small guide in the docs to discuss how xDS Resource API versions are implemented
and how to upgrade from v2 to v3.
Note: This should be referenced in the upgrade guide as well once we get to the release. 
Fixes #3047

site: Add guide on upgrading from xDS v2-->v3

---

.github/workflows/prbuild.yaml

Updates how paths are added when installing deps in Github Actions.
"The Error: The `add-path` command is deprecated and will be disabled soon. Please upgrade to using Environment Files."

.github: Update how deps are added to path in PR workflow

---

cmd/contour/serve.go
internal/protobuf/helpers.go
internal/xds/hash.go
internal/xds/v2/snapshotter.go
internal/xds/v3/snapshotter.go
internal/xdscache/snapshot.go

Add a snapshotter interfact to paper over the go-control-plane API
bifurcation. Use this to populate v3 and v2 resources in the snapshot
cache.
This updates #1898.

internal/xds: convert xDS resources for the envoy xDS server

---

internal/dag/builder_test.go
internal/dag/conditions.go
internal/dag/ingress_processor.go
internal/envoy/v2/regex.go
internal/envoy/v2/regex_test.go
internal/featuretests/v2/route_test.go

The Regex `max_program_size` is deprecated from Envoy and the control plane should
do this validation now. Removes the max_program_size field and adds a regex compile
check to the Ingress resource builder.
Fixes #2933

internal: Remove max_program_size from regex

---

internal/dag/accessors.go
internal/xdscache/v2/endpointstranslator.go

Fixes an issue where services were being added as DAG roots, even
though they're always children of a route, so by definition not
roots. Also fixes a bug in the endpoints translator that did not
properly track already-visited service clusters to avoid processing
them twice.

internal: fix issue with duplicate DAG services & clusters

---

internal/xds/v3/contour.go

Each xDS resource caches the protoufs that it generates from DAG updates
and hands them out to the xDS consumers via a pointer reference. When
we rewrite these to xDS v3, we were modifying the cached values, which
would cause errors if we had to rewrite them again.
This updates #1898.

internal/xds: clone xDS protobufs before rewriting them

---

site/docs/main/config/tls-termination.md
site/docs/v1.4.0/httpproxy.md
site/docs/v1.5.0/httpproxy.md
site/docs/v1.5.1/httpproxy.md
site/docs/v1.6.0/httpproxy.md
site/docs/v1.6.1/httpproxy.md
site/docs/v1.7.0/httpproxy.md
site/docs/v1.8.0/httpproxy.md
site/docs/v1.8.1/httpproxy.md
site/docs/v1.8.2/httpproxy.md
site/docs/v1.9.0/httpproxy.md

Fix a typo in HTTPProxy Client Certificate Validation.
[Link](https://projectcontour.io/docs/v1.9.0/httpproxy/#client-certificate-validation) to the current HTTPProxy Reference which contains the typo.
Signed-off-by: jwenz723 <jwenz723@gmail.com>

site: Fix typo in HTTPProxy reference

---

internal/xds/v3/contour.go

Fixes bug where rewritten resources were not being used in the
discovery responses.
Updates #3096.
Updates #1898.

internal/xds: respond with rewritten v3 xDS resources

---

_integration/testsuite/httpproxy/002-header-condition-match.yaml
_integration/testsuite/httpproxy/003-path-condition-match.yaml
_integration/testsuite/httpproxy/004-https-sni-enforcement.yaml
_integration/testsuite/httpproxy/005-pod-restart.yaml
_integration/testsuite/httpproxy/006-merge-slash.yaml
_integration/testsuite/httpproxy/007-client-cert-auth.yaml
_integration/testsuite/httpproxy/008-tcproute-https-termination.yaml
_integration/testsuite/httpproxy/009-https-misdirected-request.yaml
_integration/testsuite/httpproxy/010-include-prefix-condition.yaml
_integration/testsuite/httpproxy/012-https-fallback-certificate.yaml
_integration/testsuite/httpproxy/013-backend-tls.yaml
_integration/testsuite/httpproxy/014-auth-basic-testserver.yaml
_integration/testsuite/httpproxy/015-http-health-checks.yaml
_integration/testsuite/policies/contour-expect.rego
hack/actions/install-kubernetes-toolchain.sh

Add a new `expect` policy module to make assertions on HTTP responses
from the conformance echo server. This lets us reduce the boilerplate
needed to check HTTP responses in test documents.

testsuite: standardize HTTP checks

---

netlify.toml

Holding as draft until after release is done.

site: update quickstart redirect for 1.10

---

README.md
site/getting-started.md

We don't have a main Troubleshooting page anymore, so just link to the docs home page. I think this is fine for now; we could also add back a landing page for Troubleshooting but then we'd have to keep it up to date with an index.

fix broken troubleshooting links

---

cmd/contour/serve.go
internal/featuretests/v2/envoy.go
internal/xdscache/v2/listener.go
internal/xdscache/v2/listener_test.go
internal/xdscache/v2/visitor_test.go
site/docs/main/configuration.md

Updates the default global minimum TLS version to 1.2 from 1.1.
This forces *all* HTTPProxies and Ingresses to use at least 1.2.
Closes #3010.

internal/xdscache: change default global TLS minimum to 1.2

---

internal/envoy/v3/accesslog.go
internal/envoy/v3/accesslog_test.go
internal/envoy/v3/auth.go
internal/envoy/v3/auth_test.go
internal/envoy/v3/cluster.go
internal/envoy/v3/cluster_test.go
internal/envoy/v3/endpoint.go
internal/envoy/v3/endpoint_test.go
internal/envoy/v3/healthcheck.go
internal/envoy/v3/healthcheck_test.go
internal/envoy/v3/listener.go
internal/envoy/v3/listener_test.go
internal/envoy/v3/regex.go
internal/envoy/v3/regex_test.go
internal/envoy/v3/route.go
internal/envoy/v3/route_test.go
internal/envoy/v3/secret.go
internal/envoy/v3/secret_test.go
internal/envoy/v3/socket_test.go
internal/envoy/v3/stats.go
internal/envoy/v3/stats_test.go
internal/envoy/v3/tcp_keepalive.go
internal/envoy/v3/tls.go
internal/sorter/sorter.go
internal/sorter/sorter_test.go

 internal: Migrate all v2 xDS resource versions to v3 for package internal/envoy/v3

---

internal/xdscache/v3/cluster.go
internal/xdscache/v3/cluster_test.go
internal/xdscache/v3/contour_test.go
internal/xdscache/v3/endpointstranslator.go
internal/xdscache/v3/endpointstranslator_test.go
internal/xdscache/v3/listener.go
internal/xdscache/v3/listener_test.go
internal/xdscache/v3/route.go
internal/xdscache/v3/route_test.go
internal/xdscache/v3/secret.go
internal/xdscache/v3/secret_test.go
internal/xdscache/v3/server_test.go
internal/xdscache/v3/visitor_test.go

Depends on #3120 
Depends on #3118 
Commit 1486fda41aa94bbdcf88cb885664e2d4f8a43ddb is the only one with actual changes.

internal/xdscache: add v3 package

---

.codespell.ignorewords
.codespell.skip
.github/workflows/prbuild.yaml
Makefile
tools.go

**This PR includes commits from PR #3098**
As discussed in #3098, creating a PR which replaces `misspell` with `codespell`. IMO `misspell` can stay enabled in `golangci-lint`, as it may still catch some typos which won't be covered by `codespell`.

Replace misspell with codespell

---

README.md

Add a link to the README that points to the project's roadmap.

README.md: Add link to roadmap

---

cmd/contour/serve.go

Updates #3010.
Actually updates the default global minimum TLS version
to 1.2.

cmd/contour: update minimum TLS version to 1.2

---

internal/envoy/v3/listener.go
internal/envoy/v3/listener_test.go

Using some HTTP filter names from the go-control-plane wellknown package give warnings
due to being deprecated from Envoy.
This updates the names to use TypedConfigs which are matched differently in Envoy
and won't have the same issues with deprecation.
Fixes #2479

internal/envoy: moved to typed configs for httpfilters

---

.codespell.skip
Makefile
hack/codespell.sh

Adds additional exceptions to the code spell check list as well as move the check for the binary to hack scripts mirroring how other checks are done. 

codespell: Add more exceptions to .codespell.skip and move binary check

---

design/httpproxy-prefix-rewrite.md
design/tls-certificate-delegation.md

Fix codespell errors causing CI failure

---

site/docs/main/start-contributing.md

Adds contour operator to the contributors page.
/assign @stevesloka @skriss 

Updates Contributing Doc for Contour Operator

---

Makefile
examples/contour/03-envoy.yaml
examples/render/contour.yaml
site/_resources/envoy.md

Updates Envoy to the latest minor version.
Contains the changes listed here: https://www.envoyproxy.io/docs/envoy/v1.16.1/version_history/current

chore: update Envoy to v1.16.1

---

_integration/testsuite/httpproxy/004-https-sni-enforcement.yaml

Disables 004-https-sni-enforcement until the cause for the flaky
behavior can be found and fixed.

_integration: temporarily disable flaky SNI test

---

.golangci.yml

Ignores apis/projectcontour/v1/kubeconditions.go when linting because
this file is copy-pasted from k8s.io/apimachinery and does not conform
to Contour's linting rules -- in particular, it has a different
copyright header.
This will clear up the persistent lint failure on `main`.

golangci-lint: ignore kubeconditions.go file

---

apis/projectcontour/v1/detailedconditions.go
apis/projectcontour/v1/helpers.go
apis/projectcontour/v1/helpers_test.go
internal/contour/metrics.go
internal/dag/extension_processor.go
internal/dag/httpproxy_processor.go
internal/dag/status_test.go
internal/featuretests/v3/authorization_test.go
internal/featuretests/v3/featuretests.go
internal/featuretests/v3/replaceprefix_test.go
internal/fixture/detailedcondition.go
internal/status/cache.go
internal/status/proxystatus.go

Adds ErrorType enum to be used for the conditionType passed
when setting Error status on HTTPProxy resources.
Updates: #2988

apis: Add ErrorType constants to DetailedConditions

---

apis/projectcontour/v1/detailedconditions.go
apis/projectcontour/v1/helpers.go
internal/featuretests/v3/featuretests.go
internal/fixture/detailedcondition.go
internal/status/proxystatus.go

Following up to https://github.com/projectcontour/contour/pull/3148#discussion_r534281248 I clicked merge before seeing this comment come in. 
This restores the variable `ValidConditionType` which was renamed in #3148 to keep the api stable and not require a new version. 
Updates: #2988

Restore 'ValidConditionType' to follow api versioning rules

---

site/_guides/xds-migration.md

Just a quick typo-fix in the migration guide of v2->v3. I took a guess at what year it meant. ;-)
Signed-off-by: Sebastian Schulze <github.com@bascht.com>

site/guides: Fix typo in year of v2->v3 xDS API migration guide

---

internal/dag/ingress_processor.go

This change corrects the debug message when mutual authentication is
misconfigured with a missing secret.  When Ingress was being processed,
the error was printed with empty field secret="<nil>" while the intention
was to print the secret name: secret="namespace/secretname".

internal/dag: fix debug printout for client cert secret

---

internal/xdscache/v3/endpointstranslator.go

Fixes a bug where the `entries` map was not correctly being
guarded by its mutex against concurrent reads/writes.
Fixes #3193.

internal/xdscache: fix concurrent map access bug

---

cmd/contour/serve.go
internal/dag/cache.go
internal/dag/cache_test.go

This change adds secret references from the configuration file to the list of
secrets that will trigger DAG rebuild.  Previously only secrets referred by
HTTPProxy and Ingress resources were considered.  The result was that secrets
referred by fallback-certificate and envoy-client-certificate config file entries 
were not picked up correctly if they were created after HTTPProxy or Ingress.
Fixes #3190 

internal/dag: trigger rebuild for configured secrets

---

cmd/contour/cli.go
cmd/contour/contour.go
internal/xds/v3/callbacks.go
internal/xds/v3/callbacks_test.go

Updates the CLI commands to use xDS v3. Also fixes a panic
when no user agent build version is present.
Updates #3200.

cmd/contour: update CLI commands to use xDS v3

---

cmd/contour/servecontext.go

Should log `lerr` since that was the error from loading the config

cmd/contour: Log correct error on failed tls.Config creation

---

CONTRIBUTING.md
apis/projectcontour/v1/httpproxy.go
apis/projectcontour/v1alpha1/extensionservice.go
examples/contour/01-crds.yaml
examples/render/contour.yaml
internal/dag/dag.go
internal/envoy/v3/listener.go
internal/featuretests/v3/authorization_test.go
internal/featuretests/v3/replaceprefix_test.go
internal/xds/hash.go
internal/xds/v3/contour_test.go
pkg/config/parameters.go
site/_guides/external-authorization.md
site/docs/main/config/annotations.md
site/docs/main/config/api-reference.html
site/docs/main/config/client-authorization.md
site/docs/main/config/request-routing.md
site/docs/main/configuration.md

Updates comments, documentation, etc. to exclusively reference
xDS v3.
Closes #3200.

change remaining v2 xDS references to v3

---

Makefile
examples/contour/03-envoy.yaml
examples/render/contour.yaml

The compatibility matrix will need to be updated when 1.10.1 and 1.11 are cut.

examples: update Envoy to 1.16.2

---

Makefile
examples/contour/03-envoy.yaml
examples/render/contour.yaml

Note this PR is against the `release-1.10` branch, for the `v1.10.1` release.

[release-1.10] examples: update Envoy to 1.16.2

---

site/docs/main/troubleshooting/contour-xds-resources.md

This patch fixes wrong CA cert path for contour cli option.

Fix CA cert path for contour cli

---

CODEOWNERS

Currently we have Github configured to auto-request reviews from the @maintainers group, however, it's not working. I think this is because the PR's are opened against the `main` branch which is protected. Adding a `CODEOWNERS` file will allow the review to work properly: https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/about-code-owners

add CODEOWNERS file to make Github reviews work properly

---

internal/dag/dag.go
internal/dag/status_test.go

The GetProxyStatusesTesting() was left in the dag package to allow for an easy way to mutate
values stored in the status.Cache into an easier format to consume. This removes the helper
function, leaving the work to implement a different pattern to #2969.
Fixes #2967

internal/dag: Remove GetProxyStatusesTesting function

---

.github/workflows/prbuild.yaml
Dockerfile

Gives us security fixes and general tool/compiler/etc. fixes: https://golang.org/doc/devel/release.html#go1.15

Bump build image and CI to go 1.15.6

---

internal/envoy/v3/bootstrap.go
internal/envoy/v3/bootstrap_test.go

Adds required fields that are now validated in Envoy 1.17.0
Merge before https://github.com/projectcontour/contour/pull/3245 to ensure upgrade on Envoy 1.16.2 is validated with this change

internal/envoy/v3: Add required ConfigSource fields for Envoy 1.17.0

---

internal/envoy/v3/bootstrap.go
internal/envoy/v3/bootstrap_test.go
internal/envoy/v3/cluster.go
internal/envoy/v3/cluster_test.go
internal/featuretests/v3/envoy.go
internal/featuretests/v3/externalname_test.go
internal/xdscache/v3/cluster_test.go

Replaces the deprecated cluster Http2ProtocolOptions field
with TypedExtensionProtocolOptions.
Fixes the lint errors that came up on `main` after upgrading go-control-plane to v0.9.8 (these didn't show up on the PR lint run, that's a separate issue).
https://github.com/projectcontour/contour/runs/1703439466
ref. https://www.envoyproxy.io/docs/envoy/v1.17.0/api-v3/extensions/upstreams/http/v3/http_protocol_options.proto#envoy-v3-api-msg-extensions-upstreams-http-v3-httpprotocoloptions

internal: update HTTP/2 protocol options config

---

apis/projectcontour/v1/httpproxy.go
examples/contour/01-contour-config.yaml
examples/contour/01-crds.yaml
examples/render/contour.yaml
internal/annotation/annotations.go
internal/envoy/v3/listener_test.go
internal/envoy/v3/socket_test.go
internal/envoy/v3/tls.go
site/docs/main/config/api-reference.html
site/docs/main/config/tls-termination.md
site/docs/main/configuration.md

Support for TLS 1.1 has been officially dropped from Contour.
This PR updates all code, documentation and examples to indicate
that 1.2 is now the minimum/default.
Closes #3246.
Updates #2777.

drop all TLS 1.1 references

---

internal/dag/cache.go
internal/dag/cache_test.go
internal/k8s/informers.go

The service-apis design calls out that GatewayClasses & TCPRoutes won't be watched
or processed by Contour the controller, so this removes them from processing since
they won't be used.
Updates #3213

internal/dag: Remove processing of service-apis GatewayClass/TCPRoute

---

examples/contour/02-role-contour.yaml
examples/render/contour.yaml
internal/dag/cache.go
internal/dag/cache_test.go
internal/k8s/informers.go

Adds informers for service-apis TLSRoute & BackendPolicy
which were missing from Contour.

internal/dag: Add informers for TLSRoute & BackendPolicy

---

internal/featuretests/v3/authorization_test.go
internal/featuretests/v3/corspolicy_test.go
internal/featuretests/v3/downstreamvalidation_test.go
internal/featuretests/v3/featuretests.go
internal/featuretests/v3/ingressclass_test.go
internal/featuretests/v3/replaceprefix_test.go

Adds an IsInvalid() helper to match the existing IsValid() helper,
and uses them in all the feature tests to be more concise.
Also adds comments about the internal/featuretests event handler
being blocking.

internal/featuretests: use IsValid/IsInvalid helpers

---

.github/workflows/prbuild.yaml
Makefile
hack/generate-crd-deepcopy.sh
hack/generate-rbac.sh
hack/release/make-release-tag.sh

Removes unneeded setting of -mod=vendor from code-gen scripts
and calls to `go mod vendor` to remove requirement for a local
vendor/ directory.
Closes #3276.

remove usages of vendor/ directory

---

hack/site-proofing/cibuild
site/docs/main/configuration.md

Returns frequent false positive timeouts
See https://github.com/projectcontour/contour/pull/3292/checks?check_run_id=1809735846, checking for https://tools.ietf.org/html/rfc7540#section-9.1.1
Also syncs the example contour configmap with the actual file to ensure the siteproof check reruns in CI

Ignore tools.ietf.org in site proof check

---

.golangci.yml
internal/envoy/v3/bootstrap.go
internal/envoy/v3/bootstrap_test.go
internal/envoy/v3/cluster.go
internal/envoy/v3/cluster_test.go
internal/featuretests/v3/envoy.go
internal/featuretests/v3/externalname_test.go
internal/xdscache/v3/cluster_test.go

Reverts commit 78c434fcd9aa8e08f12ee5def7c0e215c0c805c5, which made
a Contour change that was not backwards-compatible with Envoy 1.16.
Also ignores lint errors which were the original motivation for #3260.

Revert "internal: update HTTP/2 protocol options config (#3260)"

---

internal/annotation/annotations.go
internal/annotation/annotations_test.go
internal/dag/cache.go
internal/dag/httpproxy_processor.go
internal/dag/status.go
internal/k8s/objectmeta.go
internal/k8s/statusaddress.go
internal/status/cache.go

Replaces k8s.Object and metav1.ObjectMetaAccessor with metav1.Object
usage, which all API objects implement and allows direct access to
metadata fields.

internal: use metav1.Object for metadata access

---

Makefile
_integration/testsuite/install-service-apis.sh

Add service-apis to CI tests which will enable integration tests to be built as
the service-apis work is merged into Contour.
- Install the v0.1.0 service-apis CRDs

ci: Enable service-apis when running integration tests

---

cmd/contour/serve.go
examples/contour/02-role-contour.yaml
examples/render/contour.yaml
internal/annotation/annotations.go
internal/annotation/annotations_test.go
internal/dag/builder_test.go
internal/dag/cache.go
internal/dag/cache_test.go
internal/dag/ingress_processor.go
internal/dag/policy.go
internal/dag/policy_test.go
internal/k8s/informers.go

Add support for watching networking.k8s.io/v1 Ingress resources and add/remove
from internal Cache later allowing these objects to be implemented.

internal: Add support for watching ingress/v1 resources

---

examples/contour/01-contour-config.yaml
examples/render/contour.yaml
pkg/config/parameters.go
pkg/config/parameters_test.go
site/docs/main/configuration.md

Adds a gateway reference name/namespace parameter to the config file so that when using service-apis, users are able to define which Gateway this instance of Contour should configure.
Updates #3213

pkg/config: Add Gateway reference parameters to config file

---

site/docs/main/config/request-routing.md
site/docs/v1.12.0/config/request-routing.md

The 'WeightedLeastRequest' load balancer strategy in the docs outlined some text that it wasn't useful outside of just testing. This is due to copying from the Envoy docs (v1.5) when this algorithm was new and has evolved much since that time, we just never updated the docs to match.
This came up on the Community call today (@moderation). 
v1.17 docs: https://www.envoyproxy.io/docs/envoy/v1.17.0/intro/arch_overview/upstream/load_balancing/load_balancers#weighted-least-request
Old docs: https://www.envoyproxy.io/docs/envoy/v1.6.0/intro/arch_overview/load_balancing.html#weighted-least-request

site: Update WeightedLeastRequestDescription in docs

---

design/service-apis-implementation.md

This is a WIP of the Service APIs implementation. It's been slow going, as I've been trying to check as I went that I've got the Service APIs intent correct, and that the way we'll implement is relatively consistent with Contour's current state.
Interested mostly in feedback on the high-level parts, did I miss anything?
There's quite a bit more detail required, particular for HTTPRoute and TLSRoute.
Very interested to hear about any other areas you all think I should cover as part of this design.

design: Service APIs implementation

---

site/docs/main/config/rate-limiting.md
site/docs/v1.12.0/config/rate-limiting.md

Properly quotes the header value in the rate limiting example YAML.
Also removes statement about x-envoy-ratelimited header being added
by Envoy since it's not true.
Closes #3318.

site/docs: fix rate limiting docs bugs

---

_integration/testsuite/httpproxy/018-external-name-service.yaml

The ExternalName integration test has turned out to be
flaky. This PR skips it for now until a more robust test
can be implemented.

_integration: disable flaky test

---

cmd/contour/serve.go
cmd/contour/servecontext.go

Deprecate the '--experimental-service-apis' flag to `contour serve` in favor of using the gateway.name & gateway.namespace config file options.
Follow up to #3310 to have a place to document the deprecations related to `contour serve` flags. 
Updates #3213

cmd/contour: Deprecate 'UseExperimentalServiceAPITypes' flag

---

pkg/config/parameters.go

This commit updates the timeout validation checks in
`pkg/config/parameters.go` to report the actual value
that failed validation in error messages. Previously
they all reported `t.RequestTimeout`.
Fixes #3328
Signed-off-by: Jesse Malone <jmalone@vmware.com>

pkg/config: Fix timeout validation error messages

---

internal/envoy/v3/accesslog.go
internal/envoy/v3/accesslog_test.go

Replace usage of deprecated field
envoy.extensions.access_loggers.file.v3.FileAccessLog.json_format
with
envoy.extensions.access_loggers.file.v3.FileAccessLog.log_format
Fixes: #3210
Signed-off-by: Amey Bhide <amey15@gmail.com>

Update usage of deprecated field FileAccessLog.json_format

---

site/docs/v1.12.0/config/request-rewriting.md

The docs for PR #3269 were inadvertently left out of the v1.12.0
versioned docs, this PR adds them.

site/docs: add docs for #3269 to v1.12

---

internal/dag/httpproxy_processor.go
internal/dag/status_test.go

Add validation to ensure that Passthrough and Fallback aren't specified
at the same time.
Fixes: #3197
Signed-off-by: Amey Bhide <amey15@gmail.com>

HTTPProxy: Add validation check

---

_integration/testsuite/httpproxy/018-external-name-service.yaml

Re-enables the ExternalName service integration test
and uses in-cluster services as the targets of the
ExternalName services to avoid flaky dependencies on
external domains.
Closes #3320.

_integration: fix 018-external-name-service test

---

_integration/testsuite/httpproxy/019-local-rate-limiting.yaml

Makes the local rate limit integration test less flaky by
first creating an HTTPProxy without a rate limit, and waiting
until it serves 200's before adding a rate limit and counting
allowed requests. This replaces the previous method of waiting
for the upstream service to have endpoints, which was less
reliable.

_integration: improve local rate limit test robustness

---

site/docs/main/config/api-reference.html

The generated API reference docs were slightly out-of-date,
this PR updates them.

site/docs: update generated API docs

---

hack/actions/check-uncommitted-codegen.sh

Adds the API reference docs file to the list of targets
to check for uncommitted codegen.
Closes #3344.

hack: check API ref docs for uncommitted codegen

---

.github/PULL_REQUEST_TEMPLATE/pull_request_template.md

The PR template had some explanatory text, but it was commented out, meaning that
it wouldn't be visible when you create your PR.
This uncomments the text, and makes some small updates to th template to make it
clearer for new contributors.

admin: Updates the PR template so that the text is visible

---

go.mod
go.sum
site/docs/main/config/api-reference.html

Updates the API reference docs generator to v0.3.0, primarily
to get a fix that sorts API groups/versions in the output so
it's deterministic.

deps: upgrade gen-crd-api-reference-docs to v0.3.0

---

cmd/contour/serve.go
internal/dag/builder_test.go
internal/dag/serviceapis_processor.go

Super rough initial implementation for service-apis.
Needs a lot of love, but at least has started to work while still behind the feature flag in Contour. Using this sample yaml I can get things to route properly:
```
kind: Gateway
apiVersion: networking.x-k8s.io/v1alpha1
metadata:
name: contour-gateway
spec:
gatewayClassName: contour-class
listeners:
- protocol: HTTP
port: 80
routes:
kind: HTTPRoute
selector:
matchLabels:
app: filter
namespaces:
from: "All"
---
kind: HTTPRoute
apiVersion: networking.x-k8s.io/v1alpha1
metadata:
name: http-filter-1
namespace: projectcontour-roots 
labels:
app: filter
spec:
hostnames:
- local.projectcontour.io
rules:
- matches:
- path:
type: Prefix
value: /
forwardTo:
- serviceName: rootapp
port: 80
```
Updates #2287
Signed-off-by: Steve Sloka …

internal/dag: Initial implementation for service-apis

---

site/_data/github-labels.yaml

In #3350, duplicate labels were added, this resolves that to make sure the labels are unique.
Fixes #3368

ci: fix Github labels

---

.github/workflows/prbuild.yaml
examples/ratelimit/02-ratelimit.yaml

The CI job was missing the `yamllint` & `flags` tasks to verify the yaml format as well as flags.
This adds those back in as well as fixes the one issue found with the comment on the ratelimit example.

ci: Add missing linters to CI runs

---

Makefile
_integration/testsuite/gatewayapi/001-path-condition-match.yaml

Adds a simple integration test based upon the httpproxy/003-path-condition-match.yaml test that already
exists for HTTPProxy resources, but aligns to GatewayAPI.
Updates #2287

integration: Add simple integration test for GatewayAPIs

---

hack/site-proofing/cibuild

The site proof check which runs on each run checks for invalid links, however, the links
to envoyproxy.io seem to fail the site check. This adds the envoyproxy.io site to the ignore
list which will skip this site from getting checked.

ci: Add envoyproxy.io to ignore list for site-proof check

---

Makefile

integration-tests require integration-tester tool to be installed.
If its not installed, the execution fails after doing all the test setup.
Instead check if required tool is installed right at start.

Makefile: Check if integration-tester is installed before executing tests

---

hack/actions/install-kubernetes-toolchain.sh

Updates KinD and kubectl to latest for Kubernetes 1.20.x
support.

hack: upgrade KinD and kubectl versions

---

site/_contributors/02-james-peach.md
site/_contributors/03-tong-liu.md

This will remove James Peach from the active maintainer list as he has moved to emeritus maintainer status, and also remove Tong Liu as he has moved to another role.

Remove James and Tong from the website

---

netlify.toml
site/_guides/gateway-api.md

Adds a guide for using Gateway API with contour/contour-operator. Note that `netlify.toml` was updated for v1.13.0 versioned redirects .
xref: https://github.com/projectcontour/contour-operator/issues/106

Adds Gateway API User Guide

---

netlify.toml

Updates Netlify quickstart links for the v1.13.0 release.

Updates Netlify Quickstart Links for v1.13.0 Release

---

site/_guides/gateway-api.md

The link in https://projectcontour.io/guides/gateway-api/
causes 404 error without this fix.
/cc @youngnick @danehans

Update link to gateway-apis-implementation.md

---

_integration/testsuite/httpproxy/020-global-rate-limiting.yaml
_integration/testsuite/install-ratelimit-service.sh
internal/featuretests/v3/globalratelimit_test.go
internal/xdscache/v3/route.go

Fixes a bug where global rate limit policies were being ignored
when defined at the virtual host level on secure vhosts.
Fixes #3409.

internal/xdscache: include global rate limits for secure vhosts

---

cmd/contour/ingressstatus.go
internal/k8s/statusaddress.go

Fixes an issue where non-pointers were being passed to
the StatusAddressUpdater when the load balancer address
changed, which was resulting in HTTPProxies/Ingresses
not immediately getting updated with the new address.
Fixes #3411.

cmd/contour: pass pointers to StatusAddressUpdater

---

Makefile
examples/contour/03-envoy.yaml
examples/render/contour.yaml

examples: update Envoy to 1.17.1

---

cmd/contour/serve.go
examples/contour/02-role-contour.yaml
examples/render/contour.yaml
internal/dag/cache.go
internal/dag/cache_test.go
internal/k8s/informers.go

The RouteBindingSelector in Gateway API has an option to only process routes which exist
in a namespace based upon a selector defined in the Gateway.
When "Selector" is chosen then only Routes in namespaces selected by the selector may be used by this Gateway (https://gateway-api.sigs.k8s.io/spec/#networking.x-k8s.io/v1alpha1.RouteSelectType).
_Added release note action label since this updates RBAC permissions, but only needed if Gateway APIs are present._ 
Updates #3401

internal/dag: Watch namespaces from k8s api

---

.github/workflows/prbuild.yaml
_integration/testsuite/make-kind-cluster.sh

Runs integration tests against the three supported minor versions
of Kubernetes.
Closes #3396.

CI: run integration tests against all supported Kubernetes versions

---

cmd/contour/serve.go
examples/contour/01-contour-config.yaml
examples/render/contour.yaml
internal/dag/builder_test.go
internal/dag/httpproxy_processor.go
internal/dag/policy.go
internal/dag/policy_test.go
pkg/config/parameters.go
pkg/config/parameters_test.go
site/docs/main/configuration.md

Second part of #3258
Add a policy section to the Contour configuration file with request-headers and response-headers fields that allow setting or removing default request and response headers unless overridden by users in their HTTPProxy objects.
Signed-off-by: Keith Burdis <keith.burdis@gs.com>

Default header policy

---

_integration/testsuite/httpproxy/004-https-sni-enforcement.yaml

The SNI integration test was disabled in #3163
due to unexplained sporadic failures. The failures
have not been reproducible in recent testing. It's
possible that a change made to Contour since #3163
has eliminated the source of the test flake, but
also possible that the test is still flaky and just
did not reproduce during testing.

_integration: re-enable SNI test

---

cmd/contour/serve.go

A previous PR inadvertently duplicated a block of
code. This PR removes the duplicate.

cmd/contour: remove duplicated block of code

---

_integration/testsuite/httpproxy/020-global-rate-limiting.yaml
_integration/testsuite/install-ratelimit-service.sh
internal/envoy/v3/ratelimit.go
internal/envoy/v3/ratelimit_test.go
internal/featuretests/v3/globalratelimit_test.go

Fixes a bug where a generic key descriptor's key
was not being configured in the Envoy descriptor
if it was specified, resulting in Envoy always
generating the default key of "generic_key".
Fixes #3443.

internal/envoy: use generic key descriptor's key

---

internal/featuretests/v3/backendcavalidation_test.go
internal/featuretests/v3/downstreamvalidation_test.go
internal/featuretests/v3/globalratelimit_test.go
internal/featuretests/v3/listeners_test.go
internal/featuretests/v3/localratelimit_test.go
internal/featuretests/v3/rootnamespaces_test.go
internal/featuretests/v3/tcpproxy_test.go
internal/featuretests/v3/timeouts_test.go
internal/featuretests/v3/tlscertificatedelegation_test.go

Replaces the many repeated definitions of the default HTTP listener
with calls to defaultHTTPListener(). In places where a non-default
HTTP listener is needed, uses the default as a starting point and
applies modifications to it. This reduces copy-pasted boilerplate.

internal/featuretests: use helper for default HTTP listener

---

internal/dag/dag.go
internal/envoy/v3/route.go
internal/envoy/v3/route_test.go

Adds support for exact match type which will be used by IngressV1 & GatewayAPI.

internal: Add support for exact path match type

---

internal/dag/cache.go

Namespaces don't have a "namespace", so keying off of them is incorrect, so this
changes the namespace key to be scoped to only the name.
Updates #3466

internal/dag: Change key for namespaces cache to be string

---

go.mod
go.sum
internal/envoy/v3/listener.go
internal/envoy/v3/listener_test.go
internal/envoy/v3/route.go
internal/envoy/v3/route_test.go

- Strips host port using the strip_any_host_port field on HTTP connection manager
- All filter/router processing will be done internally without the port number attached
- Ensures <HOST>:<PORT_NUM> is accepted and treated the same as the plain <HOST>
- Removes Lua logic to check port number as it is no longer needed, the filter will never see the port on the :authority header
- Removes <HOST>:* wildcard domain match in router, the router will never see the port on the domain to match
- Note that this will strip the port from the Host/:authority header sent to upstreams
- Bumps go-control-plane as latest tagged release is not new enough and does not include the field used
- Will be useful in implementing wildcard host matching, makes internal logic simpler
See: …

internal/envoy/v3: Strip port from hostname

---

internal/dag/builder_test.go
internal/dag/cache.go
internal/dag/ingress_processor.go
internal/featuretests/v3/route_test.go

- Overlaying Ingresses in reverse order
- A default backend is overriden by a no-host prefix '/' rule
- default backend is prepended to list of Ingress Rules to make this
work
Updates https://github.com/projectcontour/contour/issues/3461

Ingress: Default backend overridden by Ingress rule and add some additional tests

---

Dockerfile
site/_guides/fips.md

Details how to build Contour and Envoy with Boring Crypto and how to
configure Contour with FIPS approved ciphers
Fixes https://github.com/projectcontour/contour/issues/2878

Add FIPS guide

---

.github/workflows/prbuild.yaml
Makefile

Release notes: https://golang.org/doc/devel/release.html#go1.16.minor

Bump go to 1.16.2

---

cmd/contour/serve.go
examples/contour/01-contour-config.yaml
examples/render/contour.yaml
internal/envoy/v3/ratelimit.go
internal/envoy/v3/ratelimit_test.go
internal/xdscache/v3/listener.go
internal/xdscache/v3/listener_test.go
pkg/config/parameters.go
site/docs/main/configuration.md

Adds the EnableXRateLimitHeaders field to the config file's
RateLimitService block. When set to true, adds the X-RateLimit
headers to responses that required checking the RLS.
Closes #3431.

cmd/contour: add EnableXRateLimitHeaders config file setting

---

internal/dag/cache.go
internal/dag/cache_test.go

If a secret referenced by a Gateway or a service referenced by a HTTPRoute changes, the dag
should be rebuilt.
Also, adds missing tests for ingress, httpproxy, and secret delegation that were missing.
Closes #3476.

internal/dag: Rebuild DAG if secret or service related to a Gatway or HTTPRoute changes

---

internal/envoy/v3/bootstrap.go

Fixes: #3264
Signed-off-by: Amey Bhide <amey15@gmail.com>

Change config/resources directory permissions 075 -> 077

---

cmd/contour/serve.go
internal/dag/builder_test.go
internal/dag/cache.go
internal/dag/cache_test.go
pkg/config/parameters.go
pkg/config/parameters_test.go

Takes away the default gatewayapi gateway configuration and makes it optional. This helps determine
which listener configuration values should be used for Contour.
This does change behavior in the config file, however, it's against an alpha api without any usage so to me this is fine to change. 
Fixes #3479

pkg/config: Make gatewayconfig optional

---

internal/xds/v3/callbacks.go
internal/xds/v3/callbacks_test.go

The `handling v3 xDS resource request` info message is quite verbose on the Contour setup with many Envoys, so it makes sense to set the log level for the message to debug.
Fixes: https://github.com/projectcontour/contour/issues/3483

Use debug log level for the "handling v3 xDS resource request" log message

---

site/docs/main/config/annotations.md
site/docs/v1.13.1/config/annotations.md

The max-retriess annotation documentation was incorrect stating the default if not
specified was 1024 when it's actually Envoy's default of 3.

site: Fix wrong default for max-retries annotation.

---

_integration/testsuite/gatewayapi/001-path-condition-match.yaml
internal/dag/builder_test.go
internal/dag/gatewayapi_processor.go

Filter the HTTPRoutes that match against the namespace field on any struct
looking for if they match the "Same", "All", or "Selector" types.
Fixes #3401

internal/dag: Add namespace selector check for Gateways

---

internal/dag/conditions.go
internal/dag/dag.go
internal/envoy/v3/route.go
internal/sorter/sorter.go
internal/sorter/sorter_test.go
internal/xdscache/v3/route.go
internal/xdscache/v3/route_test.go

- This change is currently a no-op but in the future when we add more
path match types it will become important
- Extracted as its own change since it is relatively large and will
complicate reviewing other PRs
- When we add path segment prefix matching (in addition to the string
prefix matching we do today) for Ingress v1 this will become important
- This new type of Prefix matching has to be implemented as a regex
but should still sort after user requested regex matches
- Also adds sorting of Exact path matches which should come before all
other path match types
- Adds constants for the various header match types allowed
- Some cons: this change means we end up iterating the routes on a vhost twice each

internal/xdscache/v3: Sort dag Routes before converting to Envoy Routes

---

internal/dag/builder_test.go
internal/dag/gatewayapi_processor.go

Only process currently supported types of HTTPRoute on the Gateway.Listener.Selector.Kind field.
Updates #3401

internal/dag: Only process Gateway.Listener.Selector.Kind of HTTPRoute

---

internal/sorter/sorter.go
internal/sorter/sorter_test.go

Segment matches are more specific than string prefixes so they should
sort first.

internal/sorter: Sort Route prefix segment matches before string

---

apis/projectcontour/v1alpha1/extensionservice.go
examples/contour/01-crds.yaml
examples/render/contour.yaml
site/docs/main/config/api-reference.html

Only h2 or h2c options are supported.
Extension service will connect contour with other services that use gRPC
protocol. gRPC only works with HTTP/2. So TLS option is not relevant
here.
Fixes: https://github.com/projectcontour/contour/issues/3497

Remove not supported TLS value in doc

---

cmd/contour/serve.go

Fixes two issues with configuring request/response headers policy.
The first issue was that the user's configured request headers to
set were inadvertently also being used as the response headers to
set. The second issue was that some harmless empty strings were
being added to the lists of request/response headers to remove.

cmd/contour: properly configure request/response headers policy

---

cmd/contour/serve.go
internal/dag/accessors.go
internal/dag/builder_test.go
internal/dag/dag.go
internal/dag/gatewayapi_processor.go
internal/dag/httpproxy_processor.go
internal/dag/ingress_processor.go
internal/featuretests/v3/listeners_test.go
internal/xdscache/v3/listener.go
internal/xdscache/v3/listener_test.go
internal/xdscache/v3/visitor_test.go

Since the GatewayAPI Gateway needs to be the driver of the ports/addresses that get exposed, we need a way to push that through to Envoy. At the same time, if there are multiple listeners, need a way to provision that to Envoy. 
This sets up the DAG to accept multiple listeners vs the current static `insecure` & `secure`.
Updates #2287

internal: Allow listeners to be created dynamically if provided otherwise defaulted

---

internal/contour/metrics_test.go
internal/dag/builder.go
internal/dag/gatewayapi_processor.go
internal/dag/status_test.go
internal/k8s/kind.go
internal/k8s/status.go
internal/status/cache.go
internal/status/cache_test.go
internal/status/httproutestatus.go
internal/status/httproutestatus_test.go
internal/status/proxystatus.go
internal/status/proxystatus_test.go

- Update the status package to process GatewayAPI HTTPRoutes.
- Update the dag.GatewayAPIProcessor to set status.
Fixes #3436

internal: Allow status on HTTPRoutes to be set

---

cmd/contour/serve.go
cmd/contour/serve_test.go

Extracts all logic in doServe() related to constructing
the dag.Builder into a helper function.
Updates #3453.

cmd/contour: extract getDAGBuilder helper function

---

internal/dag/builder_test.go

Fixes the "insert basic single route, single hostname, gateway All namespace selector" test which
should return valid listeners given a HTTPRoute in any namespace.
The test was invalid since the service namespace in the forwardTo did not match the route's namespace.
Fixes #3535

internal/dag: Fix GatewayAPI Namespace Selector All test

---

internal/dag/policy.go
internal/dag/policy_test.go

Fixes a case where default header policies would not be applied unless headers were set in the HTTPProxy

internal/dag: always apply default headers

---

_integration/testsuite/gatewayapi/002-header-condition-match.yaml
internal/dag/builder_test.go
internal/dag/gatewayapi_processor.go
internal/dag/status_test.go
internal/status/httproutestatus.go

This patch adds Exact HTTPHeaderMatch support.
Fixes https://github.com/projectcontour/contour/issues/3356
/cc @stevesloka @youngnick @sunjayBhatia

Implement Exact HTTPHeaderMatch

---

_integration/testsuite/gatewayapi/003-invalid-forwardto.yaml
internal/dag/builder_test.go
internal/dag/dag.go
internal/dag/gatewayapi_processor.go
internal/dag/status_test.go
internal/envoy/v3/route.go
internal/envoy/v3/route_test.go
internal/xdscache/v3/route.go

If the service on an HTTPRoute.Spec.Rule.ForwardTo is invalid or missing, an HTTP503 should be returned.
Fixes #3553

internal/dag: Return an HTTP503 if the service on an invalid ForwardTo

---

internal/dag/builder_test.go

Refactors a bit of the builder tests to add helpers to generate some of the GatewayAPI
types used in various tests.

internal/dag: Refactors builder_test gatewayapi helpers

---

examples/contour/02-role-contour.yaml
examples/render/contour.yaml
internal/k8s/informers.go

The current RBAC permissions didn't allow for status to be updated from the Contour service account. This updates those so it can write status. 

update RBAC permissions for gateway-api types to allow for Status to be updated

---

internal/envoy/v3/bootstrap.go
internal/envoy/v3/bootstrap_test.go
internal/envoy/v3/cluster.go

Strict/Logical DNS clusters fail to parse ipv6 IPs and according to the
Envoy documentation should not use an IP
See: https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/service_discovery#arch-overview-service-discovery-types
See: https://github.com/envoyproxy/envoy/issues/10489
Limited to bootstrap clusters for now
Also cleans up whitespace in tests
Updates: #3564
Updates: #3284

internal/envoy/v3: Bootstrap clusters with IPs configured as STATIC

---

examples/contour/02-role-contour.yaml
examples/render/contour.yaml
internal/dag/cache.go
internal/dag/cache_test.go
internal/k8s/informers.go

Adds informers to add TCP/UDP Routes to the k8s cache to allow setting status
on them in a future PR.
Updates #3441 #3442

internal/dag: Add informers for TCPRoutes & UDPRoutes

---

_integration/testsuite/gatewayapi/004-tls-gateway.yaml
internal/dag/builder_test.go
internal/dag/gatewayapi_processor.go
internal/dag/gatewayapi_processor_test.go
internal/dag/status_test.go
internal/featuretests/v3/featuretests.go
internal/featuretests/v3/gatewayapi_test.go

Gateways can now supply certificateRefs which allow the Gateway & it's selected HTTPRoutes to
terminate TLS at the Envoy listener.
Updates #3438

internal: Add support for TLS on Gateway

---

_integration/testsuite/gatewayapi/004-post-header-modifier.yaml
_integration/testsuite/gatewayapi/005-pre-header-modifier.yaml
_integration/testsuite/gatewayapi/006-rewritehost.yaml
_integration/testsuite/policies/contour-expect.rego
internal/dag/builder_test.go
internal/dag/dag.go
internal/dag/gatewayapi_processor.go
internal/dag/policy.go
internal/dag/status_test.go
internal/envoy/route.go
internal/envoy/v3/route.go
internal/status/httproutestatus.go
internal/xdscache/v3/route.go

This patch implements HTTPRouteFilterRequestHeaderModifier for HTTPRouteFilter.
[HTTPRouteFilter](https://gateway-api.sigs.k8s.io/spec/#networking.x-k8s.io/v1alpha1.HTTPRouteFilter) is defined in `HTTPRouteForwardTo` and `HTTPRouteRule`. This patch
adds `HTTPRouteFilterRequestHeaderModifier` for both fields.
/cc @stevesloka @youngnick @sunjayBhatia

Implement HTTPRouteFilterRequestHeaderModifier for HTTPRouteFilter

---

internal/featuretests/v3/route_test.go
internal/featuretests/v3/routeweight_test.go

Refactors the tests dealing with route weights into its own test file.
Looking forward, I want to put gatewayapi tests regarding weights here as well. This only moves the current test, no changes. 

featuretests: refactor route feature tests into weights tests

---

internal/dag/builder_test.go
internal/dag/gatewayapi_processor.go

When processing through HTTPRoutes to validate if they match the configured Gateway,
any additional HTTPRoutes would not get processed after the first one. This was
due to an unneeded "break" in the code stopping execution for valid routes.
Fixes #3591

internal/dag: Fix processing of httproutes validation

---

internal/dag/dag.go
internal/dag/policy.go
internal/dag/policy_test.go
internal/envoy/v3/ratelimit.go
internal/envoy/v3/ratelimit_test.go

Refactors the DAG model of rate limit actions to have one
struct per type of rate limit action, rather than one flat
struct with fields for all the possible action types.

internal/dag: break out rate limit descriptor structs

---

cmd/contour/contour.go
cmd/contour/shutdownmanager.go
cmd/contour/shutdownmanager_test.go

To pass adminPort (got from the flag --admin-port) to shutdownManager,
we need to enrich the shutdownContext struct with this new attribute.
Then we are able to use it in the shutdownHandler() to shutdown Envoy.
Fixes #3490
Signed-off-by: alessandroargentieri <alexmawashi87@gmail.com>

cmd/contour: Added customised adminPort for the shutdown process

---

internal/dag/builder_test.go
internal/dag/gatewayapi_processor.go
internal/featuretests/v3/gatewayapi_test.go
internal/featuretests/v3/routeweight_test.go

Adds weight processing to the HTTPRoute.ForwardTos. If not specified,
defaults to the API default of "1". If set to zero, and all other services
are also set to zero or are invalid, an HTTP 503 response is returned.
Fixes #3560

internal/dag: Add weight processing to HTTPRoute.ForwardTos

---

site/_resources/compatibility-matrix.md

So we can track main, make adding a new release easier
- When we bump Envoy or k8s supported versions we can bump this
Chopped off table up to previous year, we can limit this more if we think we should

Remove old versions from matrix and add main row

---

_integration/testsuite/gatewayapi/003-invalid-forwardto.yaml
internal/dag/gatewayapi_processor.go
internal/dag/status_test.go
internal/status/httproutestatus.go
internal/status/httproutestatus_test.go

Updates the HTTPRoute status processing to only allow a single "Type" to
be specified at any given time. If there are duplicate conditions for the same
type, then the messages are appended together.
Fixes #3534

internal/status: Update HTTPRoute status to only allow a single Type

---

internal/dag/builder_test.go
internal/dag/gatewayapi_processor.go

Filters the Protocol on gateway listeners for only valid types (e.g. HTTP, HTTPS, TLS).
Fixes #3540

internal/dag: Filter on Gateway.Listener.Protocol for supported types

---

_integration/testsuite/httpproxy/002-header-condition-match.yaml
apis/projectcontour/v1/httpproxy.go
examples/contour/01-crds.yaml
examples/render/contour.yaml
internal/dag/conditions.go
internal/dag/conditions_test.go
internal/dag/policy_test.go
site/docs/main/config/api-reference.html
site/docs/main/config/request-routing.md

Adds support for the notpresent header match type.

header match conditions: add support for notpresent

---

site/_resources/release-process.md

The release process doc had some places where you couldn't copy/paste the commands.
This updates those places to allow that.

resources: Update nits in release process

---

_integration/testsuite/gatewayapi/001-path-condition-match.yaml
_integration/testsuite/gatewayapi/002-header-condition-match.yaml
_integration/testsuite/gatewayapi/003-invalid-forwardto.yaml
_integration/testsuite/gatewayapi/004-post-header-modifier.yaml
_integration/testsuite/gatewayapi/004-tls-gateway.yaml
_integration/testsuite/gatewayapi/005-pre-header-modifier.yaml
_integration/testsuite/gatewayapi/006-rewritehost.yaml
_integration/testsuite/gatewayapi/007-httproute-gatewayallowtype.yaml
internal/dag/builder_test.go
internal/dag/gatewayapi_processor.go
internal/dag/status_test.go
internal/featuretests/v3/gatewayapi_test.go
internal/featuretests/v3/routeweight_test.go
internal/status/httproutestatus.go

Implement support for HTTPRoutes.Spec.Gateways to allow an HTTPRoute to define how it
binds to a Gateway via "All", "SameNamespace", or "FromList".
Fixes #3615

internal/dag: Process HTTPRoute.Spec.Gateways

---

internal/dag/gatewayapi_processor.go
internal/dag/status_test.go
internal/status/cache.go
internal/status/conditions.go
internal/status/conditions_test.go

Refactors the HTTPRoute status logic to be generic xRoute status which will
allow us to set status on more than just HTTPRoutes.

internal: Refactor HTTPRoute status into a generic form

---

.golangci.yml
test/e2e/framework.go
test/e2e/gateway/001_path_condition_match_test.go
test/e2e/gateway/002_header_condition_match_test.go
test/e2e/gateway/003_invalid_forward_to_test.go
test/e2e/gateway/004_tls_gateway_test.go
test/e2e/gateway/005_request_header_modifier_test.go
test/e2e/gateway/gateway_test.go
test/e2e/httpproxy/002_header_condition_match_test.go

Re-implements Gateway API tests 001..005 from
_integration/testsuite/gatewayapi as Go tests.
Updates #3621.

test/e2e: add Gateway API tests 001..005

---

test/e2e/ingress/002_ensure_v1beta1_test.go
test/e2e/ingress/ingress_test.go

Basic test to make sure v1beta1 Ingress resources continue to
work as we remove internal code that references v1beta1.
This test can be removed once we support k8s versions that remove
v1beta1.
Updates #3628
This is based on https://github.com/projectcontour/contour/pull/3622 initially as that adds the new e2e go framework

test/e2e/ingress: Add test that ensures v1beta1 works

---

go.mod
go.sum
test/e2e/fixtures.go
test/e2e/framework.go
test/e2e/gateway/001_path_condition_match_test.go
test/e2e/gateway/002_header_condition_match_test.go
test/e2e/gateway/003_invalid_forward_to_test.go
test/e2e/gateway/004_tls_gateway_test.go
test/e2e/gateway/005_request_header_modifier_test.go
test/e2e/gateway/gateway_test.go
test/e2e/http.go
test/e2e/httpproxy/002_header_condition_match_test.go
test/e2e/httpproxy/003_path_condition_match_test.go
test/e2e/httpproxy/004_https_sni_enforcement_test.go
test/e2e/httpproxy/005_pod_restart_test.go
test/e2e/httpproxy/006_merge_slash_test.go
test/e2e/httpproxy/008_tcproute_https_termination_test.go
test/e2e/httpproxy/009_https_misdirected_request_test.go
test/e2e/httpproxy/010_include_prefix_condition_test.go
test/e2e/httpproxy/012_https_fallback_certificate_test.go
test/e2e/httpproxy/httpproxy_test.go
test/e2e/ingress/002_ensure_v1beta1_test.go
test/e2e/ingress/ingress_test.go

Introduces Ginkgo for running the E2E tests. Currently runs
subtests sequentially; parallelism to be re-introduced in
a subsequent PR.
Updates #3621.

test/e2e: migrate to Ginkgo for running e2e's

---

cmd/contour/serve.go
cmd/contour/servecontext.go
site/docs/main/configuration.md

cmd/contour: Remove deprecated flag 'experimental-service-apis'

---

Makefile
test/e2e/fixtures.go
test/e2e/gateway/006_host_rewrite_test.go
test/e2e/gateway/007_gateway_allow_type_test.go
test/e2e/gateway/gateway_test.go

Also bumps the test timeout from 10m (default) to 20m.
Updates #3621.

test/e2e: add Gateway tests 006, 007

---

test/e2e/framework.go
test/e2e/gateway/005_request_header_modifier_test.go
test/e2e/httpproxy/016_dynamic_headers_test.go
test/e2e/httpproxy/017_host_header_rewrite_test.go
test/e2e/httpproxy/019_local_rate_limiting_test.go
test/e2e/httpproxy/020_global_rate_limiting_test.go
test/e2e/httpproxy/httpproxy_test.go

Updates #3621.
(I omitted 018 from this because it requires backend TLS which I haven't implemented the framework code for yet; will do it along with the other backend TLS stuff shortly).

test/e2e: add HTTPProxy tests 016,017,019,020

---

internal/featuretests/kubernetes.go
internal/featuretests/v3/backendclientauth_test.go
internal/featuretests/v3/cluster_test.go
internal/featuretests/v3/externalname_test.go
internal/featuretests/v3/ingressclass_test.go
internal/featuretests/v3/listeners_test.go
internal/featuretests/v3/retrypolicy_test.go
internal/featuretests/v3/route_test.go
internal/featuretests/v3/secrets_test.go
internal/featuretests/v3/timeoutpolicy_test.go
internal/featuretests/v3/tlsprotocolversion_test.go
internal/featuretests/v3/upstreamprotocol_test.go
internal/featuretests/v3/websockets_test.go
internal/featuretests/v3/wildcardhost_test.go

Removes Ingress v1beta1 from tests as v1 is present in
all supported k8s versions and v1beta1 resources are
subscribed to with v1 informers.
Updates: #3628

internal/featuretests: Remove Ingress v1beta1

---

cmd/contour/ingressstatus.go
cmd/contour/serve.go
internal/k8s/clients_test.go
internal/k8s/helpers.go
internal/k8s/informers.go
internal/k8s/kind.go
internal/k8s/kind_test.go
internal/k8s/scheme.go
internal/k8s/statusaddress.go
internal/k8s/statusaddress_test.go

- Removes informer for v1beta1
- Removes status updater/informer for v1beta1
- Ensures k8s versions older than 1.19 are incompatible
as we are relying on Ingress v1 existing
Updates: #3628

interna/k8s: Remove v1beta1 usage

---

apis/projectcontour/v1/httpproxy.go

caSecret is now optional in downstream validation since
skipClientCertValidation can be true. Adds an omitempty
JSON tag to omit the field when serializing to JSON and
it hasn't been specified.

apis/projectcontour: add omitempty JSON tag to caSecret

---

test/e2e/httpproxy/002_header_condition_match_test.go
test/e2e/httpproxy/015_http_health_checks_test.go
test/e2e/httpproxy/019_local_rate_limiting_test.go
test/e2e/httpproxy/020_global_rate_limiting_test.go

test/e2e: add retry with backoff to all updates

---

test/e2e/certs.go
test/e2e/fixtures.go
test/e2e/framework.go
test/e2e/gateway/gateway_test.go
test/e2e/http.go
test/e2e/httpproxy/004_https_sni_enforcement_test.go
test/e2e/httpproxy/007_client_cert_auth_test.go
test/e2e/httpproxy/008_tcproute_https_termination_test.go
test/e2e/httpproxy/009_https_misdirected_request_test.go
test/e2e/httpproxy/012_https_fallback_certificate_test.go
test/e2e/httpproxy/014_external_auth_test.go
test/e2e/httpproxy/018_external_name_test.go
test/e2e/httpproxy/020_global_rate_limiting_test.go
test/e2e/httpproxy/httpproxy_test.go
test/e2e/ingress/001_tls_wildcard_host_test.go
test/e2e/ingress/ingress_test.go

test/e2e: add HTTPProxy 007,018 and Ingress 001 tests

---

_integration/testsuite/fixtures/ingress-conformance-echo.yaml
test/e2e/fixtures.go

Updates the ingress-conformance-echo Docker image used in
_integration and test/e2e to be the latest version in the
official location. Removes the custom build of it for TLS
support.
Updates #3584.

_integration, test/e2e: update ingress conformance echo image

---

test/e2e/certs.go
test/e2e/framework.go
test/e2e/httpproxy/007_client_cert_auth_test.go

Fixes a flake where the secrets are not available by
the time the test tries to download their contents.
Updates #3621.

test/e2e: wait for client certs to be ready

---

.github/workflows/prbuild.yaml
Makefile

https://golang.org/doc/devel/release.html#go1.16.minor

Bump go to 1.16.4

---

internal/dag/gatewayapi_processor.go
internal/dag/gatewayapi_processor_test.go

Adds tests to validate the logic in namespaceMatches which validates
that a namespace of a Route matches the selector on a gateway.

internal/dag: Add tests for namespaceMatches method

---

CONTRIBUTING.md

Go no longer requires source code to be present as a  subdir of $GOPATH
Fixes #3687
Signed-off-by: Kartikey Pandey <pandeykartikey99@gmail.com>

docs: update the fetch source section in the CONTRIBUTING.md

---

.github/workflows/stale.yaml

The current settings are to mark PRs stale after 14 days
of no activity, and then to close after another 90 days
of no activity. This lowers the time to close after being
marked stale to 30 days, so stale PRs don't hang around
for so long.

.github/workflows: set stale PR close time to 30 days

---

_integration/testsuite/fixtures/ingress-conformance-echo.yaml
_integration/testsuite/gatewayapi/008-tlsroute.yaml
internal/dag/builder_test.go
internal/dag/cache.go
internal/dag/gatewayapi_processor.go
internal/dag/gatewayapi_processor_test.go
internal/dag/status_test.go
internal/envoy/v3/listener.go
internal/envoy/v3/listener_test.go
internal/featuretests/v3/tlsroute_test.go
internal/status/conditions.go

Add support for TLSRoute to enable Passthrough TCP Proxying to pods via SNI.
Note: This is currently rebased from https://github.com/projectcontour/contour/pull/3620 which makes the Status bits more generic. Merging that first will make this PR smaller. 
Updates #3440

internal: Adds support for TLSRoute

---

.github/workflows/prbuild.yaml

- Cache for each job that invokes Go
- Namespaced by OS to be safe
- Each job needs its own cache so they don't clobber each other; otherwise jobs that finish first take over the cache, e.g. the `codegen` job would own the cache for all Linux jobs and the cache would be useless for the `test-linux` job
- Speeds up `test-linux/osx` jobs significantly (the former down to ~1 minute)

CI: Speed up Go builds in CI by using Github caching

---

site/content/docs/main/_index.md
site/content/docs/main/config/fundamentals.md
site/content/docs/main/config/tls-termination.md
site/content/docs/main/config/virtual-hosts.md
site/content/docs/main/configuration.md
site/content/docs/main/deploy-options.md
site/content/docs/main/grpc-tls-howto.md

Updates the "main" docs links to point to the "main" GitHub
branch instead of the latest release version. Since the "main"
docs are cloned for each new versioned set of docs, this enables
the versioned docs to point to the appropriate GitHub location.

site: fix links to point to version-specific content

---

site/content/docs/v1.15.1/config/fundamentals.md
site/content/docs/v1.15.1/config/tls-termination.md
site/content/docs/v1.15.1/config/virtual-hosts.md
site/content/docs/v1.15.1/configuration.md
site/content/docs/v1.15.1/deploy-options.md
site/content/docs/v1.15.1/grpc-tls-howto.md

Have v1.15.1 docs link to the v1.15.1 GitHub repo tag
instead of the latest tag, since as soon as we cut a
new release latest will change to v1.16.0.

site: pin v1.15.1 links to v1.15.1 instead of latest

---

.codespell.skip

fixup codespell.ingorewords to match the PR build so local runs will match the CI jobs

fixup codespell.ingorewords to match the PR build

---

site/content/docs/main/configuration.md

Followup to #3659 adds missing config page info for new controllerName config option. 

add gateway.controllername to config docs

---

.github/workflows/codeql-analysis.yml

- Use go action cache
- Select only Go as language
- Remove HEAD^2 checkout, prevents warning in codeql init step

Speed up CodeQL job

---

internal/dag/builder_test.go
internal/dag/gatewayapi_processor.go
internal/dag/status_test.go

Filters the route kind by listener so that only the specified route type
will be processed by a listener.
Updates #3529

internal/dag: Filter route Kind by listener

---

site/content/examples/kuard.yaml
site/content/resources/release-process.md

- Updates references to compatibility matrix and upgrade docs based on new site layout.
- Updates the Ingress resource to comply with the latest spec as the existing `backend` field has been removed:
```
$ kubectl apply -f https://projectcontour.io/examples/kuard.yaml
deployment.apps/kuard created
service/kuard created
error: error validating "https://projectcontour.io/examples/kuard.yaml": error validating data: ValidationError(Ingress.spec): unknown field "backend" in io.k8s.api.networking.v1.IngressSpec; if you choose to ignore these errors, turn validation off with --validate=false
```

Fixes Site Bugs for v1.16.0 Release

---

_integration/testsuite/gatewayapi/008-tlsroute.yaml
internal/dag/builder_test.go
internal/dag/gatewayapi_processor.go
test/e2e/gateway/008_tlsroute_test.go

internal/dag: Implement GatewayAllow for TLSRoutes

---

internal/dag/builder_test.go
internal/dag/gatewayapi_processor.go
internal/dag/gatewayapi_processor_test.go
internal/dag/status_test.go

Take into account gateway.listeners.hostname into account when processing HTTPRoutes
which applies to all HTTPRoutes selected for that listener.
Fixes #3561

internal/dag: Implement Gateway.Listener.Hostname when processing HTTPRoutes

---

internal/k8s/log_test.go

Flakes occurring on osx in CI so bump timeout

internal/k8s: Bump log test klog flush wait time

---

site/content/docs/v1.1.0/api.md
site/content/docs/v1.10.0/config/api.md
site/content/docs/v1.10.1/config/api.md
site/content/docs/v1.11.0/config/api.md
site/content/docs/v1.12.0/config/api.md
site/content/docs/v1.13.0/config/api.md
site/content/docs/v1.13.1/config/api.md
site/content/docs/v1.14.0/config/api.md
site/content/docs/v1.14.1/config/api.md
site/content/docs/v1.15.0/config/api.md
site/content/docs/v1.2.0/api.md
site/content/docs/v1.2.1/api.md
site/content/docs/v1.3.0/api.md
site/content/docs/v1.4.0/api.md
site/content/docs/v1.5.0/api.md
site/content/docs/v1.5.1/api.md
site/content/docs/v1.6.0/api.md
site/content/docs/v1.6.1/api.md
site/content/docs/v1.7.0/api.md
site/content/docs/v1.8.0/api.md
site/content/docs/v1.8.1/api.md
site/content/docs/v1.8.2/api.md
site/content/docs/v1.9.0/api.md

Some links to the api reference are broken, this fixes the include for the new
Hugo site.
Updates #3712

site: Fix links to api reference

---

Dockerfile
Makefile

So that Makefile docker build commands etc. do not need modification if
the variable needs to be changed.

GOPROXY can be overridden in container build

---

site/content/docs/main/config/virtual-hosts.md
site/content/docs/v1.10.0/config/virtual-hosts.md
site/content/docs/v1.10.1/config/virtual-hosts.md
site/content/docs/v1.11.0/config/virtual-hosts.md
site/content/docs/v1.12.0/config/virtual-hosts.md
site/content/docs/v1.13.0/config/virtual-hosts.md
site/content/docs/v1.13.1/config/virtual-hosts.md
site/content/docs/v1.14.0/config/virtual-hosts.md
site/content/docs/v1.14.1/config/virtual-hosts.md
site/content/docs/v1.15.0/config/virtual-hosts.md
site/content/docs/v1.15.1/config/virtual-hosts.md
site/content/docs/v1.16.0/config/virtual-hosts.md

Updates #3712
**Note! Needs #3757 to make the reference back to the API Page virtual hosts to work properly.** 

site: Fix virtual hosts page with bad links

---

Makefile

Output of "contour version" can be controlled separately from image tag
if needed.

Contour binary version and image version labels can be overridden

---

README.md
site/content/resources/compatibility-matrix.md

- We dropped support for k8s 1.18
- Contour 1.16.0 stopped falling back to Ingress v1beta1 resources
Updates: #3749

Add k8s min version clarification

---

site/content/docs/main/config/upstream-tls.md
site/content/docs/v1.10.0/config/upstream-tls.md
site/content/docs/v1.10.1/config/upstream-tls.md
site/content/docs/v1.11.0/config/upstream-tls.md
site/content/docs/v1.12.0/config/upstream-tls.md
site/content/docs/v1.13.0/config/upstream-tls.md
site/content/docs/v1.13.1/config/upstream-tls.md
site/content/docs/v1.14.0/config/upstream-tls.md
site/content/docs/v1.14.1/config/upstream-tls.md
site/content/docs/v1.15.0/config/upstream-tls.md
site/content/docs/v1.15.1/config/upstream-tls.md
site/content/docs/v1.16.0/config/upstream-tls.md

site: Fix upstream tls docs for 404 links after move to Hugo

---

test/scripts/make-kind-cluster.sh

Now that the Gateway API CRDs are being synced into the contour
repo, the local copy can be used when instantiating a KinD cluster.

test/scripts: install Gateway API CRDs from examples/gateway

---

Makefile
examples/render/contour-gateway.yaml
hack/generate-gateway-deployment.sh

Adds a script and includes the script in the `generate` make target. This is for supporting a Gateway API install experience similar to `kubectl apply -f https://projectcontour.io/quickstart/contour.yaml`.
Note that `examples/render/contour-gateway.yaml` was generated from `make generate`.
Requires https://github.com/projectcontour/contour/pull/3659

Updates Examples for Gateway API Support

---

internal/dag/builder_test.go
internal/dag/gatewayapi_processor.go
test/e2e/gateway/008_tlsroute_test.go
test/e2e/gateway/gateway_test.go

internal/dag: handle tls route gateway.listener modes
Fixup issue where the listener protocol wasn't checked for type=tls.
Also, adds logic to validate the TLS.Mode is valid.

handle tls route gateway.listener modes

---

hack/release/prepare-release.go
site/config.yaml
site/content/getting-started/_index.md
site/content/guides/cert-manager.md
site/content/guides/deploy-aws-nlb.md
site/content/guides/external-authorization.md
site/content/guides/global-rate-limiting.md
site/content/guides/ingressroute-to-httpproxy.md
site/content/guides/structured-logs.md
site/content/guides/tls.md
site/content/resources/faq.md
site/content/resources/support.md
site/themes/contour/layouts/_default/versions.html
site/themes/contour/layouts/index.redirects
site/themes/contour/layouts/partials/getting-started.html
site/themes/contour/layouts/partials/header.html

Replaces docs_latest and latest_release_tag_name with
a latest_version param.
Closes #3786.

site: use a single param for latest version

---

site/content/guides/proxy-proto.md
site/content/posts/2019-07-23-contour-v014.md
site/content/resources/compatibility-matrix.md
site/content/resources/tagging.md

Follow-up to #3788, replaces some additional instances of
latest_release_tag_name with latest_version.
Updates #3786.

site: replace latest_release_tag_name with latest_version

---

.github/ISSUE_TEMPLATE/decision.md
hack/release/sync-repo-labels.sh
site/data/github-labels.yaml

I've fixed the permissions issues for the `contour-perf` repo, but there was also a bug from the site move (fixed as well).
Then I've updated the labels with some that had been manually created, and added the new "Decision" issue template.

Fix label sync, update labels, add new decision issue type

---

README.md
hack/release/release-notes-template.md
site/content/docs/main/config/ingress.md
site/content/resources/compatibility-matrix.md
site/content/resources/philosophy.md
site/content/resources/release-process.md

- Adds release notes markdown template
- Calls out in release process doc about what to include in release
notes
- Modifies notes in compatibility matrix to remove ambiguity
- Minor updates in Philosophy document to bring it up to date
- Makes README more general about k8s prerequisites

Update compatibility docs and release cutting notes

---

examples/render/contour-gateway.yaml
hack/generate-gateway-deployment.sh

Updates the rendered gateway manifest script to include manifests defined in the examples/gateway directory.

Fixes Rendered Gateway Example

---

site/content/docs/main/troubleshooting/contour-debug-log.md
site/content/docs/v1.10.0/troubleshooting/contour-debug-log.md
site/content/docs/v1.10.1/troubleshooting/contour-debug-log.md
site/content/docs/v1.11.0/troubleshooting/contour-debug-log.md
site/content/docs/v1.12.0/troubleshooting/contour-debug-log.md
site/content/docs/v1.13.0/troubleshooting/contour-debug-log.md
site/content/docs/v1.13.1/troubleshooting/contour-debug-log.md
site/content/docs/v1.14.0/troubleshooting/contour-debug-log.md
site/content/docs/v1.14.1/troubleshooting/contour-debug-log.md
site/content/docs/v1.15.0/troubleshooting/contour-debug-log.md
site/content/docs/v1.15.1/troubleshooting/contour-debug-log.md
site/content/docs/v1.16.0/troubleshooting/contour-debug-log.md
site/content/docs/v1.8.2/troubleshooting.md
site/content/docs/v1.9.0/troubleshooting.md

Fix:contour: error: expected argument for flag '--kubernetes-debug', try --help

---

.codespell.skip
.github/workflows/prbuild.yaml
site/content/docs/main/configuration.md
site/content/docs/v1.10.0/configuration.md
site/content/docs/v1.10.1/configuration.md
site/content/docs/v1.11.0/configuration.md
site/content/docs/v1.12.0/configuration.md
site/content/docs/v1.13.0/configuration.md
site/content/docs/v1.13.1/configuration.md
site/content/docs/v1.14.0/configuration.md
site/content/docs/v1.14.1/configuration.md
site/content/docs/v1.15.0/configuration.md
site/content/docs/v1.15.1/configuration.md
site/content/docs/v1.16.0/configuration.md
site/content/guides/xds-migration.md

Found a bunch of codespell errors happening locally which ironically did
not show up in the CI build tests.
```
./site/public/css/style.css.map:52: CACL ==> CALC
./site/public/css/style.css.map:52: CACE ==> CACHE
./site/public/css/style.css.map:52: CACE ==> CACHE
./site/public/css/style.css.map:52: CACH ==> CATCH, CACHE
./site/public/css/style.css.map:52: CACL ==> CALC
./site/public/css/style.css.map:52: CACL ==> CALC
./site/public/css/style.css.map:52: CACH ==> CATCH, CACHE
./site/public/css/style.css.map:52: CACL ==> CALC
./site/public/css/style.css.map:52: CACE ==> CACHE
./site/public/css/style.css.map:52: CACL ==> CALC
./site/public/css/style.css.map:52: CACH ==> CATCH, CACHE
./site/public/css/style.css.map:52: CACH ==> CATCH, CACHE
./site/public/css/style.css.map:52: CACL ==> CALC …
```

site: Fixup codespell errors

---

cmd/contour/serve.go
pkg/config/parameters.go
site/content/docs/main/configuration.md

The fields in the Gateway configuration, Name & Namespace, are deprecated and will be removed in Contour v1.18.
Updates #3617

pkg/config: Mark Gateway.Name & Gateway.Namespace as deprecated

---

site/content/docs/main/README.md
site/content/docs/main/troubleshooting.md
site/content/getting-started/_index.md

site/content/docs: Add troubleshooting page
Created a troubleshooting page and added a troubleshooting section to the main Docs page.
Updates #3816 
Signed-off-by: johnnycase <johneverettcase@gmail.com>

Add troubleshooting page

---

go.mod
go.sum
internal/envoy/v3/listener.go
internal/protobuf/helpers.go
internal/xds/v3/contour.go
internal/xds/v3/contour_test.go

Found while bumping gomega in another PR, protobuf can be updated and
some deprecated helpers can be removed.

Bump protobuf and fix lint issues

---

test/e2e/http.go

- condition might be nil when we dont think the request should succeed
- return false if there is no condition

test/e2e: check for nil condition in http requestUntil

---

go.mod
go.sum

See release notes: https://github.com/onsi/gomega/releases/tag/v1.13.0

Bump gomega package to 1.13.0

---

internal/xdscache/v3/endpointstranslator.go
internal/xdscache/v3/endpointstranslator_test.go

In the EndpointsTranslator, do not recompute ClusterLoadAssignments
or notify cache observers if the Endpoints being added/updated/deleted
is not used by a ServiceCluster in the DAG.
Closes #3782.

internal/xdscache: ignore irrelevant Endpoints

---

test/e2e/deployment.go

Increases the timeout for waiting for the Contour process
to exit from 1s (default) to 1m, to avoid test flakes.
Updates #3892.

test/e2e: increase timeout for Contour process exiting

---

.github/workflows/build_main.yaml

The main build was broken with bad syntax after adding the Slack notifications. 

fixes build_main job with invalid syntax

---

internal/dag/gatewayapi_processor.go
internal/dag/status_test.go
internal/status/gatewayconditions.go

Adds tests for the Gatewaay status that results from a DAG build.
Fixes #3867

internal/dag: Add tests for Gateway status

---

internal/controller/gatewayclass_test.go
internal/controller/suite_test.go
internal/validation/gatewayclass.go
internal/validation/gatewayclass_test.go

The field parametersRef on a GatewayClass should be able to be defined.
Fixes #3874

internal/validation: allow GatewayClass.Spec.ParametersRef to be specified

---

hack/release/make-release-tag.sh

When generating a release tag, includes contour-gateway.yaml
in the commit.

[release-1.17 branch] hack/release: include contour-gateway.yaml in release commit

---

hack/release/make-release-tag.sh

When generating a release tag, includes contour-gateway.yaml
in the commit.

hack/release: include contour-gateway.yaml in release commit

---

.github/workflows/prbuild.yaml
test/e2e/deployment.go
test/e2e/gateway/gateway_test.go
test/e2e/httpproxy/httpproxy_test.go
test/e2e/ingress/ingress_test.go

Replaces projectcontour namespace deletion with per-resource
deletion after each E2E suite runs, to speed up the cleanup
phase. Also removes the dependency between build-image and
running the E2E's in the GitHub Actions workflow since the
image is not currently being used by the E2E's.

E2E tests: performance improvements

---

test/e2e/gateway/gateway_test.go

Changes Gateways to use RouteSelectSame to only select
routes in the same namespace as the Gateway, to avoid
inadvertent test pollution across namespaces.
Also removes a duplicate test.
(Hopefully) closes #3892.

test/e2e: change Gateways to RouteSelectSame

---

site/content/docs/main/config/access-logging.md
site/data/docs/main-toc.yml

Added information about 
* customizing text based access logs
* supported access log formatter extensions (there is only one so far)
This documentation is related to #3694 and #3576

site: Added versioned access logging document

---

site/content/docs/main/config/client-authorization.md
site/content/docs/main/config/external-service-routing.md

Update ExternalName Service documentation after security advisory

---

hack/actions/install-kubernetes-toolchain.sh

The install-kubernetes-toolchain.sh installs a few dependencies in order to
build, test, and lint Contour code. The env var to install gingkgo was using
OSType=Linux which breaks on a local linux machine.
This changes that variable to use "CI" which is setup by Github Actions to let the
script know if it's running in Github Actions or not.

hack: Change ginkgo install var to use CI

---

internal/dag/builder_test.go
internal/dag/gatewayapi_processor.go
internal/featuretests/v3/routeweight_test.go

Add support for weighted ForwardTos in TLSRoute rules.
Per spec, weights default to 1 if unspecified, and weights
of 0 mean no traffic is forwarded to the backend.
Updates #3440.

internal/dag: support TLSRoute weighted ForwardTos

---

go.mod
go.sum
internal/xds/v3/snapshotter.go

Bumps to commit https://github.com/envoyproxy/go-control-plane/commit/abdc764d71d207c7d28f5decb513a3fc132347f9 (latest to pass CI)

Bump go-control-plane

---

site/themes/contour/i18n/en.yaml
site/themes/contour/layouts/shortcodes/notice.html

Issue #3826 - Add deprecation style
This PR adds `warning`, `info`, `note` and `tip` notice for markdown.
```
{{< notice tip >}}
This is a TIP
{{< /notice >}}
{{< notice info >}}
This is INFORMATION
{{< /notice >}}
{{< notice warning >}}
This is a WARNING
{{< /notice >}}
{{< notice note >}}
This is a NOTE
{{< /notice >}}
```
Above code will produce the following notices:
Signed-off-by: Gary Tai <gary.c.tai@gmail.com>

add website notice feature

---

Makefile
examples/contour/03-envoy.yaml
examples/render/contour-gateway.yaml
examples/render/contour.yaml

Note: the Envoy docs for the new versions don't actually exist yet so I didn't update the compatibility matrix, but I'll circle back and bulk-update it later.

(main) update Envoy to v1.19.1

---

.github/workflows/prbuild.yaml
hack/actions/install-kubernetes-toolchain.sh

Using just a tag, kind cluster does not start up properly
Also bumps kind CLI version since we need k8s 1.21 images

[Release 1.15] Use exact kind node image

---

examples/contour/02-role-contour.yaml
examples/render/contour-gateway.yaml
examples/render/contour.yaml
internal/dag/cache.go
internal/dag/cache_test.go
internal/k8s/informers.go

The upcoming v1alpha2 release of Gateway API drops
BackendPolicy. Contour currently sets up an informer
for it but does not do any further processing based
on it. As such, this PR fully removes all code for it.

remove BackendPolicy informers, caching and RBAC

---

cmd/contour/serve.go
internal/k8s/converter.go
internal/k8s/converter_test.go

The DynamicClientHandler is no longer needed since we are
not using dynamic informers anymore. It has been silently
performing no-ops for awhile. This PR removes it.

drop obsolete DynamicClientHandler

---

internal/dag/builder.go
internal/dag/status_test.go
internal/status/cache.go
internal/status/cache_test.go
internal/status/routeconditions.go

Sets the RouteGatewayStatus Controller field to the value
of the relevant GatewayClass's Controller, rather than a
static string value.
Closes #3689.

internal/status: set RouteGatewayStatus controller field dynamically

---

.github/workflows/build_main.yaml
.github/workflows/build_tag.yaml

Starts pushing container images to GHCR in
addition to Docker Hub. Images will be pushed
to both registries for a period of time, until
the Docker Hub push is removed.

Push images to GHCR and Docker Hub in parallel

---

site/content/posts/2019-09-5-contour-v015.md

Fixes: 
- Repairs image local reference. 
- Repairs "envoy documentation on upgrading" link. 
- Repairs github links to community contributors listed in special thanks section.
Signed-off-by: Michelle Zelechoski <zelechom@oregonstate.edu>

site: repair broken links in blog post

---

site/content/getting-started/_index.md

the bitnami helm chart is now setting the `contour` ingressclassname by
default, this notes that correctly
see:
- https://github.com/bitnami/charts/blob/c3e887d475de6b4cd2ac8d3e699f9466ead95d49/bitnami/contour/values.yaml#L264
- https://github.com/bitnami/charts/pull/7381
Signed-off-by: Sunjay Bhatia <sunjayb@vmware.com>

Fix helm quick start for ingressClassName

---

site/content/docs/main/configuration.md
site/content/docs/v1.17.0/configuration.md
site/content/docs/v1.17.1/configuration.md
site/content/docs/v1.17.2/configuration.md
site/content/docs/v1.18.0/configuration.md
site/content/docs/v1.18.1/configuration.md

Updates GatewayConfig docs to drop namespace
and name going forward, and update older
versions' docs to name the correct version
in which they are removed.

docs: GatewayConfig updates

---

design/configuration-crd.md

Adds design doc for migrating the Contour conifgmap to a ContourConfiguration
along with a new ContourDeployment CRD which is managed by an additional controller.

design: Add configuration & deployment crd design

---

internal/dag/builder_test.go
internal/dag/httpproxy_processor.go
internal/dag/status_test.go
internal/featuretests/v3/tcpproxy_test.go
internal/xdscache/v3/route_test.go

This change implements
* Handle specific configuration errors as non-fatal, so that traffic will be served for the valid parts of the HTTPProxy.
* Program 502/503 direct responses for the faulty parts.
See design/httpproxy-conflict.md for more details, but note that this change addresses only missing includes and missing service references, while the design document covers wider concept of misconfigured proxies.

internal: program 502/503 routes for misconfigured services and includes

---

design/quarterly-release.md

This design document PR  is the official record of the maintainer's wish to move Contour to a quarterly release cadence.
It has proposals for how the rollout will work, comments welcomed.

Add quarterly release proposal

---

Makefile

Moves generate-gateway-crd-yaml to before
generate-deployment so any Gateway API
CRD updates are included in the example
Gateway deployment.

Makefile: fix order of generates

---

apis/projectcontour/v1/httpproxy.go
examples/contour/01-crds.yaml
examples/render/contour-gateway.yaml
examples/render/contour.yaml
internal/dag/httpproxy_processor.go
internal/dag/status_test.go
test/e2e/framework.go
test/e2e/httpproxy/fqdn_test.go
test/e2e/httpproxy/httpproxy_test.go

Adds additional validation for FQDN in HTTPProxy resources.
Fixes #3166

internal/dag: Add additional validation for fqdn

---

cmd/contour/shutdownmanager_test.go
internal/envoy/v3/bootstrap.go
internal/envoy/v3/bootstrap_test.go
internal/envoy/v3/stats.go
internal/envoy/v3/stats_test.go

Rename to `envoy-admin` which better represents the backend cluster.
Fixes #3959

Deprecate the static cluster `service-stats` 

---

apis/projectcontour/v1alpha1/register.go
cmd/contour/serve.go
cmd/contour/servecontext.go
examples/contour/02-role-contour.yaml
examples/render/contour-gateway.yaml
examples/render/contour.yaml
internal/k8s/informers.go
site/content/docs/main/configuration.md

Stubs out the '--contour-config-name' flag on 'contour serve' command
which will take precendence over any other configuration items if
specified.

cmd/contour: Stub out --contour-config-name flag

---

test/e2e/fixtures.go
test/e2e/framework.go
test/e2e/httpproxy/http_health_checks_test.go

Removes usages of httpbin and replaces it with
the ingress echoserver now that the latter supports
returning specified status codes.
Updates #3584.

test/e2e: replace httpbin with ingress echoserver

---

RELEASES.md

Remove reference to ZenHub which is no longer used

---

RELEASES.md
site/content/docs/main/github.md
site/content/docs/v1.18.1/github.md
site/content/resources/support.md
site/content/resources/tagging.md

This one should go in after #4021.

Update documentation for transition to quarterly releases

---

site/data/github-labels.yaml

I'm going to need these labels to be able to categorise PRs for the new changelog/release notes process.

Add new release note category labels

---

cmd/contour/serve.go
examples/contour/02-role-contour.yaml
examples/render/contour-gateway.yaml
examples/render/contour.yaml

Removes the code that validates that Contour
CRDs have been created as v1. Contour has now
provided v1-only CRDs for many releases, and
the v1beta1 API version is dropped as of
Kubernetes 1.22.

cmd/contour: remove legacy CRD validation code

---

site/content/docs/main/config/request-routing.md

This change aligns the description of the idle timeout parameters in the
configuration docs by re-using the exact wording from the API reference.
This adds to earlier change #4028 which clarified the timeout behavior but
by accident missed the configuration docs.
Updates #3972

site: align idle timeout description with API reference

---

go.sum
hack/actions/install-kubernetes-toolchain.sh

`go get` is deprecated in go v1.17:
```
go get: installing executables with 'go get' in module mode is deprecated.
To adjust and download dependencies of the current module, use 'go get -d'.
To install using requirements of the current module, use 'go install'.
To install ignoring the current module, use 'go install' with a version,
like 'go install example.com/cmd@latest'.
For more information, see https://golang.org/doc/go-get-install-deprecation
or run 'go help get' or 'go help install'.
```

Fixup `go get` from kubernetes toolchain install script since go get is deprecated

---

test/e2e/gateway/gateway_allow_type_test.go
test/e2e/gateway/host_rewrite_test.go
test/e2e/gateway/request_header_modifier_test.go
test/e2e/gateway/tls_wildcard_host_test.go
test/e2e/httpproxy/dynamic_headers_test.go
test/e2e/httpproxy/external_auth_test.go
test/e2e/httpproxy/external_name_test.go
test/e2e/httpproxy/global_rate_limiting_test.go
test/e2e/httpproxy/host_header_rewrite_test.go
test/e2e/httpproxy/http_health_checks_test.go
test/e2e/httpproxy/https_fallback_certificate_test.go
test/e2e/httpproxy/https_misdirected_request_test.go
test/e2e/httpproxy/https_sni_enforcement_test.go
test/e2e/httpproxy/local_rate_limiting_test.go
test/e2e/httpproxy/merge_slash_test.go
test/e2e/httpproxy/pod_restart_test.go
test/e2e/httpproxy/tcproute_https_termination_test.go
test/e2e/infra/admin_test.go
test/e2e/infra/metrics_test.go
test/e2e/ingress/tls_wildcard_host_test.go
test/e2e/upgrade/upgrade_test.go

Log message uses status code from response which might be nil

test/e2e: Nil check before assertion on succeeded request

---

.github/workflows/prbuild.yaml
apis/projectcontour/v1alpha1/contourconfig.go
cmd/contour/contour.go
cmd/contour/leadership.go
cmd/contour/serve.go
cmd/contour/serve_test.go
cmd/contour/servecontext.go
cmd/contour/servecontext_test.go
examples/contour/01-crds.yaml
examples/render/contour-gateway.yaml
examples/render/contour.yaml
internal/dag/cache.go
internal/dag/httpproxy_processor.go
internal/envoy/v3/accesslog.go
internal/envoy/v3/accesslog_test.go
internal/featuretests/v3/featuretests.go
internal/featuretests/v3/listeners_test.go
internal/k8s/informers.go
internal/xdscache/v3/listener.go
site/content/docs/main/config/api-reference.html
test/e2e/deployment.go
test/e2e/fixtures.go
test/e2e/gateway/gateway_test.go
test/e2e/gateway/multiple_gateways_and_classes_test.go
test/e2e/httpproxy/httpproxy_test.go
test/e2e/infra/infra_test.go
test/e2e/ingress/ingress_test.go

Convert the ServeContext to a ContourConfiguration and use
that for all config items which will allow for the ServeContext
to be deprecated and the optional ContourConfig CRD to be
specified.

cmd/contour: Use ContourConfiguration for all config

---

changelogs/unreleased/4142-sunjayBhatia-small.md
internal/envoy/v3/bootstrap.go
internal/envoy/v3/bootstrap_test.go
internal/envoy/v3/listener.go
internal/envoy/v3/listener_test.go
internal/featuretests/v3/envoy.go
internal/featuretests/v3/listeners_test.go
internal/xdscache/v3/listener.go
internal/xdscache/v3/listener_test.go

These fields were deprecated in Envoy 1.18 and 1.19 respectively
Fixes: #4139

Use updated fields for access log and xffNumTrustedHops

---

apis/projectcontour/v1/httpproxy.go
changelogs/unreleased/4141-sunjayBhatia-minor.md
examples/contour/01-crds.yaml
examples/render/contour-gateway.yaml
examples/render/contour.yaml
internal/dag/builder_test.go
internal/dag/dag.go
internal/dag/policy.go
internal/envoy/v3/route.go
internal/envoy/v3/route_test.go
internal/featuretests/v3/envoy.go
internal/featuretests/v3/loadbalancerpolicy_test.go
site/content/docs/main/config/api-reference.html
site/content/docs/main/config/request-routing.md

- must specify exactly one of header hashing policy or source ip hashing
in a list element (otherwise ignored and warning generated)
- cant specify to hash source ip multiple times (otherwise ignored and
warning generated)
Fixes: #3703

Add source ip hashing to RequestHash load balancing

---

changelogs/unreleased/4143-skriss-small.md
cmd/contour/serve.go
internal/controller/gateway.go
internal/controller/helpers.go
internal/controller/tcproute.go
internal/controller/udproute.go
internal/dag/cache.go
internal/dag/cache_test.go
test/e2e/framework.go
test/e2e/gateway/gateway_test.go
test/e2e/gateway/unsupported_route_types_test.go

Contour does not support Gateway API's
TCPRoute or UDPRoute. This PR sets a
condition of "Accepted: false" on all
TCPRoutes & UDPRoutes referencing a
Contour Gateway.
Closes #3441.
Closes #3442.

Gateway API: set TCPRoute and UDPRoute status

---

changelogs/unreleased/4123-skriss-small.md
internal/dag/builder_test.go
internal/dag/dag.go
internal/dag/gatewayapi_processor.go
internal/dag/status_test.go
internal/envoy/v3/route.go
internal/envoy/v3/route_test.go
internal/xdscache/v3/route.go
test/e2e/gateway/gateway_test.go
test/e2e/gateway/request_redirect_test.go
test/e2e/http.go

Adds support for the "RequestRedirect" HTTPRoute
filter type at the rule level.
Closes #4087.

Gateway API: add request redirect filter support

---

changelogs/unreleased/4138-skriss-minor.md
cmd/contour/serve.go
examples/contour/02-role-contour.yaml
examples/render/contour-gateway.yaml
examples/render/contour.yaml
internal/dag/builder_test.go
internal/dag/cache.go
internal/dag/cache_test.go
internal/dag/gatewayapi_processor.go
internal/dag/status_test.go
internal/gatewayapi/helpers.go
internal/k8s/informers.go

Implements ReferencePolicy, which enables certain
cross-namespace references to be allowed. This
currently applies only to Route->Service refs.
Closes #4118.

Gateway API: implement ReferencePolicy

---

apis/projectcontour/v1/httpproxy.go
changelogs/unreleased/4145-stevesloka-small.md
examples/contour/01-crds.yaml
examples/render/contour-gateway.yaml
examples/render/contour.yaml
internal/dag/builder_test.go
internal/dag/dag.go
internal/dag/gatewayapi_processor.go
internal/dag/httpproxy_processor.go
internal/dag/ingress_processor.go
internal/featuretests/v3/wildcardhost_test.go
test/e2e/httpproxy/fqdn_test.go

Allow wildcard fqdn's for HTTPProxy resources

---

test/e2e/httpproxy/cookie_rewrite_test.go

Names of resources and FQDN in HTTPProxies were the same across tests,
possible causing some test flakes in CI where globally set cookies were
not rewritten.

test/e2e: Fix possible cause of flakes in cookie rewrite test

---

changelogs/unreleased/4151-tsaarni-small.md
internal/envoy/v3/cluster.go
internal/featuretests/v3/envoy.go
internal/xdscache/v3/cluster_test.go

This change sets the new default connect timeout to 2 seconds. The default connect timeout was 250 msec which can be too short and may cause failed requests with slow upstream services.
Updates #2264

internal/envoy: increase default upstream connect timeout

---

test/e2e/httpproxy/fqdn_test.go
test/e2e/httpproxy/httpproxy_test.go

Moves E2E tests that verify kubebuilder validation
annotations to their own Describe block which
does not run a Contour instance, since it's not
needed for these tests.
Updates #4163.

test/e2e: simplify API validation tests

---

Makefile
test/e2e/httpproxy/httpproxy_test.go

Run ginkgo without -v to reduce the number of redundant logs on successful runs. This makes it easier to find the failures in the logs.
Test runner will still capture the stdout and stderr of tests, and replay the output when test fails.  
Fixes #4161

test/e2e: Verbose only on failures

---

changelogs/unreleased/4173-sunjayBhatia-docs.md
site/content/resources/deprecation-policy.md

Makes it more lenient since we had conflicting language here, some
saying behavior/fields could change at any time, other saying we are in
sync with k8s policies.

Updates to deprecation policy for alpha APIs

---

test/e2e/poller.go
test/e2e/upgrade/upgrade_test.go

- adds poller that can be used to asynchronously send requests to an app
and get total/successful request counts
- in upgrade test, started after app is deemed routable
- assertion is that > 90% of requests must succeed, arbitrary
measurement for now
Updates: https://github.com/projectcontour/contour/issues/3679

test/e2e/upgrade: Add app polling during upgrade

---

internal/dag/accessors.go
internal/dag/builder_test.go
internal/dag/dag.go
internal/dag/listener_processor.go
internal/xdscache/v3/listener.go

Moves the ListenerName field from VirtualHost
to Listener, to better reflect the data model.
This field is now populated by the listener
processor.

internal/dag: move ListenerName to Listener struct

---

changelogs/unreleased/4169-skriss-minor.md
internal/dag/builder_test.go
internal/dag/httpproxy_processor.go
internal/featuretests/v3/envoy.go
internal/featuretests/v3/routeweight_test.go

Fixes a bug where HTTPProxy TCPProxy service
weights were not being applied.
Closes #4158.

internal/dag: apply TCPProxy service weights

---

internal/dag/builder_test.go

Fixes some logical merge conflicts in
the tests from #4169.

internal/dag: fix tests from #4169

---

apis/projectcontour/v1/httpproxy.go
changelogs/unreleased/4117-stevesloka-minor.md
examples/contour/01-crds.yaml
examples/render/contour-gateway.yaml
examples/render/contour.yaml
internal/annotation/annotations.go
internal/annotation/annotations_test.go
internal/dag/policy.go
internal/dag/policy_test.go
internal/featuretests/v3/retrypolicy_test.go
internal/xdscache/v3/route_test.go
site/content/docs/main/config/annotations.md
site/content/docs/main/config/api-reference.html
site/content/docs/main/config/request-routing.md

Cherry-pick PR #4117 to release-1.18, in preparation for a 1.18.3 release.
Updates #4168
Original commit message below.
---
Since the current field for NumRetries is not a pointer, Contour
doesn't have a good way to understand if the field is unspecified,
or set to zero.
To keep the v1 API contract, Contour will allow this field to be set
to -1 which means the numRetries should be zero. If unspecified or set
to zero, then the Envoy default of 1 is used.

[Release 1.18] Cherry-pick: Allow retry policy, num retries to be zero

---

changelogs/unreleased/4160-skriss-minor.md
internal/dag/gatewayapi_processor.go
internal/dag/status_test.go
internal/status/cache.go
internal/status/gatewayconditions.go
internal/status/gatewayconditions_test.go
internal/status/gatewaystatus.go
internal/status/gatewaystatus_test.go
internal/status/proxystatus.go
internal/status/routeconditions.go

Sets status for Gateway Listeners, specifically
the "attachedRoutes" and "supportedKinds" fields.
Updates #4124.

internal/dag: set Gateway Listener status

---

internal/envoy/v3/ratelimit.go
internal/envoy/v3/route.go
internal/envoy/v3/route_test.go
internal/xdscache/v3/route.go

Moves logic for converting DAG objects to
Envoy objects from the route xds cache to
the internal/envoy/v3 package.

move route DAG->Envoy logic into internal/envoy/v3

---

Makefile
changelogs/unreleased/4075-sunjayBhatia-small.md
examples/contour/03-envoy.yaml
examples/render/contour-gateway.yaml
examples/render/contour.yaml
go.mod
go.sum
internal/xds/v3/snapshotter.go
internal/xdscache/snapshot.go
site/content/resources/compatibility-matrix.md
versions.yaml

https://www.envoyproxy.io/docs/envoy/v1.20.0/version_history/current
Also bumps go-control-plane to latest
Deprecation of existing headermatch usage will need to be handled in the release after this is
merged. The "string match" header matching method is preferred but was
added in 1.20.1 and it was not present in 1.19.x, we will need to
release a version with Envoy 1.20.x compatibility and the subsequent
release will need to move to the "string match" method (rather than the
individual regex/exact/etc. methods.

Bump Envoy to v1.20.1

---

changelogs/unreleased/4200-lrewega-small.md
hack/release/make-release-tag.sh

The certgen job is versioned in releases, so deleting it should not be
necessary for most consumers. Deleting the job can cause problems when
applying the quickstart config via continous deployment (e.g. Argo CD)
as the job disappears before an external observer can acknowledge it
completed successfully, or even confirm that it ever existed.
Signed-off-by: Luke Rewega <lrewega@buf.build>

hack/release: Remove ttlSecondsAfterFinished from certgen job

---

test/scripts/get-contour-upgrade-from-version.sh

Excludes tags with "alpha", "beta" or "rc" when
getting the tag to upgrade from for upgrade tests.

test/scripts: ignore pre-release tags when getting upgrade version

---

changelogs/unreleased/4197-sunjayBhatia-small.md
internal/envoy/v3/route.go
internal/envoy/v3/route_test.go
internal/featuretests/v3/envoy.go
internal/xdscache/v3/route_test.go
test/e2e/ingress/ingress_test.go
test/e2e/ingress/long_path_match_test.go

Ingress/HTTPRoute prefix matches now have an anchor to ensure long
prefixes don't increase the program size. Should ensure they are not
rejected by Envoy.
In addition, add an anchor to regex path matches since they at least
have to start with a literal /
Manually ran ingress conformance tests and besides flakes, all passed 👍🏽 
Updates: #4191

Simplify regex path match to reduce program size

---

test/e2e/httpproxy/cookie_rewrite_test.go

In case cookie attributes are in different order
Re:
https://github.com/projectcontour/contour/runs/4435347950?check_suite_focus=true

test/e2e/httpproxy: Loosen cookie matching to a contains match

---

changelogs/unreleased/4212-skriss-small.md
internal/dag/builder_test.go
internal/dag/gatewayapi_processor.go
internal/dag/status_test.go

Allows Gateways to reference TLS certificates in
other namespaces when a corresponding ReferencePolicy
exists.
Closes #4181.

internal/dag: allow valid cross-namespace Gateway TLS cert refs

---

changelogs/unreleased/4122-skriss-docs.md
site/content/guides/gateway-api-v1alpha2.md

Adds a second copy of the Gateway API
guide, for v1alpha2. Once Contour 1.20
is released, the v1alpha1 guide will
be dropped and the v1alpha2 guide will
be updated with the proper links.
Updates #4091.

site: add a Gateway API v1alpha2 guide

---

changelogs/unreleased/4219-skriss-small.md
internal/dag/cache.go
internal/dag/gatewayapi_processor.go
internal/gatewayapi/helpers.go

Previously Contour accepted either the empty string
or "core" as the group name for the core API group,
i.e. the one containing Services, Secrets, etc. However,
the "core" string is not part of the Gateway API spec
and adds complexity to all logic that interacts with
groups. This PR drops support for it, and expects
that any references to the core API group will have
an empty group string.

Gateway API: drop 'core' as allowed core API group name

---

go.mod
go.sum

See release notes: https://github.com/grpc/grpc-go/releases/tag/v1.42.0

Bump gRPC to v1.42.0

---

go.mod
go.sum

Bump `golang.org/x/net` package to address [CVE-2021-44716](https://groups.google.com/g/golang-announce/c/hcmEScgc00k).
The mitigation for the vulnerability is upgrading Go version, which is done in #4232. Since the same problem was also found in `golang.org/x/net`, upgrading that as well will remove any potential false positive findings.
Updates #4237

Bump golang.org/x/net

---

.github/workflows/stale.yaml

Follow-up to #4250, updates the workflow config
for a breaking change in how to disable marking
issues as stale or closing them.

don't set issues to stale or close them

---

.github/workflows/build_daily.yaml

Fixes error seen with daily build:
```
The workflow is not valid. .github/workflows/build_daily.yaml (Line: 14, Col: 3): The workflow must contain at least one job with no dependencies.
```
We can just run against the last built main image.

remove dependency from daily build

---

.github/workflows/build_daily.yaml

Remove matrix strategy as current daily build doesn't really need it
(don't need to test against multiple k8s versions to test envoy xDS
server).
Also remove image build/load to speed up CI run

Simplify daily build

---

internal/k8s/status.go
test/e2e/incluster/smoke_test.go

Otherwise, when not leader, update buffered channel can be filled up,
since StatusUpdateHandler does not run. This deadlocks the EventHandler.
Shows up in e2e tests in intermittent in-cluster smoke-test failures.
More prevalent with more instances so modified smoke test to test more
apps. The failure occurs when the contour instance Envoy connects to is
not the leader.

internal/k8s: StatusUpdateWriter only writes to update channel when leader

---

changelogs/unreleased/4268-skriss-small.md
examples/gateway/00-crds.yaml
examples/render/contour-gateway.yaml
go.mod
go.sum
internal/dag/builder_test.go
internal/gatewayapi/helpers.go
test/e2e/gateway/request_redirect_test.go

update Gateway API to v0.4.1

---

changelogs/unreleased/4281-sunjayBhatia-small.md
internal/certgen/certgen.go

Previously if creating a secret failed, we fell back to attempting to
update the secret, however if it didn't already exist that would also
fail, shadowing the original error.
Instead we fail fast if the failure to create a secret was not because
it already exists.

internal/certgen: Fix error handling when writing to k8s

---

changelogs/unreleased/4279-sunjayBhatia-docs.md
site/content/docs/main/config/ingress.md
site/data/docs/main-toc.yml

site: Add docs for header manipualtion with Ingress

---

site/content/docs/main/config/ingress.md

Follow-up to #4271, updates the ingress.md page
to also describe the new annotation.
Closes #4282.

site: update ingress.md for tls-cert-namespace annotation

---

hack/release/prepare-release.go

Fixes a bug where GitHub usernames containing
a '-' would break the changelog generator.
Closes #4280.
Tested manually, we now have a changelog file with a hyphenated username, all looks good.

hack/release: allow GitHub usernames with '-'

---

test/e2e/httpproxy/global_rate_limiting_test.go
test/e2e/infra/metrics_test.go

Enables up to 3 attempts for E2E tests that
are known to be flaky and have a tracking
GitHub issue.
This is my proposed pattern for dealing with recurring flakes: file an issue, label it as `kind/flake`, and add the `FlakeAttempts(3)` option to the test spec (see https://onsi.github.io/ginkgo/#repeating-spec-runs-and-managing-flaky-specs) along with a comment linking to the issue. This is more efficient than re-running the entire CI suite for known flakes, and is explicitly opt-in on a per-test basis (vs. enabling flake re-runs for *all* tests, which could hide actual bugs or new flakes). We should also spend time each release cycle trying to fix flakes so this doesn't become unmanageable.
Log output in case of a flake occurrence looks like: …

test/e2e: enable retrying flaky tests

---

changelogs/unreleased/4287-skriss-small.md
cmd/contour/serve.go
cmd/contour/serve_test.go
test/e2e/ingress/headers_policy_test.go
test/e2e/ingress/ingress_test.go

Fixes a bug where the ApplyToIngress flag
from the global headers policy was not being
passed to the ingress DAG processor, so the
headers policy was never being applied to
Ingress objects.
Closes #4285.

cmd/contour: pass ApplyToIngress flag to DAG processor

---

changelogs/unreleased/4312-sunjayBhatia-small.md
cmd/contour/serve.go

controller-runtime manager provided listeners for metrics and health
(both are implemented via our own mechanisms, health was already
disabled but this explicitly does so)
Helps with e2e tests especially, ensure Contour can start up and doesn't
conflict on binding to the same port (e.g. default metrics port 8080)
if a Contour instance does not exit properly.

cmd/contour: Disable unused listeners

---

apis/projectcontour/v1/httpproxy.go
design/downstream-crl-design.md

Signed-off-by: Aidan Jensen <aidan@artificial.com>
Wanted to run this by the maintainers before I put the effort into implementation. Have a possible need to add a certificate revocation list to our http proxies. It gets passed in as a k8s secret just like a CA Certificate, so I would just follow that functionality.
Thoughts or objections?

Add CRL to http proxy client validation

---

hack/actions/build-and-push-release-images.sh

Adds `--force` to `git fetch --tags` to
work with the v2 checkout action.
Closes #4309.
I was able to repro the error locally by running through the relevant git commands, and to confirm that with this change, the error no longer occurs. Won't be able to exercise the full workflow without pushing a dummy tag, though.

hack/actions: fix release image tag fetching

---

hack/actions/build-and-push-release-images.sh

Adds `--force` to `git fetch --tags` to
work with the v2 checkout action.
Closes #4309.

[release-1.20 branch] hack/actions: fix release image tag fetching

---

netlify.toml

cc @tsaarni @OrlinVasilev 
This is the output of "Update quickstart YAML redirects" under https://projectcontour.io/resources/release-process/#minor-release-process. We usually do this as a separate PR from the website/docs that's merged *after* the release branches are created, so the redirects are always valid.

update netlify redirects for v1.20.0

---

changelogs/unreleased/4316-alessandroargentieri-small.md
internal/dag/accessors.go
internal/dag/extension_processor.go
internal/dag/gatewayapi_processor.go
internal/dag/httpproxy_processor.go
internal/dag/ingress_processor.go
internal/dag/secret.go
internal/dag/secret_test.go

internal/dag: Removed duplicated function for secret validation in dag layer
Removed validSecret function from accessors.go in the dag package.
This function checked if a secret is a valid TLS secret and returned an error.
Substituted with the validTLSSecret in secret.go in the dag package,
function that wraps the isValidSecret function by adding some logic on it.
This way the duplication of code is avoided and the feature of the deleted function is maintained.
Fixes #3503
Signed-off-by: alessandroargentieri <alexmawashi87@gmail.com>

internal/dag: removed duplicated function for secret validation

---

.github/workflows/build_main.yaml
.github/workflows/build_tag.yaml
changelogs/unreleased/4314-skriss-major.md

Removes the Docker Hub image push since
images are now published on GHCR.
Closes #3998.
Last chance for anyone to weigh in if they think this is a bad idea and we should keep pushing images to Docker Hub in the background!

stop pushing images to Docker Hub

---

changelogs/unreleased/4329-skriss-small.md
cmd/contour/ingressstatus.go
cmd/contour/serve.go
cmd/contour/serve_test.go
examples/contour/02-role-contour.yaml
examples/render/contour-deployment.yaml
examples/render/contour-gateway.yaml
examples/render/contour.yaml
internal/dag/cache.go
internal/dag/cache_test.go
internal/featuretests/v3/ingressclass_test.go
internal/featuretests/v3/route_test.go
internal/ingressclass/ingressclass.go
internal/ingressclass/ingressclass_test.go
internal/k8s/rbac.go
internal/k8s/statusaddress.go
internal/k8s/statusaddress_test.go
test/e2e/httpproxy/httpproxy_test.go
test/e2e/httpproxy/multiple_ingress_classes_test.go

- removes duplicate `httpProxyValid` func from E2E's
- drops `IngressClass` caching from the DAG as the `IngressClass` resource itself is not used anywhere
- switch to using a string slice internally to represent ingress classes for clarity; convert comma-separated string to slice upfront in `serve.go`

4109 followups

---

changelogs/unreleased/4332-sunjayBhatia-minor.md
cmd/contour/serve.go
examples/contour/01-contour-config.yaml
examples/contour/02-role-contour.yaml
examples/render/contour-deployment.yaml
examples/render/contour-gateway.yaml
examples/render/contour.yaml
internal/k8s/rbac.go
site/content/docs/main/configuration.md
test/e2e/deployment.go
test/e2e/incluster/leaderelection_test.go

- Removes RBAC for ConfigMaps
- Also removes mentions of leader election ConfigMaps from examples
- Updates e2e tests
Fixes: #1393

Leader election only uses Lease object

---

.github/workflows/label_check.yaml
CONTRIBUTING.md
changelogs/unreleased/deprecation-sample.md
hack/actions/check-changefile-exists.go
hack/release/prepare-release.go
hack/release/release-notes-template.md
site/data/github-labels.yaml

Can be used alone or in conjunction with another label.
Also makes it so release-note and release-note-action-required legacy
labels have to be alone, for simplicity.
Fixes: #4258

release-note/deprecation PR label validated by tooling

---

changelogs/unreleased/4340-sunjayBhatia-deprecation.md
cmd/contour/serve.go
cmd/contour/servecontext.go
pkg/config/parameters.go
pkg/config/parameters_test.go

Leader election configuration via configuration file was deprecated in Contour
v1.20.0. Configuration should be done via command line parameters only.

pkg/config: Remove leader election configuration

---

changelogs/unreleased/4361-tsaarni-small.md
go.mod
go.sum

This change bumps the version of github.com/prometheus/client_golang to v1.11.1 to address CVE-2022-21698.
Fixes #4360

Bump github.com/prometheus/client_golang

---

changelogs/unreleased/4350-tsaarni-small.md
internal/envoy/cluster.go
internal/envoy/v3/cluster_test.go
internal/featuretests/v3/backendcavalidation_test.go
internal/featuretests/v3/backendclientauth_test.go
internal/featuretests/v3/externalname_test.go
internal/featuretests/v3/headerpolicy_test.go
internal/featuretests/v3/tcpproxy_test.go
internal/featuretests/v3/upstreamprotocol_test.go
internal/xdscache/v3/cluster_test.go

Include SNI and Protocol fields into cluster name generation to ensure that different cluster will be generated if two clusters are otherwise equal except for those fields.  Previously clusters overwrote each other and only one got configured to Envoy.  
Fixes #4242 
Fixes #4348

internal/envoy: fix cluster deduplication

---

Makefile
changelogs/unreleased/4350-tsaarni-small.md
changelogs/unreleased/4361-tsaarni-small.md
changelogs/unreleased/4365-skriss-small.md
examples/contour/03-envoy.yaml
examples/deployment/03-envoy-deployment.yaml
examples/render/contour-deployment.yaml
examples/render/contour-gateway.yaml
examples/render/contour.yaml
go.mod
go.sum
internal/envoy/cluster.go
internal/envoy/v3/cluster_test.go
internal/featuretests/v3/backendcavalidation_test.go
internal/featuretests/v3/backendclientauth_test.go
internal/featuretests/v3/externalname_test.go
internal/featuretests/v3/headerpolicy_test.go
internal/featuretests/v3/tcpproxy_test.go
internal/featuretests/v3/upstreamprotocol_test.go
internal/xdscache/v3/cluster_test.go
site/content/resources/compatibility-matrix.md
versions.yaml

- update Envoy to v1.21.1 (#4365)
- internal/envoy: fix cluster deduplication (#4350)
- Bump github.com/prometheus/client_golang (#4361)

Cherrypicks for Contour 1.20.1

---

changelogs/unreleased/4347-yankay-docs.md
site/content/guides/deploy-aws-tls-nlb.md

Update AWS NLB Guide with correct annotations. Follow the  [AWS EKS Doc](https://docs.aws.amazon.com/eks/latest/userguide/network-load-balancing.html)
Fix the Issue: https://github.com/projectcontour/contour/issues/4346 .
Signed-off-by: Kay Yan [kay.ay@daocloud.io](mailto:kay.ay@daocloud.io)

site/docs: Update AWS NLB Guide with correct annotations

---

site/themes/contour/assets/scss/_components.scss

Removes setting code block text to grey, to allow
the syntax highlighter to use its default text
color which improves contrast.
Updates #4289.

site: improve contrast for code blocks

---

changelogs/unreleased/4379-sunjayBhatia-minor.md
internal/envoy/v3/bootstrap.go
internal/envoy/v3/bootstrap_test.go

Was inadvertently reverted previously to Envoy's default of 100. This
change sets the error limit of a regex program size back to 1048576
(2^20).
Also adds warning threshold that Envoy will log and collect stats about.
Updates: #4241
Updates: #3452

internal/envoy/v3: Reenable larger max regex program size

---

changelogs/unreleased/4380-sunjayBhatia-small.md
cmd/contour/serve.go
internal/xds/v3/contour.go
internal/xds/v3/server.go
internal/xdscache/snapshot.go
internal/xdscache/v3/runtime.go
internal/xdscache/v3/server_test.go

Part of gradual implementation of RTDS, first step to allow configurable
runtime values. Returns an empty set of Runtime layers (instead of just
returning unimplemented to avoid issues in future upgrades). Next step
will be to add ability to dynamically fetch Runtime layer in bootstrap.
Updates: #3452

Add base RTDS implementation

---

README.md

That link is needed to fullfill the checks from
https://clomonitor.io/projects/contour/contour
https://github.com/cncf/clomonitor/issues/66
Signed-off-by: OrlinVasilev <ovasilev@vmware.com>

Add link to GOVERNANCE in Community repo

---

test/e2e/httpproxy/httpproxy_test.go
test/e2e/httpproxy/path_rewrite_test.go

To demonstrate it works, and to give a framework to use if/when we do
path regex rewriting

test/e2e: Add path prefix rewrite test

---

changelogs/unreleased/4394-skriss-small.md
cmd/contour/certgen.go
cmd/contour/certgen_test.go
internal/certgen/certgen.go

Adds an optional --name-prefix flag to the
certgen command that, if specified, adds a
prefix to the outputted Kubernetes secret
names, e.g. prefix-contourcert.

certgen: add optional --name-prefix flag

---

changelogs/unreleased/4391-sunjayBhatia-small.md
cmd/contour/contour.go
internal/k8s/log.go
internal/k8s/log_test.go

Ensures log messages from controller-runtime manager/child components
are logged and visible. Previously, these logs were actually written to
a null logger since the controller-runtime logger was not initialized
(see
https://github.com/kubernetes-sigs/controller-runtime/blob/9ee63fc65a9720568f74df9901b16883621636b4/pkg/log/log.go#L77-L85)

internal/k8s: Set logger for controller-runtime in InitLogging

---

changelogs/unreleased/4402-rajatvig-small.md
examples/render/contour-deployment.yaml
examples/render/contour-gateway.yaml
examples/render/contour.yaml
hack/generate-deployment.sh
hack/generate-gateway-deployment.sh

examples/render: Set the `imagePullPolicy` for certen job to `IfNotPresent`
Set the `imagePullPolicy` for certen job to `IfNotPresent`
Fixes #4318 
Signed-off-by: Rajat Vig <rvig@etsy.com>

Remove the hack in scripts for certgen job

---

test/e2e/framework.go
test/e2e/http.go

- Fixes a bug in the code that waits for an existing
terminating namespace to be gone before creating a
new one for E2E tests which caused the create to
fail.
- Changes the type of the condition func used
by HTTP.RequestUntil to allow checking for
properties of the response body.

test/e2e: minor fixes and improvements

---

test/e2e/framework.go
test/e2e/gateway/gateway_test.go
test/e2e/gateway/multiple_https_listeners_test.go
test/e2e/httpproxy/tcproute_https_termination_test.go

Adds a test that demonstrates a Gateway
with multiple HTTPS Listeners, each with
a different hostname and TLS cert.
Also updated some of the Describe text for clarity.

test/e2e: add test for Gateway with multiple HTTPS listeners

---

test/e2e/deployment.go
test/scripts/make-kind-cluster.sh

Moves Contour CRD installation to cluster setup
since they don't change across test suites, which
simplifies the code.

test/e2e: install Contour CRDs during cluster setup

---

examples/ratelimit/02-ratelimit.yaml

Update ratelimit image so users of the example can use newer features
like https://github.com/envoyproxy/ratelimit#custom-headers
This came up in a recent query in Slack, investigating it I noticed this feature
was added in a more recent version of ratelimit than our examples used.

Ratelimit example: Update image

---

changelogs/unreleased/4426-skriss-minor.md
internal/provisioner/model/names.go
internal/provisioner/objects/configmap/configmap.go
internal/provisioner/objects/configmap/configmap_test.go
internal/provisioner/objects/daemonset/daemonset.go
internal/provisioner/objects/deployment/deployment.go
internal/provisioner/objects/job/job.go
internal/provisioner/objects/object.go
internal/provisioner/objects/rbac.go
internal/provisioner/objects/service/service.go
internal/provisioner/validation/validation.go
test/e2e/provisioner/provisioner_test.go

Adds support for provisioning more than one Contour+Envoy instance per namespace.
Closes #4418.

internal/provisioner: support more than one instance per namespace

---

Makefile
examples/render/contour-gateway-provisioner.yaml
hack/generate-provisioner-deployment.sh
hack/release/make-release-tag.sh

Adds a rendered manifest for the Gateway
provisioner, and incorporates it into the
make-release-tag.sh script to do tag and
pull policy replacements at release time.
Closes #4420

Include gateway provisioner in codegen/release tooling

---

apis/projectcontour/v1/httpproxy.go
changelogs/unreleased/4356-tsaarni-small.md
examples/contour/01-crds.yaml
examples/render/contour-deployment.yaml
examples/render/contour-gateway.yaml
examples/render/contour.yaml
internal/dag/builder_test.go
internal/dag/dag.go
internal/dag/extension_processor.go
internal/dag/gatewayapi_processor.go
internal/dag/httpproxy_processor.go
internal/dag/ingress_processor.go
internal/dag/policy.go
internal/dag/policy_test.go
internal/envoy/cluster.go
internal/envoy/v3/auth.go
internal/envoy/v3/bootstrap.go
internal/envoy/v3/cluster.go
internal/envoy/v3/cluster_test.go
internal/envoy/v3/route.go
internal/envoy/v3/route_test.go
internal/featuretests/v3/envoy.go
internal/featuretests/v3/extensionservice_test.go
internal/featuretests/v3/timeoutpolicy_test.go
site/content/docs/main/config/api-reference.html

This change adds field `HTTPProxy.spec.routes.timeoutPolicy.idleConnection`. The field sets timeout for how long the upstream connection will be kept idle between requests before disconnecting it. This [connection timeout](https://www.envoyproxy.io/docs/envoy/latest/faq/configuration/timeouts#connection-timeouts) is different than previously existing field `timeoutPolicy.idle`, which controls the [stream timeout](https://www.envoyproxy.io/docs/envoy/latest/faq/configuration/timeouts#stream-timeouts): a timeout for single request-response. Altough connection timeout might be what user wanted in the first place, the existing field and functionality is kept for backwards compatibility and new field was introduced for the connection timeout.
When `timeoutPolicy.idleConnection` is not set then …

Added idle connection timeout to HTTPProxy

---

examples/render/contour-gateway-provisioner.yaml

Changes to generated file `contour-gateway-provisioner.yaml` did not get picked up while doing merge of #4356.
Automatic squash&merge missed it and tests failed first time when running against main.
This change adds the changes back to the generated file to fix the CI/CD failure.

Add generated example yaml file back to fix the test

---

examples/gateway-provisioner/01-roles.yaml
examples/render/contour-gateway-provisioner.yaml
hack/generate-rbac.sh
internal/provisioner/objects/rbac/clusterrole/cluster_role.go
internal/provisioner/rbac/rbac.go

Tidies up provisioner RBAC markers and reuses
the Contour RBAC file when generating the
provisioner RBAC YAML instead of requiring all
markers to be duplicated in the provisioner's
file.

clean up provisioner RBAC and reuse Contour RBAC for it

---

changelogs/unreleased/4446-lou-lan-docs.md
site/content/docs/main/config/fundamentals.md
site/content/docs/main/config/virtual-hosts.md
site/content/docs/v1.20.1/config/fundamentals.md
site/content/docs/v1.20.1/config/virtual-hosts.md

Each path in an Ingress is required to have a corresponding path type. Paths that do not include an explicit pathType will fail validation. 
Fix #4447

Each path in an Ingress is required to have a corresponding path type.

---

.github/workflows/prbuild.yaml
Makefile
test/scripts/run-gateway-conformance.sh

ci: run Gateway API conformance tests

---

test/e2e/gateway/tlsroute_test.go

test/e2e: add flake retries for TLSRoute tests

---

cmd/contour/gatewayprovisioner.go
internal/provisioner/controller/gateway_test.go
internal/provisioner/controller/gatewayclass_test.go
internal/provisioner/scheme.go

Replaces small unit tests of some of the individual helpers with full tests of the Reconcile() method that use a fake controller-runtime client.

internal/provisioner: add Reconcile tests for controllers

---

test/e2e/gateway/gateway_test.go
test/e2e/gateway/tlsroute_test.go

Drops parts of the TLSRoute tests that remove
all SNI filtering, to avoid flakes. Also uses
unique hostnames between the tests.
Updates #4431.
I've run the E2E's a bunch of times with this change and so far haven't seen any occurrences of that test failure, will repeat some more times on this PR.

test/e2e: fix TLSRoute test flake

---

changelogs/unreleased/4459-skriss-small.md
internal/provisioner/controller/gateway.go
internal/provisioner/controller/gateway_test.go
internal/provisioner/model/model.go
internal/provisioner/objects/contourconfig/contourconfig.go

When a GatewayClass has a parametersRef
to a ContourDeployment resource that has
Config specified, use that Config when
provisioning Gateways and their associated
ContourConfigurations.

internal/provisioner: support using ContourDeployment.Config

---

changelogs/unreleased/4403-bourquep-small.md
internal/envoy/v3/listener.go
internal/envoy/v3/listener_test.go

When Envoy serves as a `grpc-web` gateway, HTTP requests/responses use one of the [documented content-type](https://github.com/grpc/grpc-web#wire-format-mode), for which gzip compression is _not_ enabled by [default in Envoy](https://www.envoyproxy.io/docs/envoy/v1.17.4/api-v2/config/filter/http/compressor/v2/compressor.proto#envoy-api-msg-config-filter-http-compressor-v2-compressor).
This MR adds the `grpc-web` content types to Envoy's default ones, so they are gzip-compressed by default.
Fixes #4345
Signed-off-by: Pascal Bourque <pascal@studyo.co>

internal/envoy: Enable gzip compression for grpc-web content types.

---

changelogs/unreleased/4470-sunjayBhatia-small.md
internal/envoy/v3/listener.go
internal/envoy/v3/listener_test.go
internal/featuretests/v3/listeners_test.go
internal/xdscache/v3/listener.go
internal/xdscache/v3/listener_test.go

OriginalIPDetectionFilter is not compatible with the UseRemoteAddress
field, revert to the previous implementation which was un-deprecated in
Envoy 1.20.
See: https://github.com/envoyproxy/envoy/issues/17554 and https://github.com/projectcontour/contour/issues/4449
Reverts part of https://github.com/projectcontour/contour/pull/4142

Revert back to HTTPConnectionManager XFFNumTrustedHops

---

changelogs/unreleased/4474-skriss-small.md
cmd/contour/gatewayprovisioner.go
design/automated-provisioning-design.md
internal/provisioner/controller/gateway_test.go
internal/provisioner/controller/gatewayclass_test.go
test/e2e/provisioner/provisioner_test.go
test/scripts/run-gateway-conformance.sh

This more general controller name makes sense
given that the provisioner is just one piece
of Gateway control logic; the xDS server also
plays a major role.

update default controller name to projectcontour.io/gateway-controller

---

internal/envoy/v3/listener.go
internal/envoy/v3/listener_test.go

Follow up to https://github.com/projectcontour/contour/pull/4403 which
started using a deprecated field
Signed-off-by: Sunjay Bhatia <sunjayb@vmware.com>

Use non-deprecated Content-Type field in compressor filter

---

changelogs/unreleased/4482-skriss-small.md
internal/dag/gatewayapi_processor.go
internal/dag/status_test.go

When an HTTPRoute or TLSRoute has a cross-namespace
backend ref that's not permitted by a ReferencePolicy,
use the RefNotPermitted condition reason.
Closes #4479.
ref. https://github.com/kubernetes-sigs/gateway-api/pull/1081#discussion_r851537809

internal/dag: use RefNotPermitted reason when applicable

---

apis/projectcontour/v1alpha1/contourdeployment.go
examples/contour/01-crds.yaml
examples/render/contour-deployment.yaml
examples/render/contour-gateway-provisioner.yaml
examples/render/contour-gateway.yaml
examples/render/contour.yaml
internal/provisioner/controller/gateway.go
site/content/docs/main/config/api-reference.html

Removes kubebuilder defaults from the ContourDeployment
CRD; defaults are applied internally by the provisioner.
Closes https://github.com/projectcontour/contour/issues/4471.

remove all ContourDeployment CRD kubebuilder defaults

---

changelogs/unreleased/4487-skriss-small.md
internal/envoy/v3/listener.go
internal/envoy/v3/listener_test.go
internal/envoy/v3/stats.go
internal/envoy/v3/stats_test.go

Uses typed config for all extensions to remove
reliance on well-known names or internal type
URL constants.
(This is needed in order to upgrade to Envoy 1.22 since we still have a few spots that are relying on well-known names, support for which is being dropped in 1.22).

internal/envoy: use typed config for all extensions

---

cmd/contour/servecontext.go
cmd/contour/servecontext_test.go
test/e2e/httpproxy/httpproxy_test.go
test/e2e/httpproxy/merge_slash_test.go

Fixes a bug where the DisableMergeSlashes option
was not being propagated from the config file and
adds unit and E2E tests.
Co-authored-by: Máté Szabó <mszabo@fandom.com>
cc @mszabo-wikia, got this updated so we can get it in for the upcoming release. I've included you as a co-author here.

fix DisableMergeSlashes propagation, add tests

---

changelogs/unreleased/4486-tsaarni-small.md
cmd/contour/contour.go
site/content/docs/main/configuration.md

This change enables Contour logs in JSON format as discussed in https://github.com/projectcontour/contour/issues/4414#issuecomment-1087109701.
The PR proposes new command line argument `--log-format` over generally preferred configuration CRD or config file field. The reasoning for new command line argument is to allow setting formatter for all sub-commands, not only `serve`, and setting it as early as possible, before CR is fetched from the API server or before config file is read from filesystem.
Fixes #4414 

cmd/contour: Add support for json log formatter

---

examples/example-workload/gatewayapi/kuard/kuard.yaml
netlify.toml
site/content/getting-started/_index.md
site/content/guides/gateway-api.md

Updates #4468.
Since the quickstart and guides aren't versioned, holding this until the 1.21 GA release.

update quickstart and Gateway API guide

---

changelogs/unreleased/4523-skriss-small.md
internal/dag/gatewayapi_processor.go
internal/dag/status_test.go

Computes Gateway API Listener supported kinds
sooner, so it's populated in all cases where
it can be computed.
(FYI this will be needed in order to pass an upcoming conformance test, and I think makes sense regardless).

internal/dag: compute Listener supported kinds sooner

---

changelogs/unreleased/4477-mmalecki-small.md
go.mod
go.sum
internal/envoy/v3/route.go
internal/envoy/v3/route_test.go
internal/featuretests/v3/envoy.go
internal/xdscache/v3/route_test.go

Update envoy's `go-control-plane` to latest.
Update the tests.
Remove the "path prefix match segment with regex meta char" - it testing
possible ill-behavior of the RegExp prefix implementation.
Fixes #4442.
Signed-off-by: Maciej Małecki <me@mmalecki.com>

internal/envoy: use Envoy's path-based prefix matching

---

changelogs/unreleased/4545-skriss-small.md
internal/dag/builder_test.go
internal/dag/gatewayapi_processor.go
internal/dag/status_test.go
test/e2e/gateway/gateway_test.go
test/e2e/gateway/invalid_backend_ref_test.go

The Gateway API spec has been updated to
require returning a 404 instead of a 503
when there are no valid backend refs on
an HTTPRoute rule. Updates Contour to match
the revised spec.
Gateway API ref: https://github.com/kubernetes-sigs/gateway-api/pull/1151
Updates #4543.

Gateway API: return a 404 when no valid backend refs

---

internal/envoy/v3/bootstrap.go
internal/envoy/v3/bootstrap_test.go

"path" config source is deprecated for path_config_source which also
adds the option of a watched directory that can be for different uses
Noticed when working on https://github.com/projectcontour/contour/pull/4529

internal/envoy/v3: Use path_config_source for config source specifier

---

changelogs/unreleased/4548-skriss-small.md
cmd/contour/shutdownmanager.go
site/content/docs/main/redeploy-envoy.md
test/e2e/deployment.go

Changes the default check delay on the
shutdown command from 60s to 0s, since there
is no harm in checking immediately for
all connections to be closed, and it may
lead to faster shutdown when there are no
connections.
Closes #4422.
Reviewers, please check me on logic here; I don't see any harm in starting to check for no open connections immediately, but maybe I'm missing something.

cmd/contour: change shutdown --check-delay default to 0s

---

.github/workflows/build_daily.yaml
.github/workflows/prbuild.yaml
Makefile

Also switches to using an env var in
the GitHub workflows to specify Go
version to reduce repetition.

update to Go 1.18.2 and setup-go v3

---

go.mod
internal/build/version.go
pkg/config/parameters.go
pkg/config/parameters_test.go
test/e2e/deployment.go

Use gopkg.in/yaml.v3 for config file parsing.

pkg/config: Migrate from gopkg.in/yaml.v2 to v3

---

changelogs/unreleased/4558-skriss-small.md
internal/dag/gatewayapi_processor.go
internal/dag/gatewayapi_processor_test.go

Fixes a bug where a route with multiple parent
refs to listeners would not attach to all
listeners correctly.

Gateway API: fix bug with routes having multiple listener refs

---

changelogs/unreleased/4559-skriss-small.md
internal/dag/builder_test.go
internal/dag/gatewayapi_processor.go
internal/dag/gatewayapi_processor_test.go
test/e2e/gateway/tls_wildcard_host_test.go

Changes Gateway API hostname logic to allow
wildcard hostnames to match more than one
DNS label per clarification in the upstream
spec.
Closes #4554.

Gateway API: allow wildcard hostnames to match more than one DNS label

---

test/e2e/httpproxy/merge_slash_test.go

test/e2e: add flake retries to merge slash test

---

Makefile
changelogs/unreleased/4567-sunjayBhatia-minor.md
changelogs/unreleased/4572-sunjayBhatia-minor.md
cmd/contour/gatewayprovisioner.go
examples/contour/03-envoy.yaml
examples/deployment/03-envoy-deployment.yaml
examples/render/contour-deployment.yaml
examples/render/contour-gateway.yaml
examples/render/contour.yaml
site/content/resources/compatibility-matrix.md
versions.yaml

Envoy released a 1.22.2 because of CI issues they were having

main: Bump Envoy to 1.22.2

---

changelogs/unreleased/4580-skriss-deprecation.md
changelogs/unreleased/4580-skriss-small.md
cmd/contour/serve.go
examples/contour/02-role-contour.yaml
examples/gateway-provisioner/01-roles.yaml
examples/render/contour-deployment.yaml
examples/render/contour-gateway-provisioner.yaml
examples/render/contour-gateway.yaml
examples/render/contour.yaml
internal/dag/builder_test.go
internal/dag/cache.go
internal/dag/cache_test.go
internal/dag/gatewayapi_processor.go
internal/dag/status_test.go
internal/k8s/rbac.go
internal/provisioner/objects/rbac/clusterrole/cluster_role.go
site/content/resources/security-threat-model.md

Adds support for the renamed ReferenceGrant
resource while retaining support for
ReferencePolicy, to allow for a seamless
migration. ReferencePolicy support will
be removed in a subsequent release.
Updates https://github.com/projectcontour/contour/issues/4555.

Gateway API: add support for ReferenceGrant

---

.github/workflows/build_daily.yaml
Makefile
test/scripts/run-gateway-conformance.sh

Changes the PR/push run of Gateway API
conformance to run using the go.mod
version of Gateway API, and adds a daily
run of the latest conformance tests.
Closes https://github.com/projectcontour/contour/issues/4513.

Gateway API: adjust conformance runs 

---

changelogs/unreleased/4585-izturn-minor.md
internal/provisioner/model/names.go
internal/provisioner/objects/dataplane/dataplane.go
internal/provisioner/objects/deployment/deployment.go

bind create label operation for contour's deployment to the object self for management easy

internal/provisioner: Bind create label operation for contour's deployment to the object

---

changelogs/unreleased/4586-izturn-minor.md
internal/provisioner/objects/service/service.go
test/e2e/deployment.go

it seems the fields of object nest too deeply, so use  a local variable to replace it to make read code easy

internal/provisioner: Use local variable  to replace the long access chain of fields

---

.github/workflows/build_daily.yaml

Updates the branch name used for Gateway API
for the daily conformance tests.

Gateway API: update branch name for daily conformance tests

---

changelogs/unreleased/4598-skriss-small.md
internal/dag/gatewayapi_processor.go
internal/dag/status_test.go
internal/status/gatewayclassconditions.go
internal/status/gatewayclassconditions_test.go
internal/status/gatewaystatus.go
internal/status/gatewaystatus_test.go
internal/status/routeconditions.go
test/e2e/gateway/invalid_backend_ref_test.go
test/e2e/gateway/multiple_gateways_and_classes_test.go

Replaces usage of internal Contour types
and values for Gateway API conditions with
upstream ones where available.
Updates #4560.

Gateway API: use upstream condition types and values

---

changelogs/unreleased/4615-skriss-small.md
internal/dag/gatewayapi_processor.go
internal/dag/gatewayapi_processor_test.go
internal/dag/status_test.go

Moves the logic for parsing/validating a Listener
namespace label selector into computeListener, and
sets Listener conditions appropriately when the
selector is invalid.

internal/dag: set Listener condition for invalid namespace selector

---

apis/projectcontour/v1alpha1/accesslog.go
apis/projectcontour/v1alpha1/accesslog_test.go
changelogs/unreleased/4627-sunjayBhatia-small.md

See https://www.envoyproxy.io/docs/envoy/v1.23.0/version_history/v1.23/v1.23.0#new-features
Adds support for %METADATA% complex operator (not %UPSTREAM_METADATA% since
that is deprecated apparently) and simple operators:
%UPSTREAM_PROTOCOL%, %UPSTREAM_PEER_SUBJECT%, %UPSTREAM_PEER_ISSUER%,
%UPSTREAM_TLS_SESSION_ID%, %UPSTREAM_TLS_CIPHER%,
%UPSTREAM_TLS_VERSION%, %UPSTREAM_PEER_CERT_V_START%,
%UPSTREAM_PEER_CERT_V_END%, %UPSTREAM_PEER_CERT% and
%UPSTREAM_FILTER_STATE%
Fixes https://github.com/projectcontour/contour/issues/4624

Support new access log operators from Envoy 1.23.0

---

changelogs/unreleased/4631-skriss-minor.md
internal/dag/builder_test.go
internal/dag/gatewayapi_processor.go
internal/dag/status_test.go
internal/featuretests/v3/tlsroute_test.go
test/e2e/gateway/gateway_test.go
test/e2e/gateway/tlsroute_test.go

Requires the HTTPS listener protocol to
be used with TLS mode Terminate (compatible
with HTTPRoutes) and the TLS protocol to
be used with TLS mode Passthrough (compatible
with TLSRoutes).
Closes #4629.
The actual change is pretty straightforward, but a bunch of our tests were inadvertently using invalid combos of protocols and modes that had to be cleaned up.
For reference, https://gateway-api.sigs.k8s.io/guides/tls/ provides the best explanation of how this is intended to work.

internal/dag: fix Gateway API HTTPS/TLS protocol handling

---

changelogs/CHANGELOG-v1.22.0-rc.1.md
hack/release/release-notes-template.md

Fixes links in the changelog template
and the v1.22.0-rc.1 changelog.

fix changelog links

---

examples/example-workload/gatewayapi/blue-green/blue-green.yaml
examples/example-workload/gatewayapi/kuard/kuard.yaml
site/content/getting-started/_index.md
site/content/guides/gateway-api.md

Updates Gateway API guide and other examples
to use v1beta1 resources now that they're
available.
(This should be merged around the same time v1.22.0 is released, since none of these examples are versioned and v1beta1 Gateway API resources will only work with the new release).

update Gateway API examples to use v1beta1

---

test/e2e/deployment.go
test/e2e/upgrade/upgrade_test.go

Removes the check that the Envoy DaemonSet
has become out-of-date after the upgrade,
since during the time that we're waiting
for the Contour deployment to update, the
Envoy DS is likely to become up-to-date
again.
Closes #4647.

test/e2e/upgrade: remove WaitForEnvoyDaemonSetOutOfDate check

---

test/scripts/get-contour-upgrade-from-version.sh

Updates the "upgrade from" version logic for when
on a tag to get the correct previous tag.

test/scripts: fix upgrade from version logic when on a tag

---

test/e2e/httpproxy/grpc_test.go

Reduced exponential backoff interval but increased overall
rpc deadline to make sure retries fit within it.

test/e2e/httpproxy: Adjust timeouts in gRPC test

---

changelogs/unreleased/4652-sunjayBhatia-small.md
internal/envoy/v3/bootstrap.go
internal/envoy/v3/bootstrap_test.go
internal/envoy/v3/regex.go
internal/envoy/v3/regex_test.go
internal/envoy/v3/route_test.go
internal/featuretests/v3/wildcardhost_test.go

Should now use default regex engine in bootstrap
Deprecation introduced in Envoy 1.23.0 which Contour 1.22.0 was released with so
safe to merge

internal/envoy/v3: Stop using deprecated regex engine field of regexmatch

---

go.mod
go.sum
test/e2e/fixtures.go
test/e2e/httpproxy/grpc_test.go

Rather than TCP check, use grpc-health-probe
Should hopefully help with flakes since upstream won't go healthy until the gRPC server is actually up
See https://github.com/sunjayBhatia/yages for fork
This will be the image/code used for adding upstream TLS tests as well
Updates #1894

Switch to image with better healthchecking

---

.github/workflows/build_daily.yaml
.github/workflows/prbuild.yaml
Makefile
changelogs/unreleased/4660-sunjayBhatia-small.md

Release notes: https://go.dev/doc/go1.19

Bump golang to 1.19.0

---

changelogs/unreleased/4690-tsaarni-small.md
internal/dag/policy.go
internal/dag/policy_test.go

The global connect-timeout configuration value was not taking effect for clusters when timeoutPolicy was not set for the route.
The bug was found and pinpointed by @ravilr https://github.com/projectcontour/contour/commit/0e3d735feb66c0041d4400925cf8b7fd293bc430#r82376547
Fixes #4688

internal/dag: set connect timeout when route policy is unset

---

Makefile
changelogs/unreleased/4691-skriss-small.md
cmd/contour/gatewayprovisioner.go
examples/contour/03-envoy.yaml
examples/render/contour-gateway.yaml
examples/render/contour.yaml
site/content/resources/compatibility-matrix.md
versions.yaml

update Envoy to v1.23.1

---

changelogs/unreleased/4690-tsaarni-small.md
internal/dag/policy.go
internal/dag/policy_test.go

The global connect-timeout configuration value was not taking effect for
clusters when timeoutPolicy was not set for the route.
Fixes #4688

[release-1.22] internal/dag: set connect timeout when route policy is unset (#4690)

---

Makefile
changelogs/unreleased/4691-skriss-small.md
cmd/contour/gatewayprovisioner.go
examples/contour/03-envoy.yaml
examples/render/contour-gateway.yaml
examples/render/contour.yaml
site/content/resources/compatibility-matrix.md
versions.yaml

[release-1.22] update Envoy to v1.23.1 (#4691)

---

test/e2e/gateway/request_mirror_test.go

test/e2e: add flake retries for request mirror test

---

internal/provisioner/model/model.go
internal/provisioner/objects/dataplane/dataplane_test.go
internal/provisioner/objects/deployment/deployment_test.go
internal/provisioner/objects/rbac/clusterrole/cluster_role_test.go
internal/provisioner/objects/rbac/clusterrolebinding/cluster_role_binding_test.go
internal/provisioner/objects/rbac/role/role_test.go
internal/provisioner/objects/rbac/rolebinding/role_binding_test.go
internal/provisioner/objects/service/service_test.go

The New function for creating a model was only
used in test code and was largely redundant
with the newer Default function. Replaces the
former with the latter and inlines any
customizations needed by individual tests.

internal/provisioner: drop New func for creating a model

---

internal/provisioner/model/model.go

Drops kubebuilder annotations from the internal
Model struct. These were carry-overs from when
this code was imported from the operator's API
and are not needed here.

internal/provisioner: drop kubebuilder annotations from internal Model

---

.github/workflows/sync-labels.yaml
hack/release/sync-repo-labels.sh

Also allows label sync to be run manually for testing.

hack/release: exclude yages repo from label sync

---

apis/projectcontour/v1/httpproxy.go
changelogs/unreleased/4710-sunjayBhatia-minor.md
examples/contour/01-crds.yaml
examples/render/contour-deployment.yaml
examples/render/contour-gateway-provisioner.yaml
examples/render/contour-gateway.yaml
examples/render/contour.yaml
internal/dag/dag.go
internal/dag/httpproxy_processor.go
internal/dag/httpproxy_processor_test.go
internal/dag/status_test.go
internal/envoy/v3/route.go
internal/envoy/v3/route_test.go
internal/featuretests/v3/corspolicy_test.go
site/content/docs/main/config/api-reference.html
site/content/docs/main/config/cors.md

This will allow more flexible CORS Allowed Origins with a regex pattern, rather than having to allow all (w/ "*") or enumerating all exact matches.
We attempt to parse each allow origin match as an Origin header (using go url parsing) to check if we get a scheme://host[:port]. If the string doesnt parse as a URL or the format is invalid for an Origin header exact match, then we attempt to parse it as a regex.
Fixes: https://github.com/projectcontour/contour/issues/4666

CORSPolicy AllowOrigin can be configured as a regex

---

test/e2e/fixtures.go

A shot in the dark as to why CI randomly fails w/ gRPC error code unimplemented

Set grpc fixture imagepullpolicy to ifnotpresent

---

test/e2e/httpproxy/grpc_test.go

To hopefully address
https://github.com/projectcontour/contour/issues/4707

test/e2e/httpproxy: Retry gRPC calls on Unimplemented status

---

site/content/docs/main/deploy-options.md
site/content/docs/v1.22.1/deploy-options.md

Currently when accessing Getting Started link from Deploy Options in documentation (https://projectcontour.io/docs/v1.22.1/deploy-options/) redirects to incorrect address.
This change will fix that.

Fix incorrect getting started link

---

changelogs/unreleased/4744-skriss-small.md
internal/contour/handler.go

Ignores status-only updates on Gateway API
resources when determining whether to
re-process the DAG. This avoids unnecessary
processing and xDS traffic.

internal/contour: ignore status-only Gateway API updates

---

changelogs/unreleased/4745-skriss-small.md
internal/k8s/helpers.go

Adds all Gateway API resources with status to
the isStatusEqual func, which helps avoid
extraneous status update calls to the apiserver
when status has not changed.

internal/k8s: check Gateway API resource status equality

---

test/e2e/framework.go
test/e2e/gateway/gateway_allow_type_test.go
test/e2e/gateway/gateway_test.go
test/e2e/gateway/header_condition_match_test.go
test/e2e/gateway/host_rewrite_test.go
test/e2e/gateway/invalid_backend_ref_test.go
test/e2e/gateway/path_condition_match_test.go
test/e2e/gateway/query_param_match_test.go
test/e2e/gateway/request_header_modifier_test.go
test/e2e/gateway/request_mirror_test.go
test/e2e/gateway/request_redirect_test.go
test/e2e/gateway/tls_gateway_test.go
test/e2e/gateway/tls_wildcard_host_test.go
test/e2e/gateway/tlsroute_test.go

Passes the Gateway namespace/name to
use to the test body functions, to address
the TODOs around the test bodies implicitly
knowing the Gateway to attach to.

test/e2e: pass Gateway to use to test funcs

---

test/scripts/make-kind-cluster.sh

Addresses warnings for PodSecurityPolicy
deprecation/upcoming removal in k8s 1.25.

test/scripts: upgrade metallb to v0.13.5

---

internal/sorter/sorter.go
internal/sorter/sorter_test.go

To ensure stable ordering of the xDS config sent to Envoy
Added test will fail sometimes w/o this change
Updates: #4715

internal/sorter: Routes w/ query param matches are sorted based on query param name

---

.github/workflows/build_daily.yaml
Makefile
test/e2e/gateway/gateway_test.go

Adds a daily build run that runs them in "controller" mode, and ability to focus the package to run

test/e2e: Gateway tests run in "gateway" reconcile mode by default

---

.github/workflows/build_daily.yaml
.github/workflows/prbuild.yaml
Makefile
changelogs/unreleased/4773-sunjayBhatia-small.md

See release notes: https://go.dev/doc/devel/release#go1.19.minor

Bump golang to 1.19.2

---

Dockerfile
test/e2e/fixtures.go
test/scripts/make-kind-cluster.sh

- remove default build platform of `linux/amd64` (current versions of Docker should automatically populate this based on the host)
- remove pre-loading of E2E test fixture images into kind (probably not necessary anymore given we're no longer using httpbin, which was huge; the current images are small #'s of MB -- hitting what looks like https://github.com/kubernetes-sigs/kind/issues/2549 which is actually a containerd issue, but things work fine if the images are just pulled normally)

fixes to enable development on arm64

---

test/scripts/run-gateway-conformance.sh

Uses new -supported-features flag from main of gateway-api
feature flag for ReferenceGrants is now an exemption rather than an opt-in
Fixes: #4779

Enable HTTPRouteQueryParamMatching and HTTPRouteMethodMatching in main conformance tests

---

apis/projectcontour/v1/httpproxy.go
examples/contour/01-crds.yaml
examples/render/contour-deployment.yaml
examples/render/contour-gateway-provisioner.yaml
examples/render/contour-gateway.yaml
examples/render/contour.yaml
internal/dag/dag.go
internal/dag/httpproxy_processor.go
internal/envoy/v3/listener.go
internal/featuretests/v3/jwtverification_test.go
site/content/docs/main/config/api-reference.html
site/content/docs/main/config/jwt-verification.md

Adds a ForwardJWT option to JWTProvider,
to enable forwarding JWTs to the backend
after successful verification.

add ForwardJWT option

---

internal/workgroup/group.go
internal/workgroup/group_test.go

In case functions are added to workgroup using AddContext method, the AddContext method doesn't exit if the corresponding function exits. This change makes sure the Run flow exits in case the function running has exited.

Fix workgroup AddContext bug

---

Dockerfile

This significantly speeds up repeat builds
on the same host, and is more effective at
caching go modules than the Docker layer
caching technique that was being used
previously since a single module change
does not invalidate the entire cache.
Note, this won't make CI builds any faster
since they run on a fresh host every time,
but makes repeat local dev builds way faster.
ref. https://docs.docker.com/engine/reference/builder/#run---mount

use Docker cache mounts for go build & mod cache

---

apis/projectcontour/v1/httpproxy.go
changelogs/unreleased/4796-gautierdelorme-minor.md
examples/contour/01-crds.yaml
examples/render/contour-deployment.yaml
examples/render/contour-gateway-provisioner.yaml
examples/render/contour-gateway.yaml
examples/render/contour.yaml
internal/dag/builder_test.go
internal/dag/dag.go
internal/dag/httpproxy_processor.go
internal/envoy/v3/auth.go
internal/envoy/v3/listener_test.go
internal/featuretests/v3/downstreamvalidation_test.go
site/content/docs/main/config/api-reference.html
site/content/docs/main/config/tls-termination.md
test/e2e/httpproxy/client_cert_auth_test.go

This is required to support optional mTLS so that apps can use different authentication schemes (e.g. mTLS, cookies, tokens, etc...).
I initially named the new option `OnlyVerifyClientCertIfGiven` but this was confusing when `SkipClientCertValidation` is also enabled. I decided to go with `OnlyRequestClientCert` (and not `RequireClientCert` for example) since all the other option are opt-in by setting them to true so I would like to avoid changing this assumption with this new option. The other problem was at the Go API level `DownstreamValidation.RequireClientCert` default value would be `false` since that's the null value for booleans which would change the current behavior and I wanted to avoid implementing it as a pointer.
Signed-off-by: Gautier Delorme <gautier.delorme@gmail.com>

Add support for optional certificate validation

---

changelogs/unreleased/4788-skriss-minor.md
internal/dag/builder_test.go
internal/dag/cache.go
internal/dag/cache_test.go
internal/dag/dag.go
internal/dag/extension_processor.go
internal/dag/gatewayapi_processor.go
internal/dag/httpproxy_processor.go
internal/dag/ingress_processor.go
internal/dag/secret.go
internal/dag/secret_test.go
internal/dag/status_test.go
internal/featuretests/v3/backendcavalidation_test.go
internal/featuretests/v3/backendclientauth_test.go
internal/featuretests/v3/downstreamvalidation_test.go
internal/featuretests/v3/extensionservice_test.go
internal/featuretests/v3/jwtverification_test.go

Changes Secret validation to happen when Secrets
are used by processors, rather than as they are added
to the DAG cache. Also caches the validation results
on the DAG objects for efficiency.
This eliminates the need for Contour to inspect Secrets
that are not used by an Ingress/HTTPProxy/Gateway. It
also replaces the confusing "Secret not found" errors
with specific validation errors when a Secret does exist,
but is not valid.
This also allows Secret validation logic to be more
precise, since we know what the processors are trying
to use them for.
Fixes #2616.
Fixes #2908.

internal/dag: validate Secrets only when used

---

changelogs/unreleased/4792-skriss-small.md
internal/dag/cache.go
internal/dag/cache_test.go
internal/featuretests/v3/backendclientauth_test.go
internal/featuretests/v3/fallbackcert_test.go
internal/featuretests/v3/secrets_test.go

On Secret updates and deletes, only
trigger DAG rebuilds if the Secret
is referenced by an Ingress, HTTPProxy,
Gateway or global config.
Closes #4386.

Secret updates/deletes only trigger DAG rebuilds if referenced

---

.github/workflows/prbuild.yaml
cmd/contour/shutdownmanager.go
hack/golangci-lint

Updates #4814.
I'll create a separate issue for possibly addressing the issue reported by gosec for the shutdown manager.

update golangci-lint version and action version

---

test/scripts/get-contour-upgrade-from-version.sh

- logic for when we're checked out on a tag remains the same
- Contour v1.2.0 was improperly tagged on main, so next case is when we're checked out on a release branch with a previous tag, we ignore v1.2.0 and use the existing tag
- no branches other than release branches should have tags
- remaining cases are for release branches w/ tags, main, etc. so find the latest tag
Fixes #4809

Fix upgrade from version tag finding

---

apis/projectcontour/v1alpha1/contourdeployment.go
internal/provisioner/controller/gatewayclass.go

Moves Envoy log level validation from
the API package to the GatewayClass
controller to be consistent with other
validations.

provisioner: move LogLevel validation to controller

---

.github/workflows/build_daily.yaml

Going forward, the latest Gateway API conformance
tests will be run in PRs against Contour feature
branches that track the latest Gateway API changes.
Closes #4837.

remove daily Gateway API conformance run

---

.github/workflows/prbuild.yaml
go.mod
go.sum
test/conformance/gatewayapi/gateway_conformance_test.go
test/scripts/run-gateway-conformance.sh

[dev-gwapi-0.6] updates for SupportedFeatures changes

---

test/e2e/httpproxy/grpc_test.go

Test has been stable for a while with retries, removing to ensure it is fully fixed
Updates: #4707

test/e2e/httpproxy: Remove gRPC test flake attempts

---

changelogs/unreleased/4846-Vishal-Chdhry-minor.md
changelogs/unreleased/4846-Vishal-Chdhry-small.md
internal/contour/handler.go
internal/k8s/helpers.go

Added case for ignoring transition time and status changes of extension service
Fixes: #4838 
Signed-off-by: Vishal Choudhary <contactvishaltech@gmail.com>

Fix: ExtensionServices are updated continuously by contour

---

.github/workflows/prbuild.yaml
examples/gateway/00-crds.yaml
examples/render/contour-gateway-provisioner.yaml
examples/render/contour-gateway.yaml
go.mod
go.sum
internal/dag/gatewayapi_processor.go
internal/dag/status_test.go
internal/gatewayapi/listeners.go
internal/gatewayapi/listeners_test.go
internal/k8s/statusaddress_test.go
internal/status/gatewayclassconditions_test.go
internal/status/gatewaystatus.go
internal/status/gatewaystatus_test.go
test/conformance/gatewayapi/gateway_conformance_test.go
test/e2e/gateway/gateway_test.go
test/e2e/gateway/multiple_gateways_and_classes_test.go
test/e2e/provisioner/provisioner_test.go

Replaces the "Ready" condition used for Gateways
and Listeners with "Programmed".
Updates #4848.

[dev-gwapi-0.6] replace Gateway/Listener Ready conditions with Programmed

---

.github/workflows/build_daily.yaml
.github/workflows/prbuild.yaml
Makefile
changelogs/unreleased/4856-sunjayBhatia-small.md

See release notes: https://go.dev/doc/devel/release#go1.19.minor

Bump Go to 1.19.3

---

.github/workflows/prbuild.yaml

To reduce the number of workflow runs that clutter our actions and dependabot PR workflow result reporting

Ignore prbuild workflow for dependabot branches on push

---

.github/workflows/trivy-scan.yaml
site/content/resources/release-process.md

Runs on push to main and release branches, weekly, and can be triggered manually
Uploads a code scan result similar to CodeQL

Add trivy scan workflow

---

.github/workflows/trivy-scan.yaml

github should already be checking repo for secrets etc. and trivy is finding test fixtures as issues.
An alternative to this would be to skip directories containing secrets/fixtures using the skip-dirs option.

trivy: Only perform vulnerability scanning

---

.github/workflows/trivy-scan.yaml

Removes run on push and alternative that adds workflow to all release branches
We may not need to run the scan on every commit really so this is a more passive alternative

trivy: Use matrix/ref checkout in scheduled runs

---

.github/workflows/prbuild.yaml
examples/gateway/00-crds.yaml
examples/render/contour-gateway-provisioner.yaml
examples/render/contour-gateway.yaml
go.mod
go.sum

[dev-gwapi-0.6] update to Gateway API v0.6.0-rc1

---

site/content/resources/support.md

I know it's an example and dates were estimates but now that all these versions are released, updated the table based on actual release dates.
* [v1.19.0](https://github.com/projectcontour/contour/releases/tag/v1.19.0) - released in 4Q 2021
* [v1.20.0](https://github.com/projectcontour/contour/releases/tag/v1.20.0) - released in 1Q 2022
* [v1.21.0](https://github.com/projectcontour/contour/releases/tag/v1.21.0) - released in 2Q 2022
* [v1.22.0](https://github.com/projectcontour/contour/releases/tag/v1.22.0) - released in 3Q 2022
* [v1.23.0](https://github.com/projectcontour/contour/releases/tag/v1.23.0) - released in 4Q 2022
Let me know if you want me to rephrase other parts of the paragraph.
Signed-off-by: Winnie Kwon <wkwon@vmware.com>

Update supported releases table

---

internal/provisioner/controller/gateway.go

it seems the fields of the objects nest too deeply, so use a local variable to replace it to make reading code easy

internal/provisioner: Use local variable to replace the long access chain of fields

---

Makefile
changelogs/unreleased/4897-sunjayBhatia-minor.md
cmd/contour/gatewayprovisioner.go
examples/contour/03-envoy.yaml
examples/render/contour-gateway.yaml
examples/render/contour.yaml
test/e2e/deployment.go
test/e2e/upgrade/upgrade_test.go

https://www.envoyproxy.io/docs/envoy/v1.23.3/version_history/v1.23/v1.23.3

release-1.22: Bump Envoy to 1.23.3

---

Makefile
changelogs/unreleased/4900-sunjayBhatia-minor.md
cmd/contour/gatewayprovisioner.go
examples/contour/03-envoy.yaml
examples/deployment/03-envoy-deployment.yaml
examples/render/contour-deployment.yaml
examples/render/contour-gateway.yaml
examples/render/contour.yaml
site/content/resources/compatibility-matrix.md
versions.yaml

https://www.envoyproxy.io/docs/envoy/v1.24.1/version_history/v1.24/v1.24.1

Bump Envoy to 1.24.1

---

changelogs/unreleased/4908-sunjayBhatia-small.md
internal/dag/builder_test.go
internal/dag/gatewayapi_processor.go
internal/dag/policy.go
internal/dag/status_test.go
internal/envoy/v3/route.go
test/conformance/gatewayapi/gateway_conformance_test.go
test/e2e/fixtures.go
test/e2e/gateway/gateway_test.go
test/e2e/gateway/response_header_modifier_test.go
test/scripts/run-gateway-conformance.sh

One note: Host header is allowed in response modifier filter since it is not significant in a response
Enables Gateway API conformance test for response header modifier, bumps echoserver image in e2e tests, and adds tests for filter per-backend since this is missing from upstream tests (should add this soon).
Fixes #4819

Implement support for ResponseHeaderModifier

---

apis/projectcontour/v1alpha1/accesslog.go
apis/projectcontour/v1alpha1/accesslog_test.go
changelogs/unreleased/4880-rajatvig-small.md
cmd/contour/servecontext_test.go
examples/contour/01-contour-config.yaml
examples/render/contour-deployment.yaml
examples/render/contour-gateway.yaml
examples/render/contour.yaml
pkg/config/parameters_test.go

Fixes https://github.com/projectcontour/contour/issues/4484
Signed-off-by: Rajat Vig <rvig@etsy.com>

Add grpc_status_number as a default access log field

---

changelogs/unreleased/4912-fangfpeng-small.md
internal/dag/cache.go
internal/dag/cache_test.go

For HTTProute/TLSRoute, only if it references the relevant Gateway, it will trigger DAG rebuild.
Closes #4800.
Signed-off-by: fpeng <fpeng@vmware.com>

Do not trigger DAG rebuild for irrelevant HTTProutes/TLSroutes

---

internal/provisioner/controller/gatewayclass.go
internal/provisioner/controller/gatewayclass_test.go

Related to https://github.com/kubernetes-sigs/gateway-api/pull/1586

provisioner: Ensure GatewayClass condition generations are updated

---

.github/workflows/prbuild.yaml
changelogs/unreleased/4937-skriss-small.md
site/content/resources/compatibility-matrix.md
test/scripts/make-kind-cluster.sh
versions.yaml

Supported/tested Kubernetes versions
are now 1.24 - 1.26.
Closes #4936.

update to Kubernetes 1.26

---

apis/projectcontour/v1/httpproxy.go
apis/projectcontour/v1alpha1/contourconfig.go
apis/projectcontour/v1alpha1/contourconfig_helpers.go
apis/projectcontour/v1alpha1/contourconfig_helpers_test.go
changelogs/unreleased/4909-Vishal-Chdhry-minor.md
cmd/contour/bootstrap.go
cmd/contour/servecontext.go
examples/contour/01-crds.yaml
examples/render/contour-deployment.yaml
examples/render/contour-gateway-provisioner.yaml
examples/render/contour-gateway.yaml
examples/render/contour.yaml
internal/dag/dag.go
internal/dag/httpproxy_processor.go
internal/dag/status_test.go
internal/envoy/bootstrap.go
internal/envoy/v3/cluster.go
internal/envoy/v3/cluster_test.go
pkg/config/parameters.go
pkg/config/parameters_test.go
site/content/docs/main/config/api-reference.html
site/content/docs/main/configuration.md

Added an `ALL` option which when selected, the DNS resolver returns both IPv4 and IPv6 addresses (if they exist),
Closes #4778 
Signed-off-by: Vishal Choudhary <contactvishaltech@gmail.com>

Added support for `ALL` DNS lookup family

---

internal/dag/gatewayapi_processor.go

remove redundant type params to make lint happy

dag/gatewayapi: Remove redundant type params

---

changelogs/unreleased/4962-skriss-small.md
internal/dag/builder_test.go
internal/dag/dag.go
internal/dag/gatewayapi_processor.go
internal/dag/httpproxy_processor.go
internal/dag/status_test.go
internal/envoy/v3/route.go
internal/envoy/v3/route_test.go
test/conformance/gatewayapi/gateway_conformance_test.go
test/scripts/run-gateway-conformance.sh

Closes #4300.
~~Implements prefix and full path rewriting; doesn't do host rewriting (will do that in a separate PR).~~
~~This currently passes the conformance test (with a fix for https://github.com/kubernetes-sigs/gateway-api/pull/1622/files#r1062855963 in place), but it is not working properly for the case where you want to remove the prefix entirely (e.g. `/prefix/foo` -> `/foo`). The issue is described in https://github.com/envoyproxy/envoy/issues/23130; looks like we might need to generate multiple Envoy routes to properly handle that case. Putting this up as a draft for now while I think about how to best handle that case.~~

Gateway API: support URLRewrite filter

---

changelogs/unreleased/4967-skriss-minor.md
examples/contour/03-envoy.yaml
examples/deployment/03-envoy-deployment.yaml
examples/render/contour-deployment.yaml
examples/render/contour-gateway.yaml
examples/render/contour.yaml
internal/provisioner/equality/equality_test.go
internal/provisioner/objects/dataplane/dataplane.go
site/content/docs/main/redeploy-envoy.md

The probe can currently cause problems when it fails by causing the shutdown-manager container to be restarted by itself, which then results in the envoy container getting stuck in a "DRAINING" state indefinitely.
Not having the probe is less bad overall because envoy pods are less likely to get stuck in "DRAINING", and the worst case without it is that shutdown-manager is truly unresponsive during a pod termination, in which case the envoy container will simply terminate without first draining active connections.
Updates #4851.

remove shutdown-manager liveness probe

---

changelogs/unreleased/4966-izturn-docs.md
cmd/contour/servecontext_test.go
design/configuration-crd.md
examples/contour/01-contour-config.yaml
examples/gateway/03-gatewayclass.yaml
examples/render/contour-deployment.yaml
examples/render/contour-gateway.yaml
examples/render/contour.yaml
hack/generate-gateway-deployment.sh
site/content/docs/main/configuration.md
site/content/guides/gateway-api.md
test/e2e/gateway/multiple_gateways_and_classes_test.go

Update the staled controller name to `projectcontour.io/gateway-controller` to fix `examples/gateway` and more

update the staled controller name to projectcontour.io/gateway-controller

---

test/e2e/gateway/path_condition_match_test.go
test/e2e/gateway/request_redirect_test.go

Changes:
- Remove test cases for path matching
- Covered by conformance tests for exact path matching and prefix path matching
- Still need to contribute a couple prefix match cases back upstream before we can delete this test completely
- Remove basic path redirect test
- Covered in Gateway API v0.6.0
- More advanced features are not covered in the latest release but are on main, so we cannot remove those cases yet.
Updates #4579

test/e2e/gateway: Remove redundant tests

---

site/content/guides/deploy-aws-tls-nlb.md

Envoy now listens on port 8080 within the pod
for HTTP requests.

fix target port in AWS NLB TLS guide

---

Makefile
changelogs/unreleased/4988-skriss-minor.md
cmd/contour/gatewayprovisioner.go
examples/contour/03-envoy.yaml
examples/deployment/03-envoy-deployment.yaml
examples/render/contour-deployment.yaml
examples/render/contour-gateway.yaml
examples/render/contour.yaml
site/content/resources/compatibility-matrix.md
versions.yaml

update Envoy to v1.25.0

---

changelogs/unreleased/4993-sunjayBhatia-small.md
internal/xds/v3/callbacks.go
internal/xds/v3/callbacks_test.go
internal/xds/v3/contour.go
internal/xds/v3/contour_test.go

- contour xDS server does not log errors if connection was canceled by client, detected via gRPC code
- when connection is closed change to debug from info level to avoid log noise
- add stream open/close logging callbacks for go-control-plane implementation

internal/xds/v3: Improve logging on connection close

---

internal/metrics/metrics.go
internal/metrics/metrics_test.go

The dagRebuildGauge metric was being constructed
as a GaugeVec, but with an empty label slice. This 
drops the empty label slice and changes to a plain Gauge.
There is no impact for users.
Closes #2238.

internal/metrics: drop empty labels from dagRebuildGauge

---

Makefile
go.mod
go.sum
hack/actions/install-kubernetes-toolchain.sh
tools.go

Drops kubebuilder and kustomize toolchain
installations since they're not used. Also
switches to using go run for the ginkgo CLI
to avoid having a hardcoded version outside
of go.mod.

drop unneeded toolchain installations

---

cmd/contour/serve.go
examples/contour/02-role-contour.yaml
examples/gateway-provisioner/01-roles.yaml
examples/render/contour-deployment.yaml
examples/render/contour-gateway-provisioner.yaml
examples/render/contour-gateway.yaml
examples/render/contour.yaml
internal/contour/handler.go
internal/controller/controller_test.go
internal/controller/grpcroute.go
internal/k8s/rbac.go
internal/provisioner/objects/rbac/clusterrole/cluster_role.go

add registration controller and reconcile support for GRPCRotue; update handler and serve to call the registration.
Updates #4820
Signed-off-by: Yu Ying <yingy@vmware.com>

GRPCRoute: add grpcRoute controller registration

---

test/e2e/deployment.go

The upgrade e2e test can fail in some situations because the envoy waiter is incorrectly returning true before the StatefulSet even manages to finish the rollout since it only checks the StatefulSet state on properties that are inconsistently populated due to timing differences.
This fix addressed that by using a similar condition validation method as the one already used for the Contour Deployment rollout.

Fix the upgrade e2e test flakiness

---

cmd/contour/shutdownmanager_test.go
internal/envoy/v3/route.go

Signed-off-by: Fish-pro <zechun.chen@daocloud.io>
When I read the code, I noticed that some special library calls used custom strings as arguments. Therefore, it is recommended to use package constants instead of strings
I hope the above suggestions can help contribute to the community. Thank you

Use http constants instead of string

---

changelogs/unreleased/5063-sunjayBhatia-small.md
examples/gateway/00-crds.yaml
examples/gateway/01-admission_webhook.yaml
examples/gateway/02-certificate_config.yaml
examples/render/contour-gateway-provisioner.yaml
examples/render/contour-gateway.yaml
go.mod
go.sum
test/conformance/gatewayapi/gateway_conformance_test.go
test/scripts/run-gateway-conformance.sh

~~So we can see in CI what we are currently missing and close the gaps~~
Skips redirect tests that check for original request port in returned
Location header, failing likely due to:
https://github.com/envoyproxy/envoy/issues/17318

Gateway API: Bump to v0.6.1 and run all conformance tests

---

internal/dag/gatewayapi_processor.go
internal/dag/policy.go
internal/dag/status_test.go
internal/gatewayapi/helpers.go
internal/status/routeconditions.go

Implement gatewayapi_processor.go for building GRPCRoute dag.
todos:
- add GRPCRoute into allowed route kinds for listener with HTTP/HTTPS protocol This needs quite some changes on status_test.go for wanted SupportedKinds for listeners with http/http protocols.
- add unit tests
Updates #4820
Signed-off-by: Fang Peng <fpeng@vmware.com>

internal/dag: Add GRPCRoute support in gatewayapi processor

---

design/global-external-authorization-design.md

Design proposal to address #4954 
There is a WIP draft [PR](https://github.com/projectcontour/contour/pull/4994) with some of the intended code changes. 
Signed-off-by: Clayton Gonsalves <claytonivorgonsalves@gmail.com>

Design: ExtAuth HTTP support

---

internal/sorter/sorter.go
internal/sorter/sorter_test.go
internal/xdscache/v3/route.go
internal/xdscache/v3/route_test.go

Needs to take into account match type, value, case sensitivity
Also ensures query param match conditions on routes in sorted order
Fixes a small issue in the header condition sorter as well.

internal/sorter: Fix sorting for Query parameter matches

---

changelogs/unreleased/5068-skriss-small.md
internal/dag/builder_test.go
internal/dag/dag.go
internal/dag/gatewayapi_processor.go
internal/dag/httpproxy_processor.go
internal/envoy/v3/route.go
internal/envoy/v3/route_test.go

Adds support for the Path field on the HTTPRoute
RequestRedirect filter.
Closes #4964.
Co-authored-by: Vishal Choudhary <sendtovishalchoudhary@gmail.com>
I have manually run the Gateway API conformance tests against this PR, with the host check removed since we're having some issues with that, and can confirm all tests pass.

Gateway API: support RequestRedirect path rewrite

---

design/tracing-design.md

Add tracing design support to export tracing data to OpenTelemetry
ref #399 
ref #3802
close #3792 
@skriss @sunjayBhatia 
Signed-off-by: yy [yang.yang@daocloud.io]

design: add tracing design doc

---

internal/dag/status_test.go
internal/featuretests/v3/backendcavalidation_test.go
internal/featuretests/v3/ingressclass_test.go
internal/featuretests/v3/listeners_test.go
internal/featuretests/v3/replaceprefix_test.go
internal/featuretests/v3/retrypolicy_test.go
internal/featuretests/v3/route_test.go
internal/featuretests/v3/routeweight_test.go
internal/featuretests/v3/timeoutpolicy_test.go
internal/featuretests/v3/tlscertificatedelegation_test.go
internal/featuretests/v3/tlsprotocolversion_test.go
internal/featuretests/v3/tlsroute_test.go
internal/featuretests/v3/websockets_test.go
internal/fixture/meta.go

Test objects were previously created with uninitialized `ResourceVersion` and `Generation` since the values did not matter when complete object content was compared to detect updates.
This change is preparation for #5064 and introduces a helper function to generate unique `ObjectMeta`. Test cases that depend on object update are changed to use the helper instead of hardcoded initialization. Since the number of objects constructed by test suite is extremely high and change is manual, this PR does not attempt to change _all occurrences_.

test: use helper to generate ObjectMeta

---

internal/dag/builder_test.go
internal/dag/gatewayapi_processor.go
internal/dag/gatewayapi_processor_test.go
internal/dag/status_test.go
internal/gatewayapi/helpers.go
internal/status/routeconditions.go

Adding GRPCRoute test cases for TestGetListenersForRotueParentRef and TestDAGInsertGatewayAPI
Fix mirror service default protocol type

GRPCRoute: add unit test cases

---

internal/dag/builder_test.go
internal/dag/gatewayapi_processor.go
internal/dag/status_test.go

- need to add a leading slash in the path
- need to add a prefix match if method match is not specified.
Updates #4820

internal/dag: fix method match of GRPCRoute

---

hack/generate-crd-yaml.sh

Workaround for the following controller-gen issue: https://github.com/kubernetes-sigs/controller-tools/issues/734

hack: change CRD YAML temp dir template

---

changelogs/unreleased/5129-pnbrown-docs.md
site/config.yaml
site/themes/contour/layouts/_default/baseof.html
site/themes/contour/layouts/_default/search.html

Updating docsearch to fix the search functionality on the site

Upgrade docsearch to v3

---

changelogs/unreleased/5130-sunjayBhatia-small.md
internal/dag/policy.go
internal/dag/policy_test.go

Also allows header fallback configuration %REQ(If-Present?X-Fallback)%

internal/dag: Allow REQ operator to use HTTP/2 pseudo-headers in headers policy

---

changelogs/unreleased/5125-skriss-small.md
internal/dag/gatewayapi_processor.go
internal/dag/status_test.go
internal/status/routeconditions.go

Replaces custom condition types/reasons with
upstream ones, and cleans up filter processing
for consistency.
Closes #5103.

Gateway API: clean up conditions and filter processing

---

test/e2e/bench/bench_test.go
test/e2e/http.go

Use package constants instead of strings
I hope the above suggestions can help contribute to the community
Thank you

Use constants 'http.MethodGet' instead of string 'GET'

---

cmd/contour/serve.go
internal/dag/cache.go
internal/k8s/kind.go
internal/k8s/kind_test.go

ContourConfiguration is not being cached
in the DAG cache so the informer is not
needed.
Also adds ContourConfiguration and
ContourDeployment to the KindOf function
since they are known types.
I noticed this while testing #5109 because I had a ContourConfiguration in my cluster, and it was showing up in the metric output as an unknown object.

remove informer for ContourConfiguration

---

changelogs/unreleased/5080-nsimons-minor.md
cmd/contour/serve.go
cmd/contour/servecontext.go
site/content/docs/main/configuration.md
site/content/docs/main/deploy-options.md

Allow disabling certain informers for CRDs by passing a command line flag to the serve command. This makes the corresponding CRD effectively optional.
I'd like some feedback on the terminology. Would the audience of the documents necessarily know what an `informer` is? Also `feature` is quite generic, but I tried to explain the intended meaning in this context. I'm open to other suggestions.
I tried to look for a good place to write some tests, but I didn't find much related to the flags. I have tested manually with the CRDs present/missing in my cluster.
Fixes #4684
Signed-off-by: Niklas Simons <niklas.simons@est.tech>

cmd/contour: optional CRDs

---

internal/dag/status_test.go

internal/dag: remove unneeded route labels in status_test.go

---

changelogs/unreleased/5064-tsaarni-small.md
internal/contour/handler.go
internal/k8s/helpers.go
internal/k8s/helpers_test.go
internal/k8s/testdata/endpoint-content-change.yaml
internal/k8s/testdata/httpproxy-annotation-change.yaml
internal/k8s/testdata/ingress-annotation-change.yaml
internal/k8s/testdata/namespace-label-change.yaml
internal/k8s/testdata/secret-content-change.yaml
internal/k8s/testdata/secret-metadata-change.yaml
internal/k8s/testdata/service-annotation-change.yaml
internal/k8s/testdata/service-status-change.yaml

This change optimizes processing of `HTTPProxy`, `Secret` and other objects by avoiding full object comparison. This reduces CPU usage during object updates.
Comparing the full objects with `cmp.Equal()` during `EventHandler.onUpdate()` was very costly, which was especially visible in big clusters with a lot of objects. In general, the load caused by `cmp.Equal()` during update was overwhelming compared to the load that Contour otherwise generates in total.
For objects that implement `generation` it can be used, instead of comparing the full object. Generation is updated only when object spec is updated. Updates to `status` or `annotations` fields will not trigger new generation, which needs to be considered separately for objects where those changes matter.
Fixes #5024.
Signed-off-by: …

Avoid comparing full objects during update to optimize performance

---

test/scripts/run-gateway-conformance.sh

-run flag swallowed ./conformance as an argument

Fix Gateway API conformance invocation

---

.github/workflows/trivy-scan.yaml

ref. https://github.com/aquasecurity/trivy-action/releases/tag/0.9.2

trivy-scan: rename security-checks to scanners

---

Makefile
cmd/contour/gatewayprovisioner.go
examples/contour/03-envoy.yaml
examples/deployment/03-envoy-deployment.yaml
examples/render/contour-deployment.yaml
examples/render/contour-gateway.yaml
examples/render/contour.yaml
go.mod
go.sum
site/content/resources/compatibility-matrix.md
versions.yaml

Keeps main in sync with updates on latest
release branch. The Envoy bump will end
up being replaced by Envoy 1.26.0 eventually
so doesn't really need a changelog.

update Envoy and golang.org/x/image

---

test/e2e/http.go

Repeats the change from #5210 for requests to
the metrics and admin listeners.

test/e2e: clone DefaultTransport and disable keep-alives for metrics & admin

---

changelogs/unreleased/5211-rajatvig-small.md
cmd/contour/contour.go
go.mod
go.sum

Follow up to https://github.com/projectcontour/contour/pull/5023 to address https://github.com/projectcontour/contour/issues/5022

Automatically set GOMAXPROCS to match the number of CPUs available to the container

---

internal/envoy/v3/route.go
internal/envoy/v3/route_test.go

Found when testing out
https://github.com/kubernetes-sigs/gateway-api/pull/1855
We could also do this higher up in dag processing but this seems like the common/failsafe option.

internal/envoy/v3: Trim trailing slashes from path separated prefix match

---

design/ip-filtering-design.md

I took a stab at a proposal to address https://github.com/projectcontour/contour/issues/3693
I haven't looked deeply at the envoy filters available for this, but I wrote down what looked like would work based on the docs.

Add ip filter design doc

---

test/scripts/get-contour-upgrade-from-version.sh

Properly detect upgrade from version on
feature branches based off release branches.
Closes #5184.

test/scripts: fix upgrade from version

---

CONTRIBUTING.md
hack/codespell.sh
test/scripts/install-contour-working.sh
test/scripts/install-provisioner-working.sh
test/scripts/kind-expose-port.yaml

This is a proposal for minimal update on contributor docs. It could be useful for KubeCon EU 2023 ContribFest participants. Any further ideas are welcome!
Some notes:
- ~When user runs `make install-{contour,provisioner}-working` it exposes the cluster not only to localhost but to the network their laptop is on. https://github.com/projectcontour/contour/blob/3a85420d0b97155629fa18ca03db01db2c65438e/test/scripts/kind-expose-port.yaml#L9 Can we change this without impacting e2e tests?~ Now using 127.0.0.1 instead.
- I added support for running `codespell` as a container, using image from the codespell actions, allowing people to run `make lint` without python requirement
- I removed `sed -i` in-place edit of manifests, so that people do not accidentally end up committing them.
- We require …

docs: updated contributing instructions

---

Makefile
changelogs/unreleased/5250-sunjayBhatia-minor.md
cmd/contour/gatewayprovisioner.go
examples/contour/03-envoy.yaml
examples/deployment/03-envoy-deployment.yaml
examples/render/contour-deployment.yaml
examples/render/contour-gateway.yaml
examples/render/contour.yaml
site/content/resources/compatibility-matrix.md
versions.yaml

Adding as a "minor" tag to bump up the priority in release notes for the CVEs

main: Bump Envoy to 1.25.4

---

changelogs/unreleased/5233-Jean-Daniel-small.md
internal/provisioner/objects/dataplane/dataplane.go
internal/provisioner/objects/dataplane/dataplane_test.go

This fix an issue with envoy pods generated by contour provisioner.
Envoy pods are never declared `Ready` when using a custom health port.
Envoy exposes the wrong port in prometheus annotations when using a custom metrics port.

internal/provisioner: Do not use hard-coded values, but configuration defined ports.

---

internal/dag/httpproxy_processor.go
internal/dag/status_test.go

Sets Valid=false on an HTTP vhost with
External Auth configured. Note that it
is still valid to explicitly disable
ExtAuth for an HTTP vhost.
Closes #5237.

internal/dag: set condition for HTTP vhost with ExtAuth configured

---

CONTRIBUTING.md

Did a few more small edits to try to make the happy path as clear as possible:
- start with the basic `go build` and `go test` commands since they're fastest and require the least tooling
- combine some of the other `make` target docs into a single section on pre-submit checks using `make checkall`
- clarify that running the Contour binary locally against a kind cluster is an alternative approach to `make install-contour-working` (I think at this point the latter is efficient enough on repeat builds that it'll work for most folks)

minor reorganization for CONTRIBUTING.md

---

changelogs/unreleased/5239-fangfpeng-small.md
internal/dag/builder_test.go
internal/dag/gatewayapi_processor.go
internal/dag/status_test.go
internal/gatewayapi/helpers.go

- support regex path and regex header match for HTTPRoute.
- support regex header match for GRPCRoute.
Fixes #3357
Fixes #5219

Gateway API: support regex path and header match

---

cmd/contour/serve.go

This change fixes a nil pointer when the `authPolicy.context` is not configured for global external auth on the contour configuration.

fix: nil pointer on global extauth when `authPolicy.context` not configured.

---

changelogs/unreleased/5157-liangyuanpeng-small.md
internal/dag/builder_test.go
internal/dag/httpproxy_processor.go

Set 502 response if include references another root
Fixes #5016

internal/dag:  configure 502 if include references another (#5016)

---

test/scripts/install-contour-working.sh
test/scripts/install-provisioner-working.sh

Contour should be automatically restarted each time the install scripts deploy a new build (as discussed https://github.com/projectcontour/contour/pull/5238#discussion_r1165994971)

hack: change back to random image tag

---

changelogs/unreleased/5296-sunjayBhatia-small.md
internal/dag/httpproxy_processor.go
internal/dag/status_test.go

If we have an include on a certain path, then a different valid include condition on that same path, duplicates of the later include conditions were not detected.
This actually does not need to be backported to the 1.24 release as that introduced the improved duplicate detection behavior, but did add the seen path/header conditions to the map, see here: https://github.com/projectcontour/contour/blob/v1.24.3/internal/dag/httpproxy_processor.go#L1441

internal/dag: Fix for duplicate include detection

---

apis/projectcontour/v1/httpproxy.go
changelogs/unreleased/5000-arjunsalyan-minor.md
examples/contour/01-crds.yaml
examples/render/contour-deployment.yaml
examples/render/contour-gateway-provisioner.yaml
examples/render/contour-gateway.yaml
examples/render/contour.yaml
internal/dag/builder_test.go
internal/dag/conditions.go
internal/dag/conditions_test.go
internal/dag/dag.go
internal/dag/httpproxy_processor.go
internal/dag/status_test.go
internal/fixture/service_fixtures.go
site/content/docs/main/config/api-reference.html
site/content/docs/main/config/inclusion-delegation.md
site/content/docs/main/config/request-routing.md
test/e2e/httpproxy/exact_path_condition_match_test.go
test/e2e/httpproxy/httpproxy_test.go
test/e2e/httpproxy/include_exact_condition_test.go

This adds support for exact path matching in the HttpProxy along side prefix matching
fixes #4069
Signed-off-by: Arjun Salyan <iarjunsalyan@gmail.com>

internal/dag: Add exact path match condition in HttpProxy

---

test/e2e/incluster/incluster_test.go
test/e2e/incluster/memory_usage_test.go

Tests that Contour reconciles a root properly that has many children with header match include conditions and that the Contour pods are not restarted (which would happen due to OOM since we set a memory limit).
Cherry-picking this commit against the release-1.24 branch and it fails (the root HTTPProxy never is valid in the runs I have done, but watching the container restarts, there are a few due to OOM)

test/e2e/incluster: Add memory usage test for header includes

---

internal/dag/httpproxy_processor.go
internal/dag/status_test.go
test/e2e/incluster/incluster_test.go
test/e2e/incluster/memory_usage_test.go

While looping through seen include match conditions for a particular path, code was appending to the seen list 😅.
Also using a slice of slices causes a lot more allocations as you increase includes and header match conditions.
Was able to repro a huge memory spike with a single root HTTPProxy with 500 includes with 5 header match conditions each.
No release note but will add when cutting the patch release that contains this change

[release-1.24] internal/dag: Fix bug in duplicate include match detection that caused memory usage spike

---

changelogs/unreleased/5099-tsaarni-small.md
cmd/contour/serve.go

This PR tries to avoid storing data in controller-runtime / client-go cache when we know for sure we do not need it.
While working on https://github.com/projectcontour/contour/pull/5064#issuecomment-1424616124 it was discovered that considerable time was spent on processing `Secrets` of type `helm.sh/release.v1`. These secrets contain the helm manifest, and they are just noise for Contour. Besides CPU impact, there is also memory footprint impact, since these `Secrets` can get large. See related discussion [cert-manager/cert-manager#5220](https://www.github.com/cert-manager/cert-manager/issues/5220).
I was looking for ways to avoid caching objects that fail to fulfil given criteria. I found one: [`SelectorByObject`](https://github.com/kubernetes-sigs/controller-runtime/blob/master/designs/ …

Reduce the memory footprint by optimizing Kubernetes informer cache

---

changelogs/unreleased/5310-padlar-small.md
internal/dag/builder_test.go
internal/dag/gatewayapi_processor.go
internal/dag/status_test.go

support query param regex matching in Gateway API

---

test/e2e/httpproxy/ip_filtering_test.go

Adds a deny filter for ::/0
Fixes: https://github.com/projectcontour/contour/issues/5326

test/e2e/httpproxy: Fix ip filtering tests for ipv6 clusters

---

cmd/contour/gatewayprovisioner.go

This matches behavior for the `contour serve`
command and enables upgrades/restarts to happen
faster.
ref. https://github.com/projectcontour/contour/blob/main/cmd/contour/serve.go#L271

Gateway provisioner: release leader election on shutdown

---

internal/envoy/v3/listener.go

Previously would configure the Lua script to match on requestedServerName when fqdn had a prefix of "*.". Now Gateway API allows a complete wildcard listener hostname match of "*" so this needs to be amended. Gateway API 0.7.x conformance tests surfaced this.

internal/envoy/v3: Loosen FilterMisdirectedRequests helper

---

apis/projectcontour/v1alpha1/contourdeployment.go
changelogs/unreleased/5386-Jean-Daniel-small.md
examples/contour/01-crds.yaml
examples/render/contour-deployment.yaml
examples/render/contour-gateway-provisioner.yaml
examples/render/contour-gateway.yaml
examples/render/contour.yaml
internal/provisioner/controller/gateway.go
internal/provisioner/controller/gateway_test.go
internal/provisioner/controller/gatewayclass.go
internal/provisioner/controller/gatewayclass_test.go
internal/provisioner/equality/equality.go
internal/provisioner/equality/equality_test.go
internal/provisioner/model/model.go
internal/provisioner/objects/service/service.go
internal/provisioner/objects/service/service_test.go
site/content/docs/main/config/api-reference.html

Add ipFamilyPolicy field to Envoy NetworkPublishing definition.
Fixes #5308

[provisioner] Add `ipFamilyPolicy` field to NetworkPublishing.

---

test/e2e/poller.go
test/e2e/upgrade/upgrade_test.go

Uses log.Logger to add timestamps which should help in debugging upgrade tests.

test/e2e: Additional logging in app poller

---

go.mod
go.sum

https://github.com/envoyproxy/envoy/commit/672b41532a9f03bc84fbbfec0d1db5b633833f9c was the last commit in Envoy 1.26 to the api dir, bumped go-control-plane to the corresponding mirror commit.
In case there are newer apis we want to take advantage of in the future.

deps: Bump go-control-plane to commit for Envoy 1.26

---

site/content/docs/1.23/guides/deploy-aws-tls-nlb.md
site/content/docs/1.24/guides/deploy-aws-tls-nlb.md
site/content/docs/1.25/guides/deploy-aws-tls-nlb.md
site/content/docs/main/guides/deploy-aws-tls-nlb.md

This was fixed in the un-versioned guide
in #4976 but looks like it got dropped in
the move to versioned guides.

docs: fix target port for AWS NLB TLS termination

---

changelogs/unreleased/5427-sunjayBhatia-minor.md
cmd/contour/contour.go

This is an issue in certain local development and other environments where cgroup namespaces are distinct per container. The automaxprocs library errors with 'path <foo> is not a descendent of mount point root <foo>/kubelet and cannot be exposed from "/sys/fs/cgroup/misc/kubelet"'

cmd/contour: Failure setting GOMAXPROCS is non-fatal

---

changelogs/unreleased/5427-sunjayBhatia-minor.md
cmd/contour/contour.go

This is an issue in certain local development and other environments where cgroup namespaces are distinct per container. The automaxprocs library errors with 'path <foo> is not a descendent of mount point root <foo>/kubelet and cannot be exposed from "/sys/fs/cgroup/misc/kubelet"'

release-1.25 backport: cmd/contour: Failure setting GOMAXPROCS is non-fatal (#5427)

---

.github/workflows/prbuild.yaml
.golangci.yml
hack/golangci-lint

- bump patch version to v1.51.2
- use `go run` when running golangci-lint locally (pins version and faster than running in Docker)
- clean up config file to remove obsolete config and comments
Hold until #5424 is merged

golangci-lint: use go run locally, tidy config file

---

test/e2e/deployment.go

Suppresses warning from API server/controller-runtime
```
time="2023-06-05T16:22:27Z" level=info msg="child pods are preserved by default when jobs are deleted; set propagationPolicy=Background to remove them or set propagationPolicy=Orphan to suppress this warning" caller="logr.go:278" logger=KubeAPIWarningLogger
```

test/e2e: Delete dependent objects in background

---

.github/workflows/prbuild.yaml
changelogs/unreleased/5353-sunjayBhatia-minor.md
examples/gateway/00-crds.yaml
examples/gateway/01-admission_webhook.yaml
examples/gateway/02-certificate_config.yaml
examples/render/contour-gateway-provisioner.yaml
examples/render/contour-gateway.yaml
go.mod
go.sum
internal/dag/builder_test.go
internal/dag/gatewayapi_processor.go
internal/gatewayapi/helpers.go
test/conformance/gatewayapi/gateway_conformance_test.go
test/e2e/framework.go
test/scripts/run-gateway-conformance.sh

To ensure compatibility with upcoming release
Fixes: #5336
Fixes: #5414

Bump Gateway API to v0.7.1

---

Makefile
changelogs/unreleased/5449-sunjayBhatia-small.md
cmd/contour/gatewayprovisioner.go
examples/contour/03-envoy.yaml
examples/deployment/03-envoy-deployment.yaml
examples/render/contour-deployment.yaml
examples/render/contour-gateway.yaml
examples/render/contour.yaml
site/content/resources/compatibility-matrix.md
versions.yaml

Routine patch bump for Envoy dependency CVEs
See:
https://www.envoyproxy.io/docs/envoy/v1.26.2/version_history/v1.26/v1.26.2

Bump Envoy to v1.26.2

---

Makefile
cmd/contour/gatewayprovisioner.go
examples/contour/03-envoy.yaml
examples/deployment/03-envoy-deployment.yaml
examples/render/contour-deployment.yaml
examples/render/contour-gateway.yaml
examples/render/contour.yaml

Routine patch bump for Envoy dependency CVEs
See:
https://www.envoyproxy.io/docs/envoy/v1.25.7/version_history/v1.25/v1.25.7

release-1.24: Bump Envoy to v1.25.7

---

Makefile
cmd/contour/gatewayprovisioner.go
examples/contour/03-envoy.yaml
examples/deployment/03-envoy-deployment.yaml
examples/render/contour-deployment.yaml
examples/render/contour-gateway.yaml
examples/render/contour.yaml

Routine patch bumps for Envoy dependency CVEs
See:
- https://www.envoyproxy.io/docs/envoy/v1.24.6/version_history/v1.24/v1.24.6
- https://www.envoyproxy.io/docs/envoy/v1.24.7/version_history/v1.24/v1.24.7
- https://www.envoyproxy.io/docs/envoy/v1.24.8/version_history/v1.24/v1.24.8

release-1.23: Bump Envoy to v1.24.8

---

test/scripts/install-provisioner-release.sh

Motivation for this change is flaky upgrade tests
When running upgrade tests, we install and setup kind which installs the current version of gateway api admission server and then in the tests, install the latest release of contour + the supported gateway api components, which might mean a redeploy of the admission webhook. Since we don't wait for the webhook to roll out, creating gateway resources causes the tests to fail if the webhook isnt up yet or some pods are terminating (also why waiting for the deployment to be available is a little problematic).

Wait for gateway-api admission server to roll out in install script

---

changelogs/unreleased/5434-sunjayBhatia-minor.md
internal/sorter/sorter.go
internal/sorter/sorter_test.go

This is to support Gateway API conformance, release 0.7.1 dictates that HTTP method comes before length of header matches in the precendence order for choosing routes.
Since we currently implement method matching in the DAG by adding a :method header match, this solution finds any :method headers being matched on and first determines precedence of two routes being compared based on that. If method matches are equal (both present or not present), then we go ahead with comparing the remaining header matches.
Since HTTPProxy provides this ability as well, this will affect priority of routes from HTTPProxies, not just Gateway API HTTPRoute.
Alternately we could add a method field directly to the dag.Route struct and implement method matching that way. We may want to in that case also sanitize …

internal/sorter: Routes with method matching get precedence

---

changelogs/unreleased/5425-izturn-small.md
internal/provisioner/objects/dataplane/dataplane.go
internal/provisioner/objects/dataplane/dataplane_test.go

set the default resource requirements for containers: shutdown-manager & envoy-initconfig
fix #5349

internal/provisioner: set the default resource requirements for containers: shutdown-manager & envoy-initconfig

---

test/e2e/deployment.go
test/e2e/gateway/query_param_match_test.go
test/e2e/gateway/tls_gateway_test.go
test/e2e/http.go

- use --debug flag on local contour invocation to get more logs
- more non-nil assertions to prevent panics
- print error from making requests in requestUntil helper
Related to debugging failures like: https://github.com/projectcontour/contour/actions/runs/5255150370/jobs/9494687568

test/e2e: Debugging fixes

---

internal/dag/accessors.go
internal/dag/accessors_test.go

This method is used by the EndpointsTranslator on dag change to recalculate the relevant endpoints to send to Envoy. Since we do not use EDS to configure endpoints for Clusters that come from ExternalName Services, we no longer collect ServiceClusters associated with these Clusters. This is required for ADS, as go-control-plane will not respond to requests if the snapshot contains resources that were not requested.

internal/dag: GetServiceClusters no longer returns ExternalName clusters

---

test/scripts/run-gateway-conformance.sh

Likely related to
https://github.com/kubernetes-sigs/gateway-api/issues/2102

Extend gateway api conformance test timeout

---

.github/workflows/prbuild.yaml
hack/actions/install-kubernetes-toolchain.sh
test/scripts/make-kind-cluster.sh

Bumps to kind 0.20.0 (and associated node images) and kubectl 1.27.3

test tooling: Bump kind and kubectl

---

internal/dag/builder_test.go
internal/dag/listener_processor.go
internal/featuretests/v3/listeners_test.go

Use existing config flags/fields for HTTP/S listen addresses to configure Envoy Listeners when in Gateway mode.
Fixes: #5480

internal/dag: Listener processor uses HTTP/S addresses for Gateway Listeners

---

test/e2e/ingress/ingress_class_test.go

Test client complains about the annotation being deprecated

test/e2e/ingress: Use ingress class name spec field

---

internal/k8s/statusaddress_test.go
internal/xds/v3/contour_test.go
internal/xdscache/v3/server_test.go

Move to using fixture.NewTestlogger|NewDiscardLogger
To fix flakes such as: https://github.com/projectcontour/contour/actions/runs/5291876520/jobs/9578040749

More test logger fixes

---

changelogs/unreleased/5484-tsaarni-small.md
hack/release/make-release-tag.sh

Avoids Kubernetes warning when deploying contour.
Fixes #5483

Remove dots in certgen job name

---

Makefile

name: Pull request
about: fix wrong typo in Makefile :run-gateway-conformance and lint-flags
labels: ["release-note/not-required"]

fix wrong typo in Makefile :run-gateway-conformance and lint-flags

---

.github/workflows/build_daily.yaml
.github/workflows/prbuild.yaml
Makefile
changelogs/unreleased/5502-sunjayBhatia-small.md

For CVEs, see release notes: https://go.dev/doc/devel/release#go1.20

Bump go to 1.20.5

---

site/content/getting-started/_index.md

labels: ["release-note/not-required"]
---
Read the code 
```
internal/provisioner/objects/dataplane/dataplane.go
func desiredContainers(contour *model.Contour, contourImage, envoyImage string) ([]corev1.Container, []corev1.Container) {
containers := []corev1.Container{
{
Name:            ShutdownContainerName,
Image:           contourImage,
ImagePullPolicy: corev1.PullIfNotPresent,
Command: []string{
"/bin/contour",
},
Args: []string{
"envoy",
"shutdown-manager",
},
},
{
Name:            EnvoyContainerName,
Image:           envoyImage,
ImagePullPolicy: corev1.PullIfNotPresent,
Command: []string{
"envoy",
},
Args: []string{
"-c",
```
The Gateway install is the same with the Yaml install.
``` 
kubectl apply -f https://projectcontour.io/quickstart/contour.yaml
```
So the Envoy pod maybe the …

docs for install envoy containers.

---

changelogs/unreleased/5485-yanggangtony-small.md
internal/dag/cache.go
internal/dag/cache_test.go

/kind bug
Fixes #5476 
labels: ["release-note/small"]
The [serviceTriggersRebuild](https://github.com/projectcontour/contour/blob/main/internal/dag/cache.go#L387) method determines whether a Service change should trigger a DAG rebuild, based on whether the Service is referenced by any routing config. It looks like we forgot to add code to check GRPCRoutes for Service references here. That should be added and look similar to the existing checks for HTTPRoutes and TLSRoutes.
```release-note
Add  check GRPCRoutes for Service references .
```

services referenced by a GRPCRoute dont trigger a DAG rebuild

---

site/content/docs/1.23/guides/gateway-api.md
site/content/docs/1.23/guides/global-rate-limiting.md
site/content/docs/1.24/guides/gateway-api.md
site/content/docs/1.24/guides/global-rate-limiting.md
site/content/docs/1.25/guides/gateway-api.md
site/content/docs/1.25/guides/global-rate-limiting.md
site/content/docs/main/guides/gateway-api.md
site/content/docs/main/guides/global-rate-limiting.md
site/content/guides/gateway-api.md
site/content/guides/global-rate-limiting.md

name: Pull request
about: The configmap is k8s's terminology , and can not be separated.
docs change 'config map to configmap , its will be more k8s terminology word.'
labels: ["release-note/not-required"]

Fix configmap word in docs.

---

internal/k8s/log_test.go

internal/k8s: Make log test flush timeout more lenient

---

.github/workflows/prbuild.yaml
test/scripts/make-kind-cluster.sh

Test setup installs Gateway API CRDs and webhook in the initial Contour version it installs in the cluster so allow skipping cluster setup install.

Skip Gateway API install in upgrade tests

---

.github/PULL_REQUEST_TEMPLATE/pull_request_template.md

name: Pull request
about: update pr template notes.
labels: ["release-note/none-required"]
when i raise a pr , the ci is error to me , and the pr template is not accurate match the pr label.
Like the pic shows.

update pr template notes.

---

site/data/docs/main-toc.yml

labels: ["release-note/none-required"]

docs:Delete the link of operator.md

---

apis/projectcontour/v1/httpproxy.go
changelogs/unreleased/5516-hshamji-small.md
examples/contour/01-crds.yaml
examples/render/contour-deployment.yaml
examples/render/contour-gateway-provisioner.yaml
examples/render/contour-gateway.yaml
examples/render/contour.yaml
internal/dag/builder_test.go
internal/dag/dag.go
internal/dag/gatewayapi_processor.go
internal/dag/httpproxy_processor.go
internal/envoy/v3/route.go
internal/envoy/v3/route_test.go
internal/featuretests/v3/envoy.go
internal/featuretests/v3/mirrorpolicy_test.go
internal/xdscache/v3/route_test.go
site/content/docs/1.20/config/request-routing.md
site/content/docs/main/config/api-reference.html
site/content/docs/main/config/request-routing.md

Fixes #1889
Fixes #5495
internal/dag: & internal/envoy/v3:
- Updated internal MirrorPolicy struct to with a `weight` field;
- The `weight` attribute on an HTTPProxy mirrored service is overloaded to also mean an integer percent of traffic to be sent to the mirrored service;
- The GatewayAPI does not describe fractional mirroring so mirroring is kept at 100%;
- Added test confirming that HTTProxy mirror `weight` is correctly propagated to Envoy config;
- Updated docs;
Signed-off-by: Hassan Shamji [hshamji@etsy.com](mailto:hshamji@etsy.com)

Enable HTTPProxy Fractional Mirroring

---

changelogs/unreleased/5524-skriss-small.md
internal/dag/builder_test.go
internal/dag/dag.go
internal/dag/listener_processor.go
internal/envoy/v3/listener.go
internal/featuretests/v3/envoy.go
internal/featuretests/v3/listeners_test.go
internal/xdscache/v3/listener.go
site/content/docs/main/config/websockets.md

Closes #5241.
I had another look at all the context around this, and I can't see any issue with just enabling this by default, which tells envoy to pass the `Connection: Upgrade` and `Upgrade: websocket` headers to the upstream rather than returning a 403. However, given that the classic/non-Gateway API websockets behavior is and has been opt-in for a long time, I don't think we should necessarily change that now.

enable websockets for Gateway listeners

---

apis/projectcontour/v1/httpproxy.go
changelogs/unreleased/5529-tsaarni-small.md
examples/contour/01-crds.yaml
examples/render/contour-deployment.yaml
examples/render/contour-gateway-provisioner.yaml
examples/render/contour-gateway.yaml
examples/render/contour.yaml
internal/dag/cache.go
internal/dag/extension_processor.go
internal/dag/gatewayapi_processor.go
internal/dag/httpproxy_processor.go
internal/dag/ingress_processor.go
internal/dag/status_test.go
site/content/docs/main/config/api-reference.html

This change unifies handling of cross-namespace certificate delegation for all secret references: TLS certificate, CA certificate, CRL file.

Clarify TLS certificate delegation

---

changelogs/unreleased/5463-tsaarni-small.md
internal/dag/cache.go
internal/dag/cache_test.go
test/e2e/httpproxy/client_cert_crl_test.go

Update of CRL Secret did not trigger DAG rebuild when it was not co-located in the same Secret with CA certificate. The effect was that CRL secret was not recognized if it was created after the HTTPProxy and updates to CRL content were not taken into use.
Trigger for DAG rebuild was also missing for Ingress when using certificate delegation via `projectcontour.io/tls-cert-namespace` annotation (Ingress v1 does not anymore allow `/` as part of secret name). It is also fixed in this PR.
Fixes #5462
Fixes #5538

Fix dag rebuild trigger when Secret object changes

---

.github/workflows/build_daily.yaml
.github/workflows/prbuild.yaml
Makefile
changelogs/unreleased/5502-sunjayBhatia-small.md
changelogs/unreleased/5555-skriss-small.md

Looks like Go 1.21 won't be out until August so we'll likely miss it for Contour 1.26, so doing the patch bump here too.

update to Go 1.20.6

---

test/e2e/deployment.go

Locally when running the test the default timeout `bootstrapCmd` 1sec is not enough and I can't run the e2e tests. Small code change to increase the timeout.

Increase `bootstrapCmd` timeout

---

go.mod

https://github.com/cert-manager/cert-manager/issues/5953 is now closed and included in cert-manager 1.12.2, so looks like we don't need this anymore.
Running `go list -modfile=go.mod -m all` now works fine.

remove vcert replace

---

.github/dependabot.yml
site/content/resources/release-process.md

Add go and github action bumps for only patch versions on release branches
Also updates release process for minor releases to mention this config should be updated

Add dependabot config for release branches

---

internal/envoy/v3/route.go
internal/envoy/v3/route_test.go

Cleanup: Use Envoy contains for header routing

---

changelogs/unreleased/5652-LiorLieberman-minor.md
internal/dag/accessors.go
internal/dag/accessors_test.go
internal/dag/builder_test.go
internal/dag/dag.go
internal/dag/gatewayapi_processor.go
internal/dag/httpproxy_processor.go
internal/dag/status_test.go
internal/debug/dot.go
internal/envoy/v3/route.go
internal/envoy/v3/route_test.go

Adding support for multiple RequestMirror filters per rule in GW API. both GRPC and HTTP
Fixes: https://github.com/projectcontour/contour/issues/4566
ref: https://github.com/kubernetes-sigs/gateway-api/pull/2199

gw-api: Support multiple RequestMirror filters per rule in GW API

---

changelogs/unreleased/5651-Jean-Daniel-small.md
internal/k8s/statusaddress.go
internal/k8s/statusaddress_test.go

That field is used by other components like k8s external-dns, and should contains all information provided by the envoy service load balancer status.
It also fixes the `Gateway.Status.Addresses` field update when all Ingress entries are remove from the envoy service.
Fixes #5650

Fix Gateway Status Addresses Updater with multiple Ingress entries.

---

go.mod
go.sum

v1.0.0 was retracted, so downgrades to the version pinned by github.com/vektra/mockery/v2@v2.32.4.
ref. https://github.com/projectcontour/contour/pull/5684#discussion_r1300352030

deps: downgrade github.com/chigopher/pathlib to v0.15.0

---

.mockery.yaml
Makefile
internal/controller/controller_test.go
internal/debug/dot_test.go
internal/k8s/status_test.go
internal/k8s/statusaddress_test.go
internal/leadership/notifier_test.go

Migrate to new Mockery config

---

site/content/docs/main/config/gateway-api.md
site/content/docs/main/guides/gateway-api.md
site/content/getting-started/_index.md
site/data/docs/main-toc.yml

Adds a Gateway API document under
"Configuration", and moves some of
the content that was previously in
the guide into it.
Closes #4786.
Feedback on organization, missing content, etc. welcome!
Preview: https://deploy-preview-5433--projectcontour.netlify.app/docs/main/config/gateway-api/

docs: add Gateway API documentation

---

design/endpoint-slice-support.md

Design proposal to address https://github.com/projectcontour/contour/issues/2696

Design: Endpoint slice support

---

apis/projectcontour/v1alpha1/contourdeployment.go
changelogs/unreleased/5699-yangyy93-small.md
examples/contour/01-crds.yaml
examples/render/contour-deployment.yaml
examples/render/contour-gateway-provisioner.yaml
examples/render/contour-gateway.yaml
examples/render/contour.yaml
internal/provisioner/model/model.go
internal/provisioner/objects/dataplane/dataplane.go
site/content/docs/main/config/api-reference.html
site/content/docs/main/configuration.md

provisioner: add field overloadMaxHeapSize for envoy

---

changelogs/unreleased/5752-davinci26-major.md
internal/featuretests/v3/replaceprefix_test.go
internal/featuretests/v3/route_test.go
internal/sorter/sorter.go
internal/sorter/sorter_test.go
internal/xdscache/v3/route_test.go

Since Envoy is greedy matching path routes, order is important. Contour decides to sort the routes in a way that is not really intuitive and can lead to suprises.
In particular even tho the comment in the code state that routes are ordered based on legnth the reality is that they are sorted based on string comparison. This PR fixes this.
* I think the current behaviour doesnt make much sense and it is a bit brittle.
* Updating the behaviour has significant update risk since there might be folks that rely on this routing behaviour without really knowing it.
* Should we even merge this PR? I am of two minds and I would like some input:
1. Option (1): Merge it as and make a clear changelog/announcement about the fix
2. Option (2): Create a config flag with a feature-flag e.g. …

Fixup: Sort paths based on length rather than lexi

---

changelogs/unreleased/5804-skriss-small.md
internal/dag/gatewayapi_processor.go
internal/dag/status_test.go
test/scripts/run-gateway-conformance.sh

Sets Gateway Listeners' ResolvedRefs condition
to true by default, to meet conformance.
Closes #5648.
Ran Gateway API main branch conformance manually, confirmed it fails without this change and passes with it.

internal/dag: default Listener ResolvedRefs to true

---

go.mod
go.sum
internal/k8s/log.go
internal/k8s/log_test.go
test/conformance/gatewayapi/gateway_conformance_test.go
test/e2e/framework.go

Fixes data races found in #5805

deps: Bump logrusr to v4.0.0

---

Makefile
changelogs/unreleased/5821-sunjayBhatia-small.md
cmd/contour/gatewayprovisioner.go
examples/contour/03-envoy.yaml
examples/deployment/03-envoy-deployment.yaml
examples/render/contour-deployment.yaml
examples/render/contour-gateway.yaml
examples/render/contour.yaml
site/content/resources/compatibility-matrix.md
versions.yaml

https://www.envoyproxy.io/docs/envoy/v1.27.1/version_history/v1.27/v1.27.1

Bump Envoy to 1.27.1

---

Makefile
cmd/contour/gatewayprovisioner.go
examples/contour/03-envoy.yaml
examples/deployment/03-envoy-deployment.yaml
examples/render/contour-deployment.yaml
examples/render/contour-gateway.yaml
examples/render/contour.yaml

https://www.envoyproxy.io/docs/envoy/v1.27.1/version_history/v1.27/v1.27.1

release-1.26: Bump Envoy to 1.27.1

---

Makefile
cmd/contour/gatewayprovisioner.go
examples/contour/03-envoy.yaml
examples/deployment/03-envoy-deployment.yaml
examples/render/contour-deployment.yaml
examples/render/contour-gateway.yaml
examples/render/contour.yaml

https://www.envoyproxy.io/docs/envoy/v1.26.5/version_history/v1.26/v1.26.5

release-1.25: Bump Envoy to 1.26.5

---

Makefile
cmd/contour/gatewayprovisioner.go
examples/contour/03-envoy.yaml
examples/deployment/03-envoy-deployment.yaml
examples/render/contour-deployment.yaml
examples/render/contour-gateway.yaml
examples/render/contour.yaml

https://www.envoyproxy.io/docs/envoy/v1.25.10/version_history/v1.25/v1.25.10

release-1.24: Bump Envoy to 1.25.10

---

go.mod
go.sum

release-1.25: Bump grpc-go to v1.56.3

---

internal/provisioner/controller/gateway.go
internal/provisioner/controller/gateway_test.go
internal/provisioner/model/model.go
internal/provisioner/objects/dataplane/dataplane_test.go

There was a problem in the previous [PR](https://github.com/projectcontour/contour/pull/5699) ,The `OverloadMaxHeapSize` field in contourDeployment was not assigned correctly. This PR fixes this problem.

provisioner: fix envoy-max-heapsize not set

---

Makefile
cmd/contour/gatewayprovisioner.go
examples/contour/03-envoy.yaml
examples/deployment/03-envoy-deployment.yaml
examples/render/contour-deployment.yaml
examples/render/contour-gateway.yaml
examples/render/contour.yaml

https://www.envoyproxy.io/docs/envoy/v1.26.6/version_history/v1.26/v1.26.6

release-1.25: Bump Envoy to v1.26.6

---

Makefile
cmd/contour/gatewayprovisioner.go
examples/contour/03-envoy.yaml
examples/deployment/03-envoy-deployment.yaml
examples/render/contour-deployment.yaml
examples/render/contour-gateway.yaml
examples/render/contour.yaml

https://www.envoyproxy.io/docs/envoy/v1.27.2/version_history/v1.27/v1.27.2

release-1.26: Bump Envoy to v1.27.2

---

Makefile
changelogs/unreleased/5821-sunjayBhatia-small.md
changelogs/unreleased/5863-sunjayBhatia-small.md
cmd/contour/gatewayprovisioner.go
examples/contour/03-envoy.yaml
examples/deployment/03-envoy-deployment.yaml
examples/render/contour-deployment.yaml
examples/render/contour-gateway.yaml
examples/render/contour.yaml
site/content/resources/compatibility-matrix.md
versions.yaml

https://www.envoyproxy.io/docs/envoy/v1.27.2/version_history/v1.27/v1.27.2

Bump Envoy to v1.27.2

---

.golangci.yml
cmd/contour/shutdownmanager.go
internal/contour/handler.go
internal/controller/gateway.go
internal/controller/gatewayclass.go
internal/dag/cache.go
internal/dag/cache_test.go
internal/envoy/route.go
internal/envoy/v3/bootstrap.go
internal/envoy/v3/listener.go
internal/k8s/helpers.go
internal/k8s/helpers_test.go
internal/k8s/log.go
internal/k8s/statusaddress.go
internal/provisioner/objects/secret/secret.go
internal/status/gatewayclass.go
internal/xds/v3/contour_test.go
internal/xdscache/snapshot.go
internal/xdscache/v3/endpointstranslator.go
internal/xdscache/v3/runtime.go
test/e2e/incluster/incluster_test.go
test/e2e/incluster/leaderelection_test.go

When we enabled the use-any rule we disabled all the default rules that are run by revive (see: https://revive.run/docs#golangci-lint)
This change grabs all the default rules from
https://github.com/mgechev/revive/blob/master/defaults.toml and adds the use-any rule

release-1.26: golangci-lint: Fix revive rules

---

test/e2e/deployment.go
test/e2e/framework.go

Compile contour binary with -race flag and look for "DATA RACE" in stderr. Fails test if found.

test/e2e: Add race detection in e2e tests

---

.golangci.yml
cmd/contour/shutdownmanager.go
internal/contour/handler.go
internal/controller/gateway.go
internal/controller/gatewayclass.go
internal/dag/cache.go
internal/dag/cache_test.go
internal/dag/policy.go
internal/envoy/route.go
internal/envoy/v3/bootstrap.go
internal/envoy/v3/listener.go
internal/k8s/helpers.go
internal/k8s/helpers_test.go
internal/k8s/log.go
internal/k8s/statusaddress.go
internal/provisioner/objects/secret/secret.go
internal/status/gatewayclass.go
internal/xds/v3/contour_test.go
internal/xdscache/snapshot.go
internal/xdscache/v3/endpointstranslator.go
internal/xdscache/v3/runtime.go
test/e2e/incluster/incluster_test.go
test/e2e/incluster/leaderelection_test.go

When we enabled the use-any rule we disabled all the default rules that are run by revive (see: https://revive.run/docs#golangci-lint)
This change grabs all the default rules from
https://github.com/mgechev/revive/blob/master/defaults.toml and adds the use-any rule

golangci-lint: Fix revive rules

---

.github/workflows/build_tag.yaml
.gitignore
test/conformance/gatewayapi/gateway_conformance_test.go
test/scripts/run-gateway-conformance.sh

Run Gateway API conformance and generate report on tagged builds

---

.github/workflows/build_tag.yaml
test/conformance/gatewayapi/gateway_conformance_test.go

- Don't build/load contour image to kind as we should be using the image we just pushed
- Fill in Gateway API version from our environment var

Minor fixes to Gateway API conformance on release tag

---

test/scripts/install-provisioner-release.sh

In install-provisioner-release.sh, check for
the gateway-system namespace before waiting
on the admission server.
This fixes upgrade test failures post-1.27.0.

test/scripts: check for gateway-system namespace

---

test/scripts/install-provisioner-release.sh

In install-provisioner-release.sh, check for
the gateway-system namespace before waiting
on the admission server.
Backport of #5916

[release-1.27] test/scripts: check for gateway-system namespace

---

test/e2e/infra/metrics_test.go

test/e2e: add flake retries for HTTPS metrics test

---

test/e2e/framework.go

changed the function signature from func `(f *Framework) NamespacedTest(namespace string, body NamespacedTestBody)` to this
`func (f *Framework) NamespacedTest(namespace string, body NamespacedTestBody, additionalNamespaces ...string)`
Updates: #3837

test/e2e: NamespacedTest helper can create/delete multiple namespaces

---

cmd/contour/serve.go

These log lines are useful to see by default and do not show up with the default log level when using log.Printf

Use Info instead of Printf logs for dag build info lines

---

.github/workflows/codeql-analysis.yml

So the go version used is kept up to date, to prevent actions warnings

Use setup-go action before codeql

---

test/e2e/infra/endpointslice_test.go

Makes the endpoint slice E2E test faster and
less likely to flake.
Closes #5974.

test/e2e: replace fixed sleeps with require.Eventually

---

test/e2e/infra/metrics_test.go

release-1.25: test/e2e: add flake retries for HTTPS metrics test

---

test/e2e/infra/metrics_test.go

release-1.27: test/e2e: add flake retries for HTTPS metrics test

---

.github/reviewers.yaml
.github/workflows/request-reviews.yaml

CODEOWNERS only allows requesting reviews from users/teams with owner permission on the repo
Use this action which should not require the reviewers github team to have owner permissions

Use necojackarc/auto-request-review action to request reviews from non-maintainers

---

site/content/docs/1.21/configuration.md
site/content/docs/1.22/configuration.md
site/content/docs/1.23/configuration.md
site/content/docs/1.24/configuration.md
site/content/docs/1.25/configuration.md
site/content/docs/1.26/configuration.md
site/content/docs/1.27/configuration.md
site/content/docs/main/configuration.md

Should have been removed in #4332

site: Remove leaderelection from config file params

---

test/conformance/gatewayapi/gateway_conformance_test.go
test/scripts/run-gateway-conformance.sh

Adds comments for excluded Gateway API conformance tests and syncs run-gateway-conformance.sh with
gateway_conformance_test.go.
To merge after https://github.com/projectcontour/contour/pull/5961

update Gateway API conformance exclusions

---

.github/workflows/prbuild.yaml
hack/actions/install-kubernetes-toolchain.sh

Upstream Ingress conformance is flaky/poorly maintained and
unlikely to reach a state where it can reliably be run in CI.

remove disabled ingress-conformance run from CI

---

changelogs/unreleased/5828-KauzClay-major.md
changelogs/unreleased/5828-KauzClay-minor.md

After #5828 was merged (Thank You @KauzClay!) it occurred to me that we could promote the change from `minor` to `major` category, to call out the maximum TLS protocol version update. All information was there already, but I think it could be good to highlight it as a major change, since users might observe some differences with their upstream services after upgrade, when TLS handshake selects TLSv1.3. In worst case users could even have some minor problems due to the gaps in Envoy's retry handling, described in [envoyproxy/envoy#9300](https://www.github.com/envoyproxy/envoy/issues/9300).

Promote upstream TLS changelog entry from minor to major

---

internal/xdscache/v3/endpointslicetranslator.go
internal/xdscache/v3/endpointstranslator.go

clarify logic in endpointstranslator.go

---

.github/workflows/build_daily.yaml
.github/workflows/build_main.yaml
.github/workflows/build_tag.yaml
.github/workflows/codeql-analysis.yml
.github/workflows/label_check.yaml
.github/workflows/openssf-scorecard.yaml
.github/workflows/prbuild.yaml
.github/workflows/request-reviews.yaml
.github/workflows/stale.yaml
.github/workflows/trivy-scan.yaml

Dependabot should be able to update these and preserve the tag in the comment, as per: https://github.com/dependabot/dependabot-core/pull/5951
Workflows updated with: https://app.stepsecurity.io/secureworkflow

Pin github actions using shas

---

internal/envoy/cluster.go
internal/xdscache/v3/listener.go

Internal: replace funcs with the builtin 

---

CONTRIBUTING.md

Docker Mac Net Connect allows you to connect directly to Docker-for-Mac containers using their ip address instead of binding ports.
This also adds more helpful instructions for installation of tools, either tells them the recommended way to install the tool or links to the installation instructions of the specific tool.
Fixes #5294
Fixes #5269

Add instructions for docker-mac-net-connect and installation instructions to contributing guide

---

changelogs/unreleased/6063-lubronzhan-small.md
internal/envoy/v3/bootstrap.go
internal/envoy/v3/bootstrap_test.go

Right now dynamic runtime layer is available, they add the same config, so the static layer could be removed
Fix https://github.com/projectcontour/contour/issues/5845

Remove static base runtime layer from bootstrap

---

test/e2e/fixtures.go
test/e2e/framework.go

Will retry updates on conflict rather than failing immediately
To fix failures like: https://github.com/projectcontour/contour/actions/runs/7460847887/job/20299759302

Improve e2e helper updateAndWaitFor to avoid conflicts

---

.github/workflows/codeql-analysis.yml
.github/workflows/label_check.yaml
.github/workflows/prbuild.yaml
.github/workflows/request-reviews.yaml
.github/workflows/welcome-new-contributors.yaml

To address OpenSSF security scan/best practices
Also does a little whitespace cleanup/standardizes YAML indenting

Use minimum permissions for github token in PR workflows

---

README.md

also move badges to multiple lines

Add OpenSSF scorecard to README

---

.github/workflows/prbuild.yaml
changelogs/unreleased/6095-lubronzhan-small.md

Fix https://github.com/projectcontour/contour/issues/6095
Example run after adding the change in my PR
https://github.com/projectcontour/contour/pull/6073
[projectcontour/contour/actions/runs/7551166827/job/20557981226?pr=6073](https://github.com/projectcontour/contour/actions/runs/7551166827/job/20557981226?pr=6073)
```
run golangci-lint
Running [/home/runner/golangci-lint-1.55.2-linux-amd64/golangci-lint run --out-format=github-actions --build-tags=e2e,conformance,gcp,oidc,none --out-${NO_FUTURE}format=colored-line-number] in [] ...
Error: internal/provisioner/objects/rbac/role/role.go:100:45: unused-parameter: parameter 'namespace' seems to be unused, consider removing or renaming it as _ (revive)
func desiredRoleForContourInNamespace(name, namespace string, contour *model.Contour) …
```

Add flag to golangci-lint to show line number if there is error

---

site/content/docs/1.24/guides/proxy-proto.md
site/content/docs/1.25/guides/proxy-proto.md
site/content/docs/1.26/guides/proxy-proto.md
site/content/docs/1.27/guides/proxy-proto.md
site/content/docs/main/guides/proxy-proto.md

issue https://github.com/kubernetes/kubernetes/issues/57250 has been resolved 2 years ago

Update proxy-proto.md to remove warning about aws load balancer annotations not working 

---

hack/actions/check-uncommitted-codegen.sh
hack/generate-crd-deepcopy.sh
hack/generate-crd-yaml.sh
hack/generate-rbac.sh

Currently, the `check-uncommited-codegen` shows there are uncommited change, but not the details of the change. So add some command to help debug
1. print git diff if there is diff
2. print controller-gen version, since sometimes it could just because the controller-gen version is incorrect, then the generated output is different between remote job and local environment

Add more debugging log on generating crd related code.

---

changelogs/unreleased/6077-abbas-gheydi-small.md
internal/envoy/v3/accesslog.go
internal/envoy/v3/accesslog_test.go
site/content/docs/main/config/access-logging.md

This PR addresses the issue #6067 by implementing the feature to omit empty fields in Envoy logs for the access log.
- Modified the access log to exclude empty fields in Envoy logs.
#6067

feat(access-log): omit empty fields in Envoy logs

---

go.mod
go.sum

This PR fixes race condition introduced by #6100 where certyaml package got called concurrently from multiple goroutines (see example logs [here](https://github.com/projectcontour/contour/actions/runs/7627504023/job/20776383300)). New version of certyaml adds support for this use case https://github.com/tsaarni/certyaml/pull/48.

Bump certyaml to fix race condition

---

changelogs/unreleased/6124-skriss-small.md
internal/envoy/v3/listener.go
internal/envoy/v3/listener_test.go
internal/envoy/v3/route.go
internal/envoy/v3/route_test.go
internal/featuretests/v3/authorization_test.go
internal/featuretests/v3/envoy.go
internal/featuretests/v3/global_authorization_test.go
internal/featuretests/v3/ipfilter_test.go
internal/featuretests/v3/jwtverification_test.go
internal/featuretests/v3/localratelimit_test.go
internal/xdscache/v3/route_test.go

Use the same names for HTTP filters when they
are added to an HTTP connection manager and
when they are configured with per-filter config
on virtual hosts or routes. Extracts a set of
constants for filter names to ensure they remain
in sync.
This addresses a change in Envoy behavior in Envoy 1.29.
See https://github.com/envoyproxy/envoy/issues/29461 for
more detail.

internal/envoy: use consistent HTTP filter names

---

Makefile
changelogs/unreleased/6123-skriss-small.md
cmd/contour/gatewayprovisioner.go
examples/contour/03-envoy.yaml
examples/deployment/03-envoy-deployment.yaml
examples/render/contour-deployment.yaml
examples/render/contour-gateway.yaml
examples/render/contour.yaml
go.mod
go.sum
site/content/resources/compatibility-matrix.md
versions.yaml

bump Envoy to v1.29.0

---

changelogs/unreleased/6143-skriss-docs.md
site/content/docs/1.26/config/gateway-api.md
site/content/docs/1.27/config/gateway-api.md
site/content/docs/main/config/gateway-api.md

site: document Gateway name length limit

---

changelogs/unreleased/6147-sunjayBhatia-small.md
examples/gateway-provisioner/01-roles.yaml
examples/render/contour-gateway-provisioner.yaml
internal/provisioner/controller/gatewayclass.go
internal/provisioner/controller/gatewayclass_test.go
internal/provisioner/rbac/rbac.go
internal/provisioner/scheme.go
test/e2e/provisioner/provisioner_test.go

Based on Gateway API CRD bundle-version annotation
We will still reconcile the GatewayClass etc. but will set a status condition on the GatewayClass saying this support is best effort.
Fixes #5754

provisioner: Set SupportedVersion condition on GatewayClass

---

apis/projectcontour/v1alpha1/contourconfig.go
changelogs/unreleased/6144-skriss-deprecation.md
cmd/contour/serve.go
cmd/contour/servecontext.go
examples/contour/01-crds.yaml
examples/render/contour-deployment.yaml
examples/render/contour-gateway-provisioner.yaml
examples/render/contour-gateway.yaml
examples/render/contour.yaml
pkg/config/parameters.go
site/content/docs/main/config/api-reference.html
site/content/docs/main/config/gateway-api.md
site/content/docs/main/configuration.md
site/content/guides/gateway-api.md
test/e2e/gateway/gateway_test.go

Users should either statically configure Contour with a specific Gateway ref, or use the Gateway provisioner to dynamically provision Gateways.
Updates #5923.

deprecate configuring Contour with a Gateway controller name

---

changelogs/unreleased/6148-lubronzhan-minor.md
changelogs/unreleased/6148-lubronzhan-small.md
examples/deployment/03-envoy-deployment.yaml
examples/render/contour-deployment.yaml
internal/provisioner/objects/dataplane/dataplane.go
internal/provisioner/objects/dataplane/dataplane_test.go
site/content/resources/upgrading.md

Fix https://github.com/projectcontour/contour/issues/5558
Tested inside a kind cluster and checked the manifest of envoy deployment 
```
- apiVersion: apps/v1
kind: Deployment
metadata:
annotations:
deployment.kubernetes.io/revision: "1"
creationTimestamp: "2024-01-31T00:58:19Z"
generation: 2
labels:
app.kubernetes.io/component: ingress-controller
app.kubernetes.io/instance: http
app.kubernetes.io/managed-by: contour-gateway-provisioner
app.kubernetes.io/name: contour
gateway.networking.k8s.io/gateway-name: http
projectcontour.io/owning-gateway-name: http
name: envoy-http
namespace: gateway-with-envoy-deployment
resourceVersion: "1072"
uid: c8ed4bf0-de29-4d18-9553-639712cc46ff
....
spec:
affinity:
podAntiAffinity:
requiredDuringSchedulingIgnoredDuringExecution:
- labelSelector: …
```

Add anti-affinity for envoy deployed by provisioner

---

changelogs/unreleased/6161-sunjayBhatia-docs.md
site/content/docs/main/troubleshooting.md
site/content/docs/main/troubleshooting/common-errors.md
site/content/docs/main/troubleshooting/common-proxy-errors.md
site/data/docs/main-toc.yml

This doc should contain steps to diagnose common errors, focused on mainly HTTP req/responses

site: Add troubleshooting doc for common errors

---

changelogs/unreleased/6151-christianang-small.md
internal/dag/gatewayapi_processor.go
internal/dag/status_test.go
internal/status/backendtlspolicyconditions.go
internal/status/backendtlspolicyconditions_test.go
internal/status/cache.go
test/e2e/gateway/backend_tls_policy_test.go
test/e2e/gatewayapi_predicates.go

This PR adds the Accepted Condition to the BackendTLSPolicy.
The Status contains an array of Ancestor Policy Statuses. The Ancestor Ref will be set to the gateway similar to what happens on routes now.
If the BackendTLSPolicy is successfully applied to the Gateway for a given HTTPRoute and Backend Service the "Accepted" condition status will be set to true with the "Accepted" Reason.
If the BackendTLSPolicy is found, but is invalid due to any validation reasons (e.g unsupported certRefs, missing certs, malformed hostname, etc) the status will be set to false with the "Invalid" Reason.
Fixes #6137

Add Accepted condition to BackendTLSPolicy

---

site/content/resources/release-process.md

They don't need to be set since the changelog
is now generated manually for patch releases,
one less thing to have to look up/fill in.

drop Kubernetes version vars from patch release process

---

changelogs/unreleased/6185-sunjayBhatia-small.md
internal/dag/gatewayapi_processor.go
internal/dag/status_test.go
internal/status/backendtlspolicyconditions.go
internal/status/cache.go

DAG cache objects were being written to when StatusUpdater fetched resource to perform update on since status updates held a reference to them.

Fixes BackendTLSPolicy Status Update data race

---

internal/dag/gatewayapi_processor.go
internal/dag/status_test.go
internal/status/backendtlspolicyconditions.go
internal/status/cache.go

DAG cache objects were being written to when StatusUpdater fetched resource to perform update on since status updates held a reference to them.

release-1.28: Fixes BackendTLSPolicy Status Update data race

---

internal/featuretests/v3/upstreamtls_test.go

BackendTLSPolicy takes precedence over the upstream-protocol annotation if both are specified. This PR adds a test to assert on this precedence.
Reading the documentation here https://projectcontour.io/docs/main/config/upstream-tls/, it seems like you can specify the protocol on the service, but the certificates for upstream tls would have been specified on HTTPProxy, which is not something that exists on HTTPRoute (because the intended way is to use BackendTLSPolicy). So the test just adds the protocol annotation, along with providing a BackendTLSPolicy, and the test will assert that the protocol is tls as well as the certificates from BackendTLSPolicy exists on the final envoy cluster.
Fixes #6138

Add test demonstrating backendtlspolicy precedence

---

internal/featuretests/v3/backendclientauth_test.go
internal/featuretests/v3/upstreamtls_test.go
internal/k8s/statusaddress_test.go
internal/k8s/statuscache.go

This PR validates that the cluster name generation creates unique names when the tls settings are different due to creating one cluster using HTTPRoute with BackendTLSPolicy and another with HTTPProxy.
This PR also makes a small refactor of adding the type to the `StatusUpdateCacher` to differentiate resources with the same name but different types.
Fixes #6141

Add test validating cluster name generation is unique in HTTPRoute with BackendTLSPolicy vs HTTPProxy

---

internal/featuretests/v3/route_test.go
internal/gatewayapi/listeners.go
internal/sorter/sorter.go
internal/sorter/sorter_test.go
test/e2e/bench/bench_test.go
test/e2e/deployment.go
test/e2e/gateway/response_header_modifier_test.go
test/e2e/httpproxy/cookie_rewrite_test.go
test/e2e/incluster/memory_usage_test.go
test/e2e/incluster/smoke_test.go

See https://go.dev/doc/go1.22#language.
Looks like we have to get #6182 merged first though

use Go 1.22 range over integers syntax

---

test/e2e/httpproxy/grpc_test.go

Updates #6092.
https://github.com/projectcontour/contour/actions/runs/8087545863/attempts/1 hit the flake.

test/e2e: add flake attempts for gRPC plaintext E2E

---

Makefile

Allows builds on multiple architectures.
(can see this SHA via `docker buildx imagetools inspect golang:1.22.0`)

use multi-arch golang base image

---

changelogs/unreleased/6230-yangyy93-small.md
internal/envoy/v3/cluster_test.go
internal/envoy/v3/endpoint.go
internal/envoy/v3/endpoint_test.go

Fix for specifying a health check port with an ExternalName Service

---

Makefile

I found that when running [Cloudflare WARP](https://developers.cloudflare.com/warp-client/) it adds DNS server listening two new loopback interface IPs, `127.0.2.2` and `127.0.2.3`. This broke the envoy xDS configuration because the it was trying to use `127.0.2.2:8001`.
This grep change should just remove all IPs in the loopback CIDR block since they all start with `127.`

Ignore all loopback IPs in local ip grep

---

test/e2e/gateway/request_header_modifier_test.go

For the RequestHeaderModifierBackendRef test, check the service reached by the request as part of the
eventual consistency condition to avoid issues with test pollution.
ref. https://github.com/projectcontour/contour/actions/runs/8179127307/job/22364621818
Oddly, when failing, the request is hitting an "echo" backend pod, which isn't even defined as part of the test in question (it only has "echo-header-filter" and "echo-header-nofilter"). There must be some pollution going on from another test, but I can't spot it. It's a little odd given that the HTTPRoute has a distinct hostname that's being used in the requests. In any case, I think this should help avoid issues. Haven't been able to repro locally.

test/e2e/gateway: check service as part of request condition

---

changelogs/unreleased/6250-skriss-small.md
cmd/contour/serve.go
internal/protobuf/helpers.go
internal/protobuf/helpers_test.go
internal/xdscache/v3/endpointslicetranslator.go
internal/xdscache/v3/endpointstranslator.go
internal/xdscache/v3/snapshot.go

Uses a separate go-control-plane snapshot
cache for EDS. This allows Endpoints updates
to be independent of other config updates,
minimizing the amount of unnecessary xDS
traffic that is generated. This is more consistent
with the legacy Contour xDS server's implementation.
Note, this PR sets the envoy/go-control-plane xDS server as the default for testing purposes, but that change will be reverted before merge.

use a separate snapshot cache for EDS

---

test/e2e/gateway/tcproute_test.go
test/e2e/http.go

use a less generic name so we can see if this test is causing pollution issues

test/e2e/gateway: prevent tcproute test causing pollution

---

.github/workflows/build_daily.yaml
.github/workflows/build_tag.yaml
.github/workflows/codeql-analysis.yml
.github/workflows/prbuild.yaml
Makefile
changelogs/unreleased/6181-sunjayBhatia-small.md
changelogs/unreleased/6265-sunjayBhatia-small.md

See release notes: https://go.dev/doc/devel/release#go1.22.0
https://github.com/golang/go/issues/65831 is the most relevant CVE backport for Contour

Bump golang to 1.22.1 for CVEs

---

internal/featuretests/v3/cluster_test.go
internal/featuretests/v3/endpoints_test.go
internal/featuretests/v3/featuretests.go
internal/featuretests/v3/secrets_test.go
internal/xdscache/v3/snapshot.go

use envoy xDS server for featuretests

---

.github/workflows/build_daily.yaml
apis/projectcontour/v1alpha1/contourconfig.go
changelogs/unreleased/6146-skriss-deprecation.md
changelogs/unreleased/6146-skriss-major.md
cmd/contour/servecontext_test.go
examples/contour/01-contour-config.yaml
examples/contour/01-crds.yaml
examples/render/contour-deployment.yaml
examples/render/contour-gateway-provisioner.yaml
examples/render/contour-gateway.yaml
examples/render/contour.yaml
internal/contourconfig/contourconfiguration.go
pkg/config/parameters.go
pkg/config/parameters_test.go
site/content/docs/main/config/api-reference.html
site/content/docs/main/configuration.md
test/e2e/fixtures.go

The default xDS server implementation is
now `envoy`, i.e. the go-control-plane
implementation.
Updates #2134.
Signed-off-by: Steve Kriss <stephen.kriss@gmail.com>

change default xDS server to envoy

---

Makefile
cmd/contour/gatewayprovisioner.go
examples/contour/03-envoy.yaml
examples/deployment/03-envoy-deployment.yaml
examples/render/contour-deployment.yaml
examples/render/contour-gateway.yaml
examples/render/contour.yaml

See release notes: https://www.envoyproxy.io/docs/envoy/v1.29.2/version_history/v1.29/v1.29.2

release-1.28: Bump Envoy to v1.29.2

---

Makefile
changelogs/unreleased/6283-sunjayBhatia-minor.md
changelogs/unreleased/6283-sunjayBhatia-small.md
cmd/contour/gatewayprovisioner.go
examples/contour/03-envoy.yaml
examples/deployment/03-envoy-deployment.yaml
examples/render/contour-deployment.yaml
examples/render/contour-gateway.yaml
examples/render/contour.yaml
site/content/resources/compatibility-matrix.md
versions.yaml

See release notes: https://www.envoyproxy.io/docs/envoy/v1.29.2/version_history/v1.29/v1.29.2

Bump Envoy to v1.29.2

---

.codespell.ignorewords
changelogs/unreleased/6288-sunjayBhatia-minor.md
internal/envoy/v3/runtime.go
internal/envoy/v3/runtime_test.go
internal/xdscache/v3/runtime_test.go

Removal of the header was added by default in Envoy v1.29.0. This change reverts back to prior behavior.
This change can be reverted once https://github.com/envoyproxy/envoy/pull/32255 is backported or present in a new release of Envoy.

Disable Envoy removing TE request header

---

.codespell.ignorewords
internal/envoy/v3/runtime.go
internal/envoy/v3/runtime_test.go
internal/xdscache/v3/runtime_test.go

Removal of the header was added by default in Envoy v1.29.0. This change reverts back to prior behavior.
This change can be reverted once https://github.com/envoyproxy/envoy/pull/32255 is backported or present in a new release of Envoy.

release-1.28: Disable Envoy removing TE request header

---

changelogs/unreleased/6295-tsaarni-small.md
internal/contour/handler.go

This change fixes a bug that caused follower instance of Contour not reach the ready state when started under following condition:
1. Namespace(s) configured with `--watched-namespaces` do not contain any resources.
2. Resources that informer sends during initial synchronization are not triggering DAG rebuild because Contour decides those resources were not relevant.
As result, XDS server is not started at all and those Contour instances will not reach ready state.
Note that leader instance still worked correctly even when the conditions were true. This is because leader election triggers "fake" DAG update and therefore the same code path gets executed as if informer delivered some relevant resources that necessitated DAG rebuild - and therefore XDS server start. 
The change adds explicit …

Allow follower to start with empty initial resource list

---

.github/workflows/build_daily.yaml
test/e2e/fixtures.go

Now that using EndpointSlices is the default behavior, flip the daily build to continue running E2E's with the Endpoints translator for coverage until it's
removed.

daily build: run E2E's against endpoints translator

---

changelogs/unreleased/6335-skriss-small.md
internal/dag/builder_test.go
internal/dag/gatewayapi_processor.go
internal/dag/status_test.go
test/conformance/gatewayapi/gateway_conformance_test.go
test/scripts/run-gateway-conformance.sh

Implements the Gateway API BackendRequest timeout in a way that satisfies current conformance. Since retries do not exist yet in Gateway API, BackendRequest is functionally equivalent to Request timeout, but according to the API spec must be less than/equal to Request timeout if both are specified.
(Yes, I know I was the one who originally suggested we don't implement this field yet, but since it's the only blocker to our conformance report showing full success for both core and extended, it seemed worth doing the simple/conformant implementation for now).

internal/dag: basic Gateway API Timeouts.BackendRequest impl

---

apis/projectcontour/v1/httpproxy.go
changelogs/unreleased/6188-lubronzhan-minor.md
internal/dag/dag.go
internal/dag/dag_test.go
internal/dag/gatewayapi_processor.go
internal/dag/gatewayapi_processor_test.go
internal/dag/status_test.go
internal/status/routeconditions.go
test/e2e/gateway/gateway_test.go
test/e2e/gateway/http_route_conflict_match_test.go
test/e2e/gateway/http_route_partially_conflict_match_test.go
test/e2e/gatewayapi_predicates.go

Fix https://github.com/projectcontour/contour/issues/3608
Now if there is conflicts between HTTPRoute's match, then only the HTTPRoute with
- older creationTimestamp
- alphabetically smaller on `namespace/name`
, will be chosen as the valid HTTPRoute, other HTTPRoute will be marked as conflict condition
TODO:
Signed-off-by: lubronzhan <lubronzhan@gmail.com>

handle Route conflicts with HTTPRoute.Matches

---

changelogs/unreleased/6375-skriss-small.md
internal/dag/builder_test.go
internal/dag/gatewayapi_processor.go

In Gateway API, a timeout specified as 0s (or any
other explicitly zero-valued duration string) should disable the timeout rather than use the default
value.
Closes #6373.

internal/dag: 0s HTTPRoute timeout disables the timeout

---

internal/provisioner/objects/deployment/deployment.go
internal/provisioner/objects/deployment/deployment_test.go

Flags on Contour Deployment should be separate, not comma separated list (list causes contour to fail to deploy)

provisioner: Use separate flag for each disabled feature

---

internal/provisioner/objects/deployment/deployment.go
internal/provisioner/objects/deployment/deployment_test.go

Flags on Contour Deployment should be separate, not comma separated list

release-1.28: provisioner: Use separate flag for each disabled feature

---

changelogs/unreleased/6426-shadialtarsha-small.md
internal/envoy/v3/route.go
internal/envoy/v3/route_test.go
test/e2e/httpproxy/external_auth_test.go

Previously, auth policies on direct response routes were ignored.
Based on #5962, included just the ExtAuth changes (will look at global rate limit E2E additions separately) and added routes/test cases to the existing ExtAuth E2E for simplicity.

internal/envoy: support AuthPolicy on direct response routes

---

changelogs/unreleased/6162-sunjayBhatia-minor.md
internal/dag/gatewayapi_processor.go
internal/dag/gatewayapi_processor_test.go
test/conformance/gatewayapi/gateway_conformance_test.go

Requests should be "isolated" to the most specific Listener and it's attached routes. This means our existing logic on finding intersecting route and Listener hostnames needs an update to factor in the other Listeners on a Gateway that the route in question may not actually be attached to.
Fix for conformance test: https://github.com/kubernetes-sigs/gateway-api/pull/2669
https://github.com/kubernetes-sigs/gateway-api/pull/2465 for spec

Gateway API: Fix for Listener/Route hostname isolation

---

changelogs/unreleased/6447-davinci26-small.md
internal/envoy/v3/stats.go
internal/envoy/v3/stats_test.go

We want to block all requests to the `admin` listener endpoint that are not `GET`. In particular someone know can do `/runtime_modify?key1=value1&key2=value2&keyN=valueN` to change runtime variables such as the max regexp program size
This is mostly for security reasons to prevent any potential attacks that could happen by an attacker modifying the `runtime` configuration of Envoy (or any other configuration).
Note that since `shutdownmanager.go` uses the admin socket `/admin/admin.sock` to send a `POST` request it should be unaffected by this change.
Some manual verifications:
```
curl http://localhost:9001/ready
LIVE
```
```
curl -vv --request POST http://localhost:9001/runtime
*   Trying [::1]:9001...
* Connected to localhost (::1) port 9001
> POST /runtime HTTP/1.1
> Host: …
```

Enforce `deny-by-default` approach on the `admin` listener by matching on exact paths and on `GET` requests

---

.codespell.ignorewords
apis/projectcontour/v1alpha1/ciphersuites.go
apis/projectcontour/v1alpha1/contourconfig_helpers.go
apis/projectcontour/v1alpha1/contourconfig_helpers_test.go
changelogs/unreleased/6461-tsaarni-small.md
internal/provisioner/objects/deployment/deployment_test.go

This change corrects the parsing of cipher configuration by adding support for equal-preference cipher groups `[cipher1|cipher2|...]`:
- The `ValidTLSCiphers` list now contains only individual cipher names, not groups.
- When configuring a group, the group is split into individual ciphers before comparing against cipher names in valid TLS cipher list.
- User is now able to configure ciphers `ECDHE-ECDSA-CHACHA20-POLY1305` and `ECDHE-RSA-CHACHA20-POLY1305` individually, whereas previously they were only accepted as part of the hardcoded groups.
- User can now define their own equal-preference ciphers groups.
Fixes #6380
**Background:**
Prior this change the list of valid TLS ciphers had hardcoded ciphers in bracketed format https://github.com/projectcontour/contour/blob/0796cd9d76578f147db9 …

Parse equal-preference cipher groups

---

Makefile
cmd/contour/gatewayprovisioner.go
examples/contour/03-envoy.yaml
examples/deployment/03-envoy-deployment.yaml
examples/render/contour-deployment.yaml
examples/render/contour-gateway.yaml
examples/render/contour.yaml

For CVE fixes
See release notes: https://www.envoyproxy.io/docs/envoy/v1.30.2/version_history/v1.30/v1.30.2

release-1.29: Bump Envoy to 1.30.2

---

Makefile
cmd/contour/gatewayprovisioner.go
examples/contour/03-envoy.yaml
examples/deployment/03-envoy-deployment.yaml
examples/render/contour-deployment.yaml
examples/render/contour-gateway.yaml
examples/render/contour.yaml

For CVE fixes
See release notes: https://www.envoyproxy.io/docs/envoy/v1.29.5/version_history/v1.29/v1.29.5

release-1.28: Bump Envoy to 1.29.5

---

Makefile
changelogs/unreleased/6483-sunjayBhatia-small.md
cmd/contour/gatewayprovisioner.go
examples/contour/03-envoy.yaml
examples/deployment/03-envoy-deployment.yaml
examples/render/contour-deployment.yaml
examples/render/contour-gateway.yaml
examples/render/contour.yaml
site/content/resources/compatibility-matrix.md
versions.yaml

For CVE fixes
See release notes: https://www.envoyproxy.io/docs/envoy/v1.30.2/version_history/v1.30/v1.30.2

Bump Envoy to 1.30.2

---

.codespell.ignorewords
Makefile
cmd/contour/gatewayprovisioner.go
examples/contour/03-envoy.yaml
examples/deployment/03-envoy-deployment.yaml
examples/render/contour-deployment.yaml
examples/render/contour-gateway.yaml
examples/render/contour.yaml

For CVE fixes
See release notes: https://www.envoyproxy.io/docs/envoy/v1.28.4/version_history/v1.28/v1.28.4

release-1.27: Bump Envoy to 1.28.4

---

.github/workflows/build_daily.yaml
.github/workflows/build_tag.yaml
.github/workflows/codeql-analysis.yml
.github/workflows/prbuild.yaml
Makefile

release-1.29: Bump golang to 1.22.4

---

.github/workflows/build_daily.yaml
.github/workflows/build_tag.yaml
.github/workflows/codeql-analysis.yml
.github/workflows/prbuild.yaml
Makefile

See release notes: https://go.dev/doc/devel/release#go1.21.minor

release-1.28: Bump golang to 1.21.11

---

.github/workflows/build_daily.yaml
.github/workflows/build_tag.yaml
.github/workflows/prbuild.yaml
Makefile

See release notes: https://go.dev/doc/devel/release#go1.21.minor

release-1.27: Bump golang to 1.21.11

---

changelogs/unreleased/6503-clayton-gonsalves-small.md
internal/envoy/v3/stats.go
internal/envoy/v3/stats_test.go

As part of the changes made in https://github.com/projectcontour/contour/pull/6447
the admin endpoint was tightened to only allow `GET` requests with path matches as `exact`.
This change blocked the `stats/prometheus` endpoint which is used by prometheus to scrape metrics. 
Note: If not fixed, this will lead to loss of all prometheus based metrics.

Enable admin route for `stats/prometheus`

---

changelogs/unreleased/6523-therealak12-small.md
cmd/contour/shutdownmanager.go

The PR adds a query param to the stats URL used in the shutdown-manager when waiting for the active connections to drain.
In clusters with a high number of routes (such as ours in Snapp with over 3000 routes), the `/stats/prometheus` response size is above 80MBs. This makes rendering and fetching the URL take a few seconds.
The introduced filter makes rendering faster and the response time shorter. Also, it reduces the time required for parsing and searching the response.
An example of the response when utilizing the filter:
Comparison of total request time before and after the filter:

shutdown manager: use filter on downstream_cx_active stats url

---

apis/projectcontour/v1alpha1/contourconfig.go
changelogs/unreleased/6561-skriss-deprecation.md
cmd/contour/serve.go
examples/contour/01-crds.yaml
examples/render/contour-deployment.yaml
examples/render/contour-gateway-provisioner.yaml
examples/render/contour-gateway.yaml
examples/render/contour.yaml
internal/contourconfig/contourconfiguration_test.go
pkg/config/parameters.go
site/content/docs/main/config/api-reference.html
site/content/docs/main/configuration.md

Fields are planned to be removed in the 1.31 release.
Updates #2134.

deprecate xDS server type field

---

Makefile
changelogs/unreleased/6483-sunjayBhatia-small.md
changelogs/unreleased/6562-sunjayBhatia-small.md
cmd/contour/gatewayprovisioner.go
examples/contour/03-envoy.yaml
examples/deployment/03-envoy-deployment.yaml
examples/render/contour-deployment.yaml
examples/render/contour-gateway.yaml
examples/render/contour.yaml
site/content/resources/compatibility-matrix.md
versions.yaml

- https://www.envoyproxy.io/docs/envoy/v1.30.3/version_history/v1.30/v1.30.3
- https://www.envoyproxy.io/docs/envoy/v1.30.4/version_history/v1.30/v1.30.4

Bump Envoy to 1.30.4

---

.github/workflows/build_daily.yaml
.github/workflows/build_tag.yaml
.github/workflows/codeql-analysis.yml
.github/workflows/prbuild.yaml
Makefile
changelogs/unreleased/6499-sunjayBhatia-small.md
changelogs/unreleased/6563-sunjayBhatia-small.md

Bump go to 1.22.5

---

changelogs/unreleased/6558-erikflores7-minor.md
internal/featuretests/v3/envoy.go
internal/featuretests/v3/global_authorization_test.go
internal/xdscache/v3/listener.go

When using IP to connect, no SNI is sent so the Fallback certificate has to be used in these cases. But when using Fallback certificate, there is currently no support for auth. This change adds the auth filter to add support for the fallback certificate.
Fixes #6512 
Signed-off-by: Erik Flores eflores@anduril.com

contour: adds global ext auth support to fallback certificates

---

changelogs/CHANGELOG-v1.29.0.md
changelogs/unreleased/6566-lubronzhan-minor.md
internal/dag/dag_test.go
internal/dag/gatewayapi_processor.go
internal/dag/gatewayapi_processor_test.go
internal/dag/status_test.go
internal/status/routeconditions.go
test/e2e/framework.go
test/e2e/gateway/gateway_test.go
test/e2e/gateway/grpc_route_conflict_match_test.go
test/e2e/gateway/grpc_route_partially_conflict_match_test.go
test/e2e/gatewayapi_predicates.go

Fix https://github.com/projectcontour/contour/issues/6267
Handle the match conflict of grpcroutes
It's possible that multiple GRPCRoutes will define the same Match conditions. In this case the following logic is applied to resolve the conflict:
- The oldest Route based on creation timestamp. For example, a Route with a creation timestamp of “2020-09-08 01:02:03” is given precedence over a Route with a creation timestamp of “2020-09-08 01:02:04”.
- The Route appearing first in alphabetical order (namespace/name) for example, foo/bar is given precedence over foo/baz.

Gateway API: handle Route conflicts with GRPCRoute.Matches

---

Makefile

Removes ENVOY_IMAGE, SRCDIRS, LOCAL_BOOTSTRAP_CONFIG and SECURE_LOCAL_BOOTSTRAP_CONFIG.

remove unused Makefile variables

---

site/content/docs/main/config/tls-termination.md

Since XFCC headers contain authentication information, it's important for users to know precisely how Contour (ie Envoy) handles existing XFCC headers from clients - ie, are they blocked, or appended to, and if blocked, in what circumstances are they blocked? Getting this wrong could allow serious vulnerabilities such as spoofing TLS client authentication via the XFCC header.
This documents Contours precise behaviour, so that users can know exactly how they are required to handle that header without needing to dive into the Contour source code.
My understanding from reading the [Contour source code](https://github.com/projectcontour/contour/blob/main/internal/envoy/v3/listener.go#L544), as well as the [Envoy documentation](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filte …

Clarified how XFCC headers are handled

---

docs/README.md

The docs/README.md made no sense. Anyone reading it in GitHub clearly wants to contribute to the documentation, that's why they're in the source code of Contour, why else would they have found their way to the source repository? So, it should point to where the documentation lives in the git repository, not to the website where it's served.

Update README.md to be more helpful

---

changelogs/unreleased/6616-Krast76-small.md
internal/dag/accessors.go
internal/dag/accessors_test.go

When contour is used as api-gateway in kubernetes clusters, appProtocol set to http or https doesn't work.
This PR, if applied, allow the following protocol (as defined by [IANA](https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml?search=https)) : 
- http and www-http
- https
That doesn't allow all the IANA services, but that'll support a common case
Fix #6560

[api-gateway]: Support http(s) as AppProtocol in Kubernetes svc

---

changelogs/unreleased/6714-tsaarni-small.md
cmd/contour/gatewayprovisioner.go
examples/contour/03-envoy.yaml
examples/deployment/03-envoy-deployment.yaml
examples/render/contour-deployment.yaml
examples/render/contour-gateway.yaml
examples/render/contour.yaml
site/content/resources/compatibility-matrix.md
versions.yaml

This change updates envoy in `main` branch to v1.32.0.

Bump Envoy to v1.32.0

---

.github/workflows/build_daily.yaml
.github/workflows/build_main.yaml
.github/workflows/build_tag.yaml
.github/workflows/label_check.yaml
.github/workflows/prbuild.yaml

Associated slack workspace is now defunct and notifications were minimally useful at this point.

Remove slack notification in CI workflows

---

changelogs/unreleased/6614-tsaarni-small.md
internal/contour/handler.go

This change will use polling for  `HasSynced()` call to align with how client-go's [`WaitForCacheSync()`](https://github.com/kubernetes/client-go/blob/690fd5274dfc971dcda653e45bc6e6852ab57316/tools/cache/shared_informer.go#L327-L343) operates. Previously it was only called when we received objects from the informer. By changing to polling, we prevent a race condition where Contour fails to recognize that the final object in the initial list has been received, which would prevent the xDS server from ever starting.
Fixes #6613 
The startup of a follower instance depends on informers signaling that they have finished synchronizing resources with the API server. We use the [`SingleFileTracker`](https://github.com/projectcontour/contour/blob/f9b6f6fdfdd83d3639f6e8c55836401d749c19e1/internal/con …

Use polling during startup to wait for informers to sync

---

.github/workflows/build_daily.yaml
.github/workflows/build_tag.yaml
.github/workflows/codeql-analysis.yml
.github/workflows/prbuild.yaml
Makefile
cmd/contour/gatewayprovisioner.go
examples/contour/03-envoy.yaml
examples/deployment/03-envoy-deployment.yaml
examples/render/contour-deployment.yaml
examples/render/contour-gateway.yaml
examples/render/contour.yaml

This change updates `release-1.28` branch with
* envoy v1.29.10
* See release notes for v1.29.8 [here](https://www.envoyproxy.io/docs/envoy/v1.29.9/version_history/v1.29/v1.29.8).
* See release notes for v1.29.9 [here](https://www.envoyproxy.io/docs/envoy/v1.29.9/version_history/v1.29/v1.29.9).
* See release notes for v1.29.10 [here](https://www.envoyproxy.io/docs/envoy/v1.29.10/version_history/v1.29/v1.29.10).
* go v1.21.13
* See release notes [here](https://go.dev/doc/devel/release#go1.21.minor).

release-1.28: Bump Envoy to v1.29.10 and Go to v1.21.13

---

.github/workflows/build_daily.yaml
.github/workflows/build_tag.yaml
.github/workflows/codeql-analysis.yml
.github/workflows/prbuild.yaml
Makefile
cmd/contour/gatewayprovisioner.go
examples/contour/03-envoy.yaml
examples/deployment/03-envoy-deployment.yaml
examples/render/contour-deployment.yaml
examples/render/contour-gateway.yaml
examples/render/contour.yaml

This change updates `release-1.29` branch with
* envoy v1.30.7
* See release notes for v1.30.5 [here](https://www.envoyproxy.io/docs/envoy/v1.30.6/version_history/v1.30/v1.30.5).
* See release notes for v1.30.6 [here](https://www.envoyproxy.io/docs/envoy/v1.30.6/version_history/v1.30/v1.30.6).
* See release notes for v1.30.7 [here](https://www.envoyproxy.io/docs/envoy/v1.30.7/version_history/v1.30/v1.30.7).
* go v1.22.8
* See release notes [here](https://go.dev/doc/devel/release#go1.22.minor).

release-1.29: Bump Envoy to v1.30.7 and Go to v1.22.8

---

.github/workflows/build_daily.yaml
.github/workflows/build_tag.yaml
.github/workflows/codeql-analysis.yml
.github/workflows/prbuild.yaml
Makefile
cmd/contour/gatewayprovisioner.go
examples/contour/03-envoy.yaml
examples/deployment/03-envoy-deployment.yaml
examples/render/contour-deployment.yaml
examples/render/contour-gateway.yaml
examples/render/contour.yaml

This change updates `release-1.30` branch with
* envoy v1.31.3
* See release notes for v1.31.1 [here](https://www.envoyproxy.io/docs/envoy/v1.31.2/version_history/v1.31/v1.31.1).
* See release notes for v1.31.2 [here](https://www.envoyproxy.io/docs/envoy/v1.31.2/version_history/v1.31/v1.31.2).
* See release notes for v1.31.3 [here](https://www.envoyproxy.io/docs/envoy/v1.31.3/version_history/v1.31/v1.31.3).
* go v1.22.8
* See release notes [here](https://go.dev/doc/devel/release#go1.22.minor).

release-1.30: Bump Envoy to v1.31.2 and Go to v1.22.8

---

changelogs/CHANGELOG-v1.28.7.md
changelogs/CHANGELOG-v1.29.3.md
changelogs/CHANGELOG-v1.30.1.md
site/content/resources/compatibility-matrix.md
versions.yaml

This PR updates the `main` branch with information for the patch releases v1.30.1, v1.29.3 and v1.28.7, along with an Envoy version bump in `main`.
Unlike before, I’ve linked the Envoy changelog index pages that contain the changelogs for each minor version. This is because we may skip certain Envoy releases, as in this case, so readers will need to refer to multiple changelogs anyway. Additionally, it may help reduce the effort required to update the links.
Related PRs
* `main`: https://github.com/projectcontour/contour/pull/6714
* https://github.com/projectcontour/contour/pull/6715
* https://github.com/projectcontour/contour/pull/6716
* https://github.com/projectcontour/contour/pull/6717

Patch release updates

---

apis/projectcontour/v1/helpers.go
changelogs/unreleased/6661-SamMHD-minor.md
internal/dag/httpproxy_processor.go
internal/envoy/v3/route.go
internal/featuretests/v3/authorization_test.go
internal/featuretests/v3/envoy.go
internal/featuretests/v3/global_authorization_test.go
internal/featuretests/v3/headerpolicy_test.go
internal/featuretests/v3/route_test.go
internal/featuretests/v3/tcpproxy_test.go
internal/xdscache/v3/route_test.go

closes #6617 and #6659
--- 
In order to fix #6617 I have changed how `dagRoute.DisableAuth` is caclulated. 
Also, to fix #6659 I thought it is needed to change behavior when we are upgrading a request to HTTPS (when `permitInsecure` is not set and we are redirecting HTTP to HTTPS). Thereby, when `dagRoute.AuthContext`/`dagRoute.AuthDisabled` is configured it will affect redirection as well --  before these changes, redirection won't care about them.
---
Changes:
- use dagRoute's AuthContext and AuthDisabled in HTTPS-Upgrade to fix 6659
- Use globalExtAuth.AuthPolicy.Disabled to calculate dagRoute.AuthDisabled
- Fix Tests

Apply Disable ExtAuth from GlobalExtAuth and Remove Auth from HTTP Upgrade

---

go.mod

To prevent issues with go commands and downloading correct toolchain versions.
See: https://go.dev/doc/toolchain#version
Detected locally when go tool attempted to download a new toolchain for go1.23 and was unable to.
Also see CodeQL warning:

Use 1.N.P form for go directive in go.mod file

---

apis/projectcontour/v1/httpproxy.go
changelogs/unreleased/6772-tsaarni-small.md
examples/contour/01-crds.yaml
examples/render/contour-deployment.yaml
examples/render/contour-gateway-provisioner.yaml
examples/render/contour-gateway.yaml
examples/render/contour.yaml
site/content/docs/main/config/api-reference.html

This change adds missing route config retry-on conditions that are available in Envoy 1.32.
Fixes #6770

Added missing retryOn conditions

---

apis/projectcontour/v1alpha1/zz_generated.deepcopy.go
hack/generate-crd-deepcopy.sh

The script [hack/generate-crd-deepcopy.sh](https://github.com/projectcontour/contour/blob/d05f43a103e53fc21078a8dbd2daf1ac56b5e787/hack/generate-crd-deepcopy.sh) was unintentionally rendered ineffective by #6117. This occurred because `exec` replaces the current shell process with the specified binary, preventing remaining lines of the script from running.
This update restores the deepcopy generation functionality and includes the results of `make generate` to address changes missed since the last successful run.
Fixes #6790

Fix deepcopy generation script

---

.github/workflows/build_daily.yaml
.github/workflows/build_tag.yaml
.github/workflows/codeql-analysis.yml
.github/workflows/prbuild.yaml
Makefile

release-1.30: Bump go to 1.22.10

---

.github/workflows/build_daily.yaml
.github/workflows/build_tag.yaml
.github/workflows/codeql-analysis.yml
.github/workflows/prbuild.yaml
Makefile

release-1.29: Bump go to 1.22.10

---

changelogs/unreleased/6714-tsaarni-small.md
changelogs/unreleased/6841-sunjayBhatia-small.md
cmd/contour/gatewayprovisioner.go
examples/contour/03-envoy.yaml
examples/deployment/03-envoy-deployment.yaml
examples/render/contour-deployment.yaml
examples/render/contour-gateway.yaml
examples/render/contour.yaml
go.mod
go.sum
site/content/resources/compatibility-matrix.md
versions.yaml

Also bumps go-control-plane root module to 1.13.4

Bump envoy to 1.32.3 and use go-control-plane/envoy versioned module for APIs

---

design/external-authorization-design.md

Recently PR builds are failing in `actions-codespell`
```
Error: ./design/external-authorization-design.md:37: Re-using ==> Reusing
```

Fix codespell error to pass CI

---

apis/projectcontour/v1/zz_generated.deepcopy.go
design/external-authorization-design.md
hack/generate-crd-deepcopy.sh
hack/generate-crd-yaml.sh

This PR removes the [workaround](https://github.com/projectcontour/contour/pull/6709#issuecomment-2466179766) which was applied due to controller-tools issue https://github.com/kubernetes-sigs/controller-tools/issues/1088. The issue was fixed in [v0.17.1](https://github.com/kubernetes-sigs/controller-tools/releases/tag/v0.17.1).

Remove workaround for controller-tools typealias bug

---

go.mod
go.sum
hack/generate-api-docs.sh
site/content/docs/main/config/api-reference.html

This PR removes the [workaround](https://github.com/projectcontour/contour/pull/6709#issuecomment-2466179766) for the typealias issue, which was needed for recent Go compiler versions.  Since no new releases have been made since v0.3.0 in 2021, the latest commit hash is used instead.
Additionally, the tool was previously installed in the user's `GOBIN` directory. Now `go run` is used to avoid requiring installing without user's consent.

Remove workaround for gen-crd-api-reference-docs

---

design/external-authorization-design.md

This PR fixes an issue introduced by `actions-codespell` where a change in dictionary causes the CI to fail with following error
```
Error: ./design/external-authorization-design.md:37: Re-using ==> Reusing
```
This is a "backport" of #6884 for branch `release-1.28`.

Make codespell happy

---

.github/workflows/build_daily.yaml
.github/workflows/build_tag.yaml
.github/workflows/codeql-analysis.yml
.github/workflows/prbuild.yaml
Makefile
apis/projectcontour/v1alpha1/contourconfig_helpers.go
changelogs/unreleased/6918-tsaarni-small.md
go.mod
hack/golangci-lint
test/e2e/deployment.go
test/e2e/provisioner.go

This change updates to Go 1.24.0. See https://go.dev/doc/devel/release#go1.24.0 for details.
The PR also updates golangci-lint to v1.64.5 for Go 1.24 support and fixes lint errors reported by new linter version
```
apis/projectcontour/v1alpha1/contourconfig_helpers.go:148:34: redefines-builtin-id: redefinition of the built-in function min (revive)
func ValidateTLSProtocolVersions(min, max string) error {
^
test/e2e/provisioner.go:111:38: redefines-builtin-id: redefinition of the built-in function new (revive)
func (p *Provisioner) ensureResource(new, existing client.Object) error {
^
test/e2e/deployment.go:269:37: redefines-builtin-id: redefinition of the built-in function new (revive)
func (d *Deployment) ensureResource(new, existing client.Object) error {
```

Bump to golang 1.24.0 and golangci-lint v1.64.5

---

.github/workflows/build_daily.yaml
.github/workflows/build_tag.yaml
.github/workflows/codeql-analysis.yml
.github/workflows/label_check.yaml
.github/workflows/prbuild.yaml

CI in maintenance branche `release-1.28` fails with following error
```
Error: This request has been automatically failed because it uses a deprecated version of `actions/cache: 0c45773b623bea8c8e75f6c82b208c3cf94ea4f9`. Please update your workflow to use v3/v4 of actions/cache to avoid interruptions. Learn more: https://github.blog/changelog/2024-12-05-notice-of-upcoming-releases-and-breaking-changes-for-github-actions/#actions-cache-v1-v2-and-actions-toolkit-cache-package-closing-down
```
Fixes #6929

Bump action/cache version in release-1.28 branch

---

.github/workflows/build_daily.yaml
.github/workflows/build_tag.yaml
.github/workflows/codeql-analysis.yml
.github/workflows/label_check.yaml
.github/workflows/prbuild.yaml

CI in maintenance branche `release-1.29` fails with following error
```
Error: This request has been automatically failed because it uses a deprecated version of `actions/cache: 0c45773b623bea8c8e75f6c82b208c3cf94ea4f9`. Please update your workflow to use v3/v4 of actions/cache to avoid interruptions. Learn more: https://github.blog/changelog/2024-12-05-notice-of-upcoming-releases-and-breaking-changes-for-github-actions/#actions-cache-v1-v2-and-actions-toolkit-cache-package-closing-down
```
Fixes #6929

Bump action/cache version in release-1.29 branch

---

.github/workflows/build_daily.yaml
.github/workflows/build_tag.yaml
.github/workflows/codeql-analysis.yml
.github/workflows/label_check.yaml
.github/workflows/prbuild.yaml

CI in maintenance branche `release-1.30` fails with following error
```
Error: This request has been automatically failed because it uses a deprecated version of `actions/cache: 0c45773b623bea8c8e75f6c82b208c3cf94ea4f9`. Please update your workflow to use v3/v4 of actions/cache to avoid interruptions. Learn more: https://github.blog/changelog/2024-12-05-notice-of-upcoming-releases-and-breaking-changes-for-github-actions/#actions-cache-v1-v2-and-actions-toolkit-cache-package-closing-down
```
Fixes #6929

Bump action/cache version in release-1.30 branch

---

Makefile
changelogs/unreleased/6969-tsaarni-small.md
cmd/contour/gatewayprovisioner.go
examples/contour/03-envoy.yaml
examples/deployment/03-envoy-deployment.yaml
examples/render/contour-deployment.yaml
examples/render/contour-gateway.yaml
examples/render/contour.yaml

This PR updates to [Envoy 1.31.6](https://www.envoyproxy.io/docs/envoy/v1.31.6/version_history/v1.31/v1.31.6). The update addresses [CVE-2025-30157](https://github.com/envoyproxy/envoy/security/advisories/GHSA-cf3q-gqg7-3fm9): "_Envoy crashes when HTTP ext_proc processes local replies_".

Bumped Envoy to 1.31.6 in release-1.30

---

Makefile
changelogs/unreleased/6970-tsaarni-small.md
cmd/contour/gatewayprovisioner.go
examples/contour/03-envoy.yaml
examples/deployment/03-envoy-deployment.yaml
examples/render/contour-deployment.yaml
examples/render/contour-gateway.yaml
examples/render/contour.yaml

This PR updates to [Envoy 1.30.10](https://www.envoyproxy.io/docs/envoy/v1.30.10/version_history/v1.30/v1.30.10). The update addresses [CVE-2025-30157](https://github.com/envoyproxy/envoy/security/advisories/GHSA-cf3q-gqg7-3fm9): "_Envoy crashes when HTTP ext_proc processes local replies_".

Bumped Envoy to 1.30.10 in release-1.29

---

.github/workflows/build_daily.yaml
.github/workflows/build_tag.yaml
.github/workflows/codeql-analysis.yml
.github/workflows/prbuild.yaml
Makefile
changelogs/unreleased/6972-tsaarni-small.md

This PR updates Go to version [1.22.12](https://go.dev/doc/devel/release#go1.22.0) for release 1.29 branch.

Bump Go version to 1.22.12 for release-1.29

---

.github/workflows/build_daily.yaml
.github/workflows/build_tag.yaml
.github/workflows/codeql-analysis.yml
.github/workflows/prbuild.yaml
Makefile
changelogs/unreleased/6971-tsaarni-small.md

This PR updates Go to version [1.22.12](https://go.dev/doc/devel/release#go1.22.0) for release-1.30 branch.

Bump Go version to 1.22.12 for release-1.30

---

.github/workflows/stale.yaml

This PR changes the stalebot settings:
* Lifecycle/stale is applied after 30 days of inactivity (was 14 days).
* PR is closed after 60 days of inactivity after lifecycle/stale (was 30 days).

Relax the stalebot times for PRs

---

changelogs/unreleased/6996-tsaarni-small.md
internal/envoy/v3/bootstrap.go
internal/envoy/v3/bootstrap_test.go

When Envoy connects to Contour over the xDS gRPC interface, it doesn't include `secp521r1` in the TLS `signature_algorithms` extension because of BoringSSL’s default settings. As a result, the TLS handshake fails when using EC certificates with 521-bit private keys for the xDS interface.  
This PR updates the Envoy bootstrap configuration to explicitly specify the list of supported signature algorithms, including `secp521r1`, enabling compatibility with these certificates.
Fixes #6997

Add ECDSA P-521 support for XDS interface

---

changelogs/unreleased/6872-tsaarni-small.md
cmd/contour/ingressstatus.go
cmd/contour/serve.go

This PR fixes a memory leak that was triggered by LoadBalancer status updates. Only the leader instance runs `loadBalancerStatusWriter` and therefore follower does not have anyone reading from the channel that receives status updates. The LoadBalancer status updates are still watched by followers and sent to the channel, causing the go routine calling `ServiceStatusLoadBalancerWatcher.notify()` to block. This led to `LoadBalancerStatus` updates piling up and consuming memory, eventually causing an out-of-memory condition and killing the Contour process.
With this change, `Service` updates are watched only after the instance becomes the leader and starts the `loadBalancerStatusWriter`.
Fixes #6860

Prevent LoadBalancer updates on follower.

---

changelogs/unreleased/7033-tsaarni-small.md
cmd/contour/gatewayprovisioner.go
examples/contour/03-envoy.yaml
examples/deployment/03-envoy-deployment.yaml
examples/render/contour-deployment.yaml
examples/render/contour-gateway.yaml
examples/render/contour.yaml
site/content/resources/compatibility-matrix.md
versions.yaml

This PR updates Envoy to version 1.34.1 and addresses https://github.com/envoyproxy/envoy/security/advisories/GHSA-c7cm-838g-6g67.
Contour was not affected by this vulnerability because it does not use `uri_template` permissions with Envoy's HTTP RBAC extension.

Bump Envoy to 1.34.1

---

go.mod
go.sum

release-1.30: Bump golang.org/x/net to 0.38.0

---

changelogs/unreleased/6906-tsaarni-small.md
internal/xdscache/v3/endpointslicetranslator.go
internal/xdscache/v3/snapshot.go

This change attempts to improve performance in clusters with a large number of endpoints, as discussed in https://github.com/projectcontour/contour/issues/6743#issuecomment-2538586264. 
Envoy does not send a wildcard `DiscoveryRequest` (a request without a resource name) for EDS / `ClusterLoadAssignment` resources. Instead, it creates a separate EDS stream for each CDS entry and requests specific resource by name. For example, with 10000 upstream clusters, each Envoy instance sends 10000 `DiscoveryRequests`, one per endpoint, e.g. from `echoserver-0000` to `echoserver-9999`.
As a result, the SotW-style update, where full set of resources is sent at every update, is not applicable. If `echoserver-0000` changes, updates should not be sent to streams watching `echoserver-0001` - …

Use LinearCache to optimize StreamEndpoint discovery.

---

internal/xdscache/v3/endpointslicetranslator.go

Since we are now directly modifiying the map of clusterloadassignments, we need to protect the write with the relevant mutex to prevent a data race

Protect endpointslicetranslator.entries on change

---

go.mod
go.sum

Manual bump to github.com/go-viper/mapstructure/v2 v2.4.0 for 1.32 release track to resolve GHSA-fv92-fjc5-jj9h.

Bump github.com/go-viper/mapstructure/v2 to v2.4.0

---

.github/workflows/build_daily.yaml
.github/workflows/build_tag.yaml
.github/workflows/codeql-analysis.yml
.github/workflows/prbuild.yaml
Makefile
go.sum

Bump golang from 1.24.3 to 1.24.6.
Changes https://go.dev/doc/devel/release#go1.24.minor

Bump Go to v1.24.6 for release track 1.31

---

.github/workflows/build_daily.yaml
.github/workflows/build_tag.yaml
.github/workflows/codeql-analysis.yml
.github/workflows/prbuild.yaml
Makefile

Bump golang from 1.24.3 to 1.24.6.
Changes https://go.dev/doc/devel/release#go1.24.minor

Bump Go to v1.24.6 for release track 1.32

---

.github/workflows/build_daily.yaml
.github/workflows/build_tag.yaml
.github/workflows/codeql-analysis.yml
.github/workflows/prbuild.yaml
Makefile
changelogs/unreleased/7168-sunjayBhatia-small.md
hack/golangci-lint
internal/provisioner/objects/rbac/clusterrole/cluster_role.go
internal/provisioner/objects/rbac/clusterrole/cluster_role_test.go
internal/provisioner/objects/rbac/policyrule/policyrule.go
internal/provisioner/objects/rbac/policyrule/policyrule_test.go
internal/provisioner/objects/rbac/resources/resources.go
internal/provisioner/objects/rbac/role/role.go
internal/provisioner/objects/rbac/role/role_test.go

Also bumps golangci-lint to 2.4.0 which supports 1.25
Minor refactor to internal/provisioner/objects/rbac to get rid of overly general 'util' package name flagged by revive linter

Bump go to 1.25.0
